### ISSUE TITLE
Marcar mais de um autor na ref

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#1009]
ABNT
surname, fname; surname, fname; surname, fname.
surname, fname, et al.

Vancouver
surname fname, surname fname, [...].
surname fname, surname fname, et al.

APA
surname, fname, surname, fname & surname, fname.

**Comment by leticiaquino** [comment]
@robertatakenaka segue abaixo alguns tipos de normas para uma possível automatização de referências bibliográficas por estrutura:

**ABNT**

Artigo de revista - 

BOYD, A. L.; SAMID, D. Molecular biology of transgenic animals. **Journal of Animal Science**, Albany, v. 71, n. 3, p. 1-9, 1993.

Legislação -

BRASIL. **Código civil**. Organização dos textos, notas remissivas e índices por Juarez de Oliveira. 46. ed. São Paulo: Saraiva, 1995.

BRASIL. Congresso. Senado. Resolução nº 17, de 1991. Autoriza o desbloqueio de Letras Financeiras do Tesouro do Estado do Rio Grande do Sul, através de revogação do parágrafo 2º, do artigo 1º da resolução no 72, de 1990. **Coleção de leis da República Federativa do Brasil**, Brasília, DF, v. 183, p. 1156-1157, maio/jun. 1991.

No prelo- 

ELEWA, H. H. Water resources and geomorphological characteristics of Tushka and west of Lake Nasser, Agypt. **Hydrogeology Journal**, Berlin, v. 16, n. 1, 2006. In press.

(Nota: em português: No prelo, em inglês: In press, em alemão: In druck e em francês: Sous press.)


Publicação em suporte eletronico:

WU, H. et al. Parametric sensitivity in fixed-bed catalytic reactors with reverse flow operation. **Chemical Engineering Science**, London, v. 54, n. 20, 1999. Disponível em: ```<http://www.probe.br/sciencedirect.html>```. Acesso em: 8 Nov. 1999.


Livro:

ESPÍRITO SANTO, A. **Essências de metodologia científica: aplicada à educação**. Londrina: Universidade Estadual, 1987.

MOSS, D. W.; HENDERSON, A. R. Clinical enzymology. In: BURTIS, C. A.; ASHWOOD, E. R. (Ed.). **Tietz textbook of clinical chemistry**. 3rd ed. Philadelphia: W. B. Saunders, 1999. cap. 22, p. 617-721.

DUDEK, S. G. (Ed.). **Nutrition essentials for nursing practice**. 5th ed. Philadelphia: Lippincott Williams & Wilkins, 2006. Disponível em: ```<http://gateway.ut.ovid.com/gw1/ovidweb.cgi>```. Acesso em: 24 Oct. 2006.



**VANCOUVER - **

Artigo de revista:

Goracci C, Tavares AU, Fabianelli A, Monticelli F, Raffaelli O, Cardoso PC, Tay F, Ferrari M. The adhesion between fiber posts and root canal walls: comparison between microtensile and push-out bond strength measurements. Eur J Oral Sci. 2004 Aug;112(4):353-61.

Legislação e portaria -

Brasil. Lei n. 7000 de 20 de dezembro de 1990. Dispõe sobre a proibição da pesca. Diário Oficial da União, Brasília (1991 jan. 21); Sec.1:51.

Brasil. Secretaria da Receita Federal. Desliga a Empresa de Correios e Telégrafos - ECT do sistema de arrecadação. Portaria n.12, 21 março 1996. Lex: coletânea de legislação e jurisprudência. 1996 mar.-abr.: 742-3.

Epub

Simoes-Costa MS, Azambuja AP, Xavier-Neto J. The search for non-chordate retinoic acid signaling: lessons from chordates. J Exp Zoolog B Mol Dev Evol. 2006 Nov 15; [Epub ahead of print].

Publicação em meio eletrônico:

Abood S. Quality improvement initiative in nursing homes: the ANA acts in an advisory role. Am J Nurs. 2002;102(6) [cited 2002 Aug 12]. Available from: http://www.nursingworld.org/AJN/2002/june/Wawatch.htm.

Livro:

Jenkins PF. Making sense of the chest x-ray: a hands-on guide. New York: Oxford University Press; 2005. 194 p.

Catani AM. O que é capitalismo. In: Spindel A. Que é socialismo e o que é comunismo. São Paulo: Círculo do Livro; 1989. p. 7-87. (Primeiros passos; 1).

Kasper DL, Braunwald E, Fauci AS, et al., editors. Harrison’s on-line [Internet]. 16th ed. Columbus (OH): McGraw-Hill Companies; c2006 [cited 2006 Nov 20]. Available from: http://www.accessmedicine.com/resourceTOC.aspx?resourceID=4.


**APA**

Artigo de revista:

Bosi, E. (2003). O tempo vivo da memória: ensaios de psicologia social. São Paulo: Ateliê Editorial. Resenha de C. Ades (2004). A memória partilhada. Psicologia USP, 15(3), 233-244.

Legislação e portaria -

Lei n. 9.394, de 20 de dezembro de 1996. (1996, 23 de dezembro). Estabelece as Diretrizes e Bases da Educação Nacional. Diário Oficial da União, seção 1.

Constituição da República Federativa do Brasil. (1988, 05 de outubro). Recuperado em 6 de novembro de 2006, de http://www.senado.gov.br/sf/legislacao/const/

No prelo:

Teixeira Júnior, A. L., & Caramelli, P. (no prelo). Apatia na doença de Alzheimer. Revista Brasileira de Psiquiatria.


Publicação em meio eletrônico:

Celes, L. A. (2005). Sedução e feminilidade em transferência [Versão eletrônica]. Ágora: Estudos em Teoria Psicanalítica, 8(1), 77-94.

Mann, M. A. (2005, September). The formation and development of individual and ethnic identity: Insights from psychiatry and psychoanalytic theory. The American Journal of Psychoanalysis, 66(3), 211-224. Recuperado em 06 de novembro de 2006, de http://www.springerlink.com.w10077.dotlib.com.br/content/ uv84215120031746/fulltext.pdf


Livro:

Barros Neto, T. P. (2000). Sem medo de ter medo: um guia prático para ajudar pessoas com pânico, fobias, obsessões, compulsões e estresse. São Paulo: Casa do Psicólogo.

Bergeret, J. (1981). Aspects économiques du comportement d’addiction. In M. Bandelier (Org.), Le psychanalyste à l’écoute du toxicomane (pp. 9-25). Paris: Dunod.



Fonte: ```<http://www.ip.usp.br/portal/index.php?option=com_content&view=article&id=203:normas-de-normatizacao&catid=122:capacitacao-manuais&Itemid=141>```. Verificar PDFs.

**Comment by leticiaquino** [comment]
@robertatakenaka Programa não marca autores corretamente utilizando o botão [*authors]. Veja:

![authors-automatic-asterscj](https://cloud.githubusercontent.com/assets/4397365/7137827/ba1250a0-e292-11e4-8eac-c743318af1f2.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1009

**Comment by leticiaquino** [comment]
@robertatakenaka sobre o comentário acima, notei que o programa só marca autores automaticamente se na referência existir mais que 1 autor. Veja:

![authiosd](https://cloud.githubusercontent.com/assets/4397365/7137934/7bf92a2c-e293-11e4-9a68-a82c214eec98.jpg)
