### ISSUE TITLE
Link para PDF de material suplementar não disponivel no site SciELO

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#102]
MIOC v108n6 - Links para PDF de material suplementar não está disponível no site SciELO:

* http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0074-02762013000600778&lng=en&nrm=iso&tlng=en

* http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0074-02762013000600707&lng=en&nrm=iso&tlng=en

Verificamos que nos validadores do PubMed Central, os arquivos não apresentam erro e ao subir os arquivos no article previewer temos o seguinte resultado:

* http://www.pubmedcentral.nih.gov/utils/pv/articlerender.fcgi?artid=358376

* http://www.pubmedcentral.nih.gov/utils/pv/articlerender.fcgi?artid=358385

Por gentileza, verificar a possibilidade de disponibilizar o link para o site SciELO.

**MODULO: ArticlePage
PRIORIDADE: Medium**

**Comment by robertatakenaka** [comment]
fechado porque está em local errado
