### ISSUE TITLE
Marcação automática para subdoc (seção, doctitile, etc)

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#1024]

**Comment by leticiaquino** [comment]
@robertatakenaka acredito que esse ticket pode ser fechado, pois não há uma estrutura única para sub-article. Alguns podem apresentar seção, outros não, alguns podem apresentar nome de autores e afiliações, outros não..

A meu ver podemos considerar como um procedimento manual, como temos feito.
O que você acha?

**Comment by robertatakenaka** [comment]
De acordo.
