### ISSUE TITLE
Automatizar resenha

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#1037]

**Comment by leticiaquino** [comment]
@robertatakenaka há a possibilidade de, pelo tipo de documento selecionado no formulário, o programa apresente apenas as tags que pode apresentar no documento?

Para esse caso, a marcação automática poderia ser por estrutura.

Geralmente arquivos do tipo resenha apresentam doi, título, autores, afiliação (às vezes) e a referência do livro resenhado. Veja:

![reesenhaaaa](https://cloud.githubusercontent.com/assets/4397365/6153721/d0440522-b20d-11e4-92b9-0517f5db30cd.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1037
