### ISSUE TITLE
(Markup 4.0.089 - Word 2013) inserir droplist para identificação automática de URL de licença

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1053]
Verificar a possibilidade de inserir um droplist no formulário (no campo de licença) com os links dos tipos de licença e versões que aceitamos. Dessa forma não será necessário sair do Markup para buscar a URL da licença adotada pela revista.

As licenças que aceitamos hoje são as que seguem abaixo:

http://creativecommons.org/licenses/by/4.0/ 	        CC-BY versão 4.0
http://creativecommons.org/licenses/by/3.0/ 	        CC-BY versão 3.0
http://creativecommons.org/licenses/by-nc/4.0/ 	CC-BY-NC versão 4.0
http://creativecommons.org/licenses/by-nc/3.0/ 	CC-BY-NC versão 3.0

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
vou fechar porque acho que tem que ficar livre
