### ISSUE TITLE
(MArkup 4.0.090 - Word 2013) Inserir "http://" quando não há na tag <ext-link ext-link-type="uri" xlink:href="">

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1128]
Para o PMC, se não é inserido o protocolo "http://", por exemplo, no atributo @xlink:href, os validadores PMC apresentam erro.

Veja que para o Schema SciELO o prefixo http é obrigatório para link de site:

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.1-branch/tagset.html#ext-link

**Comment by leticiaquino** [comment]
@robertatakenaka desconsiderar tícket. Fiz novos testes e percebi que é possível que o @xlink:href não apresente a informação "http".
O arquivo o qual apresentava erro nesse dado tinha tag identificada incorretamente.

**Comment by robertatakenaka** [comment]
DESCONSIDERAR TICKET
