### ISSUE TITLE
(markup 090 - word 2013) Marcação manual de autor com erro

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1142]
Na marcação manual do autor, quando aplicamos a tag surname-fname, marca errado. Ex:
[author role="nd" rid="aff1" corresp="n" deceased="n" eqcontr="nd"][surname]JÚLIO CEZAR BASTONI DA[/surname] [fname]SILVA[/fname

**Comment by leticiaquino** [comment]
@robertatakenaka @javani podem disponbilizar o arquivo que apresentou erro?
Caso não o tenham.. de acordo com os testes realizados com a versão mais recente do programa Markup, esse erro não ocorreu para o Markup 90.

**Comment by robertatakenaka** [comment]
@leticiaquino e @javani: consegui simular o erro. Sim o problema é quando está tudo em letras maiúsculas.

**Comment by javani** [comment]
@robertatakenaka @leticiaquino Então devemos incluir no manual de preparação de arquivos que o nome do autor não deve estar em caixa alta.

**Comment by leticiaquino** [comment]
@javani @robertatakenaka ok, vou incluir.

**Comment by robertatakenaka** [comment]
@javani: vou tentar resolver...

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-12-15 16:48 GMT-02:00 javani <notifications@github.com>:

**Comment by robertatakenaka** [comment]
@javani e @leticiaquino : acho melhor deixar anotado no manual mesmo. Não vou conseguir resolver sem danificar a automação nas referências.
