### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Marcação de tabela como imagem inverte a ordem das tags que fecha

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1149]
Verifiquei que ao fazer a marcação de tabela como imagem, o programa inverte a ordem das tags que fecha. Veja:

![table-tags-trocadas](https://cloud.githubusercontent.com/assets/4397365/5476794/a636a6c2-860c-11e4-9caa-2d850210e035.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1149

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : você selecionou inclusive a imagem? Para mim funcionou.

**Comment by leticiaquino** [comment]
@robertatakenaka testei novamente, porém agora com a versão mais recente do programa Markup e o resultado foi positivo:

![tab-graphic-ok](https://cloud.githubusercontent.com/assets/4397365/11811030/e48eb75e-a319-11e5-9a67-efcbad965096.jpg)


Ticket resolvido.
