### ISSUE TITLE
RBP v35s1 - Arquivo com problema em apresentação de Box

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#115]
O arquivo "Mood disorders in.." da RBP v35s1 possui um Box, de acordo com o PMC essa informação deve ser identificada em  boxed-text (http://dtd.nlm.nih.gov/publishing/tag-library/3.0/n-8w30.html) e deve ser apresentado como um quadro, conforme segue o exemplo do link abaixo:

http://www.pubmedcentral.nih.gov/utils/pv/articlerender.fcgi?artid=372468

![box-rbp](https://f.cloud.github.com/assets/4397365/1297248/f776d168-30dd-11e3-828a-74e21c43ecb9.jpg)

Contudo no site SciELO essa informação é apresentado como texto, confundindo parágrafos com a informação do box:

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1516-44462013000500004&lng=en&nrm=iso&tlng=en

![box - rbp ii](https://f.cloud.github.com/assets/4397365/1297250/0135086e-30de-11e3-8753-4ad72cbfcd3f.jpg)

Por gentileza, verificar a possibilidade de apresentar o Box como um quadro em vez de texto.

**MODULO - ArticlePage
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
https://github.com/scieloorg/Web/issues/209
