### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Programa insere automaticamente id "n" para figuras.

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1163]
Verificamos que ao identificar figuras pela tag [figgrp], o programa insere automaticamente um id "n". Veja:

![figura-id](https://cloud.githubusercontent.com/assets/4397365/5645816/766c11e8-965b-11e4-829e-53eee16a0b8d.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1163

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka estranhamente, parou de aparecer o id "n"..

**Comment by javani** [comment]
@leticiaquino @robertatakenaka para mim aparece n... e quanto tento alterar para f... apresenta erro de ID inválido e não deixa prosseguir a marcação. Quando tentei marcar com n... novamente também não deixou seguir.

**Comment by javani** [comment]
@robertatakenaka 
Continua com o problema de ID n. No arquivo que estou trabalhando, marquei 3 notas de autor antes de iniciar a marcação do corpo do texto e quando fui marcar a primeira figura assumiu o ID n4. Tentei alterar o ID para f1 mas dá msg de erro de ID inválido.
![image](https://cloud.githubusercontent.com/assets/912953/6083471/e9f7fcaa-ae0f-11e4-8b95-fe7c0c97291e.png)

**Comment by robertatakenaka** [comment]
Me manda este arquivo. Eu não tinha um exemplo para corrigir isso. Tinha
parado de acontecer.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-02-06 14:54 GMT-02:00 javani <notifications@github.com>:

**Comment by javani** [comment]
Robs,
Acabou que não salvei a marcação.
O arquivo é este.

Grata,

Javani
On 06/02/2015 14:58, Roberta Takenaka wrote:
> Me manda este arquivo. Eu não tinha um exemplo para corrigir isso. Tinha
> parado de acontecer.
>
> Roberta Takenaka
>
> SciELO - Scientific Electronic Library Online
> FAPESP - CNPq - BIREME - FapUNIFESP
> www.scielo.org | www.scielo.br
> ______________________________
> Avenida Onze de Junho, 269
> 04041-050 - São Paulo-SP - Brasil
> Tel.: 55-11-5083-3639
>
>
> 2015-02-06 14:54 GMT-02:00 javani <notifications@github.com>:
>
> > @robertatakenaka <https://github.com/robertatakenaka>
> > Continua com o problema de ID n. No arquivo que estou trabalhando, 
> marquei
> > 3 notas de autor antes de iniciar a marcação do corpo do texto e 
> quando fui
> > marcar a primeira figura assumiu o ID n4. Tentei alterar o ID para 
> f1 mas
> > dá msg de erro de ID inválido.
> > [image: image]
> > 
> <https://cloud.githubusercontent.com/assets/912953/6083471/e9f7fcaa-ae0f-11e4-8b95-fe7c0c97291e.png>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/scieloorg/PC-Programs/issues/1163#issuecomment-73270028>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scieloorg/PC-Programs/issues/1163#issuecomment-73270953>.
>

-- 
Javani Araujo
SciELO
FAPESP - CNPq - BIREME - FAP UNIFESP
Av. Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
www.scielo.org | www.scielo.br | blog.scielo.org


Responsible: responsable
System Date: 06/02/2015 

File Name: C:\Users\javani.araujo\Desktop\rec\v1\markup_xml\scielo_markup\a04.doc
Normal.dot: C:\Users\javani.araujo\AppData\Roaming\Microsoft\Templates\Normal.dotm
File Size Before (bytes):  206848
File Size After (bytes):  206848
Pages Number:  13 

References Number: 
Initial Time: 14:17:20 
Final Time: 14:55:02 
Markup Time:  0h  37min  42s
********************************************************************************

**Comment by leticiaquino** [comment]
@robertatakenaka  Continua ocorrendo.
Insiro o arquivo de exemplo em:
Y:\SciELO_team\XML_PMC\TICKETS\1163

![error-fig](https://cloud.githubusercontent.com/assets/4397365/6111574/00ebebd4-b071-11e4-8bbd-4ff445a33ecd.jpg)

**Comment by leticiaquino** [comment]
@robertatakenaka com a versão mais recente do programa Markup, eu refiz o teste e o resultado foi positivo:
![fig-ok](https://cloud.githubusercontent.com/assets/4397365/11810663/cd43d870-a316-11e5-95a1-fb3a5b167546.jpg)

Considerar ticket como resolvido.
