### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Programa não identifica corretamente footnote no body

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1168]
Foi verificado que ao selecionar a tag [*fn] o programa não identifica corretamente a footnote no corpo do texto. Veja:

![xref-markup](https://cloud.githubusercontent.com/assets/4397365/5669013/53c19ac2-975b-11e4-9280-67c7f4a9fb78.jpg)

Arquivos disponíveis em:
Y:\SciELO_team\XML_PMC\TICKETS\1168

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino e @javani: detectei que não é um problema da versão 4.0.090, mas é particular do arquivo, que ainda vou pensar em outra solução para atender isso. Se vocês tiverem exemplos de arquivos em que já funcionavam me mandem. Pode colocar em Y:\SciELO_team\XML_PMC\TICKETS\1168
