### ISSUE TITLE
(markup 090 - word 2013) Apresenta erro na marcação com a tag publoc-name

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1187]
Ao marcar, aparece o erro: a variável do objeto ou a variável do bloco wirh não foi definida
![sem titulo](https://cloud.githubusercontent.com/assets/912953/5957669/77958b40-a7a3-11e4-8f64-a89e9c308063.png)

**Comment by robertatakenaka** [comment]
@javani: pode me mandar este arquivo?

**Comment by javani** [comment]
Segue Robs.

2015-02-03 11:05 GMT-02:00 Roberta Takenaka <notifications@github.com>:

> @javani <https://github.com/javani>: pode me mandar este arquivo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/PC-Programs/issues/1187#issuecomment-72646586>
> .
>



-- 
Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

**Comment by robertatakenaka** [comment]
@javani : não localizei o arquivo. Por favor, mande por email com o assunto #1187.

**Comment by javani** [comment]
Segue novamente.
On 03/02/2015 12:12, Roberta Takenaka wrote:
>
> @javani <https://github.com/javani> : não localizei o arquivo. Por 
> favor, mande por email com o assunto #1187 
> <https://github.com/scieloorg/PC-Programs/issues/1187>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scieloorg/PC-Programs/issues/1187#issuecomment-72656365>.
>

-- 
Javani Araujo
SciELO
FAPESP - CNPq - BIREME - FAP UNIFESP
Av. Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
www.scielo.org | www.scielo.br | blog.scielo.org
