### ISSUE TITLE
(Markup 090 - word 2013) erro na inclusão de doctype

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1188]
Programa faz a marcação automática e inclui uma tag [/authors] dentro de [doc]. Foi incluída dentro de stitle.

[doc acron="epsic" jtitle="Estudos de Psicologia (Natal)" stitle="Estud. psicol. [/authors] (Natal)" issn="1413-294X" pissn="1413-294X" pubname="Programa de Pós-graduação em Psicologia, Universidade Federal do Rio Grande do Norte" license="http://creativecommons.org/licenses/by-nc/3.0/" volid="19" issueno="4" dateiso="20141200" season="Oct-Dec" fpage="241" lpage="259" doctopic="oa" language="pt" version="4.0"]

**Comment by robertatakenaka** [comment]
@javani: pode me enviar o arquivo que teve este problema?

**Comment by robertatakenaka** [comment]
resolvido
