### ISSUE TITLE
Inclusão do DOI no xml do enviado ao pubmed

### ISSUE THREAD

**Issue by salgadoe** [scieloorg/PC-Programs#1190]
O xml que enviamos ao Pubmed possui o PID do artigo mas não  apresenta o DOI.
Incluir esse dado no script.
exemplo:
Como aparece no Pubmed: 
GRIZ, Luiz Henrique Maciel et al. Vitamin D e diabetes melito: uma atualização 2013. Arq Bras Endocrinol Metab [online]. 2014, vol.58, n.1, pp. 1-8. ISSN 0004-2730. 
como deveria aparecer;
GRIZ, Luiz Henrique Maciel et al. Vitamin D e diabetes melito: uma atualização 2013. Arq Bras Endocrinol Metab [online]. 2014, vol.58, n.1, pp. 1-8. ISSN 0004-2730.  http://dx.doi.org/10.1590/0004-2730000002535. 
att
Eliana

**Comment by robertatakenaka** [comment]
@salgadoe : acho que este problema já está resolvido (https://github.com/scieloorg/PC-Programs/issues/1103). Foi registrado por email:

"
Eliana Salgado <eliana.salgado@scielo.org>
	
12/11/14
		
On 11/12/2014 09:24, Marcia Morgan wrote:
> Bom dia,
>
> fiz o teste com o xml do Pubmed da abc v103n5 e da bjmbr v48n1 e a tag de DOI foi incluída no xml.
> exemplo
> ```xml
<ArticleId IdType="doi">10.1590/1414-431X20143701</ArticleId>
```
"


Verificar se não seria o caso de regerar os XML para os fascículos que ainda não tem este dado apresentado.

**Comment by salgadoe** [comment]
Ok.
Obrigada.
A reclamação sobre esse item é anterior ao ajuste. Vou solicitar 
reprocessamento.
At
Eliana
On 02/02/2015 08:34, Roberta Takenaka wrote:
>
> @salgadoe <https://github.com/salgadoe> : acho que este problema já 
> está resolvido (#1103 
> <https://github.com/scieloorg/PC-Programs/issues/1103>). Foi 
> registrado por email:
>
> "
> Eliana Salgado eliana.salgado@scielo.org 
> <mailto:eliana.salgado@scielo.org>
>
> 12/11/14
>
> On 11/12/2014 09:24, Marcia Morgan wrote:
>
>     Bom dia,
>
>     fiz o teste com o xml do Pubmed da abc v103n5 e da bjmbr v48n1 e a
>     tag de DOI foi incluída no xml.
>     exemplo
>
>     <ArticleId  IdType="doi">10.1590/1414-431X20143701</ArticleId>
>
>     "
>
> Verificar se não seria o caso de regerar os XML para os fascículos que 
> ainda não tem este dado apresentado.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scieloorg/PC-Programs/issues/1190#issuecomment-72435979>.
>

-- 
Eliana Montuori Salgado
SciELO Brasil
FAPESP - CNPq - FapUNIFESP - BIREME
www.scielo.org
_____________________________
Av. Onze de junho, 269
04041-050 - São Paulo/SP - Brasil
Tel.: (55 11)5083 3639 R.112
