### ISSUE TITLE
(markup 090 - word 2013) Exclui tag não apaga fecha-tag em referências

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1192]
Quando excluída a marcação feita errada, o programa não apaga o [/xxxx]

([date dateiso="20120000" specyear="2012"]2012[/date]).  Resolução CNS nº 466/12, de 12 de dezembro de 2012[/arttitle].

**Comment by robertatakenaka** [comment]
@javani: é comportamento esperado. O programa somente deve apagar as tags que abrem e fecham ou as tags que apenas abrem (mas este caso acho que nao existe mais).
