### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Programa apresenta lentidão ao identificar tags no documento.

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1194]
Verificamos que ao editar a tag [normaff] o programa para de responder e depois de alguns minutos (uns 5 - 7 min) volta a funcionar. Veja:

![normaff](https://cloud.githubusercontent.com/assets/4397365/5975363/14b3e782-a867-11e4-876c-29c9cf95606b.jpg)

(parece que é porque não há é fornecido o texto para consultar)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1194

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : depende da velocidade da rede porque executa chamada ao serviço wayta.scielo.org.
