### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Programa apresenta erro ao fazer marcação de ID de figuras

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1201]
Verificamos que o programa Markup apresenta erro ao fazer a marcação do ID de figuras. Ao selecionar a imagem, o programa insere um ID "ch1". Veja:

![grafico](https://cloud.githubusercontent.com/assets/4397365/6024497/d25b289c-abb2-11e4-930c-a801703b2051.jpg)

Ao tentar trocar o ID "ch1" para "f1" o programa apresenta erro, porém percebemos que mesmo aceitando o ch1 e clicando em Ok, é apresentado erro. Veja:

![id-grafico](https://cloud.githubusercontent.com/assets/4397365/6024546/1b817378-abb3-11e4-93b9-6b520e963f57.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1201

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino: quando o label é diferente de Fig, automaticamente seleciona
ch (chart) e pega o próximo número até o caracter em branco.

O erro é que o hífen foi selecionado também. A solução é editar o id,
removendo o hífen.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-02-03 14:45 GMT-02:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka agors está OK, porém no xref de sub-article não está como incremental. Notei que no artigo traduzido a tabela 1 que deveria ter @rid="t2" é identificado como [xref ref-type="table" rid="t1"].
