### ISSUE TITLE
Inclusao do intervalo de publicação no xml Pubmed

### ISSUE THREAD

**Issue by salgadoe** [scieloorg/PC-Programs#1217]
Pubmed nos envia o email abaixo copiado sobre a inclusão do intervalo de meses no xml que enviamos a eles. Segundo Renata, ao gerar o xml para o Pubmed, é considerado apenas 1 mes do intervalo. O último mês. Peço verificar. grata

Hi Eliana,
It’s come to my attention that SciELO has been submitting the pubdate for Rev Bras Psiquiatr with a single month rather than the month range displayed on the journal website.
For example, Rev Bras Psiquiatr v36n4 was submitted with a December 2014 pubdate, while the journal’s website shows an Oct/Dec 2014 pubdate.
Going forward, could you please submit the pubdate using the month range? Here is sample XML:

```xml
<PubDate>
<Year>2008</Year>
<Month>Nov-Dec</Month>
</PubDate>
```

If you have any further questions or concerns, please feel free to contact us at publisher@ncbi.nlm.nih.gov.

**Comment by robertatakenaka** [comment]
@salgadoe : por favor, testar. Nota: curioso que sempre foi assim.

**Comment by salgadoe** [comment]
Roberta,
Gerou o xml vazio.
Obrigada,
Eliana
On 09/02/2015 11:12, Roberta Takenaka wrote:
>
> @salgadoe <https://github.com/salgadoe> : por favor, testar. Nota: 
> curioso que sempre foi assim.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scieloorg/PC-Programs/issues/1217#issuecomment-73506034>.
>

-- 
Eliana Montuori Salgado
SciELO Brasil
FAPESP - CNPq - FapUNIFESP - BIREME
www.scielo.org
_____________________________
Av. Onze de junho, 269
04041-050 - São Paulo/SP - Brasil
Tel.: (55 11)5083 3639 R.112
