### ISSUE TITLE
(Markup 4.0.090 - Word 2013) [normaff] não reconhece instituições corretamente

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1221]
Verificamos que o programa Markup não reconhece algumas instituições. Exemplo:

![normaff2](https://cloud.githubusercontent.com/assets/4397365/6107257/4f45ff0c-b050-11e4-85a7-e7b347421424.jpg)

Teste: Se inserir o mesmo nome da instituição no serviço wayta.scielo.org, a API encontra o nome correto. Ou seja, o erro ocorre apenas no Markup.

relacionado ao tícket  #1204

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1221

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka verifiquei que, realmente, a aspa atrapalha na busca da instituição. 
Eu retirei as aspas e os parênteses, busquei novamente e o programa conseguiu encontrar a instituição correta.

**Comment by robertatakenaka** [comment]
@leticiaquino : refiz este formulário de modo que o usuário pode refazer a pesquisa alterando o texto que vem ao lado do botão FIND.
