### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Instituições que não constam na planilha, o Markup deve gerar um "normalized" fechado

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1239]
Verificar a possibilidade do programa Markup gerar um elemento ```<institution content-type="normalized"/>``` fechado para afiliações que apresentam instituiçoes que não constam na planilha.
Outra possibilidade é inserir a tag  institution com o valor "not-normalized". Veja:```<institution content-type="not-normalized">```

**Comment by leticiaquino** [comment]
@robertatakenaka 
Isso ainda não ocorre.

**Comment by robertatakenaka** [comment]
@leticiaquino : Não entendi este ticket. Qual o problema que esta sugestão resolve?  O fato de inserir vazio só camufla a ausência do dado, ou seja, não resolve nada. De uma forma ou outra fica como inexistente o valor normalizado.

**Comment by leticiaquino** [comment]
@robertatakenaka preciso verificar com a @javani se essa recomendação para a equipe ainda é valida.
No início, o uso de ```<institution content-type="normalized"/>``` era necessário em todas as tags ```<aff>``` e, muitas vezes, inseríamos manualmente.

**Comment by javani** [comment]
@leticiaquino @robertatakenaka pior que eu nem lembro dessa recomendação. Acredito não ser necessária já que nem sempre existe a instituição normalizada. Melhor deixar sem a tag quando não houver correspondência.

**Comment by robertatakenaka** [comment]
@leticiaquino e @javani : colocar vazio só ocultaria o erro no style checker e/ou no xpm. No entanto, no final, resulta que fica mesmo sem afiliação. Então não acho que é uma boa prática.

**Comment by leticiaquino** [comment]
@robertatakenaka @javani  Ok. Então desconsideramos o ticket.
