### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Implementar valor para referência incompleta.

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1240]
Verificar a possibilidade do programa Markup gerar valor "incomplete" para referências incompletas no XML.
Exemplo:

```xml
<ref id="B05">
   <label>5</label>
   <element-citation publication-type="incomplete">
      <person-group person-group-type="author">
         <name>
            <surname>Hess</surname>
              <given-names>DR</given-names>
         </name>
      </person-group>
      <article-title>Noninvasive ventilation for acute respiratory failure</article-title>
      <source>Respir Care</source>
      <volume>58</volume>
      <issue>6</issue>
      <fpage>950</fpage>
      <lpage>972</lpage>
</element-citation>
</ref>
```
Observe que nessa referência não há informação de **Ano de publicação**.

Nota: A meu ver o valor "incomplete" deve ser inserido automaticamente ao gerar o documento XML. A validação deve confirmar se a referência é incompleta mesmo ou não, verificando os dados-chave de uma referência como ```<source>``` e ```<year>```.

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : eleger outro atributo para inserir este valor. Não deve ser no publication-type.

**Comment by leticiaquino** [comment]
@robertatakenaka podemos utilizar o atributo @specific-use. Veja:

```<element-citation publication-type="journal" specific-use="incomplete">```

http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-t2u0.html

**Comment by robertatakenaka** [comment]
https://github.com/scieloorg/scielo_publishing_schema/issues/64
