### ISSUE TITLE
(markup 090 - word 2013) Preview em referência autor de capítulo = autor de livro

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1258]
Inclui a tag text-ref mas não substitui _____ por nome do autor:

[ref id="r4" reftype="book"][text-ref]FOUCAULT, Michel. A prosa do mundo. In:______. As palavras e as coisas. São Paulo: Martins Fontes, 2000. p. 23-58.[/text-ref] FOUCAULT, Michel. A prosa do mundo. In:______. As palavras e as coisas. São Paulo: Martins Fontes, 2000. p. 23-58.[/ref]

**Comment by robertatakenaka** [comment]
@javani : Sim. É isso mesmo. Tive que alterar a lógica do programa senão não funcionaria para todos os casos. Agora ao marcar o ___ como authors e *pauthor, será substituido. Mas primeiro é necessário marcar o autor do capítulo.
