### ISSUE TITLE
(markup 090 - word 2013) Text-ref duplicado

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1259]
Quando tem text-ref, duplicada dado.

[ref id="r10" reftype="book"]OKAZAKI, Victor H. A. Diagnóstico da especificidade técnica de jogadores que desempenham a função de armadores, alas e pivôs no basquetebol. 2002. Monografia (Graduação em Licenciatura Plena em Educação Física) - Universidade Federal do Paraná, Curitiba-PR.[/ref]
[ref id="r11" reftype="book"][text-ref]_________. O arremesso de jump no basquetebol de adultos e crianças em função do aumento da distância. 2006. Dissertação (Mestrado em Educação Física) - Universidade Federal do Paraná, Curitiba-PR. _________. O arremesso de jump no basquetebol de adultos e crianças em função do aumento da distância. 2006. Dissertação (Mestrado em Educação Física) - Universidade Federal do Paraná, Curitiba-PR.[/text-ref] _________. O arremesso de jump no basquetebol de adultos e crianças em função do aumento da distância. 2006. Dissertação (Mestrado em Educação Física) - Universidade Federal do Paraná, Curitiba-PR. _________. O arremesso de jump no basquetebol de adultos e crianças em função do aumento da distância. 2006. Dissertação (Mestrado em Educação Física) - Universidade Federal do Paraná, Curitiba-PR.[/ref]

**Comment by robertatakenaka** [comment]
@javani: será que já não estava duplicado?

**Comment by javani** [comment]
Vou fazer outro teste.
On 10/03/2015 08:12, Roberta Takenaka wrote:
>
> @javani <https://github.com/javani>: será que já não estava duplicado?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scieloorg/PC-Programs/issues/1259#issuecomment-78034328>.
>

-- 
Javani Araujo
SciELO
FAPESP - CNPq - BIREME - FAP UNIFESP
Av. Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
www.scielo.org | www.scielo.br | blog.scielo.org

**Comment by leticiaquino** [comment]
Relacionado ao #1413
revolvido.
