### ISSUE TITLE
(markup 090 - word 2013) Imagem em caption de tabela

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1271]
Nas revistas da área de exatas é comum ter imgs em caption de tabela.
 [tabwrap id="t3"][label]Tabela 3:[/label] [caption]Valores para o parâmetro de não centralidade do modelo ([graphic href="?ART21_2"] [/graphic]) para cada par de desníveis considerados (cenário bi-dimensional).[/caption]

Quando gera o XML, inclui a informação de graphic ao invés de inline-graphic.

```caption>
                  <title>
                  	Valores para o parâmetro de não centralidade do modelo (<graphic xlink:href="1982-2170-bcg-21-01-00026-gt3.png"/>
					) para cada par de desníveis considerados (cenário bi-dimensional).
				</title>

Quando deveria ser:

caption>
                  <title>
                  	Valores para o parâmetro de não centralidade do modelo (<inline-graphic xlink:href="1982-2170-bcg-21-01-00026-gt3.png"/>
					) para cada par de desníveis considerados (cenário bi-dimensional).
				</title>

**Comment by javani** [comment]
O erro não ocorre mais em body, mas ocorre em app-group. Enviado arquivo via email

**Comment by robertatakenaka** [comment]
@javani: você quer dizer que o graphic fica fora do caption?

```xml
<caption>
                     <title>Mathematical formulae of modified kernels and
truncation coefficients of corresponding integral formulae according to
methods of Meissl, Wong and Gore (WG), Heck and Gruningar (HG), Molodensky
(Mol), Vanicek and Kleusberg (VK), and Featherstone, Evans and Oliver
(FEO).</title>
                  </caption>
                  <graphic xlink:href="1982-2170-bcg-21-01-00189-gt1.png"
position="float" orientation="portrait"></graphic>
```

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by robertatakenaka** [comment]
@javani: você quer dizer que o graphic fica fora do caption?

```xml
<caption>
                     <title>Mathematical formulae of modified kernels and
truncation coefficients of corresponding integral formulae according to
methods of Meissl, Wong and Gore (WG), Heck and Gruningar (HG), Molodensky
(Mol), Vanicek and Kleusberg (VK), and Featherstone, Evans and Oliver
(FEO).</title>
                  </caption>
                  <graphic xlink:href="1982-2170-bcg-21-01-00189-gt1.png"
position="float" orientation="portrait"></graphic>
```

**Comment by javani** [comment]
@robertatakenaka desculpa, vem sem a informação de inline-graphic, fica só
graphic no XML.

2015-03-13 10:17 GMT-03:00 Roberta Takenaka <notifications@github.com>:

> @javani: você quer dizer que o graphic fica fora do caption?
>
> ```xml
> <caption>
> <title>Mathematical formulae of modified kernels and
> truncation coefficients of corresponding integral formulae according to
> methods of Meissl, Wong and Gore (WG), Heck and Gruningar (HG), Molodensky
> (Mol), Vanicek and Kleusberg (VK), and Featherstone, Evans and Oliver
> (FEO).</title>
> </caption>
> <graphic xlink:href="1982-2170-bcg-21-01-00189-gt1.png"
> position="float" orientation="portrait"></graphic>
> ```
>
> Roberta Takenaka
>
> SciELO - Scientific Electronic Library Online
> FAPESP - CNPq - BIREME - FapUNIFESP
> www.scielo.org | www.scielo.br
> ______________________________
> Avenida Onze de Junho, 269
> 04041-050 - São Paulo-SP - Brasil
> Tel.: 55-11-5083-3639
>
>
> On Fri, Mar 13, 2015 at 9:54 AM, javani <notifications@github.com> wrote:
>
> > O erro não ocorre mais em body, mas ocorre em app-group. Enviado arquivo
> > via email
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/scieloorg/PC-Programs/issues/1271#issuecomment-78958435
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/PC-Programs/issues/1271#issuecomment-78965827>
> .
>



-- 
Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

**Comment by robertatakenaka** [comment]
@javani: no meu funcionou. Só não funcionou a tabela 3 porque faltou idenficar um graphic.

```xml
         <app id="app01">
            <label>APPENDIX</label>
            <p>
               <table-wrap id="t3" position="float" orientation="portrait">
                  <label>Table 3</label>
                  <caption>
                     <title>: Statistics of errors of generated SGG data at different <inline-graphic xlink:href="1982-2170-bcg-21-01-00189-it4.png"></inline-graphic> using modified estimators to <italic>L</italic> = 150 and <inline-graphic xlink:href="1982-2170-bcg-21-01-00189-gt4.png"></inline-graphic> gravity anomalies at sea level. Unit: 1 mE. </title>
                  </caption>
                  <graphic xlink:href="1982-2170-bcg-21-01-00189-it4.png" position="float" orientation="portrait"></graphic>
               </table-wrap>
            </p>
            <p>
               <table-wrap id="t4" position="float" orientation="portrait">
                  <label>
                     <bold>Table 4</bold>:</label>
                  <caption>
                     <title>Statistics of errors of generated gradients from <inline-graphic xlink:href="1982-2170-bcg-21-01-00189-gt4.png"></inline-graphic> gravity anomalies at different <inline-graphic xlink:href="1982-2170-bcg-21-01-00189-it4.png"></inline-graphic> and <italic>L</italic> = 75. Unit: 1 mE. </title>
                  </caption>
                  <graphic xlink:href="1982-2170-bcg-21-01-00189-gt4.png" position="float" orientation="portrait"></graphic>
               </table-wrap>
            </p>
            <p>
               <table-wrap id="t5" position="float" orientation="portrait">
                  <label>
                     <bold>Table 5</bold>:</label>
                  <caption>
                     <title>Statistics of errors of generated gradients for <inline-graphic xlink:href="1982-2170-bcg-21-01-00189-gt5.png"></inline-graphic> at different degrees of modification. Unit: 1 mE. </title>
                  </caption>
                  <graphic xlink:href="1982-2170-bcg-21-01-00189-gt5.png" position="float" orientation="portrait"></graphic>
               </table-wrap>
            </p>
            <p>
               <table-wrap id="t6" position="float" orientation="portrait">
                  <label>Table 6:</label>
                  <caption>
                     <title>Statistics of errors of generated gradients using the modified estimator with <inline-graphic xlink:href="1982-2170-bcg-21-01-00189-it6.png"></inline-graphic> and  with <italic>L</italic> = 100 and 125 from <inline-graphic xlink:href="1982-2170-bcg-21-01-00189-it6.png"></inline-graphic> gravity anomalies. Unit: 1 mE. Mean (M). </title>
                  </caption>
                  <graphic xlink:href="1982-2170-bcg-21-01-00189-it6.png" position="float" orientation="portrait"></graphic>
               </table-wrap>
            </p>
         </app>

```
