### ISSUE TITLE
Site SciELO apresenta imagem com problemas

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#129]
Na revista BJMBR v46n10 as imagens apresentam uma faixa preta ao lado da imagem, o que não existe na imagem do pacote. Informo ainda que no pacote enviado ao FTP continha imagens nos formatos .tif e .jpg. Exemplo:

![img_comerro](https://f.cloud.github.com/assets/4397365/1362607/634f2750-381d-11e3-8884-5a58e1b8f7f4.jpg)

Verificar em:
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-879X2013001000861&lng=en&nrm=iso&tlng=en

**MODULO- ArticlePage
PRIORIDADE- Medium**

**Comment by robertatakenaka** [comment]
Erro BJMBR (já foi conversado com eles)
