### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Seções não são identificadas ao marcar o [xmlbody]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1293]
Verificamos que o programa Markup não identifica as seções e subseções no corpo do texto, bem como as referências indicadas no body. Veja:

![secoes](https://cloud.githubusercontent.com/assets/4397365/6897120/cb1e4eac-d6c7-11e4-9173-4ac5d5de99f5.jpg)

Obs.: as referências bibliográficas foram identificadas corretamente.

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1293

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka Obs.: Eu retirei todos os links do documento, apaguei a tag [xmlbody] e remarquei. Dessa forma foi possível identificar as seções e refs de autor no corpo do texto.

**Comment by robertatakenaka** [comment]
@leticiaquino : eu vou precisar analisar...

**Comment by leticiaquino** [comment]
@robertatakenaka ocorreu com mais um arquivo. Porém nesse documento eu retirei todos os links antes de iniciar a marcação e formatei as seções de acordo com o que foi especificado.

Veja:
![error-xmlbody](https://cloud.githubusercontent.com/assets/4397365/7300476/cd2e4672-e9b2-11e4-8858-9ea8688000e8.jpg)


Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1293\outro

**Comment by leticiaquino** [comment]
@robertatakenaka além disso, ao fazer a marcação manual das seções, o programa exclui as últimas tags de parágrafo e mantém o [/sec]. Veja:

![sec-erroe](https://cloud.githubusercontent.com/assets/4397365/7300847/3b49beb4-e9b5-11e4-980e-5522fa15e986.jpg)
Obs.: é o mesmo arquivo encontrado em: Y:\SciELO_team\XML_PMC\TICKETS\1293\outro
