### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Programa não identifica corretamente ref "previous"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1295]
Markup não recupera nome para autor do tipo Previous. Veja:

![previous-com-erro](https://cloud.githubusercontent.com/assets/4397365/6897264/d620e084-d6c8-11e4-8d30-7a88acb8710b.jpg)
Nesse caso, deveria ter sido recuperado o nome do autor da referência de cima.

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1293

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : houve a necessidade de modificar a lógica.

Agora tem-se que marcar o ______ como *pauthor. Fazendo isso, o programa marcará corretamente cada previous.
