### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Programa não valida corretamente "refstatus" em referência

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1302]
Percebi que se for inserido o valor "incomplete" em uma referência que apresenta todos os dados necessários, mesmo assim o programa gera o arquivo xml com o atributo @specific-use="display-only". Veja:

markup:
![incomplete-markup](https://cloud.githubusercontent.com/assets/4397365/6919440/5ee2ef24-d78d-11e4-9384-b832158f6b0c.jpg)

XML
![incomplete](https://cloud.githubusercontent.com/assets/4397365/6919443/64a267aa-d78d-11e4-9e7f-6d5b04d90b52.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1302

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : o markup não tem capacidade de avaliar se o refstatus está correto. O relatório de avaliação do conteúdo acusa erro?
