### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Programa não gera arquivo .xml para PMC

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1306]
Programa não gera arquivo .xml para PMC.
Foi verificado que o programa Markup consegue gerar arquivo .xml para SciELO, mas ao entrar na pasta "pmc_package" notamos que não há nenhum arquivo. Veja:

![pasta-vazia-pmc](https://cloud.githubusercontent.com/assets/4397365/6926402/5e197ec6-d7bc-11e4-8100-d3a669edb782.jpg)

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : o package maker somente gerará pmc para as revistas que tem nlm-ta. Se não for o caso, é bug.

**Comment by leticiaquino** [comment]
@robertatakenaka Ok. Funciona conforme esperado.

**Comment by leticiaquino** [comment]
@robertatakenaka Verifiquei que o programa voltou a não gerar o arquivo .xml para pmc em "pmc_package".  Veja:

![pasta-pm-nada-vazia](https://cloud.githubusercontent.com/assets/4397365/7075277/06e185dc-ded7-11e4-83c1-d907c4f00547.jpg)

e ainda, ao clicar em "Relatório de Estilos PMC", o programa volta para a tela "Relatório de Erros de Arquivos/DTD". Veja:

![relatorio-pmc](https://cloud.githubusercontent.com/assets/4397365/7075330/72db81c0-ded7-11e4-81e9-4b719858b3fa.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1306

**Comment by leticiaquino** [comment]
@robertatakenaka notei que esse arquivo gerou esse erro, pois o histórico estava com marcação incompleta. Após marcar a data de recebido e aceito e também corrigir a marcação de nome e sobrenome da segunda afiliação, o programa conseguiu gerar o relatório pmc corretamente e também o xml em pmc_package.

**Comment by robertatakenaka** [comment]
@leticiaquino : entendi... Preciso ajustar quando o XML não é gerado corretamente... Preciso verificar.

**Comment by robertatakenaka** [comment]
@leticiaquino : No markup sempre gerar o relatório de PMC. No entanto, seu conteúdo depende de se é ou não um artigo PMC e/ou se há erro no XML.

**Comment by leticiaquino** [comment]
@robertatakenaka marquei um arquivo como BJMBR (que é MedLine, portanto apresenta título nlm-ta) e gerei o arquivo .xml, porém o programa não gerou o arquivo .xml em pmc_package. Veja:

![pmc-packagers](https://cloud.githubusercontent.com/assets/4397365/7162225/d66b2c4a-e369-11e4-94c2-c8cbde796aab.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1306\outro

**Comment by robertatakenaka** [comment]
@leticiaquino: Havia algum erro? de DTD, por exemplo? Se há algum erro não
gerará.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-04-15 12:21 GMT-03:00 Letícia Aquino <notifications@github.com>:
