### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Identificação incompleta de autores para editorial com sig-block

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1308]
Verificamos que para arquivos editoriais que apresentam assinatura, a identificação de autores é realizada ainda em [sigblock], porém ao copiar as afiliações para o inicio do texto e marcar com a tag [normaff], essa informação é suprimida do documento XML. Veja:

No Markup:
![normaff-sig](https://cloud.githubusercontent.com/assets/4397365/6940507/0cb792e2-d84e-11e4-8902-becd5a4f0795.jpg)
![sig-block-mkp](https://cloud.githubusercontent.com/assets/4397365/6940515/2cdc1c14-d84e-11e4-991f-0413d2696099.jpg)

No XML:
![aff-sig-ed](https://cloud.githubusercontent.com/assets/4397365/6940530/52e8cf2e-d84e-11e4-9330-8541dd2d048e.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1308

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : sendo assim, deveria também haver o xref dentro de cada sig. A marcação deve ser corrigida também, pois o link entre autor e aff é obrigatório para scielo.

**Comment by leticiaquino** [comment]
@robertatakenaka nesse caso que não há label não existe a possibilidade de identificar uma [xref]. Verifiquei também em  ao marcar o [sig] de cada editor abre-se uma janela com apenas 1 campo, de "role". Veja:

![sig-sem-id](https://cloud.githubusercontent.com/assets/4397365/6942416/dbba3982-d85d-11e4-8be2-467ec6cb45f6.jpg)

é possível acrescentar um campo de rid nessa janela?
