### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Não é possível identificar [attrib] em [verse-group]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1309]
Verificamos que ao selecionar um verso por inteiro, o programa Markup faz a marcação automática do [versegrp] e [verseline], porém não é apresentado a possibilidade de identificação de [attrib]. Percebemos que para isso, é necessário desmarcar a tag [verseline] que identifica o autor do verso para depois identificar com o elemento [attrib]. Veja:

![verse-line](https://cloud.githubusercontent.com/assets/4397365/6944738/b7ad1b96-d86b-11e4-9a79-36f8a20cb5e3.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1309

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : Foi considerado que attrib é opcional. Ele é obrigatório?

**Comment by leticiaquino** [comment]
@robertatakenaka  realmente, é opcional. Tícket resolvido.
