### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Programa apresenta lentidão para gerar arquivo .xml

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1312]
Por gentileza, verificar a possibildade de otimizar o tempo de gerar o documento .xml. A versão .90 tem apresentado lentidão além do comum.

**Comment by robertatakenaka** [comment]
@leticiaquino : ao resolver o #1292, este deve ter sido resolvido também. Favor, verificar.

**Comment by leticiaquino** [comment]
@robertatakenaka Agora está melhor.
