### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Erro em identificação de figuras

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1328]
Verificamos que ao fazer a marcação de uma figura, o ID apresentado é "ch" em vez de "f+nºde ordem". Porém, se corrigido para o ID correto o programa nao apresenta erros. 
Veja:

![id-figs-ch](https://cloud.githubusercontent.com/assets/4397365/7006839/aa78719e-dc5a-11e4-860e-09731cec24d7.jpg)

Outro problema encontrado é ao clicar em [Continuar] no campo de ID de figuras. O programa apresenta o seguinte erro:

![fig-erro-graphic](https://cloud.githubusercontent.com/assets/4397365/7006841/af53d000-dc5a-11e4-87c6-c93acba11ae3.jpg)

Obs.: Nesse último caso, se clicarmos em [OK] a imagem é marcada sem nenhum problema.

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1328

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka após a atualização do Markup para o 40090-40(2).zip percebi que o erro continua. Veja:
![figura-errorr](https://cloud.githubusercontent.com/assets/4397365/7044352/f702af60-ddc8-11e4-98ea-139bcf54ff05.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino : tentar novamente.

**Comment by leticiaquino** [comment]
@robertatakenaka O arquivo foi testado novamente, porém agora na versão mais recente do programa Markup e o resultado foi positivo. Veja:

![ch-fiiig](https://cloud.githubusercontent.com/assets/4397365/11810316/3d09ed14-a314-11e5-98e3-d11189465752.jpg)


Ticket resolvido.
