### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Programa apresenta erro ao identificar xmlbody com imagem

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1330]
Verificamos que o programa Markup apresenta o erro abaixo ao fazer a marcação do [xmlbody] quando há imagens.

![erro-xmlbody-img](https://cloud.githubusercontent.com/assets/4397365/7006919/5e65e7fe-dc5b-11e4-9483-a860491e896d.jpg)

Relacionado ao tícket:  #1328 

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\132

**MODULO - MarkupXML
PRIORIDADE- Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka Programa continua a apresentar o erro. Veja:

![error-img-xmlbody](https://cloud.githubusercontent.com/assets/4397365/7031942/aa57ba4e-dd45-11e4-9cbb-e651192e8cf9.jpg)

Arquivo e temp disponíveis em:

Y:\SciELO_team\XML_PMC\TICKETS\1330

**Comment by leticiaquino** [comment]
@robertatakenaka o programa continua a apresentar esse erro. Veja:

![error-body-eq](https://cloud.githubusercontent.com/assets/4397365/7122733/b6fd8ffa-e1f3-11e4-8365-3b415640294a.jpg)

Ao clicar em [OK] é apresentado outra janela:

![error-body2-eq](https://cloud.githubusercontent.com/assets/4397365/7122741/c87565c8-e1f3-11e4-9590-12df5cf7de7a.jpg)

Ao clicar em [OK] é apresentado mais uma janela:

![error-body3-eq](https://cloud.githubusercontent.com/assets/4397365/7122744/d112d814-e1f3-11e4-840a-dc1733f10f79.jpg)

Ao clicar em [OK], verifiquei que o programa marca apenas links e [graphic] de imagens. Veja:

![links-e-img](https://cloud.githubusercontent.com/assets/4397365/7122785/002982f6-e1f4-11e4-8b54-f6e200d5d40c.jpg)


Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1330\outro

**Comment by robertatakenaka** [comment]
@leticiaquino :
1330/outro: converti para .doc e não indicou nenhum erro
1330: não consegui abrir o arquivo. Acho que a versão do Word que tenho teve problema para ler o arquivo
1328: converti para .doc e não indicou nenhum erro

Pode testar se convertendo para .doc funciona?

**Comment by leticiaquino** [comment]
@robertatakenaka  depois que converti o 1330/outro o programa fez a marcação do [xmlbody] corretamente.

O 1330 é aquele caso em que o programa apresenta o erro acima e ainda insere links. Veja:
![links-xmlbody](https://cloud.githubusercontent.com/assets/4397365/7141059/8cf7114c-e2a5-11e4-9a9c-7e0e213255ac.jpg)

porém esse problema já foi resolvido, pois ao marcar o xmlbody desse arquivo não foi apresentado o erro.

O arquivo 1328, após eu converter de .docx para .doc o programa não apresentou mais o erro acima.

**Comment by leticiaquino** [comment]
@robertatakenaka de acordo com o comentário acima, o problema já foi resolvido.
Entretanto, eu testei novamente e o arquivo não apresentou nenhum erro apontado. 

Disponibilizo o resultado dos arquivos em:

Y:\SciELO_team\XML_PMC\TICKETS\1330\resultado
