### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Em sub-article @rid de tabelas e figuras deve ser incremental

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1341]
Verificamos que o programa Markup não dá sequência nos @rids de tabelas e figuras em sub-article, apenas em IDs. Veja:

![rids-increm](https://cloud.githubusercontent.com/assets/4397365/7023487/f71770ac-dd0b-11e4-98d1-26c0a7c07f81.jpg)

Verificar a possibilidade de automatizar essa sequencia para @rids em sub-article, assim como é feito para IDs.

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1341

**MODULO - MarkupXML
PRIORIDADE- Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : isso deve ficar manual mesmo. O usuário deverá corrigir usando o edit.

**Comment by robertatakenaka** [comment]
assumimos que o processo deverá ser feito manualmente
