### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Não manter separadores entre tags

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1342]
Percebemos que o programa Markup mantém separadores como vírgula, entre tags no XML. veja:

![separador](https://cloud.githubusercontent.com/assets/4397365/7023792/4cbcfaca-dd0e-11e4-8dfa-e82cfc0d5106.jpg)

Verificar a possibilidade de excluir qualquer dado que não esteja identificado em uma tag.

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1342

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : acho complicado porque podemos ter uma exceção. Então, acho melhor manter assim, e remover manualmente. (a discutir)

**Comment by robertatakenaka** [comment]
@leticiaquino : uma possibilidade seria marcar [ign] e aí o que estiver em [ign] não vai pro xml. O que acha?

**Comment by leticiaquino** [comment]
@robertatakenaka verificar a possibilidade de não permitir pontuação para os ítens abaixo:

```<element-citation>```
Do not include punctuation. Tag reference that require punctuation in the XML with ```<mixed-citation>```.

```<xref>```
Used to references to objects within the article. Do not include emphasis or punctuation within the element.
If there are multiple <xref> elements in the same <contrib>, do not include punctuation between them.

Obs.: O trecho em inglês foi extraído da documentação PMC: http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html

**Comment by robertatakenaka** [comment]
@leticiaquino : vou remover ao gerar o xml do pmc. Para o nosso xml, vou manter. Concorda?
