### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Não é possível apagar a tag [et-al] utilizando a tag "Apagar tag"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1344]
Não é possível apagar a tag [et-al] utilizando o botão "Apagar tag". Veja:

![apagar-tag](https://cloud.githubusercontent.com/assets/4397365/7025698/b9f35f3c-dd1b-11e4-9766-07c6b5598a63.jpg)

Obs.: a tag foi selecionada corretamente.

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1344

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : tente selecionando o nome completo et-al.

**Comment by leticiaquino** [comment]
@robertatakenaka Roberta, eu havia selecionado o nome completo e mesmo assim não foi possível. Porém ao testar novamente esse método de selecionar toda a tag e desmarcar, notei que após a atualização do Markup para a versão 4.0.090-40.zip não é possível apagar nenhuma tag do documento. Veja o erro apresentado:

![erro-apagartag](https://cloud.githubusercontent.com/assets/4397365/7028857/3dde7a3a-dd2f-11e4-91a3-1d754095cabe.jpg)

Depois aparece o seguinte erro:

![erro-apagar-tagss](https://cloud.githubusercontent.com/assets/4397365/7028878/64ae400a-dd2f-11e4-927b-2d370b6b1147.jpg)

Obs.: Os testes feitos foram: Selecionei toda a tag e tentei apagar, selecionei uma parte da tag e tentei apagar e selecionei outras tags como [doc], [sec], [refs], [authors] etc e o resultado foi o mesmo. 

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1344\outroerro

**Comment by leticiaquino** [comment]
@robertatakenaka atualizei o Markup com o arquivo 40090-42.zip enviado ontem às 16:25, e percebi que o erro continua. Ainda não é possível apagar a tag [et-al] sem precisar selecionar toda a tag manualmente.

**Comment by leticiaquino** [comment]
@robertatakenaka outra observação, ao marcar autores e "et-al" com a tag [*authors], essa tag identifica o [et-al] fora de [/authors]. Veja:
![authors](https://cloud.githubusercontent.com/assets/4397365/7067315/a2141cea-dea0-11e4-99e9-2f3be6c4e3be.jpg)
