### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Erro em marcação de autores com [*authors]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1356]
Verificamos que o programa apresentou erro na marcação de autores alguns autores Veja:

![authors-automatr](https://cloud.githubusercontent.com/assets/4397365/7045408/400623da-ddd4-11e4-9148-3fe50f2a103b.jpg)

A marcação não é finalizada.

Percebi que se alterar o nome de "Jr." para "J." ou "J.J." o programa também não completa a identificação desses autores.

Arquino disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1356

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka informo que juntei os nomes "Lopes" e "Jr." sem o ponto, ficando da seguinte forma:

"LopesJr, V." e ao selecionar todos os autores os nomes foram marcados corretamente. veja:
![lopes-jr-authors](https://cloud.githubusercontent.com/assets/4397365/7045610/0d0ddcd2-ddd6-11e4-8351-a7d51068c121.jpg)

**Comment by leticiaquino** [comment]
@robertatakenaka outro caso:

![errooor-authorrs](https://cloud.githubusercontent.com/assets/4397365/7046852/1eefb03e-dddf-11e4-9203-6d68336d7177.jpg)

Arquivo em:
Y:\SciELO_team\XML_PMC\TICKETS\1356\outro

**Comment by leticiaquino** [comment]
@robertatakenaka Resolvido.

**Comment by leticiaquino** [comment]
@robertatakenaka retificando..
testei em um outro arquivo onde há autores indicados da seguinte maneira: "**Pasternak-Junior B**,Sousa-Neto MD, Silva RG" e ao marcar os autores com o botão [*authors], o programa identifica da seguinte forma:

![authorrrss-error-2](https://cloud.githubusercontent.com/assets/4397365/7070801/b513b988-deb7-11e4-877d-559078536fdc.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1356\outro2-author

**Comment by robertatakenaka** [comment]
@leticiaquino : os padrões esperados estão em #1009.
