### ISSUE TITLE
(Markup 4.0.090 - Word 2013) [*source] não está funcionando corretamente

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1357]
Verificamos que o [* source] não está funcionando conforme o esperado. Veja que ao selecionar a revista "Journal of intelligent Material Systems and Structures" e marcar com a tag [*source], o programa não marca na referência abaixo:

![source-autmorat](https://cloud.githubusercontent.com/assets/4397365/7045690/aa53fe04-ddd6-11e4-9219-fe5b21f5a5fe.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1357

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : Não identificou porque o texto teria que ser idêntico inclusive nas maíusculas/minúsculas. O i de Intelligence está em minúscula.

Já ocorreu de source igual a Dados e haver a palavar dados no título do artigo, por exemplo.
Sendo assim, resolvi que tem que ser idêntico quando houver até 3 palavras, acima disso não importa se é maiúsculo/minúsculo.

**Comment by leticiaquino** [comment]
@robertatakenaka resolvido.
