### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Markup apresenta erro de pouca memória em arquivo com muitas fórmulas

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1358]
Verificamos que ao fazer a marcação de [xmlbody] de um arquivo com muitas fórmulas/equações, o programa apresenta erro de memória. Veja:

1º erro:
![error-memor](https://cloud.githubusercontent.com/assets/4397365/7046061/a1710a04-ddd9-11e4-89b2-e3c3d01580a3.jpg)

2º erro:
![2error-memm](https://cloud.githubusercontent.com/assets/4397365/7046074/b0c6d268-ddd9-11e4-93eb-8190a3ef0499.jpg)

3º erro:
![3-error-memm](https://cloud.githubusercontent.com/assets/4397365/7046077/b6bae2fe-ddd9-11e4-9659-1d5b3f835337.jpg)

Ao clicar em OK, o programa faz a marcação de todos os [graphic] do arquivo, mas não marca [xmlbody], [sec], [p] etc..

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1358

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka Inseri a pasta temp no mesmo diretório, caso seja necessário.

**Comment by leticiaquino** [comment]
@robertatakenaka ocorreu em outro arquivo também, porém esse outro arquivo não apresenta equações.

Disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1358\outro

**Comment by leticiaquino** [comment]
@robertatakenaka consegui fazer a marcação do [xmlbody] desse arquivo, porém ao gerar o arquivo XML é apresentado o seguinte erro:

![erro-arq-memmo](https://cloud.githubusercontent.com/assets/4397365/7069343/9cb1d8a6-deae-11e4-860e-f33ff6975606.jpg)

**Comment by leticiaquino** [comment]
@robertatakenaka Obs.: Notei que essa informação "Main.SaveDocumentAsSciELOMarkup..." apareceu, pois o programa não reconheceu um símbolo matemático. Ao retirar esse símbolo o programa gerou o arquivo .xml corretamente e a janela não apareceu.

o símbolo que apresenta erro é o que segue abaixo:
![simboloooo](https://cloud.githubusercontent.com/assets/4397365/7069926/f100115e-deb1-11e4-8826-d5c0a872e203.jpg)

No XML o símbolo aparece da seguinte forma:

![simbolooos](https://cloud.githubusercontent.com/assets/4397365/7069979/414a4774-deb2-11e4-8d1b-b42414abdcfc.jpg)

Arquivo disponivel em:

Y:\SciELO_team\XML_PMC\TICKETS\1358\simbolo

**Comment by robertatakenaka** [comment]
@leticiaquino : acho que isso é outra coisa. Pode abrir um ticket somente para isso.
