### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Marcação de autores com o botão [*authors] ou [authors] envolve a data

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1374]
Verificamos que ao selecionar os autores de uma referência e marcar com  o botão  [*authors] ou [authors], o programa envolve a data dentro de [fname]. Veja:

![authors-error](https://cloud.githubusercontent.com/assets/4397365/7087714/813145f6-df64-11e4-85a7-a1471d519757.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1374

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
Há link na referência que quando selecionados os autores também é selecionada a data, pois ambos fazem parte do link
