### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Programa gera Relatorio de estilos sem erro e relatório interativo com fatal error

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1377]
Verificamos que o programa Markup gera Relatório de Estilos SciELO sem nenhum erro:

![relatorio-erros-ok](https://cloud.githubusercontent.com/assets/4397365/7088861/b0ee643c-df6d-11e4-9bd5-740ff4dbd947.jpg)

Porém no "Relatório de erros de Conteúdo" é apresentado um Fatal Error:

![relatorio-erros-interestrt-erorr](https://cloud.githubusercontent.com/assets/4397365/7088871/ca20927c-df6d-11e4-984e-fa7dd97f09f6.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1377

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : tente apagar o work e gerar de novo.
