### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Erro em apresentação de box de afiliação

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1380]
O "relatório de erros de conteúdo" apresenta erro em box de afiliação marcada. veja:

![relatoriodeerros-conteudo](https://cloud.githubusercontent.com/assets/4397365/7093443/9dab4aee-df8f-11e4-9eaa-bb65bc678025.jpg)

O box é apresentado em posição incorreta e aparenta estar flutuante.

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1380

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
#1381
