### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Sugestão de nova apresentação para box de trechos de xml

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1381]
Verificar  a possibilidade de apresentar os trechos de XML (ex.: afiliação, referência bibliográfica etc..) estruturada. Perceba que atualmente é inserido uma caixa com duas barras de rolagem, uma que funciona apenas para os lados e outra ao lado que não funciona:

![estrutura-aff](https://cloud.githubusercontent.com/assets/4397365/7093566/c022257e-df90-11e4-93a4-bfd9c2dbb55a.jpg)

É possível uma estrutura semelhante com a que segue abaixo?
![estryuteya](https://cloud.githubusercontent.com/assets/4397365/7093622/25c1de4c-df91-11e4-8ec2-a03f4be9ff30.jpg)

Outra possibilidade seria usar o recurso 'onclick="openClose('datarep1')" ' para esses trechos.

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1381

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
RESOLVIDO DE OUTRA FORMA
![captura de tela 2015-12-14 as 17 22 10](https://cloud.githubusercontent.com/assets/505143/11791622/0fadfb16-a289-11e5-87b8-029ea7f0e3a4.png)
