### ISSUE TITLE
(Markup 4.0.090 - Word 2013) equações - [/equation] e [/graphic] ordem invertida

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1384]
Verificamos que o programa Markup insere as tags [/equation] e [/graphic] em ordem invertida. Veja:

![equation-eerrs](https://cloud.githubusercontent.com/assets/4397365/7095238/fcc05808-df9e-11e4-9aab-a7204d053a8a.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1384
**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : quando eu testei funcionou. Tente converter .docx para .doc. Veja se funciona.

**Comment by leticiaquino** [comment]
@robertatakenaka fiz o teste com o mesmo documento, porém agora na versão mais recente do programa Markup e o resultado foi positivo:

![eq-ok](https://cloud.githubusercontent.com/assets/4397365/11809897/40138ef0-a311-11e5-921b-49682977ce98.jpg)

Ticket resolvido.
