### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Markup não identifica corretamente o @mime-subtype

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1390]
Verificamos que o programa Markup não identifica corretamente o @mime-subtype. Veja:

![mime-subtype-error](https://cloud.githubusercontent.com/assets/4397365/7117861/f201fe46-e1d1-11e4-901f-1db47cb8e7d7.jpg)

Na marcação de material suplementar não há a opção para inserir o tipo do arquivo. Veja:

![marcacao-suppl-formats](https://cloud.githubusercontent.com/assets/4397365/7117922/462280e0-e1d2-11e4-814c-e042b3893924.jpg)

Conferir listagem de valores dos atributos @mimetype e @mime-subtype:
http://www.iana.org/assignments/media-types/media-types.xhtml

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1390

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : vai ficar na categoria que não será resolvido. Este tipo o python obtem do próprio arquivo. ESta tabela que você indicou provavelmente não é estática, vai sofrer evolução, assim não se pode fixar nela tampouco.

**Comment by robertatakenaka** [comment]
assumimos que o processo deverá ser feito manualmente
