### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Markup mantém formatação de <article-title>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1409]
Verificamos que o programa Markup mantem a formatação de ```<article-title>``` e da tradução também. Veja:

![bold-title](https://cloud.githubusercontent.com/assets/4397365/7166917/7519b16e-e387-11e4-92a8-4c230a0915c6.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1409

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : pode manter italic?

**Comment by leticiaquino** [comment]
@robertatakenaka italic pode manter.
