### ISSUE TITLE
Correção XSLT: Agradecimentos

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#141]
Em <sub-article>, em <ack> aparece título em inglês "ACKNOWLEDGEMENTS" para todos os idiomas.
Ex.: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0080-62342013000300539&lng=en&nrm=iso
Modulo: ArticlePage, Prioridade:Minor

**Comment by leticiaquino** [comment]
@robertatakenaka  esse tícket e o #69 Deve ser resolvido no web: https://github.com/scieloorg/Web/issues/139
