### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Programa não gera o report PMC

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1423]
Verifiquei que ao tentar gerar o relatório PMC o programa apresenta o seguinte erro:

![error-pmc-report](https://cloud.githubusercontent.com/assets/4397365/7203549/bac29f94-e4f1-11e4-83de-d75ffcb8d509.jpg)

Ao clicar em [OK] o Programa volta para a tela inicial.
Tentei gerar o relatório depois de alguns minutos, mas o resultado foi o mesmo.

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1423
**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : funcionou para mim.
