### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Resumos - Não apresentar mensagem de marcação de ref ao identificar resumos.

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1427]
Ao fazer a marcação de resumos o programa Markup apresenta a seguinte mensagem:

![erro-marcacao-resumos](https://cloud.githubusercontent.com/assets/4397365/7208266/ea381636-e515-11e4-9695-d2cbaf4d9fde.jpg)

Verificar a possibilidade de não apresentar a mensagem de erro.

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1426

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino: esta mensagem aparece para que a referências no abstract
sejam identificadas. No entanto, se for desejával não se marca as
referências dentro de abstract.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-04-17 15:26 GMT-03:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka é possível que tenha citação de autor em resumos, porém não aparece com frequencia. Então nesse caso há a possibilidade de tirar essa possível marcação automática e esses "alertas", mas permitir que seja feito a identificação manual da citação do autor, se existir?
