### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Markup não identificou os 2 últimos autores

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1433]
Verificamos que o programa Markup não fez a marcação automática dos dois últimos autores do documento. Veja:

![nmarcacao-erradr](https://cloud.githubusercontent.com/assets/4397365/7299583/32a67b42-e9ad-11e4-8867-8a7ee5421d10.jpg)

Verificar se o programa não fez a identificação dos dois ultimos autores, pois o penúltimo autor apresenta nome oriental com poucas letras.

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1433

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka acredito que o erro foi causado pelo autor "So Yin NAK", pois ao inverter  a ordem no documento, o programa marcou corretamente, deixando apenas esse autore sem marcação. Veja:

![authors-ereror](https://cloud.githubusercontent.com/assets/4397365/7299893/0482d11e-e9af-11e4-96c0-94631be285fa.jpg)

**Comment by leticiaquino** [comment]
@robertatakenaka outra coisa, acredito que por esse problema do nome do autor, o programa não identifica a afiliação. Veja:

![erroorr](https://cloud.githubusercontent.com/assets/4397365/7300017/aeb60714-e9af-11e4-94f0-90e9dcd519e0.jpg)

**Comment by javani** [comment]
@robertatakenaka @leticiaquino houve alguns artigos da bwho que isso também ocorreu, mas aí marcamos na mão, já que foi pontual e não ocorreu em todos os arquivos
