### ISSUE TITLE
(markup 090 - word 2013) Previewer de capítulo de livro

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1451]
Quando há previewer de capítulo de livro na referência anterior, quando marca-se a referência seguinte com a tag *pauthor, marca com o autor do livro e não do capítulo conforme segue:

[ref id="r4" reftype="book" status="valid"][authors role="nd"][pauthor][surname]BAZERMAN[/surname], [fname]C.[/fname][/pauthor][/authors] [chptitle]The life of genre, the life in the classroom[/chptitle]. In: [authors role="ed"][pauthor][surname]BISHOP[/surname], [fname]W.[/fname][/pauthor]; [pauthor][surname]OSTROM[/surname], [fname]H.[/fname][/pauthor][/authors] (Ed.). [source]Genre writing: issues, arguments, alternatives[/source]. [publoc]Portsmouth[/publoc]: [pubname]Boynton-Cook Publishers/Heinemann[/pubname], [date dateiso="19970000" specyear="1997"]1997[/date]. p. [pages]19-26[/pages].[/ref]

[ref id="r5" reftype="book" status="valid"][text-ref]______. Atos de fala, gêneros textuais e sistemas de atividades: como os textos organizam atividades e pessoas. In: BAZERMAN, C.. Gêneros textuais, tipificação e interação. São Paulo: Cortez, 2005. p. 19-46.[/text-ref] [authors role="nd"][pauthor][surname]BISHOP[/surname], [fname]W.[/fname][/pauthor] [/authors]. Atos de fala, gêneros textuais e sistemas de atividades: como os textos organizam atividades e pessoas. In: BAZERMAN, C.. Gêneros textuais, tipificação e interação. São Paulo: Cortez, 2005. p. 19-46.[/ref]

**Comment by robertatakenaka** [comment]
@javani : eu acho que não será possível corrigir isso... Apesar de que olhe que na ref 4 está incorreto: 

[/pauthor]/authors

Ficou assim mesmo? Ou ficou errado ao criar o ticket?

**Comment by javani** [comment]
@robertatakenaka foi na hora de colar. No arquivo tá certo.

**Comment by robertatakenaka** [comment]
Há problema também se há indicação de tradutor. Ex.:

[ref id="r1" reftype="book" status="valid"][text-ref]BAKHTIN, M. Gêneros do discurso. In: ______. Estética da criação verbal. Trad. Paulo Bezerra. 4. ed. São Paulo: Martins Fontes, 2003. p. 261-306.[/text-ref] [authors role="nd"][pauthor][surname]BAKHTIN[/surname], [fname]M.[/fname][/pauthor][/authors] [chptitle]Gêneros do discurso[/chptitle]. In: [authors role="nd"][pauthor][surname]BAKHTIN[/surname], [fname]M.[/fname][/pauthor] [/authors]. [source]Estética da criação verbal[/source]. Trad. [authors role="tr"][pauthor][fname]Paulo[/fname] [surname]Bezerra[/surname][/pauthor][/authors]. [edition]4. ed[/edition]. [publoc]São Paulo[/publoc]: [pubname]Martins Fontes[/pubname], [date dateiso="20030000" specyear="2003"]2003[/date]. p. [pages]261-306[/pages].[/ref]
[ref id="r2" reftype="book" status="valid"]BARROS, E. M. D. de. Aproximações entre o funcionamento da Metodologia das Sequências Didáticas e o conceito de Zona de Desenvolvimento Proximal. Calidoscópio, São Leopoldo, v. 11, n. 1, p. 76-89, jan./abr. 2013.[/ref]
[ref id="r3" reftype="book" status="valid"]BORTONI-RICARDO, S. M. O professor pesquisador: introdução à pesquisa qualitativa. São Paulo: Parábola, 2008.[/ref]
[ref id="r4" reftype="book" status="valid"][authors role="nd"][pauthor][surname]BRONCKART[/surname], [fname]J-P[/fname][/pauthor][/authors]. [source]Atividade de linguagem, textos e discursos: por um interacionismo sócio-discursivo[/source]. Trad. [authors role="tr"][pauthor][fname]Anna Rachel Machado e Péricles[/fname] [surname]Cunha[/surname][/pauthor][/authors]. [edition]2[/edition]. reimpr. [publoc]São Paulo[/publoc]: [pubname]EDUC[/pubname], [date dateiso="20030000" specyear="2003"]2003[/date].[/ref]
[ref id="r5" reftype="book" status="valid"][text-ref]______. Atividade de linguagem, discurso e desenvolvimento humano. Org. Anna Rachel Machado e Maria de Lourdes Meireles Matencio. Trad. Anna Rachel Machado et al. Campinas/SP: Mercado de Letras, 2006.[/text-ref] [authors role="nd"][pauthor][fname]Anna Rachel Machado e Péricles[/fname] [surname]Cunha[/surname][/pauthor] [/authors]. Atividade de linguagem, discurso e desenvolvimento humano. Org. Anna Rachel Machado e Maria de Lourdes Meireles Matencio. Trad. Anna Rachel Machado et al. Campinas/SP: Mercado de Letras, 2006.[/ref]
