### ISSUE TITLE
(markup 090 - word 2013) perde formatação em referência com gera XML

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1452]
Altera formatação da referência quando gera o XML. No caso abaixo, título Genre analysis está em itálico. Ele não se mantém no mixed e ainda coloca algumas letras em maiúscula. 

```<ref id="B25">
            <mixed-citation>SWALES, J. M.  genre AnAlysis: English in academic and research settings., Cambridge: Cambridge University Press  1990.</mixed-citation>
            <element-citation publication-type="book">
               <person-group person-group-type="author">
                  <name>
                     <surname>SWALES</surname>
                     <given-names>J. M.</given-names>
                  </name>
               </person-group>
               <source>genre AnAlysis: English in academic and research settings.</source>
               <publisher-loc>Cambridge</publisher-loc>
               <publisher-name>Cambridge University Press</publisher-name>
               <year>1990</year>
            </element-citation>
         </ref>```

**Comment by robertatakenaka** [comment]
@javani : mande o arquivo .doc, por favor.

**Comment by javani** [comment]
2015-04-28 15:51 GMT-03:00 Roberta Takenaka <notifications@github.com>:

> @javani <https://github.com/javani> : mande o arquivo .doc, por favor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/PC-Programs/issues/1452#issuecomment-97168534>
> .
>



-- 
Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*
