### ISSUE TITLE
(markup 090 - word 2013) Não gera report data

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1453]
Não gera report data. Apresenta a mensagem abaixo e volta para a marcação.
![image](https://cloud.githubusercontent.com/assets/912953/7373907/a3f1df66-eda5-11e4-9b90-a60ffabfa6a5.png)

**Comment by robertatakenaka** [comment]
@javani: me manda o arquivo?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
