### ISSUE TITLE
[Converter] Mesmo com "display-only" o converter acusa "Fatal Error" em refs sem info. de ano.

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1454]
Verificamos que o Converter continua a apresentar "FATAL ERROR" em refs sem informações de ano (ou source, authors etc) mesmo quando há o atributo @specific-use="display-only". Veja:

![refs](https://cloud.githubusercontent.com/assets/4397365/7374659/eb210b56-eda9-11e4-95d4-fee57ebcbff0.jpg)

http://homolog.xml.scielo.br/reports/babt/v58n2/xml_converter.html#begin_1516-8913-babt-S1516-8913201400204conv

**Comment by robertatakenaka** [comment]
@leticiaquino : me parece que este atributo era para o ref/@specific-use, estou enganada?

**Comment by leticiaquino** [comment]
@robertatakenaka o correto seria em ```<element-citation>```, porém o Markup tem gerado em ```<ref>```.
