### ISSUE TITLE
(markup 090 - word 2013) Marcação de referência - msg de erro

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1457]
Na marcação das referências bibliográficas com hiperlink na última referência, apresentou o erro abaixo e não fechou com [/ref] a última referência.
![image](https://cloud.githubusercontent.com/assets/912953/7377450/db117a3a-edbc-11e4-9aa8-8f45f2861288.png)

**Comment by robertatakenaka** [comment]
@javani: tenta com .doc no lugar de .docx

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-04-28 15:40 GMT-03:00 javani <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka para mim não ocorre, mesmo com arquivo .docx
