### ISSUE TITLE
(markup 090 - word 2013) Não marca tabela corretamente

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1459]
Ao tentar marcar tabela apresenta o erro abaixo e não fecha table e thead. Enviado arquivo por email.
![image](https://cloud.githubusercontent.com/assets/912953/7378070/304d4020-edc1-11e4-964b-9683a3f501b1.png)

**Comment by robertatakenaka** [comment]
tente com .doc no lugar de .docx

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by javani** [comment]
Desculpa, mandei o errado.

Em 28 de abril de 2015 16:14, Roberta Takenaka <notifications@github.com>
escreveu:

> tente com .doc no lugar de .docx
>
> Roberta Takenaka
>
> SciELO - Scientific Electronic Library Online
> FAPESP - CNPq - BIREME - FapUNIFESP
> www.scielo.org | www.scielo.br
> ______________________________
> Avenida Onze de Junho, 269
> 04041-050 - São Paulo-SP - Brasil
> Tel.: 55-11-5083-3639
>
>
> On Tue, Apr 28, 2015 at 4:12 PM, javani <notifications@github.com> wrote:
>
> > Ao tentar marcar tabela apresenta o erro abaixo e não fecha table e
> thead.
> > Enviado arquivo por email.
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/912953/7378070/304d4020-edc1-11e4-964b-9683a3f501b1.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scieloorg/PC-Programs/issues/1459>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/PC-Programs/issues/1459#issuecomment-97173797>
> .
>



-- 
Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

**Comment by javani** [comment]
O thead fecha o que não está fechando é a [/table]
