### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Programa considera tabelas, listas e trechos de parágrafos como [quote]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1475]
Ao fazer a marcação do [xmlbody], verifiquei que o programa Markup faz a identificação de listas, tabelas e alguns trechos de parágrafos como [quote]. Veja:

![quotes](https://cloud.githubusercontent.com/assets/4397365/7472138/9b40980c-f305-11e4-89b8-37c63ceb4ea8.jpg)

Veja como fica o [xmlbody]:

![quotes-quotes](https://cloud.githubusercontent.com/assets/4397365/7472170/e68db4de-f305-11e4-9b9a-a0d556f987de.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1475

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
RESOLVIDO
