### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Markup apresenta lentidão para marcação de [xmlbody], [table] e [sec]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1483]
Verificamos que o programa apresenta lentidão ao marcar [xmlbody], [table] codificada e [sec] manual.
Principalmente [xmlbody].

**Comment by robertatakenaka** [comment]
dependendo o tamanho do arquivo ou do total de objetos no documento, o programa demora
