### ISSUE TITLE
Na apresentação da referência está duplicando o número da referência

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#149]
Exemplo: RLAE

Corrigir no Web a apresentação das referências.

**Comment by leticiaquino** [comment]
@robertatakenaka a Ref estava duplicando, pois o número foi identificado em ```<label>``` e em ```<mixed-citation>```.

**Comment by robertatakenaka** [comment]
https://github.com/scieloorg/Web/issues/216
