### ISSUE TITLE
(markup 090 - word 2013) Erro marcação automática de autor em ref com et-al

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1490]
Fecha o grupo de autores com [/et-al]

[ref id="r1" reftype=“journal" status="valid"][label]1.[/label] [authors role="nd"][pauthor][surname]Baggaley R[/surname], [fname]Johnson C[/fname][/pauthor], [pauthor][surname]Garcia Calleja JM[/surname], [fname]Sabin K[/fname][/pauthor], [pauthor][surname]Obermeyer C[/surname], [fname]Taegtmeyer M[/fname][/pauthor], [et-al]et al[/authors][/et-al]. [arttitle]Routine feedback of test results to participants in clinic- and survey-based surveillance of HIV[/arttitle]. [source]Bull World Health Organ.[/source] [date dateiso="20150000" specyear="2015"]2015[/date];[volid]93[/volid]([issueno]5[/issueno]):[pages]352-5[/pages]. [url]http://dx.doi.org/10.2471/BLT.15.153031[/url][/ref]

Enviado arquivo via email

**Comment by javani** [comment]
@robertatakenaka o problema na marcação ocorre quando o ponto final não é selecionado.

**Comment by leticiaquino** [comment]
@javani @robertatakenaka esse erro não é causado pela formatação dos autores?
Veja o ticket https://github.com/scieloorg/PC-Programs/issues/1009

Ontem eu testei uma revista que apresentou o mesmo problema, porém ao formatar de acordo com uma das normas que segue, o programa conseguiu fazer a marcação correta.

**Comment by javani** [comment]
@robertatakenaka @leticiaquino em alguns casos a marcação automática falha. Não é por causa da formatação, pois está identifica ao demais. Estou mandando um arquivo por email. Vejam a ref 3. Mesmo desmarcando e marcando novamente apresenta o mesmo problema.
[ref id="r3" reftype=“journal" status="valid"][label]3.[/label] [authors role="nd"][pauthor][surname]Gardner EM[/surname], [fname]McLees MP[/fname][/pauthor], [pauthor][surname]Steiner JF[/surname], [fname]Del Rio C[/fname][/pauthor], [pauthor][surname]Burman WJ.[/surname][/authors] [arttitle]The spectrum of engagement in HIV care and its relevance to test-and-treat strategies for prevention of HIV infection[/arttitle]. [source]Clin Infect Dis[/source]. [date dateiso="20110315" specyear="2011"]2011 Mar 15[/date];[volid]52[/volid]([issueno]6[/issueno]):[pages]793-800[/pages]. [url]http://dx.doi.org/10.1093/cid/ciq243[/url] PMID: [pubid idtype="pmid"] 21367734[/pubid][/ref]

**Comment by javani** [comment]
@robertatakenaka @leticiaquino neste mesmo arquivo, na última referência a tag url fechou depois de refs.
