### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Verificar a possibilidade de add o nome da coleção automaticamente no campo "collection"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1528]
Verificar a possbilidade de inserir automaticamente o nome da coleção no campo "collection".
Esse campo não apresenta nenhuma informação e não é possível selecionar nenhum dado, o que acaba confundindo quem está marcando.

Veja:
![collection](https://cloud.githubusercontent.com/assets/4397365/7684821/7a94bdc2-fd5f-11e4-9686-ebf4031e438d.jpg)

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
resolve com #1534
