### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Markup inverte tags [xref] e [label] quanod há link em "label"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1529]
Verificamos que o programa Markup inverte a ordem das tags quando há link em [label]. Veja:

![tags-ordem](https://cloud.githubusercontent.com/assets/4397365/7686555/f1cb21c6-fd6c-11e4-9921-cf8bdcfe9223.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1529

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka Obs.: Verificar a possibilidade de retirar o link e o [xref] de label. Veja que no PMC não é preciso informação de [xref] em [label]:

http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-nwr0.html
http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-ixv0.html

**Comment by robertatakenaka** [comment]
@leticiaquino : o problema aqui é formatação. Há um espaço no início do label da figura. Sem este espaço o programa identifcará corretamente label.

**Comment by javani** [comment]
@robertatakenaka @leticiaquino acho que não faz sentido ter xref no label da figura já que você está na figura. Não sei se pode ser feito, mas o ideal seria excluir o xref quando fazemos a marcação do grupo de figura, assim como ele faz com os parágrafos.

**Comment by javani** [comment]
@robertatakenaka @leticiaquino replicar a mesma ação para label de tabela.

**Comment by robertatakenaka** [comment]
@javani: o problema foi que o label e caption tinham um espaço no início. Sendo assim, o programa identificou automaticamente que o Figura 1 era xref ao invés de label. Basta retirar o espaço do início do texto para que o programa consiga identificar corretamente.
