### ISSUE TITLE
(Markup 4.0.090 - Word 2013) ao marcar [deflist] o programa desmarca os paragrafos abaixo

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1531]
Verificamos que ao marcar o [deflist], o programa retira a marcação dos parágrafos e seções que constam abaixo. Veja:

![error-deflist](https://cloud.githubusercontent.com/assets/4397365/7705095/962a1014-fe18-11e4-84f3-ae0dc3caac5b.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1531

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
resolvido
