### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Programa apresenta erro ao marcar o [doc]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1534]
Após a atualização do Markup 40090-61.zip, verificamos que o programa Markup apresenta erro ao marcar o [doc] do arquivo. Veja:

**erro 1:**
![erro1-doc](https://cloud.githubusercontent.com/assets/4397365/7710977/04d99726-fe3e-11e4-994d-1df5c7df482f.jpg)

**Ao clicar em [OK], o programa apresenta o segundo erro:**

![erro2-doc](https://cloud.githubusercontent.com/assets/4397365/7710989/14a5f7f8-fe3e-11e4-88e5-b56d0fff728c.jpg)

**Tentando finalizar o processo, ao clicar em [FIM], o programa desabilita os botões destacados na imagem abaixo:**

![erro3-doc](https://cloud.githubusercontent.com/assets/4397365/7711003/296f5530-fe3e-11e4-916e-f0579c3fb9ac.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1534

**MODULO - MarkupXML
PRIORIDADE - Major**

**Comment by leticiaquino** [comment]
Ao executar o script do cmd.log o resultado foi o seguinte:

```code
C:\Windows\System32>c:\python27\python C:\Markup_89\bin\xml\download_markup_journals.py Brazil C:\Markup_89\bin\markup\collections.ctrl
ctrl_file
C:\Markup_89\bin\markup\collections.ctrl
C:/Markup_89/bin/xml/markup/downloaded_markup_journals.csv
ignored:
[]
end

C:\Windows\System32>
```

**Comment by javani** [comment]
Apresenta o mesmo problema para mim.

2015-05-19 16:23 GMT-03:00 Letícia Aquino <notifications@github.com>:

> Ao executar o script do cmd.log o resultado foi o seguinte:
>
> C:\Windows\System32>c:\python27\python C:\Markup_89\bin\xml\download_markup_journals.py Brazil C:\Markup_89\bin\markup\collections.ctrl
> ctrl_file
> C:\Markup_89\bin\markup\collections.ctrl
> C:/Markup_89/bin/xml/markup/downloaded_markup_journals.csv
> ignored:
> []
> end
>
> C:\Windows\System32>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/PC-Programs/issues/1534#issuecomment-103641360>
> .
>



-- 
Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

**Comment by robertatakenaka** [comment]
Faltou incluir uns arquivos. No entanto, após rodar manualmente a linha de
comando, estes arquivos são gerados e o ao reabrir o programa markup, os
dados destes arquivos são carregados e não deve dar mais erro.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
