### ISSUE TITLE
(Markup 4.0.090 - Word 2013)Ao marcar xmlbody o programa desconfigura os símbolos matemáticos de equação

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1548]
Verificamos que, após a versão 40090-65.zip, ao fazer a marcação do [xmlbody] o programa desconfigura símbolos matemáticos de equações.
Veja como a equação estava identificada no arquivo .doc:

![eq-simbol-markjup](https://cloud.githubusercontent.com/assets/4397365/7800543/46ab8f66-02ed-11e5-8e3b-e233a7f8a34e.jpg)

Ao fazer a marcação do xmlbody o programa converteu os símbolos para "quadradinhos". Ao fazer a marcação de equação o programa também não identificou nenhum [graphic]. Veja:

![eq-convert-markup](https://cloud.githubusercontent.com/assets/4397365/7800557/647fd786-02ed-11e5-8edd-859d7b6ff8cf.jpg)

Obs.: apenas de equações. Os símbolos matemáticos no corpo do texto não sofreram mudanças.

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1548

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka obs.: ao gerar o arquivo .xml o programa apresenta o seguinte erro:

![error-s](https://cloud.githubusercontent.com/assets/4397365/7800587/0527c928-02ee-11e5-91a3-ae9ae851e40b.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1548

**Comment by robertatakenaka** [comment]
@leticiaquino : é um caso particular. Terá que ser arrumado manualmente, retirando o itálico.

**Comment by leticiaquino** [comment]
@robertatakenaka Ok. Funcionou quando retirei o itálico.
