### ISSUE TITLE
(markup 090 - word 2013) Erro marcação automática de autor em ref com sufixo

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1549]
Na marcação automática o programa não identifica corretamente autores com sufixo.
[authors role="nd"][pauthor][surname]ALBUQUERQUE[/surname] [fname]JÚNIOR[/fname][/pauthor], [pauthor][surname]D.[/surname] [fname]M.[/fname][/pauthor][/authors]

**Comment by robertatakenaka** [comment]
@javani : identifiquei que o problema é o espaço entre D. e M.
Fiz os ajustes necessários.

**Comment by javani** [comment]
@robertatakenaka Tem também os casos de nomes alemães que não faz a marcação correta (acho que esqueci de abrir ticket) com o *authors, mas acho que neste caso não há como prever.

**Comment by robertatakenaka** [comment]
mas teste mesmo assim, quem sabe já consertou.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-12-16 15:57 GMT-02:00 javani <notifications@github.com>:
