### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Automata de Vancouver remove seção "References" e não faz marcação automática de [label]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1559]
Verificamos que a automata de Vancouver faz a marcação correta em todas as referências, mas apresenta alguns problemas. Veja abaixo:

Ao selecionar toda a informação de refs, incluindo o título "Referências", o programa remove o título  mantendo apenas as marcações.
As referências em Vancouver possui um formato numérico, e ao fazer a marcação automática das refs o programa não identifica o label. Veja:

![ref-she](https://cloud.githubusercontent.com/assets/4397365/7885439/32d72148-05fa-11e5-886f-c9b7b56c849b.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1559

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka @javani.araujo@scielo.org Sem a marcação de [label], o programa não faz a marcação automática das referências cruzadas no corpo do texto. Veja:

![ref-slabels-](https://cloud.githubusercontent.com/assets/4397365/7885917/04e1e8ba-05fd-11e5-95bf-4608324d676e.jpg)

**Comment by leticiaquino** [comment]
@robertatakenaka fiz um teste.
Fiz a marcação manual do label em referências e depois marquei o [xmlbody]. Verifiquei que o programa, mesmo assim, não faz a marcação automática de [xref] no corpo do texto. Veja que minha tentativa foi fazer a marcação antes de tex-ref e também depois de [text-ref]:

![labels-text-](https://cloud.githubusercontent.com/assets/4397365/7886257/30ac00dc-05ff-11e5-82fe-163e7d4fe00c.jpg)


Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1559\outro

**Comment by javani** [comment]
@leticiaquino no teste que fiz, marcou.
[P]Todas as espécies animais têm formas de agir socializadas, porém é no agir verbalizado que o ser humano distingue-se dos demais animais, uma vez que a espécie humana é a única, aparentemente, a ter desenvolvido a linguagem verbal e a mobilizar signos organizados em artefatos semióticos repletos de sentido, isto é, em textos/discursos. Isso permitiu ao homem “construir um espaço gnoseológico, ou seja, mundos de conhecimentos que podem se tornar autônomos em relação às circunstâncias individuais da vida, que podem se acumular no curso da história dos grupos” ([xref  ref-type="bibr" rid="r1"]1[/xref]). Esse agir possibilitou ao homem, também, construir ferramentas (materiais e simbólicas) para intervir no mundo, transformando-o, bem como construir e acumular conhecimentos. [/p]
[p]Mas qual a configuração desse agir linguageiro nos processos interacionais? E como ele se realiza no espaço escolar, no âmbito do ensino da escrita? Para tratar desses questionamentos, trazemos, neste artigo, um recorte de uma pesquisa de doutoramento , a qual teve como objetivo investigar, no contexto brasileiro de ensino público da Língua Portuguesa, o funcionamento da metodologia que embasa o procedimento “sequência didática de gêneros”, criado pelos pesquisadores do Interacionismo Sociodiscursivo (doravante ISD) para direcionar o ensino da produção de textos.[/p]
[p]Para o ISD, a produção de um texto no locus escolar não pode ser uma simples tarefa de apropriação do código linguístico e das normas que regem a ortografia e a gramática da língua oficial. Ela deve ser fruto de uma ação linguageira na qual o aluno assume seu papel de agente e age intencionalmente para atingir os objetivos propostos (mesmo que simulados didaticamente), usando os instrumentos semióticos disponíveis na sua língua, ou seja, os diversos gêneros de textos que fazem parte da cultura letrada, legados a nós por gerações anteriores. Para isso, o papel da escola é fundamental, uma vez que é ela a principal agência de letramento ([xref  ref-type="bibr" rid="r3"]3[/xref]). É, sobretudo, no ambiente escolar que o aluno desenvolve capacidades de linguagem ([xref  ref-type="bibr" rid="r2"]2[/xref])

**Comment by leticiaquino** [comment]
@robertatakenaka Mesmo com atualização do Markup, o programa remove o título "Referências".
