### ISSUE TITLE
(markup 090 - word 2013) Automata Vancouver considerar DOI

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1571]
Não identifica automaticamente referências que possuem url e PMID.
[ref id="r4" reftype="book"][text-ref]4. Sloan NL, Amoaful E, Arthur P, Winikoff B, Adjei S. Validity of women's self-reported obstetric complications in rural Ghana. J Health Popul Nutr. 2001 Jun;19(2):45-51. PMID:11503346[/text-ref] 4. Sloan NL, Amoaful E, Arthur P, Winikoff B, Adjei S. Validity of women's self-reported obstetric complications in rural Ghana. J Health Popul Nutr. 2001 Jun;19(2):45-51. http://dx.doi.org/10.2307/2137888 PMID:11503346[/ref]

**Comment by robertatakenaka** [comment]
A marcação vancouver tanto para refs como para vancouv tem limitações. Uma
delas é não reconhecer quando há doi no final.

Existe no bin/markup/app_modules/refIdentifier um script chamado
Visualizador.bat.
Nele há 3 caixas de texto. Na primeira coloque um bloco de texto de
referências. Clique no botão Processar.

Com isso você terá certeza do que gera ou não a referência marcada.

Isso foi feito por Heitor da BIREME.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
