### ISSUE TITLE
(Markup 4.0.090 - Word 2013) MKP90 (Trial) - Programa não identifica imagens

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1574]
Verificamos que o programa (Markup 90 - trial) não identifica figuras, apenas tabelas.
Veja o que acontece ao marcar uma imagem:
![figuras-identificacsao](https://cloud.githubusercontent.com/assets/4397365/8033887/c220c5f0-0db8-11e5-8617-89d7456ea335.jpg)

O programa apresenta erro em ID e não faz nenhuma marcação.
Após essa tentativa com o programa Markup marquei a mesma imagem, mas com a versão anterior à trial (Markup 4.0.090.70) e a marcaçao foi feita corretamente.

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1574

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
funcionou para mim. Testou em atualização? Será que realmente foi atualizado? Será que o id não tem algum espaço?

**Comment by robertatakenaka** [comment]
@leticiaquino : funcionou para mim usando o arquivo indicado. Nova instalação.

**Comment by leticiaquino** [comment]
@robertatakenaka testei na nova instalação e o ocorreu o mesmo problema. Vou testar em outro arquivo para verificar se o erro persiste ou se é algum problema com esse documento em específico.

**Comment by robertatakenaka** [comment]
@leticiaquino : será que foi usado a 40090 mesmo? Melhor pedir para reinstalar.

**Comment by leticiaquino** [comment]
@robertatakenaka Ok, vou pedir.

**Comment by robertatakenaka** [comment]
resolvido
