### ISSUE TITLE
(Markup 4.0.090 - Word 2013) MKP90 (Trial) - Formulário de identificação dos metadados não apresenta campo de versão do SPS

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1575]
Verificamos que o Markup 90 não apresenta no formulário, um campo de versão do SPS. Veja:

![version-formula](https://cloud.githubusercontent.com/assets/4397365/8036826/920dfa46-0dd0-11e5-953c-78de8902d461.jpg)

Obs.: Ainda o Markup ainda não foi atualizado aqui, mas acredito que isso ocorre mesmo no Markup atualizado.

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka outra coisa, me parece que essa versão trouxe o formulário antigo, pois a lista de title apresenta apenas a lista do SciELo BR

**Comment by leticiaquino** [comment]
@robertatakenaka o Markup.90 -Trial foi atualizado em minha máquina e verifiquei que mesmo após essa atualização o formulário apresenta os mesmos problemas apontados no tícket acima. Veja:

![formulario-error](https://cloud.githubusercontent.com/assets/4397365/8089919/484b8506-0f81-11e5-994a-55fe47c77136.jpg)

Note q eu estou usando a versão 90-trial instalada recentemente:

![markup-90-trial](https://cloud.githubusercontent.com/assets/4397365/8089997/aa492efc-0f81-11e5-8740-9c9e9ffb87e7.jpg)

**Comment by robertatakenaka** [comment]
resolvido
