### ISSUE TITLE
(Markup 4.0.090 - Word 2013) MKP90 (Trial) - Programa apresenta lentidão para apresentar janela de normalização de aff

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1580]
Verificamos que o programa apresenta lentidão para apresentar a janela de normalização de afiliação.
Além disso, quando a janela aparece notei que os dados não foram identificados corretamente. Veja:

![normalized](https://cloud.githubusercontent.com/assets/4397365/8090900/e4316742-0f86-11e5-895f-6196e3253290.jpg)

Veja ainda, que essa janela apresenta a estrutura antida de campos.

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1579

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka verifiquei que o problema foi corrigido após fazer o download de titles.

**Comment by robertatakenaka** [comment]
@leticiaquino : faltou incluir no instalador o arquivo bin/xml/wayta.py.

**Comment by robertatakenaka** [comment]
@leticiaquino : me enganei. Há sim o wayta.py. Você marcou o normaff, orgname e country antes de abrir a janela para normalizar os dados?

**Comment by leticiaquino** [comment]
@robertatakenaka eu verifiquei que o problema é que eu ainda não tinha feito o download de titles, depois que eu fiz a apresentação mudou e já não estava lento.
