### ISSUE TITLE
(Markup 4.0.090 - Word 2013) MKP90 (Trial) - Markup não faz identificação de seções de resumo automaticamente.

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1581]
Verificamos que o programa não faz identificação corretamente de seções de resumo. Veja:

![secoes-resumo](https://cloud.githubusercontent.com/assets/4397365/8091038/aa4ffa92-0f87-11e5-9daa-16712f87bba9.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1580

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
tente removendo a linha entre o título e os parágrafos

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-06-10 15:45 GMT-03:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka Roberta, o erro permanece:

![resumo-abstrac-section](https://cloud.githubusercontent.com/assets/4397365/8091322/91301fae-0f89-11e5-87d6-d4076caad05d.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino: acho que o padrão esperado é:

RESUMO (sem :)
Introdução (sem :)
texto de Introdução etc
... e assim por diante

**Comment by leticiaquino** [comment]
@robertatakenaka Ok funcionou.
Tentei também retirar os dois pontos de "Palavras-chave" e marcar novamente com o botão [*kwdgrp] e veja o resultado:

![kdw-grps-sect](https://cloud.githubusercontent.com/assets/4397365/8091652/742d5f46-0f8b-11e5-8a79-e33c61526ad5.jpg)

Obs.: Retirei a marcação e marquei de novo para verificar se eu não usei o botão errado sem querer.. mas depois da terceira marcação tive a certeza de que estava usando o botão correto.

**Comment by leticiaquino** [comment]
@robertatakenaka desculpe.. a imagem abaixo apresenta melhor o problema identificado:

![kdswes](https://cloud.githubusercontent.com/assets/4397365/8091691/c54632e0-0f8b-11e5-9bfb-ca9b463a86a9.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino : remover dois-pontos de Abstract

**Comment by leticiaquino** [comment]
@robertatakenaka removendo os dois pontos de "Abstract" e das seções correspondentes veja o que acontece:

![kwd](https://cloud.githubusercontent.com/assets/4397365/8091850/c07a9f16-0f8c-11e5-8285-fba02e6920a2.jpg)

Veja onde termina:

![kwd2](https://cloud.githubusercontent.com/assets/4397365/8091856/cad8d400-0f8c-11e5-9060-f61d76123e96.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino : Acho que se espera dois pontos após Palavras-chave

**Comment by leticiaquino** [comment]
@robertatakenaka ah ok.. agora deu certo..
Então a regra será: inserir 2 pontos para titulo de palavra-chave, mas em seções de resumo não deve existir pontos.

**Comment by robertatakenaka** [comment]
@leticiaquino : exato, porque como já muda de linha não tem porquê.

**Comment by robertatakenaka** [comment]
@leticiaquino : agora eu testei e para mim funcionou no formato que estava originalmente, sem remover os dois-pontos nem mudar de linha os parágrafos das seções.
No entanto, reparei que ainda existe a mensagem que indica que o markup tentará marcar automaticamente os xref dos autores no abstract.
