### ISSUE TITLE
(Markup 4.0.090 - Word 2013) MKP90 (Trial) - Erro em marcação automática de palavras-chave envolvendo o título

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1582]
O programa não marca corretamente as palavras-chave do documento. Veja:

![kwd-kwds](https://cloud.githubusercontent.com/assets/4397365/8091099/245d8db8-0f88-11e5-946c-60fbf39322f4.jpg)

Obs.: Foi utilizado o botão [*kwdgrp]

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1581

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : funcionou para mim.

**Comment by leticiaquino** [comment]
@robertatakenaka funcionou para mim também..
