### ISSUE TITLE
(Markup 4.0.090 - Word 2013) MKP90 (Trial) - Automata de Vancouver não funciona na versão 90trial

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1583]
A automata não funciona. Veja:

![marcacao-automata](https://cloud.githubusercontent.com/assets/4397365/8091517/9ee8a37c-0f8a-11e5-81da-4b78ee1bf961.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1582

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka após download de titles o programa faz a marcação automatica de refs, porém veja o erro:

![refs](https://cloud.githubusercontent.com/assets/4397365/8092274/ff914f4a-0f8e-11e5-9da8-5123596feb9f.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino : assim que puder eu vejo. Isso não faz sentido.

**Comment by robertatakenaka** [comment]
@leticiaquino : você atualizou a lista de títulos saindo do markup e entrando novamente?

**Comment by robertatakenaka** [comment]
@leticiaquino : consegui simular. Vou verificar.
