### ISSUE TITLE
(Markup 4.0.090 - Word 2013) MKP90 (Trial) - Automata muda elemento [arttitle] para [doctitle]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1585]
Verificamos que ao fazer a marcação automática de refs (norma vancouver) o programa identifica o título de journal como [doctitle] em vez de [artititle]. Veja:

![doctitlte-em vezde arttle](https://cloud.githubusercontent.com/assets/4397365/8109617/0e9128c2-102e-11e5-9e77-b44fcae09669.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1583

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : já está resolvido (40090-71)

**Comment by leticiaquino** [comment]
@robertatakenaka atualizei o markup com a versão 4.0.071 e verifiquei que ao selecionar e marcar todas as referências com a automata o programa não faz nada.
A marcaçao não é realizada. Veja:
Seleciono todas as refs e marco com a automata:

![tentando-marcar-refs](https://cloud.githubusercontent.com/assets/4397365/8133862/2be977de-1101-11e5-8612-53639effd673.jpg)

ao marcar veja o que acontece:

![ref-s-nada-ocorre](https://cloud.githubusercontent.com/assets/4397365/8133873/4e5d60a0-1101-11e5-9a42-b95a49730358.jpg)

Envio por e-mail os arquivos do temp
