### ISSUE TITLE
(Markup 4.0.090 - Word 2013) MKP90 (Trial) - Programa não faz marcação de automata (Vancounver)

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1593]
Verificamos que o Markup 90 (Trial) não faz a marcação automática de referências bibliográficas (Vancouver).
Ao selecionar as referências e marcar com a engrenagem "Marcação automática 2", o programa não faz nenhuma marcação de ref.

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1593

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino: teste no 40090-71, se tiver fazendo feche este ticket.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-06-16 11:25 GMT-03:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka eu já atualizei o MKP 90 Trial com o arquivo 40090-71 e mesmo assim a marcação não é feita.

**Comment by javani** [comment]
@robertatakenaka @leticiaquino para mim está fazendo. Ocorre que quando trata-se de um referência com estrutura próxima de um livro e que tem url, o markeup replica a informação sem a url e o cited. Veja:
[ref id="r1" reftype="report"][text-ref]1. The global burden of disease: 2004 update. Geneva: World Health Organization; 2008. Available from: http://www.who.int/healthinfo/global_burden_disease/GBD_report_2004update_full.pdf &#091;cited 2015 Feb 18&#093;.[/text-ref] [label]1[/label][source]The global burden of disease:2004 update[/source][date dateiso="20080000"]2008[/date][publoc]Geneva[/publoc][pubname]World Health Organization[/pubname][/ref]
[ref id="r2" reftype="report"][text-ref]2. Global tuberculosis report 2014. Geneva: World Health Organization; 2014. Available from: http://www.who.int/tb/publications/global_report/en/ &#091;cited 2015 Feb 18&#093;.[/text-ref] [label]2[/label][source]Global tuberculosis report 2014[/source][date dateiso="20140000"]2014[/date][publoc]Geneva[/publoc][pubname]World Health Organization[/pubname][/ref]
Encaminhei o arquivo via email.

**Comment by javani** [comment]
@robertatakenaka neste mesmo arquivo que enviei a você, na referência 8 há um autor corporativo. Quando da marcação automática, a tag não é envolta pela tag [authors].

**Comment by robertatakenaka** [comment]
@leticiaquino e @javani: eu usei o arquivo indicado em:
Y:\SciELO_team\XML_PMC\TICKETS\1593

E as referências tem o seguinte formato, não esperado. Lembrando que o Automata 2 somente funciona com referência da norma Vancouver. Mais abaixo, o formato esperado de ref de artigo e book:

**Não Vancouver**
ALUWONG, T.; WUYEP, P.A.; ALLAM, L. Livestock-environment interactions: Methane emissions from ruminants. African Journal of Biotechnology, v.10, n.8, p. 1265-1269, 2011. 
ASSOCIATION OF OFFICIAL ANALYTICAL CHEMISTS - AOAC. Official methods of analysis. 16 ed., Washington D.C., 1995. 1094p. 
BACH, A.; YOON, I.K.; STERN, M.D.; JUNG, H.G.; CHESTER-JONES, H. Effects of type of carbohydrate supplementation to lush pasture on microbial fermentation in continuous culture. Journal of Dairy Science, v.82, n.1, p.153-160, 1999.

**E o esperado para artigos:**
1. Halpern SD, Ubel PA, Caplan AL. Solid-organ transplantation in HIV-infected patients. N Engl J Med. 2002 Jul 25;347(4):284-7.
2. Halpern SD, Ubel PA, Caplan AL. Solid-organ transplantation in HIV-infected patients. N Engl J Med. 2002;347:284-7.
3. Halpern SD, Ubel PA, Caplan AL. Solid-organ transplantation in HIV-infected patients. N Engl J Med. 2002 Jul 25;347(4):284-7. Cited in PubMed; PMID 12140307.
4. Rose ME, Huerbin MB, Melick J, Marion DW, Palmer AM, Schiding JK, et al. Regulation of interstitial excitatory amino acid concentrations after cortical contusion injury. Brain Res. 2002;935(1-2):40-6.
5. Diabetes Prevention Program Research Group. Hypertension, insulin, and proinsulin in participants with impaired glucose tolerance. Hypertension. 2002;40(5):679-86.

**E o esperado para livros:**
1.Murray PR, Rosenthal KS, Kobayashi GS, Pfaller MA. Medical microbiology. 4th ed. St. Louis: Mosby; 2002.
2.Gilstrap LC 3rd, Cunningham FG, VanDorsten JP, editors. Operative obstetrics. 2nd ed. New York: McGraw-Hill; 2002.
3.Breedlove GK, Schorfheide AM. Adolescent pregnancy. 2nd ed. Wieczorek RR, editor. White Plains (NY): March of Dimes Education Services; 2001.
4.Royal Adelaide Hospital; University of Adelaide, Department of Clinical Nursing. Compendium of nursing research and practice development, 1999-2000. Adelaide (Australia): Adelaide University; 2001.
5.Meltzer PS, Kallioniemi A, Trent JM. Chromosome alterations in human solid tumors. In: Vogelstein B, Kinzler KW, editors. The genetic basis of human cancer. New York: McGraw-Hill; 2002. p. 93-113.

**Comment by robertatakenaka** [comment]
@leticiaquino e @javani : é possível usar esta funcionalidade selecionando uma referência de cada vez ou até poucas referências por vez. Quando uma referência está mal acaba que o programinha falha aí não há como identificar nada.

Como disse antes para testar se o bloco de referências vai ou não conseguir ser identificado, use a ferramenta oculta que está em bin/markup/app_modules/refidentifier/Visualizador.bat, dando dois cliques. Abrirá uma janela e preencha a primeira caixa de texto com o bloco de referências, então, clique em Processar.
