### ISSUE TITLE
[Report - Converter local] Inserir legenda explicativa para os tipos de erro da aba Detail Report

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1594]
Verificar a possibilidade de inserir uma legenda explicativa para os tipos de report da última coluna:

![quadro-report](https://cloud.githubusercontent.com/assets/4397365/8230088/3b70e9a8-1593-11e5-9f41-96a3cb903788.jpg)

**Comment by robertatakenaka** [comment]
A solução foi usar tradução, deixando mais claro a função de cada "botão"
