### ISSUE TITLE
[Report MKP 90] Não apresentar lista de possíveis instituições em relatório de erros

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1595]
Notei que no report é apresentado erro em normalized mesmo quando esse foi inserido no XML e com a instituição normalizada. E também é apresentado uma lista de possíveis instituições. Veja:

![lista-aff](https://cloud.githubusercontent.com/assets/4397365/8230205/794cecc6-1594-11e5-977a-45d6d816136c.jpg)

Verificar a possibilidade de apresentar erro apenas quando o elemento normalized não existir ou quando a instituição indicada em normalized não constar na lista de instituições e em vez de apresentar uma lista de possibilidades, indicar uma consulta no wayta.

A lista de possíveis erros deixa a o relatório grande e um pouco confuso.

**MODULO - ReportPackage
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : Mesmo que haja conteúdo em "normalized", é verificado se o valor identificado com "normalized" está registrado como instituição normalizada. Por favor, tente testar novamente com esta instituição mesmo porque ultimamente foram feitas correções.

**Comment by leticiaquino** [comment]
@robertatakenaka talvez meu exemplo não tenha sido muito bom..
O que eu quis dizer é que, muitas vezes, uma instituição existe em mais que 1 cidade... Mesmo a marcação estando feita corretamente, o programa abre uma lista de possibilidades de cidade onde essa instituição existe.

Minha sugestão seria validar a instituição e a cidade (se existir) e não abrir mais a lista.

Já recebemos muitos e-mails com dúvidas de prestadores com relação à essa validação do package Maker. A lista causa confusão.

**Comment by robertatakenaka** [comment]
@leticiaquino : nas últimas correções, a lógica foi alterada para:

Se há uma lista (ou seja, mais de 1 item possível), e em todos os ítens é comum nome e país, então é considerado normalizado nome + país, desconsiderando os demais dados.

Então, por gentileza, testar de novo usando o mesmo exemplo.
