### ISSUE TITLE
(markup 090 - word 2013) Boxed-txt sem seção

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1597]
No XML, inclui a tag sec em boxed-text mesmo quando não há seção identificada, apontando erro de estrutura.
Marcação:
[boxedtxt id="bx1"] [p]“The trend towards monolingualism is far from decreasing, with the hegemonic use of one language, English, over the other five United Nations languages.”[/p]
[p]UN Joint Inspection Unit[/p][/boxedtxt]

No xml:
```
 <boxed-text id="bx1">
                           <sec>
                                    <p>"The trend towards monolingualism is far from decreasing,
                                             with the hegemonic use of one language, English, over
                                             the other five United Nations languages."</p>
                                    <p>UN Joint Inspection Unit</p>
                           </sec>
                  </boxed-text>
```

**Comment by robertatakenaka** [comment]
similar #1348
