### ISSUE TITLE
[Report MKP 90] Inserir botão [close] ao final de cada relatório aberto.

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1601]
Verificar a possibilidade de inserir um botão [close] ao final de cada relatório para facilitar a visualização dos demais relatórios.
Veja onde deve ser inserido o botão:

![close](https://cloud.githubusercontent.com/assets/4397365/8257823/b55b79b0-1686-11e5-80bb-ce8466142e4c.jpg)

Veja o botão que existia no relatório (versão anterior):

![fechaaa](https://cloud.githubusercontent.com/assets/4397365/8257832/c18b2ca8-1686-11e5-9c1e-53deeabff203.jpg)

**MODULO - ReportXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino: já está disponível no servidor
