### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Markup não nomeia corretamente equações em linha

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1605]
Verificamos que o programa Markup (90-trial) não identifica corretamente equações em linha. Veja:
Ao selecionar a imagem abre-se uma janela onde temos que inserir o href de cada imagem.

![equacao-em-linha](https://cloud.githubusercontent.com/assets/4397365/8290583/6c3b00a4-18fa-11e5-9516-ec826f352935.jpg)

Há  a possibilidade de inserirmos apenas o id da equação e o programa fazer a marcação automática do graphic da equação assim como é feito hoje para tabelas ou figuras?

Veja também que ao identificar as equações em linha como imagem o programa renomeia a equação para o seguinte nome:
"2179-1074-jmoea-13-02-00111**-iimage004**"

![eq-inline](https://cloud.githubusercontent.com/assets/4397365/8290504/e35f3a02-18f9-11e5-9fca-251ad093d4f4.jpg)

Verificar a possibilidade de identificar equação em linha com o seguinte prefixo: "gi01", "gi02" etc em vez de "iimage".

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino: quaisquer equações inline ou não se usa equation. graphic se
usa para uma imagem solta, que não é figura.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-06-22 16:20 GMT-03:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka com o [equation] o programa identifica a equação como ```<inline-formula>```em vez de identificar como ```<inline-graphic>```. Veja que no SPS informamos que o uso do inline-graphic é para equações em linha que estão como imagem. O inline-formula é usado para identificar equações codificadas em linha.

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.2-branch/tagset.html#inline-graphic

Se identificar a equação em linha com a tag [graphic], o elemento transforma o [graphic] em ```<inline-graphic>```.

**Comment by robertatakenaka** [comment]
@leticiaquino : entendi, sendo assim o ticket está correto. No entanto, semanticamente não seria  mais correto que isso fosse equation no lugar de graphic? ``<equation> <graphic></graphic></equation>``?

**Comment by robertatakenaka** [comment]
@leticiaquino: sugiro testar marcar equation e graphic:
<equation><graphic></graphic></equation>

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-06-22 16:49 GMT-03:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka fiz o teste e quando identifico a imagem inline com o [equation] e o [graphic] o programa transforma os elementos [equation] e [graphic] em ```<inline-formula><graphic xlink:href="">```. Veja:

![inlineee](https://cloud.githubusercontent.com/assets/4397365/8306908/ed808f70-1991-11e5-9ab1-c1e6f33fba25.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1605

**Comment by robertatakenaka** [comment]
@leticiaquino : entendi. No entanto, o prefixo para inline é i para o pmc, por isso fica iimage. Eu acho que consigo retirar o image mas não sei se dá para trocar o g para i somente para o PMC. Não pode ficar i mesmo?

**Comment by leticiaquino** [comment]
@robertatakenaka ok, pode ser "i". Então ficaria "i01", "i02", "i03" .. ?

**Comment by leticiaquino** [comment]
@robertatakenaka Fiz a atualização das pastas e agora está ok.
Eu não marquei as equações inline com a tag [equation] e o programa considerou o [graphic] com a tag correta. Veja:

![inline-ok](https://cloud.githubusercontent.com/assets/4397365/8313263/02970fee-19b8-11e5-95a4-5f615cee1c17.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino : sim, vc deve usar o graphic mesmo.
