### ISSUE TITLE
(Markup 4.0.090 Trial - Word 2013) Inserir o elemento [role] em [authors]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1611]
Verifiquei que não há o elemento [role] no markup para autores.
Também tentei inseri manualmente o elemento, mas ao gerar o XML a tag é suprimida.
Veja como ficou no markup:

![role](https://cloud.githubusercontent.com/assets/4397365/8338080/05b4ab5a-1a85-11e5-92f9-07b4ec845bb0.jpg)

No XML:

![rolees](https://cloud.githubusercontent.com/assets/4397365/8338115/5919e76a-1a85-11e5-9554-c8a3e66ef486.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1610

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka ao selecionar a função do autor com o elemento [role], o programa apresenta erro. Veja:
![role-no-funfa](https://cloud.githubusercontent.com/assets/4397365/8362507/b3b50086-1b4f-11e5-86a1-5a2566a35790.jpg)


Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1611

**Comment by leticiaquino** [comment]
@robertatakenaka obs.: notei somente agora que o elemento [role] está disponível em [aff]. 
Esse elemento deve estar disponível em [authors], pois deve aparecer em ```<contrib>```.
Veja:

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.2-branch/tagset.html#elemento-role

**Comment by robertatakenaka** [comment]
@leticiaquino : eu tinha entendido que tinha como marcar mas não gerava. Então, também não existe role dentro de author?

**Comment by leticiaquino** [comment]
@robertatakenaka Notei que na versão 90 Trial a tag [role] ainda não consta dentro de [authors].

Veja que o elemento ```<role>``` deve aparecer em ```<contrib>```:

http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-ywe0.html

```<role>```pode ser inserido em: ```<collab>```, ```<contrib>```, ```<contrib-group>```, ```<element-citation>```, ```<mixed-citation>```, ```<person-group>```, ```<product>```, ```<related-article>```, ```<related-object>```
Note que **não** é possível inserir esse elemento em ```<institution>```.

**Comment by robertatakenaka** [comment]
@leticiaquino : no caso, não há authors em doc, somente é possível colocar role em author. Assim, será gerado role em contrib, mas não em contrib-group.

**Comment by leticiaquino** [comment]
@robertatakenaka desculpe, isso mesmo. Em [author].

**Comment by robertatakenaka** [comment]
@leticiaquino : foi feito. Não funcionou?

**Comment by leticiaquino** [comment]
@robertatakenaka Não, pois foi inserido em [normaff] e não em [author]. veja:

(Nível abaixo de [author])
![roleeessd](https://cloud.githubusercontent.com/assets/4397365/8432801/82f78e56-1f18-11e5-89ce-b1e7af20d14d.jpg)

(Nível abaixo de [normaff])
![rolesaemaff](https://cloud.githubusercontent.com/assets/4397365/8432813/98411462-1f18-11e5-976a-2440282830c1.jpg)
