### ISSUE TITLE
(Markup 4.0.090 Trial - Word 2013) Markup não gera tag <related-article> de errata corretamente

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1612]
Verificamos que o programa Markup gera  a tag ```<related-article>``` com o atributo @id "A01" quando deveria ser: "ra1", o @ext-link-type" com o valor "uri" quando deveria ser: "doi" e ainda, não gera a tag fechada. Veja:
![errata](https://cloud.githubusercontent.com/assets/4397365/8338528/e9322766-1a87-11e5-8a5c-76956fd2ad15.jpg)

Veja como deve ser:

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.2-branch/narr/errata.html

**Comment by robertatakenaka** [comment]
@leticiaquino : como ficou no markup?

**Comment by leticiaquino** [comment]
@robertatakenaka no Markup ficou assim:
![related](https://cloud.githubusercontent.com/assets/4397365/8353153/974e9cec-1b11-11e5-9d3c-acdc5339c136.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1612
