### ISSUE TITLE
(markup 090 - word 2013) Cited

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1613]
No markup, quando marcada a data de citação a tag é gerada da seguinte forma no XML:

```
<date-in-citation content-type="access-date"
                                          iso-8601-date="2015-05-11">2015 May 11</date-in-citation>
                            </element-citation>
```

Na documentação está

```
<element-citation>
    <date-in-citation content-type="access-date">cited 2007 Feb 21</date-in-citation>
</element-citation>
```

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.2-branch/tagset.html#date-in-citation

Acontece que o converter não está aceitando a forma como vem do markup.
Ajustar o markup ou o converter

**Comment by robertatakenaka** [comment]
@javani: eu acho que resolve com o 40090-75 que mandei ontem.

**Comment by javani** [comment]
ok, obrigada.

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

2015-06-25 8:33 GMT-03:00 Roberta Takenaka <notifications@github.com>:
