### ISSUE TITLE
[xpm] validação dos elementos dependentes de idioma

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#1625]
- article-title/trans-title
- abstract / trans-abstract
- keywords

Nota: a dependência implica que o dado está relacionado a um idioma, não significa que ele deve ou não ter o atributo @xml:lang. article-title depende de idioma, mas, neste caso, seu idioma está descrito em article/@xml:lang.
O objetivo deste ticket é descobrir se há problemas nos elementos/idiomas antes de verificar isso no site.

**Comment by leticiaquino** [comment]
@robertatakenaka article-title não depende de idioma.
acredito que faltou: 
```<article>``` 
```<sub-article>```
