### ISSUE TITLE
(Markup 4.0.090 Trial - Word 2013)Não identifica corretamente os xrefs de autores e não faz marcação automática de aff

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1629]
Após a atualização do pacote ..90-77.zip o programa não faz a marcação de [xref] de autores corretamente e também não marca as afiliações do documento. Veja:

![errorp-affs](https://cloud.githubusercontent.com/assets/4397365/8476519/951dc704-2098-11e5-8897-2da4888eeab9.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1629

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino: há uma linha entre autores e aff?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-07-02 9:00 GMT-03:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka Sim. Há uma linha separando autores de afiliações

**Comment by leticiaquino** [comment]
@robertatakenaka entretando, ao marcar o "doc" ele insere o [/author] na linha que separa os dois.

**Comment by leticiaquino** [comment]
Resolvido com a atualização do programa Markup.
