### ISSUE TITLE
(Markup 4.0.090 - Trial - Word 2013) Inserir um [p] em um nível abaixo de [quote] para marcação de mais que um parágrafo em um mesmo [quote]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1632]
Verificar a possibilidade de inserir um [p] em um nível abaixo de [quote] para identificar mais que um parágrafo de uma mesma citação.
 Veja como é feito hoje:

![quotees](https://cloud.githubusercontent.com/assets/4397365/8477456/ba1b3ba6-20a0-11e5-8a4a-c9e8bbaebbf6.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1631

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : não funcionaria ter um quote para cada parágrafo?

**Comment by leticiaquino** [comment]
@robertatakenaka o dado ficará marcado, mas vai ser apresentado como uma citação diferente da outra.
O Arturo (México) também se deparou com uma situação como essa, de identificar 1 citação que contém mais que um parágrafo utilizando o Markup. O programa não faz esse tipo de marcação.

**Comment by robertatakenaka** [comment]
@leticiaquino : sim. Acabaria ficando duas citações ao invés de uma. Mas aí se ajusta manualmente. Não me parece o caso de corrigir isso.
