### ISSUE TITLE
[Relatórios - XPM | XC] -Não apresentar erro em editorial por falta de abstract ou keyword

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1638]
Verificar a possibilidade de não apresentar erro em editoriais por falta de ```<kwd-group>``` ou de ```<abstract>```. Geralmente editorial não possui esse tipo de estrutura.

Veja o erro:
![editorials-kwds](https://cloud.githubusercontent.com/assets/4397365/8499698/cca0f6b4-216b-11e5-9539-ed210e44ffc2.jpg)

**MODULO - XC / XPM
PRIORIDADE - Medium**

**Comment by luanaaraujo** [comment]
@robertatakenaka  o erro persiste, e agora além do abstract e kwd-group, ele também está apontando erro de title-group, mesmo os arquivos tendo apenas abstract e title apenas em um idioma.


Erro:
![erro_abstract](https://cloud.githubusercontent.com/assets/4633779/8683367/c6af7740-2a48-11e5-8166-da8b8a576ddd.png)



Arquivo: V:\SciELO\serial\aem\2015nahead\2359-3997-aem-nahead0115\2359-3997-em-2359-3997000000064

**Comment by robertatakenaka** [comment]
@luanaaraujo : o problema já foi corrigido, só que vc não está com a versão atualizada.
