### ISSUE TITLE
(Markup 4.0.090 - Trial - Word 2013) Errata - Programa não identifica corretamente o [related]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1655]
Verificamos que o programa apresenta erro ao identificar informação de [related] para erratas.
Ao selecionar um espaço em branco e identificar com o elemento [related] o programa apresenta o seguinte erro:
![error-related](https://cloud.githubusercontent.com/assets/4397365/8778159/87269dfe-2ed2-11e5-8960-26a18a30ec0e.jpg)
informa que não existe pid-doi.

Ao abrir a janela para identificação do tipo de related e da URL do DOI relacionado, notei que falta o atributo "id-doi". Veja: 
![related-errata-error2](https://cloud.githubusercontent.com/assets/4397365/8778373/e929438e-2ed3-11e5-982b-fbd8b807bd65.jpg)

De qualquer forma, inseri a URL e ao clicar em OK foi apresentado essas duas janelas:
![not-extst-related-3](https://cloud.githubusercontent.com/assets/4397365/8778416/387d2a40-2ed4-11e5-9557-826acd1d1821.jpg)

![error-4](https://cloud.githubusercontent.com/assets/4397365/8778418/3bae1274-2ed4-11e5-8282-57e0697f4d2f.jpg)

E a marcação desse elemento ficou da seguinte forma no Markup:
![error-5](https://cloud.githubusercontent.com/assets/4397365/8778425/47a9142a-2ed4-11e5-9cb8-3adb8498665c.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1655

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
O Espaço em branco nao faz diferença. Faltou atualizar no instalador o
arquivo bin/markup/link.mds. so trocar id-doi por pid-doi.

**Comment by leticiaquino** [comment]
@robertatakenaka verifiquei que no link.mds e em related já consta o pid-doi.
Veja:
![related](https://cloud.githubusercontent.com/assets/4397365/8801293/eb1f822c-2f8f-11e5-93f6-8b94fbd85504.jpg)
