### ISSUE TITLE
[Report converter] incluir msg de erro quando o tipo de documento estiver [in brief]

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1656]
Inserir msg de erro para XMLs onde o tipo de artigo for identificado como in brief (pr).

**Comment by robertatakenaka** [comment]
@javani : não entendi. Você quer que quando o @article-type='in-brief' considerar erro? @article-type nunca pode ser in-brief?

**Comment by javani** [comment]
O in-brief é utilizado apenas para press-release, acontece que fazendo uma avaliação dos arquivos que recebemos percebi que estão incluindo indevidamente este tipo de documento, quando deveria ser original article. Pode ser apresentado como erro, mas não como fatal erro para a pessoa verificar o tipo ou, por exemplo, se houver afiliação, resumo, palavra-chave não pode ser esse tipo de documento bem como announcement.
