### ISSUE TITLE
(Markup 4.0.090 - Trial - Word 2013) Programa não identifica corretamente [surname] e [fname] em front

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1657]
Verificamos que a marcação automática de autores no início do documento não é feita corretamente. Veja o exemplo abaixo:

![authors-error](https://cloud.githubusercontent.com/assets/4397365/8824694/9290318c-304e-11e5-9190-286bb8a65d52.jpg)
Nesse artigo os autores inseriram um hífen nos dois últimos nomes para que sejam identificados em [surname]. No entanto o programa identificou os dois últimos nomes como [fname] e o primeiro como [surname]. 

Verificar a possibilidade de identificar o hífen e considerar como [surname].

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1657

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : se não me engano, o modelo é fname e surname, nesta ordem.

**Comment by robertatakenaka** [comment]
@leticiaquino : este ticket pode ser fechado por ser inválido?
