### ISSUE TITLE
[XC] - Validar intervalo de ano

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1677]
Verificamos que o XC apresenta Fatal Error para intervalo de ano: ```<year>1999-2002</year>```.

Entretanto, verifiquei no PMC e é possível essa identificação. Veja:
![rbepop v32n1 1](https://cloud.githubusercontent.com/assets/4397365/9060870/1c587084-3a8e-11e5-914f-861945b0d6b0.png)

http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/citations/v3/books1.html#d3e23653
Obs.: Passei nos validadores no PMC e não foi apresentado erro.

Por gentileza, verificar a possibilidade de não apresentar Fatal Error no XC.
Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1678

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino: A mensagem está correta porque não foi identifica o elemento
year. O intervalo de ano deveria ter sido marcado como year e não como
season.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-08-04 9:50 GMT-03:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka desculpe..
Segue a imagem correta:

![year-intervalo](https://cloud.githubusercontent.com/assets/4397365/9061070/931a4f70-3a8f-11e5-8b07-3765be396f20.jpg)
