### ISSUE TITLE
[Package Maker] Programa apresenta erro em títulos e palavras-chave sem o atributo de idioma

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1686]
Verificamos que o programa Markup apresenta erro de falta do atributo @xml:lang para ```<title-group>``` e ```<kwd-group>```. Veja:

![report](https://cloud.githubusercontent.com/assets/4397365/9171230/4963e2a0-3f40-11e5-80b2-16b1f88ab3e4.jpg)

Informo que o elemento ```<title-group>``` não deve conter o atributo @xml:lang. Esse atributo é utilizado apenas para tags de tradução.
Obs.:  o elemento ```<kwd-group>``` apresenta o atributo @xml:lang.

Arquivo .xml e relatórios disponíveis em:
Y:\SciELO_team\XML_PMC\TICKETS\1686

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : note que a mensagem não diz que o title-group deve conter @xml:lang. Mas diz que para o idioma @xml:lang=X está faltando dados de title-group. E o mesmo para kwd-group. Quais são os idiomas do texto? Pelo idioma do texto se espera que haja os títulos e as palavras-chave correspondentes.

**Comment by leticiaquino** [comment]
@robertatakenaka o arquivo .xml está no idioma em inglês. Em ```<article>``` foi identificado o idioma correto, notei ainda que o título está com o idioma em inglês, bem como o resumo.

**Comment by robertatakenaka** [comment]
@leticiaquino : para o arquivo 00325.xml, por exemplo, foi encontrado abstract em português, no entanto, faltaram título em pt e também palavras-chaves. Isto está correto?

**Comment by leticiaquino** [comment]
@robertatakenaka o arquivo .325 está correto.
está no idioma em inglês, apresenta título em inglês, resumo em inglês e apresenta apenas resumo traduzido em ```<trans-abstract xml:lang="pt">```. 
Assim como os demais arquivos .xml.

**Comment by leticiaquino** [comment]
@robertatakenaka desculpe, apresenta resumo nos dois idiomas, em inglês e em português, que está marcado com ```<trans-abstract xml:lang="pt">```.

**Comment by robertatakenaka** [comment]
@leticiaquino : o que o validador está questionando é que sim existe o abstract para pt, mas não o título nem as palavras-chave.

**Comment by leticiaquino** [comment]
@robertatakenaka ok entendi.
Há a possibilidade de não apresentar mais esse tipo de erro? pois isso não ocorre apenas para a BDJ e verifiquei que os números anteriores foram publicados dessa forma.

Se precisar eu procuro outros exemplos para disponibilizar aqui no ticket.

**Comment by robertatakenaka** [comment]
@leticiaquino : Vou ajusta o validador, para indicar erro apenas para os idiomas de article/@xml:lang e sub-article/@xml:lang. Assumo que somente nestes casos, é obrigatório ter título, resumo e palavras-chave. De acordo?

**Comment by leticiaquino** [comment]
@robertatakenaka há um caso o qual o Gustavo está verificando que está relacionado à esse ticket:

https://github.com/scieloorg/scielo_publishing_schema/issues/127

No email "[scielo-xml-sig] Escorregadas na especificação SciELO PS ou anomalias?" de 14/07 a Eliana comentou que a revista Química Nova não insere o resumo no idioma original.

Acredito que devemos avaliar isso melhor.

**Comment by robertatakenaka** [comment]
@leticiaquino : Você está afirmando que em sub-article nem sempre tem os mesmos dados (resumo, título, palavras-chave) de article mas traduzidos?

**Comment by leticiaquino** [comment]
@robertatakenaka em caso de sub-article eu preciso verificar. O caso o qual eu comentei no ticket é de um arquivo que não apresenta tradução, (```<sub-article>```) a BDJ.

**Comment by robertatakenaka** [comment]
Neste caso, o programa identificou que há um resumo em pt, então ele
esperava que houvesse a correspondencia de título e palavras-chaves. No
entanto, vc confirmou que não adianta este tipo de validação porque pode
acontecer de não existir mesmo.

Então sugeri se a validação poderia ser feita por sub-article, ou seja, se
há um sub-article ele deveria conter tudo: o resumo, título e
palavras-chave no idioma do sub-article. Não um ou outro.

Me confirmaram que isso também não é verdade. Pode acontecer de faltar.

Então, acho que vou manter o teste no idioma do article. De acordo?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-08-10 10:45 GMT-03:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka Ok entendi. Mas ao mesmo tempo pode acontecer de um artigo no idioma em português, por exemplo (apenas nesse idioma, sem tradução) não apresentar resumo em português, somente em inglês. Que é o caso da Química Nova: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-40422015000100030&lng=en&nrm=iso&tlng=pt

**Comment by leticiaquino** [comment]
@robertatakenaka após a atualização enviada ontem, 24/08, verifiquei que o erro persiste. Veja:

![error-checker](https://cloud.githubusercontent.com/assets/4397365/9466304/4821b9e6-4b0a-11e5-92cd-b391fe9e023d.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1686\erro-persiste
