### ISSUE TITLE
(Markup SPS 1.3) ao gerar o XML converter o <title> de <caption> em <p>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1714]
Verificar a possibilidade de, ao gerar o arquivo .xml transformar o ```<title>``` de ```<caption>``` em ```<p>```, podendo aparecer 1 ou mais vezes.
Exemplo:

```code
<label>Tabela 1</label>
<caption>
<p>Caracterização química em óxidos do rejeito.</p>
<p xml:lang="en">Chemical characterization of the oxides of the tailing</p>
</caption>
```

Note, que de acordo com a JATS 1.0 o label deve aparecer 0 ou 1 vez, tanto para figuras quanto para tabelas:

http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-krn0.html

http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-8ju0.html

Essa solicitação se deve ao fato de trabalharmos com periódicos que publicam legendas traduzidas de tabelas ou figuras.

Ticket relacionado ao: https://github.com/scieloorg/scielo_publishing_schema/issues/98
Essa regra passará a valer a partir da versão 1.3 da documentação a qual será disponibilizada em Setembro desse ano.
Ou seja, periódicos que nos enviarem XML na versão 1.2 devemos aceitar o ```<caption>``` ainda com o elemento ```<title>``` até que a versão 1.2 seja descontinuada.

**MODULO - MarkupXML
PRIORIDADE - Major**

**Comment by robertatakenaka** [comment]
@leticiaquino : dentro de caption sempr haverá pelo menos 1 p?, mesmo que não tenha @xml:lang?

**Comment by leticiaquino** [comment]
@robertatakenaka nesse caso, pode desconsiderar esse ticket. Veja que encontramos uma estrutura que resolve a questão de legendas traduzidas. Exemplo:

```xml
<fig-group id="f1">
    <fig xml:lang="pt">
        <label>Figura 1</label>
        <caption>
            <title>Caracterização química em óxidos do rejeito.</title>
        </caption>
    </fig>
    <fig xml:lang="en">
        <label>Figure 1</label>
        <caption>
            <title>Chemical characterization of the oxides of the tailing.</title>
        </caption>
    </fig>
    <graphic xlink:href="1234-5678-rctb-45-05-0110-gf05.tif"/>
</fig-group>
```
Veja: 
https://gist.github.com/gustavofonseca/fe4cb78b0b41b7dcced2
