### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Programa não marca tfn automaticamente de tabelas em img

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1726]
Verificamos que o programa Markup não faz a identificação automática de nota de rodapé de tabela (TFN) quando a tabela está como imagem. Veja:

![tab-img](https://cloud.githubusercontent.com/assets/4397365/9465868/bb2e1668-4b06-11e5-83b4-63ba3bd84750.jpg)

Arquivo disponível em:

Y:\SciELO_team\XML_PMC\TICKETS\1726

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by leticiaquino** [comment]
@robertatakenaka retirei a formatação da nota de rodapé e tentei marcar novamente, mas o problema persiste.

**Comment by robertatakenaka** [comment]
@leticiaquino : quebre a linha entre graphic e footnote

**Comment by javani** [comment]
@robertatakenaka e @leticiaquino vou tentar incluir a linha e fazer a marcação novamente. Se for necessário isso, temos que colocar uma observação no manual de preparação de arquivos. Vou verificar e retorno.

**Comment by robertatakenaka** [comment]
@leticiaquino e @javani : a quebra de linha é necessária porque já houve caso em que o "graphic" era uma imagem que fazia parte do caption. Então para distinguir o graphic que é representação do elemento "table" ou "figura" do graphic que é parte do caption este procedimento é necessário.

**Comment by leticiaquino** [comment]
@robertatakenaka veja que pulei uma linha entre a imagem da tabela e a nota de rodapé e ainda assim, o programa não fez a marcação automática de [fntable].

![tab-1linha-graphic](https://cloud.githubusercontent.com/assets/4397365/11625046/163c2626-9cbf-11e5-92bd-3d31a979ba0a.jpg)

Envio abaixo o arquivo .docx para avaliação:

[01_18342.docx](https://github.com/scieloorg/PC-Programs/files/53802/01_18342.docx)


Envio anexo o arquivo marcado.

**Comment by robertatakenaka** [comment]
@leticiaaquino: deixe cada a nota em um parágrafo. Note que tabwrap está no
final de um parágrafo. Ele deve ficar isolado.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-12-07 8:47 GMT-02:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka não entendi muito bem..
Veja se é isso:

coloquei cada nota de rodapé dessa tabela em um parágrafo e pulei 1 linha entre o graphic e a nota de rodapé da tab e também uma linha entre a ultima nota e o parágrafo:

![nots-linhas](https://cloud.githubusercontent.com/assets/4397365/11625197/2a79d376-9cc0-11e5-9e54-975f49b7d85f.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino: aguarde, vou dar uma revisada.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-12-07 8:55 GMT-02:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka agora a marcação automática de [fntable] está ok:

![tag-ok](https://cloud.githubusercontent.com/assets/4397365/11630215/8785e03c-9ce3-11e5-8941-aedb4052f232.jpg)
