### ISSUE TITLE
Data de epub para artigos rolling in pass

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#173]
Quando a revista é rolling in pass, preenchemos a data iso como 20130000. Contudo os artigos tem data de publicação online, de aceito e recebido.
Apresenta o erro abaixo:
20131025(accepted date) must be a date before 20130000 (epub date)
20131025(accepted date) must be a date before 20130000 (ppub date)

**Comment by javani** [comment]
@robertatakenaka @leticiaquino na versão 91 não está gerando a tag de collection com ano.

**Comment by robertatakenaka** [comment]
epub (do artigo) e collection (do fascículo)

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
