### ISSUE TITLE
[Markup v.90] Idioma chinês

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1755]
Quando selecionamos o idioma "chinês" na lista, insere o código iso errado. Ao invés de "cn", inclui "ch"

**Comment by robertatakenaka** [comment]
@javani : onde aconteceu isso? cn não é China não Chinês. Na Internet encontrei zh para Chinês.

**Comment by javani** [comment]
@robertatakenaka acontece no markup quando seleciona o idioma do título ou resumo. Chinês, marca ch
