### ISSUE TITLE
(XPM e XC) Atualizar validadores para aceitar e validar estrutura SPS 1.3

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1782]
Atualizar validadores "Package Maker" e "Converter" para aceitar e validar arquivos na versão 1.3:
Verificar abaixo o que há de novo:

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/whatsnew-1.3.html

Verificar também estrutura de figuras e tabelas com legendas traduzidas:

* Figura: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/tagset.html#legendas-traduzidas

* Tabela: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/tagset.html#legenda-traduzida

**Comment by robertatakenaka** [comment]
@leticiaquino : de acordo com este link, neste ticket foram resolvidos:

* alteração da mensagem de "error: obrigatório volume e/ou número" para "warning: ausentes volume e número. Será considerado um ahead of print."
* Na ausência de counts, nenhuma mensagem é fornecida
* announcement e abstract foram removidos da lista de valores em uso.

Para as demais novidades não achei necessidade em fazer alterações. Por favor, avalie se algo faltou ser considerado. Reabrir o ticket ou criar outro especificando todos os ítens faltantes.
