### ISSUE TITLE
(Markup 4.0.090 - Word 2013) Erro em marcação automática - Automata

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1829]
Verifiquei que o programa Markup não está fazendo a marcação automática de referências bibliográficas com o automata. Veja o erro apresentado:

![ref-automata](https://cloud.githubusercontent.com/assets/4397365/10692406/25a5ff50-7970-11e5-9058-02916c09f811.jpg)

Ao clicar em [ok] o programa abre uma nova janela informando que é recomendável sair da marcação:

![erro-automata-2](https://cloud.githubusercontent.com/assets/4397365/10692425/3e3e5198-7970-11e5-85fb-4ac17f1140fe.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\1829

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : Qual botão de marcação automática você selecionou? O segundo botão deve funcionar.

**Comment by leticiaquino** [comment]
@robertatakenaka o segundo: "Markup: Marcação Automática 2"
