### ISSUE TITLE
[Markup v.90] programa junta nota de autor traduzida em <article>

### ISSUE THREAD

**Issue by renatogaldino** [scieloorg/PC-Programs#1858]
Quando existe nota de autor em `[sub-doc]`, o programa junta as duas notas - original e tradução - em `<article>`:

![sem titulo](https://cloud.githubusercontent.com/assets/11942249/11241349/3764fcde-8de1-11e5-81f9-1c8b9bc7e67c.png)

**Comment by robertatakenaka** [comment]
@renatogaldino : você tem este arquivo Word? Por favor, anexa pelo github. Agora o github aceita anexar arquivos.

**Comment by renatogaldino** [comment]
@robertatakenaka segue arquivo:
[a02nahead0315 (1).docx](https://github.com/scieloorg/PC-Programs/files/45108/a02nahead0315.1.docx)
