### ISSUE TITLE
XC- Indicar erro na validação quando há duplicação de título em article e sub-article

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#1865]
Possibilidade de incluir na validação do XC  indicação de  "error" quando há presença de ```<trans-title-group xml:lang="x">``` em  /article/front/article-meta/title-group com o mesmo idioma de ```<sub-article article-type="translation" id="TRen" xml:lang="en">```

Exemplo:
![titulo traduzido](https://cloud.githubusercontent.com/assets/6921625/11399790/b9508bb6-9370-11e5-90a3-776f9573f018.png)

![titulo traduzido_2](https://cloud.githubusercontent.com/assets/6921625/11399551/4ffc950c-936f-11e5-8ee7-dafbbfe4ce53.png)

Não deve ocorrer duplicação do título no artigo ```<article>``` quando este mesmo título já está na tradução ```<sub-article>```

**Comment by robertatakenaka** [comment]
@suelylc : boa sugestão
