### ISSUE TITLE
XC- Sinalizar erro para informação inteira em tag de formatação

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#1869]
Ocorrências conforme exemplo abaixo não estão sendo apontadas por XC

![error 2](https://cloud.githubusercontent.com/assets/6921625/11429416/a3621452-945e-11e5-9601-3b3367c00a7c.png)

**Comment by robertatakenaka** [comment]
@suelylc : na versão que estou trabalhando terá a funcionalidade de extrair o bold e o itálico quando ele pega todo o conteúdo e não algumas palavras. No XC que já está em funcionamento, já está com esta característica, por isso não aparece na tabela.
