### ISSUE TITLE
[Markup v.90 - 30/11] TFN em tabela em figura

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1881]
Não marcar TFN de tabela quando apresentada em figura.

**Comment by robertatakenaka** [comment]
@javani : não entendi.

**Comment by javani** [comment]
@robertatakenaka Quando a tabela está em figura, e marco a tag tabwrap não marca automaticamente a nota de tabelae recomeça do TFN1 nas próximas tabelas.

**Comment by robertatakenaka** [comment]
@javani : fornecer arquivo de exemplo

**Comment by leticiaquino** [comment]
@robertatakenaka e @javani desculpe a intromissão, mas acredito que esse ticket tem a ver com o que eu abri há algum tempo atrás: #1726

**Comment by robertatakenaka** [comment]
@leticiaquino : se tem relação, qual é a resposta à pergunta que deixei lá?

**Comment by leticiaquino** [comment]
@robertatakenaka não vi a pergunta, mas o ticket que eu abri não foi fechado..
o programa continua não fazendo a marcação automática de nota de rodapé de tabela quando a tabela está como imagem.
O Markup faz a identificação de nota de rodapé automaticamente apenas para tabelas em texto.
