### ISSUE TITLE
[xpm] Indicação do tipo de ref junto com nome dos XML quando houver marcação de mesma fonte em ref com tipos diferentes

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1892]
Indicar no relatório de visão geral do pacote em quais arquivos a fonte de uma determinada referência foi marcada com tipos diferentes:

mesmas fontes (source) como tipos diferentes (element-citation/@publication-type)	ERROR [E6]	
Ciência Rural:
book: 1
journal: 7

mesmas fontes (source) com difentes tipos de referências (element-citation/@publication-type)	book INFO	
Ciência Rural:
B26 - 1678-5150-pvb-35-11-00919

mesmas fontes (source) com difentes tipos de referências (element-citation/@publication-type)	journal  INFO	
Ciência Rural:
B13 - 1678-5150-pvb-35-11-00906
B7 - 1678-5150-pvb-35-11-00893
B28 - 1678-5150-pvb-35-11-00882
B34 - 1678-5150-pvb-35-11-00882
B33 - 1678-5150-pvb-35-11-00875
B28 - 1678-5150-pvb-35-11-00933
B10 - 1678-5150-pvb-35-11-00899

**Comment by robertatakenaka** [comment]
@javani: já está. 

No seu exemplo, diz que Ciência Rural está como journal (7 vezes) e book (1 vez).
E Ciência Rural ocorreu nos locais (ref e nome de arquivo)

Livro:
B26 - 1678-5150-pvb-35-11-00919

Journal:
B13 - 1678-5150-pvb-35-11-00906
B7 - 1678-5150-pvb-35-11-00893
B28 - 1678-5150-pvb-35-11-00882
B34 - 1678-5150-pvb-35-11-00882
B33 - 1678-5150-pvb-35-11-00875
B28 - 1678-5150-pvb-35-11-00933
B10 - 1678-5150-pvb-35-11-00899

Outro exemplo:
http://homolog.xml.scielo.br/reports/mana/v21n2/xml_converter.html
![captura de tela 2015-12-02 as 16 36 56](https://cloud.githubusercontent.com/assets/505143/11540299/2f0a3800-9913-11e5-9896-88449d8732f3.png)

**Comment by javani** [comment]
@robertatakenaka nesse caso fica fácil pq vc só tem dois arquivos para verificar. No caso que eu passei havia 8 ocorrências. Se eu soube em qual arquivo ela foi marcada como book, não precisaria olhar todos. Descobri qual estava marcada como book abrindo 6 arquivos.

**Comment by robertatakenaka** [comment]
@javani : entendi
