### ISSUE TITLE
[xpm] Indicação de nome de arquivos quando houver afiliação incompleta

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1893]
No relatório de visão geral do pacote incluir nome dos arquivos em a afiliação apresenta-se incompleta.

**Comment by robertatakenaka** [comment]
@javani: será mesmo necessário? individualmente já não é apresentado?

**Comment by javani** [comment]
@robertatakenaka eu não consegui localizar. Os erros e warnings apresentados não tinham vínculo com aff.
