### ISSUE TITLE
(XPM) Pacote PMC - Verificar a possibilidade de desconsiderar o elemento <pub-date pub-type="epub"> para Ex AOP 

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1903]
Para arquivos Ex AOP, verificar a possibilidade de retirar data de publicação "epub" e manter apenas a data de publicação "collection" (que apresenta ```<month>``` e ```<year>``` do fascículo) no pacote pmc_package.

**Comment by robertatakenaka** [comment]
@leticiaquino, @javani: estou tentando imagina como se sabe que é ex aop?
Posso considerar que se há a data collection, excluir a data epub?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-12-04 12:26 GMT-02:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka @javani sim, considerar que se existe "collection" é ex ahead of print.

**Comment by suelylc** [comment]
Letícia , e no caso das revistas rolling pass?

Os aquivos serão enviados sem o "epub"
ao invés de : 

Segue exemplo da bjmbr que passou a ser rollling pass
![roling_pass](https://cloud.githubusercontent.com/assets/6921625/11597733/9eddaf30-9aa4-11e5-9ee6-4b4e5e98e153.png)

**Comment by robertatakenaka** [comment]
@suelylc, @javani, @leticiaquino: realmente, Suely, bem questionado. E
agora, pessoal?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by suelylc** [comment]
Acho que não há problemas em manter a nossa da data de "epub" em ex-aheads de fascículos enviados ao PMC... Não?

**Comment by javani** [comment]
Se eles aceitam assim acredito que não, mas temos que verificar as
orientações para não termos problemas futuros.




Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

Em 4 de dezembro de 2015 16:50, suelylc <notifications@github.com> escreveu:

**Comment by leticiaquino** [comment]
@robertatakenaka @javani @suelylc Então de acordo com as orientações PMC a regra é:

para revistas **apenas** online (caso da bjmbr) usar: collection + epub
para revistas impressa usar:  ppub

**Comment by robertatakenaka** [comment]
@javani @leticiaquino @suelylc : então? como fica? este ticket tem que ser desfeito?

**Comment by leticiaquino** [comment]
@robertatakenaka penso que deve ser desfeito. Eu não considerei o RP, nem o caso apresentado no comentário acima.

**Comment by suelylc** [comment]
@robertatakenaka Acho tb Roberta, pois "collection" dever estar presente para casos de revistas que publicam todos os artigos em ahead e depois os reúne no fascíuclo e para os rolling-passs. Ambos os casos possuem uma data de "epub"

**Comment by leticiaquino** [comment]
@suelylc só um comentário.. concordo que o ticket deve ser desconsiderado.

mas apenas para situar, estamos falando aqui de arquivos .xml que o Package Maker gera para **PMC**...
então para pmc, considerar a regra comentada acima:
para revistas **apenas online** (caso da bjmbr) usar: collection + epub
para revistas impressa usar: ppub
