### ISSUE TITLE
XMP para PMC - Excluir xref fechada para ```<aff>``` em ```<contrib>```

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#1911]
Ocorrências de um ou mais autores relacionados a uma única afiliação sem label marcado, exclui-se a xref fechada ```<xref ref-type="aff" rid="aff1"/>``` de contrib e o atributo de aff 
```<aff id="aff1">```

Atualmente esse ajuste é feito manualmente nos .xml para envio ao PMC
Exemplo 
![aff_fechada_errada](https://cloud.githubusercontent.com/assets/6921625/11657383/80b169c8-9da3-11e5-9445-9085bf99caa0.png)

Sugestão para geração dos arquivos:
![aff_fechada_correta](https://cloud.githubusercontent.com/assets/6921625/11657187/f2683ee0-9da1-11e5-8297-96188041a6bb.png)

**Comment by javani** [comment]
O xref e aff-id são as únicas formas para relacionar o autor à afiliação,
mesmo que não haja label. Por isso o id em aff é obrigatório em nosso
esquema.
O xref fechado é utilizado no índice bibliométrico (para relacionar os
autores corretamente ao ID). Assim, mesmo se tratando de uma mesma
afiliação para todos, ambos os valores devem estar presentes



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

Em 8 de dezembro de 2015 11:59, suelylc <notifications@github.com> escreveu:

**Comment by suelylc** [comment]
@javani  Este caso é para os arquivos gerados em pmc_package

**Comment by leticiaquino** [comment]
@suelylc você pode compartilhar essa orientação do PMC?

**Comment by javani** [comment]
@suelylc @robertatakenaka ahhhh, ok

**Comment by robertatakenaka** [comment]
@suelyc: já tem até ticket fechado disso (#1258). Pode me dar um arquivo
para eu testar?


Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by leticiaquino** [comment]
@suelylc encontrei! pensei que eu tivesse excluído.

**Comment by suelylc** [comment]
@leticiaquino segue o link http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html#dob-auaff

**Comment by leticiaquino** [comment]
@suelylc o link eu conheço. Queria o e-mail, mas já o encontrei.
