### ISSUE TITLE
[titlemanager] Inclusão de dado para indicar publicação continuada

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1912]
Incluir a periodicidade na title principal para publicação continuada.

Pt: Publicação Continuada
En: Continuous Publication
Es: Publicación Continua
Discussão em: https://github.com/scieloorg/scielo-manager/issues/1230

**Comment by robertatakenaka** [comment]
@javani : preciso saber qual é o problema que isso resolveria para assegurar de que ao incluir um campo realmente resolverá o problema desejado.
