### ISSUE TITLE
[markup v.91 - 12/01] Quando há et al em referência bibliográfica apresenta mensagem de argumento inválido

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1965]
Quando a referência finaliza com et al, ao usar a tag *authors, apresenta o erro abaixo. Contudo, clicanco em ok, segue a marcação normalmente e inclui [/pauthor] antes de [doc] no início do documento. Artigo enviado por email.
![image](https://cloud.githubusercontent.com/assets/912953/12268317/58652f30-b933-11e5-9c7d-d73e39e1aa4c.png)

**Comment by robertatakenaka** [comment]
relacionado com #1969, resolvido
