### ISSUE TITLE
(Markup 4.0.091 - Word 2013) Programa apresenta erro ao fazer a marcação de [*authors]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1969]
Verificamos que ao fazer a marcação de [*authors] o programa apresenta a seguinte janela de erro:

![error-mkp-authors](https://cloud.githubusercontent.com/assets/4397365/12388650/281fe568-bdbb-11e5-8255-b0cc74dd9665.jpg)

Entretanto, ao clicar em [OK] o programa realiza a marcação dos autores da referência.
Envio anexo o documento:
[abc-carta-105-02-0206.docx](https://github.com/scieloorg/PC-Programs/files/94084/abc-carta-105-02-0206.docx)

Relacionado ao #1965

**Comment by javani** [comment]
@leticiaquino @robertatakenaka esta tag está apresentando mais um problema.
Quando identificamos um autor que é o único autor do documento com esta tag, o programa abre a tag no autor e fecha apenas na referência seguinte onde este autor aparece.

![image](https://cloud.githubusercontent.com/assets/912953/12390105/4cd34ef0-bdc4-11e5-8df0-d11ae5e23747.png)

Enviado arquivo por email.

**Comment by leticiaquino** [comment]
@javani @robertatakenaka Para mim funciona bem:

![authotr-errorno](https://cloud.githubusercontent.com/assets/4397365/12390149/ad42cdc4-bdc4-11e5-9be2-32658695944b.jpg)
