### ISSUE TITLE
(Markup 4.0.091 - Word 2013) Implementar [normaff] para [subdoc].

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1970]
Implementar a tag [normaff] para [subdoc] tendo em vista que nem sempre um ```<sub-article>``` será do tipo 'tradução'. Veja que é previsto no SPS os seguintes tipos:

* abstract
* letter
* reply
* translation

Repare no documento anexo a dificuldade em identificar a afiliação de sub-article que é diferente do artigo principal:

[abc-carta-105-02-0206.docx](https://github.com/scieloorg/PC-Programs/files/94139/abc-carta-105-02-0206.docx)

**MODULO - MakupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : por favor, confirmar se as afiliações de documentos que não são **artigos** são contabilizados. Eu acho que não, então não valeria a pena marcar com nível de detalhes

**Comment by javani** [comment]
Olá Roberta,
Para afiliação são contabilizadas todas as afiliações.

Grata,

On 28/01/2016 13:42, Roberta Takenaka wrote:
>
> @leticiaquino <https://github.com/leticiaquino> : por favor, confirmar 
> se as afiliações de documentos que não são *artigos* são 
> contabilizados. Eu acho que não, então não valeria a pena marcar com 
> nível de detalhes
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scieloorg/PC-Programs/issues/1970#issuecomment-176241254>.
>

-- 
Javani Araujo
SciELO
FAPESP - CNPq - BIREME - FAP UNIFESP
Av. Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
www.scielo.org | www.scielo.br | blog.scielo.org
