### ISSUE TITLE
(Markup 4.0.091 - Word 2013)Programa insere o [/caption] após o elemento [/tabwrap]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#1971]
Percebemos que o programa faz a marcação de [/caption] de tabelas incorretamente:

![caption-mkp](https://cloud.githubusercontent.com/assets/4397365/12417284/20407a3c-be8e-11e5-86ac-91f9adfbc51a.jpg)

note na imagem acima que o [/caption] é inserido após o elemento [/tabwrap].

Ver arquivo:
[a11_218_235_mml.docx](https://github.com/scieloorg/PC-Programs/files/95805/a11_218_235_mml.docx)

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@leticiaquino : na verdade acho que o problema é que falta quebra de linha entre o caption e o elemento gráfico.
Insira uma quebra de linha e tente marcar novamente.
