### ISSUE TITLE
[Markup v.90 e v91] Perda de qualidade de imagem na conversão para gif e jpg pelo programa

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1973]
Quando é gerado o XML a partir de docs com imagens incluídas em png, as mesmas perdem qualidade na conversão para .gif ou .jpg.
[v32n6a02.docx](https://github.com/scieloorg/PC-Programs/files/96389/v32n6a02.docx)
![1984-4689-zool-32-06-00438-gf1](https://cloud.githubusercontent.com/assets/912953/12427873/c5b85c5c-bec8-11e5-83a0-f1dc9ae766f9.gif)
![1984-4689-zool-32-06-00438-gf2](https://cloud.githubusercontent.com/assets/912953/12427874/c5b88498-bec8-11e5-9c89-ae953e4a83de.gif)
![1984-4689-zool-32-06-00438-gf3](https://cloud.githubusercontent.com/assets/912953/12427875/c5bb95d4-bec8-11e5-823d-cc0af4e27ca0.gif)

**Comment by robertatakenaka** [comment]
@javani : o XPM somente altera as imagens que são .tiff, .tif ou .eps. Nenhuma outra é alterada. O que se faz a partir do Word é extrair as imagens embutidas. 

Executando o Markup e XPM 4.0.091, as imagens ficam com os seguintes tamanhos:
1984-4689-zool-32-06-00438-gf1.gif 40K 
1984-4689-zool-32-06-00438-gf2.gif 21K
1984-4689-zool-32-06-00438-gf3.gif 16K

No entanto, no servidor, no site, estão com tamanho reduzido:
1984-4689-zool-32-06-00438-gf1.gif 18K 
1984-4689-zool-32-06-00438-gf2.gif 8,2K
1984-4689-zool-32-06-00438-gf3.gif 8,5K

E também verifiquei que no pacote enviado as imagens já estão com tamanho reduzido.

Talvez este pacote quando foi gerado, tenha sido gerado com uma versão anterior de Markup que estivesse com defeito, mas a atual me parece que está OK.

Sugiro que seja identificado qual foi a versão usada para gerar este pacote com defeito nestas imagens para ficar registrado.
Sugiro que o XML seja gerado novamente usando o Markup 4.0.091, ou com uma versão posterior a que sugiu o defeito.

**Comment by javani** [comment]
@robertatakenaka nesse arquivo em específico as imagens estão em png. No arquivo estão com boa qualidade e foram convertidas todas para gif quando utilizei o markup. Nesse caso então deveria ter mantido o formato, certo?

**Comment by robertatakenaka** [comment]
@javani: a extração das imagens é feita salvando o arquivo em HTML, função
do próprio Word. Ao fazer isso, o Word gera uma pasta com as imagens.
Talvez para o Word o que não for jpg é gif.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2016-02-01 9:57 GMT-02:00 javani <notifications@github.com>:

**Comment by javani** [comment]
@robertatakenaka acho que não é isso não. Gerei com um arquivo .doc da Bwho e gerou com png no pacote. Alterei para docx e mesmo assim gerou como png.
[BLT.14.150516.docx](https://github.com/scieloorg/PC-Programs/files/112189/BLT.14.150516.docx)

**Comment by robertatakenaka** [comment]
@javani: hum... então acho que algo típico deste arquivo da zool, porque
para mim ele gerou .gif.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2016-02-01 10:16 GMT-02:00 javani <notifications@github.com>:

**Comment by robertatakenaka** [comment]
@javani , @leticiaquino :
Acontece o seguinte: quando é usado o Markup para gerar o XML, provavelmente ao inserir a imagem no markup ela perde a qualidade. Isso eu não tenho controle. Ao gerar o XML, o Markup converter o .doc ou .docx em .html, de forma que consegue extrair as imagens, pois uma pasta com o arquivo html + imagens.

O Markup usa estas imagens, as renomeia para o padrão scielo, e as copia para a pasta do pacote. Ignorando totalmente os .jpg em boa resolução.

Uma solução que não envolve alterar o programa é: no Markup, onde está o elemento [graphic href=?...], editar o href, inserindo o nome da imagem com a extensão, preferencialmente .tiff, e a imagem deve estar no src, junto com os pdf.

Tentarei buscar uma solução mais automática.

**Comment by robertatakenaka** [comment]
@javani, @leticiaquino , @luanaaraujo:
O Markup usará para compor o pacote nesta ordem de prioridade:

1. arquivo de imagem cujo nome está formato final padrão que adotamos para o XML  que esteja em src. Ex.: 1234-5678-acron-9-1-gf1.tiff, desde que o XML gerado seja 1234-5678-acron-9-1.xml
2. arquivo de imagem informado no [graphic href="arquivo_01.tiff"], desde que esteja no src
3. arquivo de imagem cujo nome é formato por nome_do_arquivo_doc + id do graphic e que esteja no src. Ex.: para arquivo a01.doc e graphic de uma fig cujo id="f1", então deve existir em src, um arquivo a01f1.tiff, ou a01f1.jpg, etc, ou seja, se fig/id = "f01" entao o arquivo tem que ser a01f01.tiff ou .jpg.
4. arquivo de imagem gerado a partir das imagens embutidas no HTML.

O XPM vai testar cada uma das situações, nesta ordem, para decidir qual arquivo de imagem ele incluirá no pacote.
