### ISSUE TITLE
[XPM para PMC] Possibilidade de extração de dados apenas do artigo principal, desconsiderando sub-article

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#1974]
Para o PMC há necessidade apenas do XML com o artigo no idioma inglês.
Quando é gerado o pacote do PMC é incluído também o sub-article que é retirado do arquivo manualmente.
Verificar a possibilidade de gerar um pacote com apenas o idioma principal do documento que deverá ser o inglês, por nossa orientação.

**Comment by suelylc** [comment]
Verificar a possibilidade de transferir o ```<article-title>``` ,o ```<abstract>``` e o  ```<kwd-group>``` do ```<sub-article>``` para o ```<article>``` como elementos de tradução no .xml

**Comment by leticiaquino** [comment]
@javani @suelylc @robertatakenaka Não sei se entendi bem, nós não enviamos mais arquivos com tradução para o PMC?

Lembro que enviávamos há um tempo atrás, pois o PubMed aceita arquivos em mais que um idioma:

http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html#dob-multi-lang
http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/genprac.html#lang

Esse ticket tem é motivado por conta de algum modelo de publicação diferente (fascículos que publicam 100% em inglês mas somente alguns arquivos traduzidos?)?

**Comment by javani** [comment]
@leticiaquino @suelylc @robertatakenaka esse ticket foi solicitado porque envios com traduções ao PMC são a excessão e não a regra. Como há vários periódicos que enviamos que possuem tradução, a exclusão é manual o que pode acarretar problemas, ainda mais quando o idioma original é marcado como português.
