### ISSUE TITLE
Converter gravando tags HTML na base de dados

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/PC-Programs#1975]
Erro reflete em resultados inesperados em diversas aplicações.

Ex: Search SciELO
http://search.scielo.org/?q=S0074-02762015000500691

**Comment by robertatakenaka** [comment]
@fabiobatalha :
Verifiquei este registro e está correto:
A data de entrada foi 20150818 (campo v91 do registro O)
A data de atualização foi 20150826 (campo v93 do registro O).

No registro h:
12  "Draft genome sequence of a multidrug-resistant Acinetobacter baumannii ST15 (CC15) isolated from Brazil^len"

No registro f (que mantém a formatação html):
12  "Draft genome sequence of a multidrug-resistant <em>Acinetobacter baumannii</em> ST15 (CC15) isolated from Brazil^len"
