### ISSUE TITLE
Documentar a maneira de executar via linha de comando o XPM

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/PC-Programs#1998]
Desculpem se isso já está documentado mas não achei..

Seria muito prático se fosse possível rodar o XPM gerando os relatório etc via linha de comando linux...

**Comment by robertatakenaka** [comment]
@lpanebr : sim, é possível. Vamos documentar.

**Comment by lpanebr** [comment]
sério?! que maravilha!!

Aguardo ansiosamente! :-D

**Comment by lpanebr** [comment]
@robertatakenaka se me der alguma dica eu posso tentar por aqui...

tentei o básico:
```bash
$ pwd
/home/lpanebr/Documents/scielo-programs/SciELO_XPM/xml
$ python ./xml_package_maker.py
```

Mas da esse erro:
```bash
Traceback (most recent call last):
  File "./xml_package_maker.py", line 5, in <module>
    from modules import xpmaker
  File "/home/lpanebr/Documents/scielo-programs/SciELO_XPM/xml/modules/__init__.py", line 28, in <module>
    t = gettext.translation('xpm-xc', locale_path, [current_locale])
  File "/usr/lib/python2.7/gettext.py", line 484, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'xpm-xc'
```

Fiz algum debbuging básico e no ponto em que da pau `t = gettext.translation('xpm-xc', locale_path, [current_locale])` as variáveis estão setadas:
 - current_locale = `en`
 - locale_path = `/home/lpanebr/Documents/scielo-programs/SciELO_XPM/xml/modules/../locale`

**Comment by lpanebr** [comment]
Oi @robertatakenaka desculpe perguntar novamente:

 - é possível rodar via linha de comando no windows e no linux?
 - será que tem alguma dica pra me ajudar a tentar por aqui?

**Comment by robertatakenaka** [comment]
O ticket foi resolvido na sexta mas a documentação deve ficar pública hoje
em docs.scielo.org.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2016-02-15 11:43 GMT-02:00 Luciano <notifications@github.com>:

**Comment by lpanebr** [comment]
Obrigado!

Tive outro problema mas resolvi. Vou criar outro ticket.
