### ISSUE TITLE
Prever Errata como AOP

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#2006]
Prever errata como AOP.

Ver relatório rbh v35n70.

Ver arquivos:
V:\SciELO\serial\rbh\2015nahead-erratas
V:\SciELO\serial\rbh\v35n70

**Comment by robertatakenaka** [comment]
@RPostalli : como errata é um título que pode ocorrer mais de 1 vez tanto em um "fascículo" aop e como em um fascículo regular e não há autores, a etapa de confirmação ficará **somente** dependente do nome do arquivo, ou talvez, usar as primeiras palavras do body.

**Comment by RPostalli** [comment]
Você havia comentado de validar através da tag <related>, não seria melhor?
Sendo a mesma tag com o mesmo DOI informado?
