### ISSUE TITLE
Criação do status "Indexação interrompida"

### ISSUE THREAD

**Issue by francine-curivil** [scieloorg/PC-Programs#2007]
Gostaria de solicitar a criação do status "Indexação interrompida" para razão de saída de um periódico da Coleção SciELO.

Qualquer dúvida estou à disposição.

**Comment by robertatakenaka** [comment]
@francine-curivil : já existe o status indexação interrompida

![captura de tela 2016-02-04 as 16 06 22](https://cloud.githubusercontent.com/assets/505143/12824621/3f1daa42-cb59-11e5-90d7-2599ba7b268a.png)

**Comment by javani** [comment]
@robertatakenaka @francine-curivil na verdade deve ficar como interrompida apenas. Neste caso não é interrompida pelo comitê.

**Comment by robertatakenaka** [comment]
@javani e @francine-curivil : confirmando: é para ter um status a mais ou para substituir o "interrompida pelo comitê"?

**Comment by javani** [comment]
@francine-curivil @robertatakenaka é um a mais onde quem pede a interrupção da indexação é a própria revista, mas ela ela não passou a ser acesso fechado e nem deixou de existir. É um novo status

**Comment by fabiobatalha** [comment]
Ficou definido no SciELO Manager que o status deve ser: **terminated-by-editor**

**Comment by francine-curivil** [comment]
@robertatakenaka @fabiobatalha 

Repito aqui a pergunta feita em scieloorg/scielo-manager#1240

Escolhendo o status "terminated-by-editor" qual será a mensagem que aparecerá no site?

**Comment by fabiobatalha** [comment]
Equipe, as diretivas mudaram.

Acompanhar em: #1242

**Comment by robertatakenaka** [comment]
@fabiobatalha : na base, ficará o seguinte:

S para supenso, com subcampo ^e (por exemplo), para indicar o motivo da suspensão, se aplicável.

Possíveis valores para este subcampo:

- suspended-by-editor (Suspenso a pedido do Editor)
- suspended-by-committee (Suspenso a pedido do Comitê Consultivo)
- not-open-access (Suspenso a pedido do Comitê Consultivo por deixar de ser acesso aberto)

confirma?

**Comment by fabiobatalha** [comment]
@robertatakenaka 

Correto.
