### ISSUE TITLE
Ajuste em definição suspensão de periódico.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/PC-Programs#2010]
Corrigir implementação de Histórico de Mudanças do periódico na Title Manager.

Atualmente existe uma razão de suspensão definida como "No longer open access", cuja identificação é feita no campo v51 sob o código "E". 
http://docs.scielo.org/projects/scielo-pc-programs/en/latest/code_database.html#history

Entretanto "No longer open access" esta mais para uma classificação/motivo de uma suspensão que também é realizada pelo comitê.

Sugestão: 
* Manter ambas as suspensões sob código "S" que representa uma suspensão feita pelo Comitê.
* Quando a suspensão for do tipo "No longer open access", identificá-la em um subcampo ex:
```
"^a19981207^bC^c20121200^dE^eno-longer-open-access"
```
Deste modo, futuramente, outros tipos de suspensão feitas pelo comitê poderão ser classificadas para fins de relatórios.

A ausência do subcampo ^e em casos de suspensão compreende em uma suspensão sem classificação, não havendo mudanças de comportamento no site ou nos registros da Title Manager.

A interface SciELO deverá ser ajustada para seguir apresentando o motivo da suspensão.

**Comment by robertatakenaka** [comment]
@fabiobatalha :
No lugar de:
```
"^a19981207^bC^c20121200^dE^eno-longer-open-access"
```
Acho que vc quis dizer:
```
"^a19981207^bC^c20121200^dS^enot-open-access"
```
https://github.com/scieloorg/scielo-manager/issues/1242
