### ISSUE TITLE
[instalador]  erro do gettext ao executar XPM via linha de comando no linux

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/PC-Programs#2017]
As pastas `Lc_messages` devem estar em caixa alta `LC_MESSAGES` para o gettext localizar o arquivo de tradução no linux.

**Comment by robertatakenaka** [comment]
@lpanebr : obrigado. O gerador do instalador mudou as letras maiúsculas pelas minúsculas.
Será corrigido em uma próxima versão.

**Comment by lpanebr** [comment]
oi @robertatakenaka ontem mesmo eu baixei o `xpm-4.0.091-trial-2016-02-04.zip` do FTP e ao descompactar observei que as pastas ainda estavam `Lc_messages`

No Windows não tem problema mas no linux da o erro..

**Comment by robertatakenaka** [comment]
Correto. O zip é do dia 4 de fev. O ticket foi resolvido posteriormente.
Ainda não está disponível.



Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by lpanebr** [comment]
Sorry, me enganei pois a data que aparece pra mim é 7 de março:
![image](https://cloud.githubusercontent.com/assets/129185/13880412/e0e1150e-ecfa-11e5-99f5-6357532be7ba.png)
