### ISSUE TITLE
[xpm]  incluir opção para não abrir o relatório automaticamente após executar XPM via linha de comando no linux

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/PC-Programs#2018]
O problema acontece quando o XPM é executado no Linux server, pois não existe programa para abrir o relatório gerado. Ou então abre no navegador ASCII do terminal...

Se houver uma opção para impedir que o relatório seja aberto aumenta a possibilidade de automação.

**Comment by lpanebr** [comment]
Legal Roberta! Como fica o parâmetro?

**Comment by robertatakenaka** [comment]
@lpanebr : ficou como -auto (se tiver sugestão melhor, eu mudo)

**Comment by lpanebr** [comment]
Legal @robertatakenaka 

eu estranhei poi não vi o `auto` no commit e7943cd mas funcionou perfeitamente!

Obrigado!

**Comment by robertatakenaka** [comment]
estava na dúvida do nome. Mudei o nome para -auto.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
