### ISSUE TITLE
[xpm] confundindo "TERROR" com "ERROR".

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/PC-Programs#2020]
O programa está confundindo "TERROR" com "ERROR". Não existe nenhum erro no título:

![terror](https://cloud.githubusercontent.com/assets/4633779/13077481/2b164bf8-d4a0-11e5-9041-424f1fa0ccb5.png)

**Comment by luanaaraujo** [comment]
@robertatakenaka isso foi arrumado apenas no XPM né? agora está dando no XC também: http://homolog.xml.scielo.br/reports/jistm/v12n3/xml_converter.html
abro um ticket especifico para o XC?

**Comment by robertatakenaka** [comment]
@luanaaraujo: teste e abra ticket somente para o XPM.


Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by luanaaraujo** [comment]
@robertatakenaka no XPM está correto. O erro é apenas no XC.
