### ISSUE TITLE
[xc] Error em Instituição normalizada

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/PC-Programs#2027]
O Instituto Agronômico de Campinas está normalizada, porém no XC apresenta error:

XML:
```
<aff id="aff3">
				<label>(3)</label>
				<institution content-type="original">Centro de Recursos Genéticos Vegetais, Biologia
					Molecular e Fitoquímica, Instituto Agronômico de Campinas, 13001-970 Campinas,
					São Paulo, Brasil</institution>
				<institution content-type="normalized">Instituto Agronômico de
					Campinas</institution>
				<institution content-type="orgname">Instituto Agronômico de Campinas</institution>
				<institution content-type="orgdiv1">Centro de Recursos Genéticos Vegetais, Biologia
					Molecular e Fitoquímica</institution>
				<addr-line>
					<named-content content-type="city">Campinas</named-content>
					<named-content content-type="state">São Paulo</named-content>
				</addr-line>
				<country country="BR">Brasil</country>
			</aff>
```

![aff](https://cloud.githubusercontent.com/assets/4633779/13153780/e214cbe6-d65c-11e5-8320-c593880bc547.png)

XC
![xc](https://cloud.githubusercontent.com/assets/4633779/13150752/3e189e68-d64e-11e5-9bf5-85c34532582c.png)

Wayta

![wayta](https://cloud.githubusercontent.com/assets/4633779/13150763/438bb880-d64e-11e5-8004-04b59b3da7fe.png)

**Comment by robertatakenaka** [comment]
@luanaaraujo: por favor, escrever o trecho XML de aff do Instituto
Agronômico (copie e cole o texto, não imagem).

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by luanaaraujo** [comment]
@robertatakenaka pronto.

**Comment by robertatakenaka** [comment]
@luanaaraujo: este ticket está duplicado
#1917 já foi resolvido
