### ISSUE TITLE
[Markup 90 e 91] - normaff em errata

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2035]
Ao preencher as informações de [doc] ele gera as tags de [normaff] no corpo do texto.

![errata_markup](https://cloud.githubusercontent.com/assets/15328777/13293294/d8185a90-dafd-11e5-87de-3cc02761f916.png)

**Comment by robertatakenaka** [comment]
Ticket fechado por ser inválido. O documento errata não é um artigo, sendo assim não está de acordo com o modelo para marcar o "front" semiautomaticamente.
