### ISSUE TITLE
(Markup 4.0.074 - Word 2010 e 2013) Não foi possível inicializar o programa

### ISSUE THREAD

**Issue by vivianeneves** [scieloorg/PC-Programs#204]
Tanto no Word 2010 como no Word 2013 foram Habilitadas as Macros.

Word 2013:
- mudei o caminho do start.mds e p.mds para C:\Program Files\Microsoft Office 15\root\office15
- O programa tentou abrir no Word 2010 mesmo assim, sem reconhecer o 2013.
- No 2013 quando se vai gerenciar suplementos (Opções>Suplementos), o Markup não aparece nas opções de suplementos.

Word 2010:
- mudei o caminho do start.mds e p.mds para C:\Program Files\Microsoft Office\Office14
- O programa tentou abrir mas o Markup não foi reconhecido como um modelo Word.
- No 2010 quando se vai gerenciar suplementos (Opções>Suplementos), o Markup aparece nas opções de Suplementos de Aplicativos Desabilitados (e não consegui habilitar).

Em ambas tentativas exibe o erro da imagem abaixo.
![imagem1](https://f.cloud.github.com/assets/6368517/1948113/f0b22f1e-807c-11e3-8acc-6c9c3d740822.png)

**Comment by robertatakenaka** [comment]
Não houve mais problema com isso. Provavelmente era problema de Office 64 bits, que já foi resolvido.
