### ISSUE TITLE
[xpm] criar uma aba "sumário" ou ajustar a aba visão geral do pacote

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2065]
Deve conter neste relatório:

- títulos
- autores
- doi
- licença
- fpage, lpage, elocation-id
- tipo de documento
- seção

**Comment by leticiaquino** [comment]
@robertatakenaka Aparentemente esse ticket ainda não foi resolvido.

**Comment by leticiaquino** [comment]
@robertatakenaka Ticket resolvido:

![resolvido](https://cloud.githubusercontent.com/assets/4397365/19519705/e55c7868-95eb-11e6-8375-0d021ef90c85.jpg)
