### ISSUE TITLE
[xpm] Relatório acusa "Fatal error" em "history" com data anterior a 2016.

### ISSUE THREAD

**Issue by renatogaldino** [scieloorg/PC-Programs#2084]
![sem titulo](https://cloud.githubusercontent.com/assets/11942249/13570237/046b70ee-e44c-11e5-9402-ac3ae45968ee.png)

**Comment by robertatakenaka** [comment]
@renatogaldino : a mensagem está correta. Quem produziu este XML me comentou que houve atrasos mas as datas estão corretas. O programa deve continuar a indicar erro pois é uma situação atípica. O produtor do XML deve justificar que a mensagem não se aplica a este caso.
