### ISSUE TITLE
[xpm] Acusar erro quando incluído ext-link em source

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2097]
Acusar erro quando for incluído ext-link em source de referência bibliográfica.
Exemplo de XML enviado por email.

**Comment by robertatakenaka** [comment]
@javani : em que versão isso acontece?

**Comment by javani** [comment]
@robertatakenaka na versão de 04/02

**Comment by robertatakenaka** [comment]
@javani: 
Um ticket similar #1976, resolve este ticket também.
Este aqui me parece duplicado.
Por favor, teste a 09/03 (meu users), feche o ticket se resolvido.
