### ISSUE TITLE
[xpm] Erro fatal para season em referência bibliográfica

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2101]
Apresentar como warning ou erro e não como erro fatal quando fora do formato desejado. Pode ocorrer de estar em português ou espanhol e não em inglês.

**Comment by robertatakenaka** [comment]
@javani : explicar como está e como deveria ficar, usar exemplos. Não ficou claro o problema.

**Comment by javani** [comment]
@robertatakenaka no relatório apareceem ref.  [FATAL ERROR] [F9]	Valor inválido para <season>: jan./fev.. Expected value for season: initial month and final month separated by hyphen. E.g.: Jan-Feb. Expected values for the months: Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec. No documento está marcado [season]jan./fev.[/season]

**Comment by robertatakenaka** [comment]
@javani , @luanaaraujo, @renatogaldino: o que acham de **não** validar ref//month nem ref//season?

**Comment by luanaaraujo** [comment]
Eu acho importante validar @robertatakenaka

**Comment by javani** [comment]
@robertatakenaka poderia ser só um alerta. Se não me engano, o dado não é usado para match de citação ou bibliometria, então não temos que perder muito tempo nisso.

**Comment by robertatakenaka** [comment]
@luanaaraujo e @javani : não há uso em bibliometria no nível mes nem season. 
@luanaaraujo : talvez seja importante valida, no entanto, não há um padrão para referências, nem de mês nem de season. Mes talvez pudesse ser validado como número mas só. Se o produtor de XML colocar com 1 em todos os meses seria válido. Sendo assim, não sei se a utilidade desta validação. No article-meta, sim, é importante.

**Comment by luanaaraujo** [comment]
Verdade @robertatakenaka, não tem padrão. E validar mês e não validar season acho que não tem muito sentido, já que, pelos casos que já vi, ocorre mais o dado por extenso quase nunca número.
