### ISSUE TITLE
[xpm] Trocar alerta de ausência de  ext-link em mixed-citation

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/PC-Programs#2104]
Seria melhor se warning estivesse na explicação e no alerta de elemento inexistente ser error.

![image](https://cloud.githubusercontent.com/assets/4633779/13712840/8ecb1cc0-e7a4-11e5-9117-a744b94f94dd.png)

**Comment by robertatakenaka** [comment]
@luanaaraujo : são duas coisas diferentes:

1) Não foi encontrado  **http://....** em mixed-citation porque no mixed-citation há um espaço em branco entre /age/ e pubs.
2) Em element-citation há o ext-link e não foi encontrado o elemento ext-link no mixed-citation (no entanto, não sei se esta validação continuará já que na documentação não existe a instrução de manter o ext-link ou outros elementos no mixed-citation.

**Comment by luanaaraujo** [comment]
Mmm entendi @robertatakenaka, obrigada pela explicação.
