### ISSUE TITLE
[Markup v91] Insere atributo xml@lang em <license>

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2125]
Ao gerar o XML insere atributo xml@lang em license

**Comment by leticiaquino** [comment]
@javani Você está fazendo a marcação do arquivo na versão 1.4? se sim, o programa deve gerar o atributo @xml:lang dentro do elemento ```<license>```. 
Veja que na versão 1.4 do SPS foi definido que esse atributo é obrigatório:
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/master/tagset/elemento-license.html

**Comment by javani** [comment]
@leticiaquino sim Letícia, gera com o atributo vazio

**Comment by leticiaquino** [comment]
Ok @javani , como não estava descrito no ticket pensei que a sugestão fosse de retirar.
Farei testes aqui também.

**Comment by robertatakenaka** [comment]
@javani : o atributo fica vazio para todos os idiomas? você preencheu o idioma? ou nem aparece o campo para preencher o idioma?

**Comment by javani** [comment]
@robertatakenaka após a inclusão de copyrigth, mesmo com a URL da licença preenchida no formulário, a tag de license não é incluida no XML. 
![image](https://cloud.githubusercontent.com/assets/912953/13890310/7fc0648a-ed29-11e5-86d7-d363ef442e65.png)
