### ISSUE TITLE
[Markup v91] Insere atributo errado @reftype em xref de referencia bibliográfica

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2126]
[9101.docx](https://github.com/scieloorg/PC-Programs/files/179575/9101.docx)
No caso de marcação automática de xref de referência bibliográfica numérica inclui alguns reftype de boxed-text ao invés de bibr.

![captura de tela 2016-03-18 as 11 11 36](https://cloud.githubusercontent.com/assets/505143/13880249/3403b6f2-ecfa-11e5-80db-8f9ddc0c5e00.png)

Synergy generated by second and fifth mechanisms implies inhibition of the ubiquitin-proteasome system that is involved in skeletal muscle atrophy[xref ref-type="boxed-text" rid="r12"]12[/xref],[xref ref-type="boxed-text" rid="r38"]38[/xref]

**Comment by robertatakenaka** [comment]
@javani : fazendo uma análise superficial notei que não foi identificado com bibr porque em ambos números não há o link com a referência. 
Eu acredito que não vale apenas fazer nenhum ajuste. A menos que considere que é uma coisa muito persistente.
