### ISSUE TITLE
[Markup v91] Não indica linha de erro no XML quando há problema de marcação errada

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2127]
Indicar a linha onde há o erro no XML incorrect.

**Comment by javani** [comment]
@robertatakenaka complementando, quando há um erro de marcação e o programa não consegue gerar o XML, apresenta erro e pede para abrir o arquivo no editor de XML. Antigamente aparecia a linha onde estava o problema.
![image](https://cloud.githubusercontent.com/assets/912953/13918247/aea02084-ef44-11e5-8f47-c109f2b8f812.png)

**Comment by robertatakenaka** [comment]
@javani : consegue me enviar este arquivo para simular esta situação?

**Comment by javani** [comment]
@robertatakenaka incluí uma barra no primeiro xref do texto. Segue arquivo

**Comment by robertatakenaka** [comment]
@javani : quando o XML está bem formado (abre e fecha tags, caracteres válidos), mas tem problema de DTD, o XML é mostrado linha a linha e os erros são apontados. Mas quando o XML não está bem formado e/ou tem problemas com caracteres, o validador (JAVA) nem consegue ler o arquivo.

Vou avaliar se há um modo de mostrar neste caso.
