### ISSUE TITLE
[xpm] Não indicar *Fatal error* em *orgdiv*

### ISSUE THREAD

**Issue by renatogaldino** [scieloorg/PC-Programs#2128]
Cria-se muitas possibilidade para "falsos positivos" como é o caso de indicar *Fatal error* para o elemento  `<institution content-type="orgdiv1">`.

![sem titulo](https://cloud.githubusercontent.com/assets/11942249/13879669/6e445d74-ecf7-11e5-9231-0c674b6b5c3c.png)

Talvez poderia ser indicado somente *warning* ou nenhum aviso.

**Comment by robertatakenaka** [comment]
@renatogaldino : já foi registrado e já foi consertado. está usando a versão nova? #2122

**Comment by renatogaldino** [comment]
@robertatakenaka  a versão nova continua apontando o erro:

![sem titulo](https://cloud.githubusercontent.com/assets/11942249/13881599/481a2a12-ed00-11e5-9626-a60865dcc832.png)
