### ISSUE TITLE
[Markup v.91] [HTML] Erro no uso de fname-surname em nomes com pontuação

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/PC-Programs#2143]
Ao identificar nome que contém abreviação, com ponto, a tag fname-surname, não faz a  identificação corretamente, tanto em monog quanto em contrib:

Exemplos:

Nesse caso ele não funciona:
```[oauthor role="nd"]L. S. Vygotski[/oauthor]```

Sem ponto a tag funciona:
```[oauthor  role="nd"][fname]L S[/fname] [surname]Vygotski[/surname][/oauthor]```

Nesse caso ele identifica como surname o fname:
```[oauthor role="nd"][surname]Maria[/surname] J. N. Santos[/oauthor]```

Nomes sem abreviações ele identifica corretamente:
```[oauthor role="nd"][fname]Carlos Henrique[/fname] [surname]Moraes[/surname][/oauthor]```

**Comment by robertatakenaka** [comment]
@luanaaraujo : Para o Markup para SGML vamos dar uma prioridade menor. Especialmente quando  há alternativas, ou seja, o usuário consegue usar fname e surname separados. Para este ticket, como funciona em alguns casos, vou manter o botão, no entanto, não será corrigido para atender todos os casos.

**Comment by luanaaraujo** [comment]
Ok @robertatakenaka

**Comment by robertatakenaka** [comment]
@luanaaraujo : tive que resolver um ticket e acho que este acabou sendo resolvido também. Pode testar?
