### ISSUE TITLE
[Markup v.91] [HTML] Inserção de id errado em aff

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/PC-Programs#2154]
Markup insere id aff1, porém para html é a01, e ao tentar editar ele não salva:

![id errado em aff](https://cloud.githubusercontent.com/assets/4633779/14019470/b2323fba-f1b1-11e5-8e72-f446ff49cd3c.png)

**Comment by robertatakenaka** [comment]
@luanaaraujo: a rigor não é importante ser a01 ou aff1, o ideal é que em
author e em aff os valores estejam iguais. Verifique se esta versão do
markup permite isso.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by luanaaraujo** [comment]
@robertatakenaka abri porque está dando erro no parser. Sim, os valores estão iguais, ele dá erro por ser aff e não a0.
