### ISSUE TITLE
[Markup v.91] [HTML] Gerando tag <label> e <sup> em <aff>

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/PC-Programs#2162]
O programa está inserindo ```<label>``` e ```<sup>``` na primeira afiliação marcada:

![affe com label](https://cloud.githubusercontent.com/assets/4633779/14079893/a110c1d8-f4d7-11e5-99e0-f276018c7455.png)

**Comment by robertatakenaka** [comment]
@luanaaraujo : acho que não há problemas nisso. Para o Converter (HTML) label e sup serão igorados

**Comment by luanaaraujo** [comment]
Ok @robertatakenaka
