### ISSUE TITLE
[Markup v91] Marcação de material suplementar em linha

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2174]
No arquivo enviado por email, quando incluo em "The questionnaire ([supplmat id="suppl1" href="pharmpract-14-639-suppl1"]Online Appendix 1[/supplmat])" e gero o XML, não apresenta erro de DTD mas não gera o relatório de conteúdo. Outra coisa é que não gera a tag corretamente.
No XML
```<inline-supplementary-material xlink:href="1885-642X-pharmacy-14-01-00639-ssuppl1.pdf">Online Appendix 1</inline-supplementary-material>```

E deveria ser:
```<inline-supplementary-material xlink:href="1885-642X-pharmacy-14-01-00639-ssuppl1.pdf" mimetype="application" mime-subtype="pdf">Online Appendix 1</inline-supplementary-material>```

Não gera relatório de conteúdo.
![image](https://cloud.githubusercontent.com/assets/912953/14124032/c9e427b4-f5d9-11e5-8f21-804b12a8a7e2.png)

**Comment by robertatakenaka** [comment]
@javani : me esqueci de pedir o arquivo .doc.

**Comment by robertatakenaka** [comment]
@javani: sobre o mimetype, para mim funcionou:

```xml
(<inline-supplementary-material mime-subtype="pdf" mimetype="application" xlink:href="1885-642X-pharmacy-14-01-639-ssuppl1.pdf">Online Appendix 1</inline-supplementary-material>) 
```
você tinha o pdf dentro da pasta src?

**Comment by javani** [comment]
@robertatakenaka sim, está na estrutura correta. O mesmo ocorreu para os outros arquivos com suplemento.

**Comment by javani** [comment]
@robertatakenaka tem como verificar o erro XPM que não valida/gera relatório quando há arquivos com material suplementar em linha?
