### ISSUE TITLE
[Markup 91] No relatório de conteúdo apresenta erro de PDF não encontrado como subarticle

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2175]
![image](https://cloud.githubusercontent.com/assets/912953/14147021/38a769a4-f670-11e5-8187-e0b32e9dea39.png)
Quando marcada a imagem, apresenta erro no relatório de conteúdo de pdf não disponível para sub-article. Acontece que não há sub-article no artigo.

**Comment by robertatakenaka** [comment]
@javani: existe este arquivo -gf1.pdf ? Este pdf é uma figura? Está marcado como fig? ou material suplementar?

**Comment by javani** [comment]
@robertatakenaka está marcado como figura e só existe dentro do arquivo word. Quando gera o XML, renomeia o próprio do artigo com a extensão pdf e inclui gf na sua nomeação.
