### ISSUE TITLE
[Markup 91] Inclui nome inválido em href de imagem

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2176]
Ao fazer a marcação com xmlbody, inclui no nome da imagem g0001 etc. Quando gera o relatório de conteúdo não localiza a imagem.
![image](https://cloud.githubusercontent.com/assets/912953/14148868/de3977a2-f677-11e5-9d6e-f3900c15f40d.png)

![image](https://cloud.githubusercontent.com/assets/912953/14148898/f14f8ef8-f677-11e5-8502-67e493ee5344.png)

**Comment by robertatakenaka** [comment]
Para registro, aconteceu porque neste arquivo, as imagens estão com dados da origem de onde foram retiradas

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4800013/bin/pharmpract-14-650-g001.jpg

![captura de tela 2016-03-31 as 15 42 42](https://cloud.githubusercontent.com/assets/505143/14187159/092b4798-f758-11e5-8825-9b7f4af5d6bd.png)
