### ISSUE TITLE
XC e XPM dão como válida instituição de ensino brasileira que em normalized aff está no idioma inglês

### ISSUE THREAD

**Issue by marciamorgan** [scieloorg/PC-Programs#2184]
XC e XPM dão como válida instituição de ensino brasileira que em normalized aff está no idioma inglês e no wayta ela é recuperada em português: 
![wayta](https://cloud.githubusercontent.com/assets/4700259/14179469/9239859a-f735-11e5-905b-842916200f2f.JPG)

Relatório:
![realtorio](https://cloud.githubusercontent.com/assets/4700259/14179559/e86d6526-f735-11e5-92e4-e3449c2ba47d.JPG)

XML:
```
<aff id="aff02">
					<label>b</label>
					<institution content-type="orgdiv1">School of Engineering</institution>
					<institution content-type="orgname">Federal University of Rio Grande do
						Sul</institution>
					<institution content-type="normalized">Federal University of Rio Grande do
						Sul</institution>
					<addr-line>
						<named-content content-type="state">RS</named-content>
						<named-content content-type="city">Porto Alegre</named-content>
					</addr-line>
					<country country="BR">Brazil</country>
					<institution content-type="original">School of Engineering, Federal University
						of Rio Grande do Sul (UFRGS), RS, Porto Alegre, Brazil</institution>
				</aff>
```

**Comment by robertatakenaka** [comment]
@marciamorgan : marcia, não se preocupe, está correto. Explico-me:

apesar de "normalized" estar "Federal University of Rio Grande do Sul",
o XPM consulta Wayta e localiza que o nome correto é "Universidade Federal do Rio Grande do Sul" e assim ficará registrado na base que o converter gera.

O ideal é corrigir o normalized.
O mais ideal ainda seria que apesar de wayta ter encontrado o normalized correto e haver um normalized errado no XML, alertar o usuário que ele está usando o normalized incorreto...
