### ISSUE TITLE
[Markup 91] Não valida dados errados em referência

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2201]
Ao simular um erro (marquei arttitle em book), o relatório de conteúdo não apresenta erro. Também não está mais apresentando aqueles alertas de que o conteúdo está diferente em mixed e em source.
Envio o artigo por email

**Comment by javani** [comment]
@robertatakenaka esse é um dos arquivos com o material suplementar, que não gerava o relatório de conteúdo, agora gera mas não valida tudo.

**Comment by robertatakenaka** [comment]
@javani: o XPM corrige algumas coisas, então, verifique se no XML final, que fica dentro do scielo_package, está ou não corrigido.

**Comment by javani** [comment]
@robertatakenaka ele converteu article-title para source, até aí tudo bem, mas não marquei o ano, autores nada. No XML ficou
```
<ref id="B14">
					<mixed-citation>14.World Health Organization. Adherence to long-term therapies: evidence for action. SabatéE eGWH, Organization. 2003 accessed May 1 2015. http://www.who.int/chp/knowledge/publications/adherence_introduction.pdf.</mixed-citation>
					<element-citation publication-type="book">
						<source>Adherence to long-term therapies: evidence for action.SabatéE eGWH, Organization</source>
					</element-citation>
				</ref>
```
Não teria que apresentar erro uma vez que não tem os dados básicos para o tipo de referência?

**Comment by javani** [comment]
@robertatakenaka quando eu passo no package apresenta o erro, mas no relatório de conteúdo do markup não.
Abaixo resultado do relatório do package:
![image](https://cloud.githubusercontent.com/assets/912953/14215265/5f602956-f818-11e5-90a7-24d67451969f.png)

Não deveria dar o mesmo erro no relatório de conteúdo do markup?

**Comment by robertatakenaka** [comment]
Sim, tem que ser igual. O XPM está incluído dentro do pacote do Markup.



Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2016-04-01 14:45 GMT-03:00 javani <notifications@github.com>:

**Comment by javani** [comment]
@robertatakenaka o estranho que eu gero o relatório do package da pasta XML e o resultado está diferente. Fiz a cópia daqueles 2 itens que você pediu de manhã (modules e locale) para a minha scielo_markup. Antes estava funcionando e agora não mais. Vou testar com outro arquivo

**Comment by robertatakenaka** [comment]
@javani : me envia o .doc?
