### ISSUE TITLE
(Markup 4.0.091 -  word 2013) Programa apresenta erro ao marcar informação de [onbehalf]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2205]
Verificamos que ao fazer a identificação da informação de [onbehalf] o programa Markup apresenta o seguinte erro:

![erro-onbehalf](https://cloud.githubusercontent.com/assets/4397365/14286360/26d945a8-fb25-11e5-8e51-f90159aa2d48.jpg)

Anexo arquivo de teste.
[abc-01.docx](https://github.com/scieloorg/PC-Programs/files/204740/abc-01.docx)

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
@javani: não é um elemento esperado dentro de author. Mas parece que
deveria. Como deve ficar isso no XML?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2016-04-05 11:58 GMT-03:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
@robertatakenaka Na versão anterior o programa estava marcando dessa maneira.
Até documentamos essa forma de marcar.

Veja: http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_how_to_generate_xml-markup.html#on-behalf

O XML deverá ser apresentado da seguinte forma:

```xml
    <contrib>
        <name>
            <surname>Proietti</surname>
            <given-names>Fernando Augusto</given-names>
        </name>
        <xref ref-type="aff" rid="aff4">II</xref>
        <on-behalf-of>Interdisciplinary HTLV Research Group</on-behalf-of>
    </contrib>
```

**Comment by robertatakenaka** [comment]
@leticiaquino : o onbehalf está sendo esperado somente dentro de doc e não dentro de author. Mas vou inserí-lo dentro de author.
