### ISSUE TITLE
[Markup v.91] [HTML] Automata para normas APA, NBR, OTHER não funciona

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/PC-Programs#2208]
Ao tentar fazer a marcação automática (opção 2) o programa apresenta a seguinte caixa de diálogo informando que automata está disponível apenas para vancouver:
![erro_apa](https://cloud.githubusercontent.com/assets/4633779/14289551/af741134-fb31-11e5-8e3e-948c9b4125d2.png)

No botão automata1 apresenta erro a seguir:
![erro_automata1](https://cloud.githubusercontent.com/assets/4633779/14292278/d00d5b2e-fb3d-11e5-8cd9-1669e34c5c51.png)

**Comment by robertatakenaka** [comment]
@luanaaraujo , @javani , @leticiaquino :
Automata1 = depende de haver o arquivo acron.amd dentro de bin/markup, com as regras de automatas para a revista
Automata 2 = somente disponível para Vancouver
Automata 3= disponível para article e text: apa e abnt; para doc: abnt

para other realmente não há como ter automata.
se puderem escrever um texto sobre os automatas que estão disponíveis, seria bom.

**Comment by luanaaraujo** [comment]
@robertatakenaka Antes de abrir o ticket verifiquei se o acron.amd estava dentro de bin/markup, e pelo que entendi todas estavam. Segue esse periódico da img, acima, em bin/markup/automata, veja, por favor, se é isso que deve conter:
![automata_mds](https://cloud.githubusercontent.com/assets/4633779/14292725/b536c93c-fb3f-11e5-8d79-952231445c1b.png)

**Comment by robertatakenaka** [comment]
@luanaaraujo , @javani , @leticiaquino : este arquivo que contém esta lista não é necessário.
o que está faltando é o arquivo cinet.amd dentro do bin/markup.

O automata_samples é uma pasta que contém alguns automatas mas são como exemplos. O programa só vai considerar os arquivos .amd que estiverem logo abaixo o bin/markup.
Ou seja, se vc tem o cinet.amd dentro automata_samples, copia ele para dentro de bin/markup.

**Comment by luanaaraujo** [comment]
@robertatakenaka Ok, vou testar.

**Comment by luanaaraujo** [comment]
Agora foi @robertatakenaka pelo automata 3, algumas referências ficam com marcação errada, ou o automata nem reconhece, mas é por estarem fora de como indica a norma. 
O automata 1 continua dando o mesmo erro.
Vou continuar fazendo testes.
