### ISSUE TITLE
(Markup 4.0.091 - word 2013) Inserir tag [suffix] em [pauthor] de [ref]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2215]
Verificamos que o programa Markup insere a tag [suffix] quando há nome de autor com sufixo com a informação "Jr", entretanto não há uma tag para fazer a identificação manual desse dado.

Veja que na referência abaixo o autor tem o sufixo "3rd", mas o programa identifica como [surname].
Verificar as seguintes possibilidades:
1- Inserir uma tag [suffix] para marcação manual e
2 - Considerar suffix os seguintes sufixos: "Jr", "Júnior", "Junior", "Neto", "Filho", "Sobrinho", "2nd", "Segundo", "3rd" e "Terceiro".

Ver ref. e documento anexo:

![suffix-3rd](https://cloud.githubusercontent.com/assets/4397365/14386699/411d1f1c-fd7c-11e5-9073-447b8524bced.jpg)

[abc-01.docx](https://github.com/scieloorg/PC-Programs/files/210295/abc-01.docx)

**MODULO - XMLMarkup
PRIORIDADE - Medium**

**Comment by javani** [comment]
@robertatakenaka @leticiaquino acho que estes casos são muito difíceis de prever. Não há como ter uma tag [suffix] para incluirmos manualmente?

**Comment by leticiaquino** [comment]
@robertatakenaka Sim, caso não haja a possibilidade da marcação automática o ideal é ter a tag para identificação manual.
