### ISSUE TITLE
[xpm] Mudar a regra de orcid começar com URL

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2218]
(leticiaquino) Verifiquei também que o programa apresenta desconformidade com o PMC quando há informação de ORCID sem o dado: "http://orcid.org/"

O erro apresentado no relatório de erros é:

"/article/front/article-meta/contrib-group/contrib: [error]ORCID contrib-id check: ORCID values must start with 'http://orcid.org/' (Tagging Guidelines)"

Verificar em: http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-contrib-id

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-contrib-id.html

**Comment by leticiaquino** [comment]
@robertatakenaka Foi decidido que para SciELO PS o elemento  ```<contrib-id>``` não pode conter dados do tipo URI (URL). Veja:
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-contrib-id.html

Sem o prefixo "http://orcid.org/" a validação do ID se torna mais consistente. O @gustavofonseca pode dar mais detalhes sobre essa decisão.

Atualmente ao gerar um arquivo XML, o programa Markup apresenta o seguinte erro:

![contrib-id](https://cloud.githubusercontent.com/assets/4397365/19269755/acf7439a-8f92-11e6-85ba-b546c98f3655.jpg)

Caso esse dado seja imprescindível para PMC, por favor verificar a possibilidade de inserir automaticamente para revistas PMC.

Arquivo disponível anexo.
[abc-01.docx](https://github.com/scieloorg/PC-Programs/files/521753/abc-01.docx)

**Comment by robertatakenaka** [comment]
@leticiaquino : verifique se está com a versão correta para os testes.

**Comment by leticiaquino** [comment]
@robertatakenaka atualizei o Markup e ainda sim o programa apresenta erro de "http://..."

**Comment by leticiaquino** [comment]
@robertatakenaka com a última atualização disponibilizada hoje, o programa não apresenta erro em ```<contrib-id>```.
