### ISSUE TITLE
[xpm] Validação de quantidade de figuras (fig-group/fig)

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2219]
Em um artigo com legenda bilíngue ocorre o seguinte erro na validação do XML. Falto positivo?

 
```xml

<fig-group id="f1">
  <fig xml:lang="pt">
     <label>Figura 1</label>
     <caption>
        <title>xxxxxxxxxx.</title>
     </caption>
     <graphic xlink:href="xxxxxxx-gf1.jpg"/>
  </fig>
  <fig xml:lang="en">
     <label>Figure 1</label>
     <caption>
        <title>yyyyyyyyyyyyyy.</title>
     </caption>
  </fig>
</fig-group>
```

 

[ERROR [E1]: fig-count check: fig-count (4) and number of fig (8) in XML do not match]

**Comment by leticiaquino** [comment]
@robertatakenaka acredito ser falso positivo. Trata-se de 1 única figura, mas que apresenta legenda traduzida.
