### ISSUE TITLE
[XPM] - Considerar elementos <break>, <italic>, <bold> em tabelas

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2232]
Verificar a possibilidade de considerar os elementos ```<break>```, ```<italic>```, ```<bold>``` em tabelas. 

Ticket relacionado ao ticket 459 do repositório WEB: https://github.com/scieloorg/Web/issues/459

**Comment by robertatakenaka** [comment]
ticket fechado por ser do Web e não do PC programs.
