### ISSUE TITLE
[xc] Instituições normalizadas apresentando warning

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/PC-Programs#2240]
O XC apresenta warning para as seguintes instiuições, porém as mesmas constam no wayta:

Universiti Sains Malaysia
Université d'Aix-Marseille
University of Medical Sciences

![unversidade](https://cloud.githubusercontent.com/assets/4633779/15363870/aca79896-1cf0-11e6-9bb7-4f3d80385856.png)

![normacod](https://cloud.githubusercontent.com/assets/4633779/15363891/c09d2294-1cf0-11e6-9906-16b6f971a2bc.png)

XML: 
```<aff id="aff1">
				<label>1</label>
				<institution content-type="original">Universiti Sains Malaysia, Medical Entomology
					Laboratory, School of Biological Sciences. Penang 11800, Malaysia. E-mails:
					wfatma@usm.my; abbyrra88@yahoo.com; tiamalini@yahoo.com; nfadzly@usm.my </institution>
				<institution content-type="normalized">Universiti Sains Malaysia</institution>
				<institution content-type="orgname">Universiti Sains Malaysia</institution>
				<institution content-type="orgdiv1">School of Biological Sciences</institution>```

**Comment by robertatakenaka** [comment]
@luanaaraujo , @leticiaquino : verificar se problema persiste
