### ISSUE TITLE
[XPM] [XC] Sugere tipo inexistente no SPS

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2255]
o XPM e o XC está sugerindo a inserção de um tipo que não existe no SPS.

![xpm_other](https://cloud.githubusercontent.com/assets/15328777/15540829/d6794db2-225f-11e6-86d4-254517fbeecd.png)

Como está no XML:

```<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article
  PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.0 20120330//EN" "http://jats.nlm.nih.gov/publishing/1.0/JATS-journalpublishing1.dtd">
<article article-type="other" dtd-version="1.0" specific-use="sps-1.4" xml:lang="en"
	xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink">```

**Comment by robertatakenaka** [comment]
@alexxsilva, @leticiaquino: que eu saiba o tipo other é usado para os
documentos que não encaixam em nenhum dos tipos previstos. Outra
possibilidade é que este documento não deveria ser aceito se ele não se
encaixar nos itens já previstos. Sugiro que discuta isso na sua equipe.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by leticiaquino** [comment]
@robertatakenaka eu notei que na página 28 dos Critérios SciELO Brasil os tipos aceitos são apenas esses que seguem abaixo: 

*adendo, artigo de pesquisa, artigo de revisão, carta, coleção, comentário de artigo, comunicação breve, comunicação rápida, discurso, discussão, editorial, errata, introdução, norma, relato de caso, resenha crítica de livro, resposta, retratação e retratação parcial e “outro” (quando o documento é indexado mas nenhum dos tipos anteriores se aplica)*

Vi que a seção desse documento é Entrevista, e de acordo com os Critérios SciELO BR esse tipo não consta na tabela. Portanto consideramos como other.

Roberta, também não encontrei em nenhum lugar o tipo "editorial-material". Você sabe informar porque o XC recomenda esse tipo?

[20141003NovosCriterios_SciELO_Brasil.pdf](https://github.com/scieloorg/PC-Programs/files/282513/20141003NovosCriterios_SciELO_Brasil.pdf)

**Comment by alexxpsilva** [comment]
@robertatakenaka e @leticiaquino este caso aconteceu novamente.
Estou mantendo como "other" até decidirmos o que faremos.

@robertatakenaka isso não é caso de ser discutido no SPS ou eu passo para as bibliotecárias?

**Comment by leticiaquino** [comment]
@alexxpsilva acredito que é melhor discutir esse caso com as bibliotecárias @javani, você acompanhou este ticket?

Não podemos continuar recebendo um documento que, de acordo com os Critérios SciELO, não são permitidos.
O prestador que está nos enviando o documento insere o tipo "other" para que seja publicado.

**Comment by javani** [comment]
@alexxpsilva @leticiaquino @robertatakenaka pelo que eu me lembre ficou decidido que não analisaríamos os tipos de documentos para barrar ou não sua subida (mesmo caso dos editoriais sem cunho científico). Não podemos é deixar que tipos que são utilizados para os indicadores bibliométricos subam errado, como artigos originais, estudos de caso e de revisão, por exemplo, bem como erratas e retratações. Essa avaliação deve ser feita pelo pessoal de indexação quando houver avaliação de permanência na coleção. Se subir como other, o tipo não será usado para métricas, será ignorado.

**Comment by robertatakenaka** [comment]
@alexxpsilva @leticiaquino @javani :
temos a seguinte tabela de equivalência de tipos de documentos:
https://docs.google.com/spreadsheets/d/11QUiwFxbprdwO542pyfI0KN3AbhsStNUvmdriPhZNs4/edit#gid=1607337150

Em teoria, seria necessário identificar como editorial-material a fim de ser registrado no WoS como Editorial Material e no PMC como editorial. Estando originalmente como other não seria possível definir este tipo para WoS nem para PMC. Na prática, não sei como está sendo registrado no WoS. Ou seja, para efeitos internos, não há nenhum, mas haveria impacto em outras bases que usam estes tipos de documentos com esta classificação.

**Comment by leticiaquino** [comment]
@javani então se recebessemos um obituário com o @article-type="other", aceitariamos?

**Comment by javani** [comment]
@leticiaquino podemos até passar para a área de indexação, mas não seremos nós que decidiremos se será publicado ou não.

**Comment by leticiaquino** [comment]
@javani aah ok.
Entendi. =)
