### ISSUE TITLE
[XPM] [XC] Acusar error para doi marcado com <ext-link>

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#2256]
Indicar erro para marcação no XML de referencias bibliográficas conforme imagem abaixo 

![exit-link-doi](https://cloud.githubusercontent.com/assets/6921625/15551489/9e1ab154-228c-11e6-972c-2d5cdf025552.png)

**Comment by robertatakenaka** [comment]
fechado por engano

**Comment by robertatakenaka** [comment]
@suelylc , @RPostalli: o correto seria:
```
    <pub-id pub-id-type="doi">numero do doi</pub-id>
```
é isso?

**Comment by suelylc** [comment]
Sim Roberta, 
Ocorrência de DOI sem a url é assim no XML

**Comment by leticiaquino** [comment]
@robertatakenaka Ticket ainda não resolvido.
Eu inseri o seguinte número de DOI em uma das referências do meu artigo-teste:
DOI: 10.1590/1234-5678-20160002458

Identifiquei com o botão [url] e gerei o arquivo XML.
O programa não apresentou erro e converteu o botão para ```<ext-link ext-link-type="uri" xlink:href="10.1590/1234-5678-20160002458">10.1590/1234-5678-20160002458<ext-link>```.

**Comment by robertatakenaka** [comment]
@suelylc : avaliamos esta possibilidade na reunião de SPS e concluimos que se o doi vem em formato de link no artigo, deve ser marcado como ext-link, se o doi vem marcado sem link, deve ser marcado como pub-id (doi). Desde que identificado não tem importância a forma.
