### ISSUE TITLE
[XC] Evitar que um artigo "novo" use o mesmo pid que um artigo anteriormente registrado

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2260]
Apontar erro quando o elocation estiver duplicado, independente do lote.

**Comment by robertatakenaka** [comment]
Por favor, indique o pacote em que deu o problema.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by jenniferamato** [comment]
Elocations duplicados da rlae v24: 

e2687 (lote 3 e lote 5)
e2688 (lote 4 e lote 5)
e2689 (lote 4 e lote 5)

**Comment by robertatakenaka** [comment]
@javani , @jenniferamato , @RPostalli

Comecei a analisar  e identifiquei o seguinte: os arquivos dos lotes posteriores estão com o mesmo nome dos lotes anteriores. Sendo assim, para o XC foi questão de atualização e não de artigo novo. De qualquer forma  vou investigar mais profundamente de forma a evitar que aconteça novamente.

Não existe no nome do arquivo a indicação do número de lote, por exemplo.

![captura de tela 2016-06-01 as 11 26 43](https://cloud.githubusercontent.com/assets/505143/15713217/db3478a4-27eb-11e6-8790-5da263a2103b.png)

**Comment by robertatakenaka** [comment]
@javani , @jenniferamato , @RPostalli

Enquanto isso, reprocesse o lote 3 e 4, sem mudar nada.

Do lote 05, corrija o nome dos arquivos e o elocation-id. Suba novamente. Ficará corrigido.

No entanto, como disse anteriormente, tentarei verificar como evitar que este problema ocorra de novo futuramente.

**Comment by RPostalli** [comment]
Roberta não vai dar pra corrigir isso agora, porque quem defini elocation é
o editor, só ele poderá mudar isso e consequentemente muda a nomeação dos
arquivos.



Atenciosamente,

Renata Postalli
Bibliotecária Júnior

[*Atenção*: A versão nova do XML Package Maker (XPM) foi lançada em 12/04.
Por gentileza, passem a utilizar a versão atual. Versões anteriores serão
aceitas somente até 12/05]
---------------
[*Atenção*: A versão 1.2 do SPS, foi descontinuada em 5 de abril. Por
gentileza, passem a utilizar a versão 1.3 ou 1.4 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

Em 1 de junho de 2016 11:39, Roberta Takenaka <notifications@github.com>
escreveu:

**Comment by robertatakenaka** [comment]
@jenniferamato , @RPostalli, @javani
Sugiro pelo menos subir o lote 3 e 4 novamente para ficar correto, e aguardar a correção do lote 5. Que acha?

**Comment by javani** [comment]
@jenniferamato @robertatakenaka @RPostalli Concordo. Subimos os outros quando as correções chegarem

**Comment by RPostalli** [comment]
Ah sim, certo combinado. Vou pedir pra Jennifer subir então os lotes dos
primeiros arquivos para deixarmos tudo correto.

Atenciosamente,

Renata Postalli
Bibliotecária Júnior

[*Atenção*: A versão nova do XML Package Maker (XPM) foi lançada em 12/04.
Por gentileza, passem a utilizar a versão atual. Versões anteriores serão
aceitas somente até 12/05]
---------------
[*Atenção*: A versão 1.2 do SPS, foi descontinuada em 5 de abril. Por
gentileza, passem a utilizar a versão 1.3 ou 1.4 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

2016-06-01 12:56 GMT-03:00 javani <notifications@github.com>:

**Comment by robertatakenaka** [comment]
Resolver também a troca de order.
