### ISSUE TITLE
Erros nos arquivos utilizados pelo download_markup_journals.py

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/PC-Programs#2277]
1º observei que a [planilha de metadados disponível na SPS](http://static.scielo.org/sps/titles-tab-utf-8.csv) possui periódicos com dados a mais ou em colunas a mais.
![image](https://cloud.githubusercontent.com/assets/129185/16042118/8b1a2eda-320f-11e6-95d6-c4e1ae2e901c.png)

Resolvi olhar nos arquivos utilizados para atualizar o Markup e observei que neles também vários periódicos [nos arquivos .csv](https://github.com/scieloorg/PC-Programs/blob/master/src/scielo/bin/xml/download_markup_journals.py#L190) possuem mais colunas do que o esperado.
![image](https://cloud.githubusercontent.com/assets/129185/16042178/de04b3f4-320f-11e6-9033-a231331c35c3.png)

**Comment by robertatakenaka** [comment]
Não é um erro. São planilhas com formato diferentes. No entanto, o segundo
arquivo que você mencionou é gerado a partir do
http://static.scielo.org/sps/titles-tab-v2-utf-8.csv, que é a versão 2
(explico abaixo), do primeiro arquivo mencionado.

O Markup não lê utf-8. Os dados tem que ser convertidos para uma
codificação que o Markup possa ler (este arquivo corresponde ao segundo
arquivo que você mencionou). Além disso, há vários usuários de markup. Por
exemplo, não faz sentido o pessoal do Chile ter acesso a dados de Brasil.
Principalmente porque o markup ficaria lento para carregar os dados de
todas os periódicos. Outro motivo é que nem todos os dados o Markup
precisa. O download de journals para markup faz o download e gera o arquivo
com os dados selecionados e codificação adequada.

O primeiro arquivo mencionado que corresponde a
http://static.scielo.org/sps/titles-tab-utf-8.csv.
No entanto, como houve uma demanda do Markup  de conhecer mais dados (no
caso foi somente licença), solicitei a inclusão de mais essa coluna, e para
não desse problema aos usuários de titles-tab-utf-8.csv, fizemos uma versão
2: http://static.scielo.org/sps/titles-tab-v2-utf-8.csv.

Falhei ao não divulgar explicitamente
http://static.scielo.org/sps/titles-tab-v2-utf-8.csv. Apesar de que acho
que vocês tem de onde consultar a licença. Correto?

No entanto, no relatório do XPM, é indicado que é consultado
http://static.scielo.org/sps/titles-tab-v2-utf-8.csv.


Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2016-06-14 9:11 GMT-03:00 Luciano <notifications@github.com>:

**Comment by lpanebr** [comment]
Obrigado pelo retorno @robertatakenaka 

Me desculpe por não ter explicado direito. O erro  que me refiro não é de codificação. É algo que deve ter relação com a entrada dos dados e que resulta em **informações exibidas em colunas erradas**. VEja a imagem abaixo do arquivo [http://static.scielo.org/sps/titles-tab-utf-8.csv.](http://static.scielo.org/sps/titles-tab-utf-8.csv.):

![image](https://cloud.githubusercontent.com/assets/129185/16043718/80b59db4-3217-11e6-8cf4-e95c8834827b.png)

Esse mesmo problema ocorre em todas as versões dos arquivos.

Para nós não é um grande problema mas resolvi informar mesmo assim.

**Comment by robertatakenaka** [comment]
Obrigada, Luciano. Entendido.

**Comment by robertatakenaka** [comment]
Luciano,

Eu não localizei o arquivo. Onde fica este arquivo? Pode me enviar o
arquivo por email? Por favor, verifique se é um arquivo recente. Talvez
seja antigo.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2016-06-14 10:07 GMT-03:00 Luciano <notifications@github.com>:

**Comment by lpanebr** [comment]
@robertatakenaka 

Encontrei os arquivos abaixo com esse problema:
 - http://static.scielo.org/sps/markup_journals.csv
 - http://static.scielo.org/sps/titles-tab-v2-utf-8.csv
 - http://static.scielo.org/sps/titles-tab-utf-8.csv (este é o que [possui link na SPS](http://static.scielo.org/sps/titles-tab-utf-8.csv))

**Comment by robertatakenaka** [comment]
Qual é o que está errado? Todos?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by lpanebr** [comment]
Sim, esses 3 possuem o problema de informação em coluna errada..

**Comment by robertatakenaka** [comment]
Luciano, para mim aparece corretamente. O arquivo CSV está usando TAB como separador.

![captura de tela 2016-06-15 as 11 39 02](https://cloud.githubusercontent.com/assets/505143/16084097/cf1f055e-32ed-11e6-807a-2ce4a18f3a62.png)
