### ISSUE TITLE
[pubmed] Implementação de tag para identificação de Clinical Trial

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2279]
Pubmed passa a identificar e indexar dados de Clinical Trial conforme estrutura abaixo.
```
<ObjectList>
<Object Type="ClinicalTrials.gov">
<Param Name="id">NCT00000125</Param>
</Object>
</ObjectList>
```
----
PubMed data providers may now include ClinicalTrials.gov identifiers in their XML citation data submitted to PubMed.

Sample XML:
```
<ObjectList>
<Object Type="ClinicalTrials.gov">
<Param Name="id">NCT00000125</Param>
</Object>
</ObjectList>
```

Supplying these identifiers will create a link from the PubMed citation to the study on the ClinicalTrials.gov website.

As a reminder, data providers may submit the Publication Type values "Clinical Trial" and "Observational Study." Please keep in mind the following definitions:

CLINICAL TRIAL:
A work that reports on the results of a clinical study in which participants are assigned to receive one or more interventions so that researchers can evaluate the interventions on biomedical or health-related outcomes. The assignments are determined by the study protocol. Participants may receive diagnostic, therapeutic, or other types of interventions. While most clinical trials concern humans, this publication type may be used for clinical veterinary articles meeting the requisites for humans.

OBSERVATIONAL STUDY:
A work that reports on the results of a clinical study in which participants may receive diagnostic, therapeutic, or other types of interventions, but the investigator does not assign participants to specific interventions (as in an interventional study).

**Comment by robertatakenaka** [comment]
@javani: por favor, indique a documentação do PubMed referente  a este elemento.

**Comment by javani** [comment]
@robertatakenaka 
A instrução foi enviada por email, mas existe este link sobre objectList
http://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.ObjectList_O
