### ISSUE TITLE
[xpm][pubmed] Problema com abstract reportado pelo PubMed

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#2289]
Corrigir a forma como esta gerando abstract nos arquivos SciELO de envio ao Pubmed. 
Retirar o  - (hífen).

Email Pubmed:

In addition, please do not include hyphens in the structured abstract labels, e.g., <AbstractText Label="Background -">. These labels are formatted in PubMed uniformly as “BACKGROUND:”, so the hyphens make for an odd display:
http://www.ncbi.nlm.nih.gov/pubmed/27305418

Arq Gastroenterol. 2016 Apr-Jun;53(2):108-12. doi: 10.1590/S0004-28032016000200011.
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0004-28032016000200108&lng=en&nrm=iso&tlng=en

``` xml
<abstract>
                                <title>ABSTRACT</title>
                                <sec>
                                        <title> Background - </title>
                                        <p><italic>Helicobacter pylori</italic> infection is the gram negative bacillus with the close association with chronic antral gastritis. </p>
                                </sec>
                                <sec>
                                        <title> Objective - </title>
                                        <p>In this study, we evaluate the accuracy of urea breath test (UBT) with carbon isotope 13 in comparison with histopathology of gastric antrum for detection of <italic>H. pylori</italic> infection in children with dyspepsia. </p>
                                </sec>
                                <sec>
                                        <title> Methods - </title>
...
```

**Comment by robertatakenaka** [comment]
Deve estar assim no dado.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by robertatakenaka** [comment]
@RPostalli : houve correção nos dados?

**Comment by RPostalli** [comment]
Não houve e não haverá, não é um dado errado é apenas a diagramação. É possível ao gerar os arquivos PubMed que seja extraído o hífen (caso exista) automaticamente do abstract?

**Comment by RPostalli** [comment]
@robertatakenaka novamente estamos dentro problema com a diagramação de abstract em PubMed.

Email da ress.
---------------------------------
Estimada Renata,

Agradeço novamente sua atenção e o envio destas excelentes notícias.
Observamos a duplicidade dos "dois pontos" após os itens de estrutura do resumo, por exemplo:

Abstract
OBJECTIVE::
to describe the occurrence of the recording of mental disorders (MD) in primary health care (PHC) services in Brazilian municipalities and to analyze associated factors.
https://www.ncbi.nlm.nih.gov/pubmed/27869957
Esta duplicidade aparece em todos os abstracts que verificamos, e parece ser uma questão de formatação.
É possível retificar?
Att,
---------------------------------

Nosso XML agora esta gerando o dado dentro da tag, dentro do atributo.***"OBJECTIVE:">

```<Abstract>
			<AbstractText Label="OBJECTIVE:">to analyze the circulation of respiratory viruses in
            people living in the metropolitan area of Belo Horizonte, Brazil, and hospitalized in
            Belo Horizonte from 2011 to 2013.</AbstractText>```
