### ISSUE TITLE
[pubmed] Problema ao gerar arquivo na pasta errata.

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#2299]
Arquivo PubMed deve gerar pasta base e pasta pubmed dentro de pastas de errata no serial (V:) com padrão exemplo: 2016nahead-erratas.

Foram realizadas 3 tentativas de gerar este arquivo V:\SciELO\serial\hcsm\2016nahead-erratas no gera padrão e gerou apenas um arquivo  vazio na pasta principal da revista no serial (hcsm).
![1](https://cloud.githubusercontent.com/assets/6084959/16465088/6f779acc-3e13-11e6-8c01-9c046cc309a6.jpg)

O correto seria gerar a pasta base e pubmed dentro da pasta da errata, assim como é feito em Ahead.
Exemplo da pasta principal de ahead do serial = 2016nahead
Dentro da pasta de ahead
![2](https://cloud.githubusercontent.com/assets/6084959/16465238/13b1f5a6-3e14-11e6-8153-fef2d337ca2a.jpg)

Para conseguir gerar o arquivo tive que jogar a pasta da errata dentro da pasta de ahead conforme visto na imagem acima..

O correto seria gerar dentro desta pasta.
![3](https://cloud.githubusercontent.com/assets/6084959/16465313/708870f2-3e14-11e6-8fd1-a03a4159d077.jpg)

**Comment by robertatakenaka** [comment]
Existe um padrão para as pastas que deve ser esperado.
v30n1
v30s1
v30
n1
v30n1s1
2016nahead
v30n1pr
e assim por diante.

Dentro de cada pasta, também há um padrão de pastas que devem haver para que os arquivos do PubMed sejam gerados:
base (com base)
pastas com XML

Como 2016nahead-erratas não é um nome padrão de pasta de fascículo e não possui uma base 2016nahead-erratas e pastas com XML e também não seria possível tê-lo registrado em Title Manager, este ticket não é válido.

Para conseguir gerar os XML de errata, seria proceder normalmente como se fosse um fascículo qualquer. OU seja, se acrescenta os arquivos das errata na pasta 2016nahead, executa o getBasesXML.
