### ISSUE TITLE
(Markup 4.0.073 - Word 2010) Afiliação não é marcada quando consta em rodapé e a tag [aff] é aplicada antes de [article] até o meio do título

### ISSUE THREAD

**Issue by vivianeneves** [scieloorg/PC-Programs#230]
- artigo 02 - pg-n18 - enviado via e-mail

- veja imagens da marcação
1) Selecionei a afiliação e marquei:
![aff1](https://f.cloud.github.com/assets/6368517/2017381/84e4f954-87f9-11e3-8233-98e7be9993f3.jpg)

2) Ao clicar em ok na caixa de diálogo a tag é aplicada antes de [article] e no meio do título
![aff2](https://f.cloud.github.com/assets/6368517/2017391/b96fabc4-87f9-11e3-8dca-9df834460116.jpg)

3) Afiliação não recebe tags
![aff3](https://f.cloud.github.com/assets/6368517/2017392/c75913b0-87f9-11e3-839a-6fb74297d6d1.jpg)

**Comment by robertatakenaka** [comment]
resolvido usando a nova estrutura de marcação: doc
