### ISSUE TITLE
[xpm][xc] Corrigir a geração e o registro de clinical trial na base SciELO

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2301]
```
<p>Número de registro clínico:<ext-link ext-link-type="ClinicalTrial" xlink:href="https://clinicaltrials.gov/ct2/show/NCT00981734">NCT00981734</ext-link></p>

```
Os programas estão considerando que o valor de ext-link-type é clinical-trial e não ClinicalTrial

Relacionados a #1738

**Comment by leticiaquino** [comment]
@robertatakenaka rever valor de ``@ext-link-type`` para Ensaios Clínicos. Nessa versão 1.5 do SciELO PS passamos a considerar o valor "clinical-trial". Veja:

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/narr/ensaio-clinico.html
