### ISSUE TITLE
[Reports] Os relatórios de erros de conteúdo apresentam erro em ID de autor de [subdoc]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2302]
Verificamos que ao gerar o arquivo XML, o relatório de erros de conteúdo informa o seguinte erro: Faltando xref [@ref-type="aff"]/@rid="aff5".

![aff5](https://cloud.githubusercontent.com/assets/4397365/16490339/9dda1d76-3eaf-11e6-90fd-d0b30372fb92.jpg)

Informo que esse é um arquivo carta e resposta e a afiliação 5, correspondente à resposta do documento, foi identificada corretamente.
Por favor, verificar a possibilidade do programa aceitar autor e afiliação em [subdoc] e não apresentar mais o erro apontado acima.
Aproveito e envio anexo o documento que apresentou o erro.

[csp_0863_15(1).docx](https://github.com/scieloorg/PC-Programs/files/341576/csp_0863_15.1.docx)

**Comment by javani** [comment]
@robertatakenaka continua apresentando erro de ID afiliação na versão 92. Anexo arquivo marcado
[v47n3a09 (2).docx](https://github.com/scieloorg/PC-Programs/files/631916/v47n3a09.2.docx)
