### ISSUE TITLE
[markup 91] Não gerar atributo collection para pub-date

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2311]
Todos os artigos em rolling serão publicados no ano corrente e não serão migrados para um número, ou seja, o atributo faz sentido para os casos onde se publica artigos AOP que serão reunidos em número e periodicidade específica, sendo este dado preenchido internamente.
O markup deverá gerar o XML apenas com a data de publicação online considerando a data preenchida em artdate (rolling)

**Comment by robertatakenaka** [comment]
@javani : a zoologia tem os dois ISSN? Parece que tem. E se você confirma isso, ela é regular ou é rolling pass? Se for rolling pass, está certo ela ter issn impresso?

**Comment by javani** [comment]
@robertatakenaka a ZOOL deixou de publicar impresso esse ano. Atualizei na planilha

**Comment by leticiaquino** [comment]
@robertatakenaka informo que a versão 91 do programa Markup continua gerando a seguinte estrutura de data de publicação para "Publicação Contínua":

```xml
<pub-date pub-type="epub">
     <day>17</day>
     <month>12</month>
     <year>2015</year>
</pub-date>
<pub-date pub-type="collection">
     <day>17</day>
     <month>12</month>
     <year>2015</year>
</pub-date>
```` 

Verificar o arquivo disponível anexo.
[rolling-pass-a01.docx](https://github.com/scieloorg/PC-Programs/files/476880/rolling-pass-a01.docx)
