### ISSUE TITLE
(Markup 40091-20160707 - Word 2013)[Rede SciELO] Programa requer número de DOI para AOP

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2325]
Testei o programa 40091-20160707 em um arquivo AOP da rede SciELO que não apresenta número de DOI e ao gerar o arquivo XML o programa apresenta o seguinte erro:

![erro-gerar-xml-aop](https://cloud.githubusercontent.com/assets/4397365/16816422/31168660-4914-11e6-8493-930d23515ffe.jpg)

Porém, gera o arquivo XML e os relatórios conforme esperamos.
Entretanto, no relatório de erros de conteúdo é apresentado o seguinte error e fatal error:

* order	[ERROR]	00000: Formato inválido de order. Esperado um número de 1 a 99999.
* doi	 [FATAL ERROR]	Requerido

Isso porque esse documento não apresenta número de DOI e, consequentemente, não há número para inserção de order.

Precisamos verificar os seguintes itens:

[1] Como atribuir um order para o documento;
[2] A possibilidade do programa nomear os arquivos com alguma sequencia numérica que não seja o DOI

Disponibilizo o documento testado.
[aop0316.docx](https://github.com/scieloorg/PC-Programs/files/362278/aop0316.docx)

**Comment by robertatakenaka** [comment]
@leticiaquino : 
Por convenção, SciELO adota 
```xml
<article-id pub-id-type="doi">10.1590/0366-69132016623621934</article-id>
<article-id pub-id-type="other">00002</article-id>
```
O XC precisa de um ID, no caso estamos usando o DOI, para identificar o ex-aop.

Atualmente, quando o artigo aop não tem DOI, o Markup gera: 

```xml
<article-id pub-id-type="pii">00002</article-id>
```
Sendo que o valor é o que foi informado no formulário como sendo order.

Ainda vou avaliar o que será necessário ter no XML de um aop sem DOI para que o link entre as versões do fascículo e a versão do aop sejam feitas. Em outras palavras, se o aop entrar no fascículo, seja possível identificá-lo no sistema a sua versão aop e excluí-la.

**Comment by leticiaquino** [comment]
@robertatakenaka sugiro que em vez de usar o "pii" utilize o "publisher-id". 
No SciELO PS não prevemos nenhum valor "pii": 

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-article-id.html

Outra coisa q eu estava verificando, é que o PII significa: "Publisher Item Identifier".
Que identificador do publisher seria?

**Comment by javani** [comment]
@leticiaquino já existe ticket para isso #2356

**Comment by leticiaquino** [comment]
@robertatakenaka relacionado ao ticket # #2356

**Comment by leticiaquino** [comment]
@robertatakenaka Programa não solicita mais número de DOI para AOP. O programa Markup gera o arquivo corretamente e o XPM valida conforme esperado.

**Comment by leticiaquino** [comment]
@robertatakenaka  Relatório de erros de conteúdo apresentou erro em [order].
Foi utilizado como teste um arquivo de publicação contínua que não apresenta número de DOI

No arquivo há a informação de elocation-id e no campo de order foi inserido a ordem: 00302.
Veja a mensagem do relatório de erros de conteúdo:

![error-report-datajpg](https://cloud.githubusercontent.com/assets/4397365/19520690/d86f7cf0-95ef-11e6-89e2-9bac10e3b6d0.jpg)
[aop0316.docx](https://github.com/scieloorg/PC-Programs/files/539139/aop0316.docx)
