### ISSUE TITLE
(Markup 40091-20160707 - Word 2013)[Rede SciELO] Programa apresenta erro em ID de afiliação quando existe um [subdoc]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2326]
O programa Markup apresenta o seguinte erro:

![erro-aff-subdoc](https://cloud.githubusercontent.com/assets/4397365/16816815/33b4b9a8-4916-11e6-8f85-110ab4d3c04c.jpg)

A afiliação 2 pertence ao [subdoc] e tanto a afiliação do artigo principal quanto a do subdoc, foram marcadas corretamente.

O programa confunde a marcação de autores e afiliações do artigo principal com a do subartigo.

Disponibilizo o documento para melhor visualização.
[resposta-art16.docx](https://github.com/scieloorg/PC-Programs/files/362289/resposta-art16.docx)

**Comment by robertatakenaka** [comment]
duplicated #2302
