### ISSUE TITLE
[XC] [XPM] Nomeação de arquivos com ponto e underline

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/PC-Programs#2333]
Indicar erro se arquivos dentro do pacote estiverem nomeados com ponto e/ou underline.

Exemplo:
1982-4327-paideia-***10.15***901982-43272665201601

0074-0276-mioc-0074-02760160088***_sd***

**Comment by leticiaquino** [comment]
@robertatakenaka ticket não resolvido.
Validei um pacote com um arquivo que apresenta a seguinte nomeação: 1678-4170-abc-10_01.00010.xml

Com ponto e uderline e o programa validou corretamente o pacote sem apresentar qualquer erro.

**Comment by leticiaquino** [comment]
@robertatakenaka resolvido.
O programa apresenta erro ao validar arquivos underline, ponto etc no nome do arquivo:

![errorr-name](https://cloud.githubusercontent.com/assets/4397365/19520927/a3e946b8-95f0-11e6-8b2b-cb6de3d404dc.jpg)
