### ISSUE TITLE
[markup 91] Inclui atributo @content-type="cited" em <comment>

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2345]
Ao marcar em referências bibliográficas data de acesso à página, o programa inclui no XML em ```<comment>``` o atributo @content-type="cited". A tag comment não tem atributo documentado, dessa forma não deve-se incluir atributo a esse elemento.
Arquivo marcado anexo.

Ref. 28

```
	<date-in-citation content-type="access-date" iso-8601-date="2015-10-24">2015 Oct
						24</date-in-citation>
					<comment content-type="cited">Available from:<ext-link ext-link-type="uri"
							xlink:href="http://gtfccc.harvard.edu/fs/docs/icb.topic1063570.files/ccd_report_111027.pdf"
							>http://gtfccc.harvard.edu/fs/docs/icb.topic1063570.files/ccd_report_111027.pdf</ext-link>
					</comment>
```
[187-4150-1-PB.docx](https://github.com/scieloorg/PC-Programs/files/422460/187-4150-1-PB.docx)

**Comment by alexxpsilva** [comment]
@javani, a informação "Disponível em" e "Available From" está duplicando em ```<mixed-citation>```

**Comment by javani** [comment]
@alexxpsilva não havia reparado nisso, agradeço.
