### ISSUE TITLE
[xpm] Verificar DOI, considerando que não é "case sensitive"

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2346]

**Comment by leticiaquino** [comment]
@robertatakenaka Ticket resolvido.

**Comment by leticiaquino** [comment]
@robertatakenaka Ticket Resolvido. Inseri algumas letras e caixa alta no número de DOI e o programa gerou o arquivo XML corretamente, sem apresentar erro em DOI.
