### ISSUE TITLE
[markup 91] Não gera XML quando há ID só com letras

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2350]
Não gera XML quando incluído ID só com letras. Arquivo para teste enviado por email (ID de tabela em app-group).

**Comment by leticiaquino** [comment]
@javani você pode especificar por favor?

**Comment by javani** [comment]
@leticiaquino como o ID pode ser qualquer um, há a possibilidade de só ter letras, já testei e está funcionando

**Comment by leticiaquino** [comment]
@javani entendi. Pedi para especificar para ficar mais claro ao fazer teste.
Obrigada
