### ISSUE TITLE
[markup 91] Não reconhece preenchimento de ordem

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2352]
Para arquivos com elocation-id, ainda que preenchido o campo de ordem no formulário de metadados , não reconhece seu preenchimento e gera nome de arquivo com a extensão do elocation-id.
Relatório enviado por email.
[RS90C_ALP.docx](https://github.com/scieloorg/PC-Programs/files/443071/RS90C_ALP.docx)

**Comment by robertatakenaka** [comment]
@javani : acho que será adotado o elocation-id como parte do nome do arquivo. (#2351), no entanto, não consigo confirmar pois o link parece que não está funcionando ainda.

**Comment by leticiaquino** [comment]
@robertatakenaka isso mesmo.
Segue o link: docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/narr/regra-nomeacao.html

**Comment by leticiaquino** [comment]
@robertatakenaka ver comentário: https://github.com/scieloorg/PC-Programs/issues/2325#issuecomment-254813604
