### ISSUE TITLE
[xpm] Ajuste de mensagem de erro para marcação de afiliação em subdoc diferente de tradução

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2353]
Programa não prevê marcação completa de afiliação em subdoc. Para marcação neste nível, temos a tag afftrans com apenas um elemento (label).
Ocorre que há casos em que o tipo de sub-article é diferente de translation e, nestes casos existe a possibilidade de afiliação e autoria diferentes (caso de reply). Quando se marca a afiliação completa utilizando a tag aff, com suas respectivas xrefs, o programa não reconhece a referência cruzada, apresentando erro.
![image](https://cloud.githubusercontent.com/assets/912953/18062539/a7c4c534-6dfd-11e6-8e95-343cf8e85750.png)

[csp_1115_16.docx](https://github.com/scieloorg/PC-Programs/files/443187/csp_1115_16.docx)

**Comment by leticiaquino** [comment]
@robertatakenaka Com o botão [normaff] inserido em [subdoc] o problema foi resolvido.

**Comment by leticiaquino** [comment]
@robertatakenaka ticket resolvido.
