### ISSUE TITLE
[markup 91] Ajustar tag de article-id para o tipo publisher-id ao invés de pii

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2356]
Para artigos sem DOI, o markup gera uma tag para identificação do artigo com o tipo pii. Alterar para publusher-id.
```
<article-meta>
			<article-id pub-id-type="pii">00007</article-id>
			<article-categories>
				<subj-group subj-group-type="heading">
					<subject>Original Research</subject>
				</subj-group>
			</article-categories>
```
E deveria ser:
```
<article-meta>
			<article-id pub-id-type="publisher-id">00007</article-id>
			<article-categories>
				<subj-group subj-group-type="heading">
					<subject>Original Research</subject>
				</subj-group>
			</article-categories>
```
Anexo arquivo marcado.
[rolling-pass-a01.docx](https://github.com/scieloorg/PC-Programs/files/480628/rolling-pass-a01.docx)

**Comment by robertatakenaka** [comment]
@javani : para JATS pelo menos 1 article-id é obrigatório. No caso do SciELO Site atual é necessário article-id (other) para gerar o order quando a paginação não é numérica ou não é única.
No caso de rolling pass, fica obrigatório o uso de article-id (other) pois a fpage não é numérica.
Ficando desnecessário marcar article-id (publisher-id)

Mesmo assim, o ticket será feito porque o correto é publisher-id no lugar de pii.
