### ISSUE TITLE
[mkp] Alteração na identificação de notas de rodapé

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2368]
1. Trocar o nome [fngrp] para [fn]
2. Incluir o [fn] e [sectitle] em [fngrp](novo)
3. Modificar a marcação automática destes elementos
---

(leticia disse:)
No Markup, para identificar notas de rodapé, utilizamos o elemento:
[fngrp] o qual apresenta, em um nível abaixo, um elemento [label] para identificação de rótulo de nota. 

[fngrp id="fn1"][label]Note 1[/label] This study was carried out at Hospital do Coração Anis Rassi, Goiânia, GO, Brazil.[/fngrp]

Ao gerar o arquivo XML, o dado é estruturado da seguinte forma:

<fn-group>
    <fn id=”fn1”>
        <label>Note 1</label>
        <p>This study was carried out at Hospital do Coração Anis Rassi, Goiânia, GO, Brazil.</p>
    </fn>
</fn-group>

Note que é inserido automaticamente o <fn-group>.

A questão é que agora o SciELO PS permite que o elemento <fn-group> apresente um elemento <title>. Veja:

<fn-group>
        <title>Notas</title>
        <fn fn-type="supported-by" id="fn01">
        ...
        </fn>
</fn-group>

Perceba que com essa funcionalidade do programa Markup, de inserir automaticamente o <fn-group>, não há a possibilidade do usuário inserir um título para o grupo de notas. Conforme o exemplo acima do SciELO PS.
end
Obs.: o <label> aparece 0 ou 1 vez em <fn>;
já o <title> aparece 0 ou 1 vez em <fn-group>.

Verificar a possibilidade de incluir no Markup um botão em um nível abaixo de [fngrp] para identificação de títulos, conforme o exemplo acima.

(Observação: em <fn-group> pode ser inserido um <title> e em <fn> pode ser inserido um <label>.)

**Comment by javani** [comment]
@robertatakenaka 

O XML não está gerando corretamente com a marcação nova de fn.
A marcação foi feita das seguintes formas:

[fngrp id="fn1" fntype="other"][sectitle]Notes:[/sectitle][fn][label]Cita sugerida:[/label]Ruiz-Romero V, Lorusso N, Expósito García S, Páez-Pinto JM, Palmero-Palmero C, Caballero-Delgado G, Zapico Moreno MJ, Fernández-Moyano A. Hospitalizaciones evitables por insuficiencia cardíaca. Variables relacionadas. Rev Esp Salud Pública. 2016; Vol. 90: 25 de abril: e1-e11[/fn].[/fngrp]

Resultado no XML:
```
<fn-group>
<fn fn-type="other" id="fn1">
<label>1</label>
<p>
<title>Notes:</title>
<fn>Ruiz-Romero V, Lorusso N, Expósito García S, Páez-Pinto JM, Palmero-Palmero C, Caballero-Delgado G, Zapico Moreno MJ, Fernández-Moyano A. Hospitalizaciones evitables por insuficiencia cardíaca. Variables relacionadas. Rev Esp Salud Pública. 2016; Vol. 90: 25 de abril: e1-e11</fn>.</p>
</fn>
</fn-group>
```
Resultado esperado:
```
<fn-group>
<title>Notes:</title>
<fn fn-type="other" id="fn1">
<label>Cita sugerida:</label>
<p>Ruiz-Romero V, Lorusso N, Expósito García S, Páez-Pinto JM, Palmero-Palmero C, Caballero-Delgado G, Zapico Moreno MJ, Fernández-Moyano A. Hospitalizaciones evitables por insuficiencia cardíaca. Variables relacionadas. Rev Esp Salud Pública. 2016; Vol. 90: 25 de abril: e1-e11.</p>
</fn>
</fn-group>
```
Para a marcação:
[fngrp id="fn1" fntype="other"][fn][label]Cita sugerida:[/label]Ruiz-Romero V, Lorusso N, Expósito García S, Páez-Pinto JM, Palmero-Palmero C, Caballero-Delgado G, Zapico Moreno MJ, Fernández-Moyano A. Hospitalizaciones evitables por insuficiencia cardíaca. Variables relacionadas. Rev Esp Salud Pública. 2016; Vol. 90: 25 de abril: e1-e11[/fn].[/fngrp]

Resultado no XML:

```
<fn-group>
<fn fn-type="other" id="fn1">
<label>1</label>
<p>
<fn>Ruiz-Romero V, Lorusso N, Expósito García S, Páez-Pinto JM, Palmero-Palmero C, Caballero-Delgado G, Zapico Moreno MJ, Fernández-Moyano A. Hospitalizaciones evitables por insuficiencia cardíaca. Variables relacionadas. Rev Esp Salud Pública. 2016; Vol. 90: 25 de abril: e1-e11</fn>.</p>
</fn>
</fn-group>
```
Resultado esperado:

```
<fn-group>
<fn fn-type="other" id="fn1">
<label>Cita sugerida:</label>
<p>Ruiz-Romero V, Lorusso N, Expósito García S, Páez-Pinto JM, Palmero-Palmero C, Caballero-Delgado G, Zapico Moreno MJ, Fernández-Moyano A. Hospitalizaciones evitables por insuficiencia cardíaca. Variables relacionadas. Rev Esp Salud Pública. 2016; Vol. 90: 25 de abril: e1-e11.</p>
</fn>
</fn-group>
```

**Comment by leticiaquino** [comment]
@robertatakenaka ao selecionar o elemento [fngrp], o programa Markup abre a seguinte tela:

![fn-group](https://cloud.githubusercontent.com/assets/4397365/19046908/eeb292c6-8975-11e6-9184-47ac8b1e0199.jpg)


Informo que ```<fn-group>``` não deve apresentar tipo de nota. O atributo de tipo deve estar inserido apenas em ```<fn>```.

Outra coisa, note que além do campo "fntype", há também o campo de "label", o qual também não tem funcionalidade alguma para nós.
O campo "id" também não se faz necessário em ```<fn-group>```.

O elemento [fn] que está um nível abaixo de [fngrp] deve apresentar campos para definição de valores dos atributos de tipo e de id.
ou seja, os campos "fntype" e "id" que constam em [fngrp] devem aparecer em [fn].
Atualmente ao marcar uma nota de rodapé, o programa Markup identifica da seguinte forma:

![fn-de-fn-group](https://cloud.githubusercontent.com/assets/4397365/19046991/5cc51e78-8976-11e6-9ca1-3c048a5db06b.jpg)

Sem informação alguma de id ou de tipo de fn.

``Na última imagem foi retirado manualmente os atributos de [fngrp] para melhor verificação da falta dos atributos mencionado acima de [fn].``

**Comment by leticiaquino** [comment]
@robertatakenaka a marcação deve ser:

![mkp-fn](https://cloud.githubusercontent.com/assets/4397365/19047579/dbc2fcac-8978-11e6-9d65-f57b53cddca3.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino : verifique se está com a sua versão atualizada para os testes.

**Comment by leticiaquino** [comment]
@robertatakenaka sim. Estou com a versão atualizada do Markup.

**Comment by leticiaquino** [comment]
@robertatakenaka atualizei com a versão que você acabou de disponibilizar, mas eu notei que a tag [*fngrp] (com asterisco) não faz a marcação automática de grupo de nota: fn-group/fn/label/p.
Além disso, ao utilizar essa tag, o programa não disponibiliza outro nível de marcação.

Video enviado por email.

**Comment by javani** [comment]
@robertatakenaka continua sem fazer a marcação automática com a tag *fngrp.

**Comment by leticiaquino** [comment]
@robertatakenaka Ainda não foi corrigido. 
Foi enviado hoje, 14/10, um e-mail com vídeos explicativos informando o que ocorre com os botões de automatização ``[*fn]`` e ``[*fngrp]``.

**Comment by leticiaquino** [comment]
O programa Markup está considerando ```<fn-group>``` em ```<author-notes>```. Informo que o elemento ```<fn-group>```deve ser inserido apenas em ```<back>```. Já em ```<author-notes>``` deve ser inserido apenas o ```<fn>```. 

Na marcação do programa Markup foi identificado a nota de conflito de interesses com o elemento [fn] e ainda sim no XML foi identificado o elemento de nota de rodapé em ```<author-notes>``` como ```<fn-group>```.

Envio via e-mail o arquivo XML do teste realizado.

**Comment by leticiaquino** [comment]
Com a versão atualizada do programa Markup, informo que ao utilizar os botões [*fn] e [fn] o programa gera o XML com a seguinte estrutura:

![fn-com-fn-group-errado](https://cloud.githubusercontent.com/assets/4397365/20102281/bcb384b2-a5ac-11e6-836b-53e5acb2e471.jpg)

Informo que em ```<author-notes>``` não deve ser inserido o elemento ```<fn-group>```. Esse elemento deve ser utilizado apenas em ```<back>```.

Veja como é a estrutura esperada:

![fn-estrutura-esperada](https://cloud.githubusercontent.com/assets/4397365/20102454/507e9d94-a5ad-11e6-9519-e480840ebb1e.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino : enviar arquivo .doc

**Comment by leticiaquino** [comment]
Outra observação:
O botão [*fngrp] não está funcionando como se espera. Ao utilizar o botão [*fngrp] o programa identifica automaticamente apenas a tag [fngrp] e [sectitle]. Nessa marcação automática o programa não abre nenhuma janela para inserir o tipo de nota e o ID. Veja como fica a marcação automática de [*fngrp]

![2fngrp-automatico](https://cloud.githubusercontent.com/assets/4397365/20102761/6bd5eb46-a5ae-11e6-90b6-fdbff8e61817.jpg)

E ao gerar o XML, esse dado é suprimido.

Porém, se utilizar o [fngrp] sem automação, é possível selecionar o tipo de nota e inserir o ID da nota:

![fngrp-semasterisco](https://cloud.githubusercontent.com/assets/4397365/20103017/6a64dbae-a5af-11e6-83de-444c34dc191d.jpg)

E o dado é apresentado no XML.

**Comment by leticiaquino** [comment]
Mais uma informação sobre a marcação de notas de rodapé.
Testei a marcação em um arquivo que apresenta tradução.
Notei que ao identificar as notas de rodapé o programa não exclui automaticamente os parágrafos [p] que envolvem as notas e ao gerar o XML é apresentado erro:

![p-em-fn-group](https://cloud.githubusercontent.com/assets/4397365/20103134/e14a139c-a5af-11e6-8a8e-1b22116fc6bc.jpg)

Obs.: Isso ocorre utilizando os botões automáticos e os manuais.


Envio anexo o arquivo .doc correspondente a este comentário e também aos outros dois comentários anteriores a esse.
[abc-01.docx](https://github.com/scieloorg/PC-Programs/files/578407/abc-01.docx)

**Comment by leticiaquino** [comment]
Relacionado ao #2414
