### ISSUE TITLE
[mkp] incluir em product os texto que estão fora de elementos

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2375]
SPS 1.5

**Comment by leticiaquino** [comment]
@robertatakenaka o programa Markup gera o ```<product>``` da seguinte forma:

![product](https://cloud.githubusercontent.com/assets/4397365/19438339/26e27eee-9458-11e6-8382-7e073d87c958.jpg)

Os autores ficarão com indentação?

Obs.: No markup deve ser considerado também o botão de paginação. Atualmente em [product] há apenas o botão [extent].
