### ISSUE TITLE
(Markup 4.0.092 - Word 2013)Sugestão para maior usabilidade do programa

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2378]
Na lista de tipo de referência, ajustar os nomes de acordo com o que irá constar na tag.
Por exemplo, uma referência do tipo "Relatório" está com o seguinte nome da lista de tipos:
**scietific and technical report**

e ao fazer a marcação, o programa identifica como: **report**.

![lista-tipos](https://cloud.githubusercontent.com/assets/4397365/19387633/d6a41a5e-91f1-11e6-8315-b734d80abdf9.jpg)

Ajustando o nome dos valores nas listas para o nome que constará no elemento, o programa terá maior usabilidade.

**Comment by robertatakenaka** [comment]
@leticiaquino : vc quer dizer apresentar na lista o mesmo valor que ficará como atributo de reftype?

**Comment by leticiaquino** [comment]
@robertatakenaka sim.

**Comment by leticiaquino** [comment]
@robertatakenaka Ok. Ticket resolvido.
