### ISSUE TITLE
(Markup 4.0.092 - Word 2013) Erro na identificação de Ensaio Clínico

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2384]
O programa Markup apresenta erro na identificação de ensaio clínico. Veja:

![clinical-trial](https://cloud.githubusercontent.com/assets/4397365/19399779/87706c70-9229-11e6-839f-0bdf48b47a5a.jpg)

Por gentileza, verificar a possibilidade de considerar a marcação de ensaio clínico com ```<ext-link>``` válida.

**Comment by robertatakenaka** [comment]
@leticiaquino : qual é a marcação válida que se deve considerar?

**Comment by leticiaquino** [comment]
@robertatakenaka deve-se considerar com o valor "clinical-trial". Veja meu comentário em: [#2301](https://github.com/scieloorg/PC-Programs/issues/2301#issuecomment-253893633)

Regra SciELO PS: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/narr/ensaio-clinico.html

**Comment by leticiaquino** [comment]
@robertatakenaka Ticket resolvido.
