### ISSUE TITLE
[xpm] Indicar como erro arquivo sem ```history```

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#2392]
Seria melhor indicação de "erro"
![sem titulo](https://cloud.githubusercontent.com/assets/6921625/19804990/7f84258e-9cf0-11e6-9b44-ec0fb8c35cf1.png)

**Comment by robertatakenaka** [comment]
@suelylc : qual é o article-type deste arquivo? Bom sempre indicar o nome do arquivo XML caso seja necessário a verificação de outros dados.

**Comment by suelylc** [comment]
@robertatakenaka é research-article, mas aparece assim para todos os tipos
