### ISSUE TITLE
[xpm] Validar ocorrência de sufixos em ```surname```

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#2393]
Não está indicando ocorrência de sufixos sozinhos em ```surname``` 

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-suffix.html#suffix

Sufixos em ```surname``` são aceitos desde que precedidos de sobrenome e traço, senão devem estar em ```<suffix>```

Ex:
```<surname>```SILVA - NETO```</surname>```

**Comment by robertatakenaka** [comment]
@suelylc : por favor, indicar o nome do XML em que houve esta incidência.

**Comment by suelylc** [comment]
@robertatakenaka arquivos enviados.

**Comment by suelylc** [comment]
Ainda está indicando erro quando há sufixo precedido por sobrenome e traço
![sem titulo](https://cloud.githubusercontent.com/assets/6921625/20007971/cb45882e-a285-11e6-868a-55956ea2bd96.png)

xml: 
![sem titulo1](https://cloud.githubusercontent.com/assets/6921625/20008006/f6979e9a-a285-11e6-9837-24d21458193a.png)


Para estes casos, desconsidere erro.
