### ISSUE TITLE
[pubmed] email de link doi

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#2394]
Dear LinkOut provider,

NCBI completed the implementation of https across the entire domain. We need to inform you that, as a result of this change to https, referrer information may be dropped when links are directed from PubMed to your Web site using http.  This means that it is likely that you may not be able to accurately track usage directed to your site from the NCBI domain.

If your Web site has implemented https, please change the information you provide in your LinkOut files to use https and to update your scripts to use https when generating new LinkOut files.

We will soon update all LinkOut files currently using the <Base>  http://dx.doi.org to https://dx.doi.org.  We will make the change for you either later this week or early next week.  However, please be sure to update your scripts to use https when generating new LinkOut files.

Should you have any questions, please write to linkout@ncbi.nlm.nih.gov

Regards,

LinkOut team
NCBI/US NLM

**Comment by RPostalli** [comment]
Essa tag Base consta nos arquivos journals das revistas. exemplo:

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LinkSet PUBLIC "-//NLM//DTD LinkOut 1.0//EN" "http://www.ncbi.nlm.nih.gov/entrez/linkout/doc/LinkOut.dtd">
<LinkSet>
	<Link>
		<LinkId>3</LinkId>
		<ProviderId>3081</ProviderId>
		<IconUrl>http://www.scielo.org.ar/img/scielo.gif</IconUrl>
		<ObjectSelector>
			<Database>Pubmed</Database>
			<ObjectList>
				<Query>0325-0075 [TA] 2008:2030 [dp]</Query>
			</ObjectList>
		</ObjectSelector>
		<ObjectUrl>
			<Base>http://www.scielo.org.ar</Base>
			<Rule>/scielo.php?script=sci_arttext&amp;pid=&lo.pii;&amp;lng=en&amp;nrm=iso&amp;tlng=en</Rule>
			<Attribute>full-text online</Attribute>
		</ObjectUrl>
	</Link>
</LinkSet>```

**Comment by robertatakenaka** [comment]
@RPostalli : Acho que não impacta neste caso.
