### ISSUE TITLE
[xpm] Não aponta ausência da tag "'article-id pub-id-type="doi" "'

### ISSUE THREAD

**Issue by JoyceRaphaela** [scieloorg/PC-Programs#2399]
Não aponta como erro a ausência da tag article-id pub-id-type="doi"
Y:\users\Joyce\Treinamento\Revistas\abc\0102-8650-acb-31-s1
artigo 0102-8650-acb-31-s1-00001.

**Comment by robertatakenaka** [comment]
@JoyceRaphaela : no momento não há como separa a validação por coleção. Então a validação é genérica. O que é obrigatório é o article-id, que tem que ser do tipo doi ou publisher-id, e realmente faltava essa validação. O article-id é um elemento obrigatório para SPS. No entanto, para o nosso sistema ele é especificamente obrigatório em aop (ahead of print) e em ex-aop, pois é uma forma de encontrar a versão aop e excluí-la quando deixa de ser aop.
