### ISSUE TITLE
[xpm] Não indica o vencimento de sps anterior a 1.4

### ISSUE THREAD

**Issue by JoyceRaphaela** [scieloorg/PC-Programs#2400]
Não indica o vencimento de sps anterior a 1.4

![sps](https://cloud.githubusercontent.com/assets/23195801/19979407/7b23b856-a1e1-11e6-9133-1d91deca1c8e.png)

Na versão anterior alertava sobre a expiração da sps.
![sps13](https://cloud.githubusercontent.com/assets/23195801/19979504/da69b1d0-a1e1-11e6-8d50-4179e91dbae1.png)

**Comment by robertatakenaka** [comment]
@JoyceRaphaela : realmente, somente existe uma mensagem para as duas mais recentes. Vou incluir um alerta para as versões mais antigas.

**Comment by robertatakenaka** [comment]
@JoyceRaphaela : as validações vão considerar a data de publicação do artigo, pois se ele não for atual, for um "reprocessamento" seria aceitável que ele estivesse em uma versão mais antiga de SPS, desde que a data da SPS em questão seja compatível com data de publicação do artigo, ou seja, ambas datas devem ser "contemporâneas".
No entanto, as duas versões mais recentes são válidas para artigos de quaisquer datas.
