### ISSUE TITLE
[xpm] Não aceitar <fpage>e<lpage> + <elocation-id>

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#2404]
Se há 
```<fpage>```
```<lpage>``` 

não deve ter ```<elocation-id>```

e vice-versa

 
![sem titulo3](https://cloud.githubusercontent.com/assets/6921625/20008560/37b40dbc-a288-11e6-8210-e49d5752b854.png)

No xml
![sem titulo4](https://cloud.githubusercontent.com/assets/6921625/20008576/47b84ec6-a288-11e6-9ef5-b160f73dc2bd.png)

**Comment by robertatakenaka** [comment]
Entendo, mas não achei isso no SPS. Seria bom, tem um documento onde esta
regra está formalizada a fim de instruir bem o usuário. Pode verificar isso?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by suelylc** [comment]
Vdd, @robertatakenaka , esqueci de colocar. 

Segue o link: (Ver nota)
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-elocation-id.html#elocation-id

**Comment by robertatakenaka** [comment]
Pior que eu tinha lido, mas revisando... me parece que o texto do
elocation-id está esquisito (abri ticket no sps)

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
