### ISSUE TITLE
[xpm] Indicar ausência de source em referencias "webpage"

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#2407]
A versão xpm 92 não está indicando essa ocorrência.
No xml está:
![sem titulo](https://cloud.githubusercontent.com/assets/6921625/20057672/f5742aba-a4d3-11e6-9fbf-863cffa7c9bf.png)

O correto é 
![sem titulo1](https://cloud.githubusercontent.com/assets/6921625/20057680/01bbaf6e-a4d4-11e6-8603-8e51af2731ff.png)

 

Conf: http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_how_to_generate_xml-markup.html#webpage

**Comment by robertatakenaka** [comment]
@suelylc: estamos validando mais rigorosamente quando é journal, book,
confproc, tesis.

Por outro lado, acho que as duas marcações estariam corretas.

Outro ponto, é que o validador de estrutura deve reclamar da ausência de
source. Pode me confirmar?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by suelylc** [comment]
Então, @robertatakenaka as validações para ```source``` estão OK quanto as que você citou acima. 
Me recordo que o ```source``` era requerido em todas as referências, daí a observação, e realmente agora isso não foi apontado no Style Cheker... 
 @leticiaquino saberia dizer se houve alteração mesmo?

**Comment by robertatakenaka** [comment]
@suelylc: deixamos de validar o source para os demais tipos, pois somente é
importante o source de para os tipos já mencionados.
Sim, o source deveria ser obrigatório em todas as referências, mas resolvi
deixar a validação mais flexível para os demais tipos*.*

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2016-11-07 16:20 GMT-02:00 suelylc <notifications@github.com>:

**Comment by suelylc** [comment]
@robertatakenaka então tá ok.
