### ISSUE TITLE
(Markup 4.0.092 - Word 2013) Programa apresenta erro de estrutura em data <season> de <pub-date>>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2408]
Ao gerar um arquivo XML que apresenta o intervalo de meses: Outubro - Dezembro, o programa Markup apresenta o seguinte erro:

![season](https://cloud.githubusercontent.com/assets/4397365/20070092/517b19ea-a506-11e6-8f33-f80c6d017204.jpg)

Envio anexo o arquivo .doc para analise:
[art01.docx](https://github.com/scieloorg/PC-Programs/files/576260/art01.docx)

Verificar a possibilidade de considerar em ```<season>```também o intervalo de meses no formato: No idioma em inglês, com 3 caracteres, separados por hífen.

Ver exemplo em: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-season.html#elemento-season

**Comment by robertatakenaka** [comment]
O erro está correto.
As abreviaturas são: Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov e Dec, conforme o link que vc mesma indicou.

**Comment by leticiaquino** [comment]
@robertatakenaka desculpa, erro meu!

Eu inseri "Dez" em vez de "Dec".
