### ISSUE TITLE
(Markup 4.0.092 - Word 2013) Retirar asterisco de obrigatoriedade do campo [pagecount] no formulário [doc]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2409]
Como o programa Markup faz a contagem automática da paginação, sugiro que seja retirado o asterisco do campo [pagecount] (do formulário .doc) ou então que este campo deixe de existir.

![formulario-pagecouont](https://cloud.githubusercontent.com/assets/4397365/20070413/5fcdf7a0-a507-11e6-91b7-54cca18c5b1f.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino : não para paginações com letras

**Comment by robertatakenaka** [comment]
já estava resolvido
