### ISSUE TITLE
(Markup 4.0.092 - Word 2013) Eliminar formatação dentro de <label>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2419]
O programa não está eliminando a formatação ```<sup>``` de ```<label>``` e ao gerar o XML é apresentado erro de formatação:

![sup-retirar](https://cloud.githubusercontent.com/assets/4397365/20391722/bc300234-acbb-11e6-88ae-7896d7ea565d.jpg)

**Comment by robertatakenaka** [comment]
@leticiaquino : no caso é só eliminar o sup ou deixar ``<sup><label></label></sup>``?
