### ISSUE TITLE
[XC] Pacote não sobe se a data de pub-date for diferente da data inserida na title

### ISSUE THREAD

**Issue by JoyceRaphaela** [scieloorg/PC-Programs#2423]
O pacote 1678-4596-cr-rpass-03-47-1 está sendo rejeitado porque o ano em pub-date está como 2016 e na title está como 2017:
http://homolog.xml.scielo.br/reports/cr/v47n1/xc.html#view-reports-1678-4596-cr-47-01-20151114.

**Comment by javani** [comment]
Isso mesmo Joyce. Nesse caso o ano de collection deve ser 2017, já que é o
ano onde se terá o conjunto de artigos publicados.



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

2016-11-17 12:36 GMT-02:00 JoyceRaphaela <notifications@github.com>:
