### ISSUE TITLE
[Sugestão | Markup]Automatizar a marcação das notas de rodapé dentro do grupo [*fngrp]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2427]
Sugiro que ao marcar um grupo de notas com o elemento [* fngrp], o programa identifica a primeira nota e abrir uma janela automaticamente para o usuário inserir o ``@id`` e o ``@fn-type``
e depois de inserir isso, o programa já abre automaticamente a janela da proxima nota, para incluir esses dados.

Dessa forma o usuário do programa não precisa voltar a marcação e editar cada nota para inserir o ``@id`` e o ``@fn-type`` e o processo de marcação do grupo de notas é automatizado.

**Comment by robertatakenaka** [comment]
resolvido
