### ISSUE TITLE
(Markup 4.0.092 - Word 2013)Programa identifica autor-data no corpo do texto mesmo quando a info de autor está distante da data

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2446]
Foi verificado que o programa identifica informação de autor-data mesmo quando a info de autor está distante da data. Veja:

![identifica-mais-info-autor-data](https://cloud.githubusercontent.com/assets/4397365/20668132/5bcdbf3e-b554-11e6-8cea-d5201c7e455e.jpg)

Nesse caso há um problema, pois após a informação "...eloquent silence" há uma nota de rodapé.

Solicito a gentileza de considerar a marcação autor-data apenas quando essas duas informações estiverem próximas. Exemplo:

SOUZA, 2014.

Envio anexo o arquivo teste
[05 - 699 - JEAN BAPTISTE PT 32-63.docx](https://github.com/scieloorg/PC-Programs/files/616229/05.-.699.-.JEAN.BAPTISTE.PT.32-63.docx)

**Comment by robertatakenaka** [comment]
resolvido, verificado por @cinthia-vieira
