### ISSUE TITLE
(Markup 4.0.092 - Word 2013)Programa suprime marcação de ano quando o dado faz parte de [thesgrp]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2447]
O programa suprime a marcação de ano quando o dado está identificado em [thesgrp]. Veja:

![data-thesis](https://cloud.githubusercontent.com/assets/4397365/20668692/526edede-b557-11e6-8743-d7137a53d74e.jpg)

Ao gerar o XML o programa apresenta a seguinte marcação:

![thesis-xml](https://cloud.githubusercontent.com/assets/4397365/20668747/8f239f72-b557-11e6-9a1c-2574501d8eba.jpg)

Envio anexo o arquivo de teste
[1835.docx](https://github.com/scieloorg/PC-Programs/files/616275/1835.docx)

**Comment by robertatakenaka** [comment]
@leticiaquino : no caso, dentro de thesgrp e confgrp as data se referem respectivamente a data de apresentação da tese e data em que ocorreu a conferência. A data de publicação fica fora. Isso fica evidente no caso de aparecer as duas datas. No entanto, o que mais acontece é aparece somente a de publicação e as pessoas acabam marcando dentro de thesgrp ou confgrp.
O mesmo quando existe orgname. Dentro de thesgrp e confgrp servem para indicar respectivamente a instituição em que foi apresentada a  tese e que organizou o evento. Fora é a instituição publicadora, que em geral pode ser ou não a mesma e também pode ou não aparecer.

Pode ser adotada a regra de que se há ausência de data de publicação, adotar a data de dentro de thesgrp ou confgrp.
