### ISSUE TITLE
(Markup 4.0.092 - Word 2013)Programa converte símbolo "Much Less-Than" e "Much Greater-Than" em entidade correspondente à "aspas"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#2448]
Informo que o programa Markup 4.0.092 está convertendo os símbolos "Much Less-Than" e "Much Greater-Than" na entidade ``&quot;``, a qual corresponde à aspas duplas.

No Markup:
![simbolooooo](https://cloud.githubusercontent.com/assets/4397365/20753364/2f1039e6-b6ed-11e6-8c8d-388fcd6570e5.jpg)

No XML:
![codigoooo-xml](https://cloud.githubusercontent.com/assets/4397365/20753384/51ddb49e-b6ed-11e6-886c-3e1db2d3607a.jpg)

Por favor, ou considerar o símbolo em texto, como está no documento .doc ou considerar a entidade correspondente ao símbolo:

**Much Less-Than** ≪      `` &#8810;``

**Much Greater-Than** ≫   ``&#8811;`` 

Arquivo enviado anexo.
[resposta-art16.docx](https://github.com/scieloorg/PC-Programs/files/621858/resposta-art16.docx)

**Comment by robertatakenaka** [comment]
@leticiaquino : pode fazer um teste para mim? Se vc salvar em .doc, o que acontece no .doc, ele muda o caracter? Me envie também os arquivos que ficam em work, correspondentes a este arquivo.

**Comment by leticiaquino** [comment]
@robertatakenaka Ok, fiz o teste. Converti o arquivo .docx para .doc e gerei o arquivo XML.
O símbolo não foi alterado e ao gerar o XML notei que o problema persiste:

![menor-maior](https://cloud.githubusercontent.com/assets/4397365/20887086/53b730b4-bae0-11e6-866e-a41759d98a8d.jpg)

Enviei hoje (05/12/2016) a pasta work e o arquivo .doc via e-mail.
