### ISSUE TITLE
[markup 92] Programa não gera tags de funding-group e funding-statement para fn do tipo financial-disclosure

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2473]
Mesmo marcando a nota de rodapé do tipo financial-disclosure e marcado funding o XML é gerado sem estas tags em front.

**Comment by robertatakenaka** [comment]
@javani enviar arquivo marcado

**Comment by javani** [comment]
RObs,

Segue.

Grata,


  <https://mailtrack.io/>Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

2017-01-31 9:39 GMT-02:00 Roberta Takenaka <notifications@github.com>:

**Comment by javani** [comment]
@robertatakenaka continua não gerando. Arquivo anexo.
[11-ARTIGO.docx](https://github.com/scieloorg/PC-Programs/files/858606/11-ARTIGO.docx)

**Comment by javani** [comment]
@robertatakenaka voltou a apresentar o programa de funding em nota. Estou usando a versão do seu users de 17/04.

Marcação:
![image](https://cloud.githubusercontent.com/assets/912953/25748015/f4a97cbe-317f-11e7-8ef1-4f8684ee6f3c.png)

XML:
![image](https://cloud.githubusercontent.com/assets/912953/25748031/084ab27e-3180-11e7-906a-13e4f9857063.png)

Arquivo anexo
[v8n1a01.docx](https://github.com/scieloorg/PC-Programs/files/979211/v8n1a01.docx)

**Comment by robertatakenaka** [comment]
@javani: aparentemente é porque não há contract em award, pois funding sem award é desconsiderado.

**Comment by javani** [comment]
@robertatakenaka foi isso mesmo.
