### ISSUE TITLE
[markup 92] Programa não apagar tags de fn quando apagamos a tag doc

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2474]
Mesmo apagando a tag doc, o programa mantém a marcação de notas de rodapé no documento.
![image](https://cloud.githubusercontent.com/assets/912953/22383224/0d8f5270-e4b0-11e6-87df-b89448234f7f.png)

**Comment by robertatakenaka** [comment]
@javani enviar o arquivo marcado

**Comment by javani** [comment]
@robertatakenaka pode usar o mesmo que mandei para o ticket #2473. Só apagar o doc raiz.
