### ISSUE TITLE
[docs] corrigir texto de formatação sobre citação numérica

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2504]
Ajustar o texto

> Para citação no sistema numérico no corpo do texto: número entre parênteses e sobrescrito;

Para ficar claro que um intervalo ou vários números devem ficar entre parênteses e não só 1 número.

**Comment by RPostalli** [comment]
Roberta, mas neste caso vai dar erro de xref não vai? Porque vai marcar só
uma no caso abaixo a B13 e não a B12, B11 e B10..

Exemplo: <xref ref-type="bibr" rid="B13">13, 12, 11, 10</xref>

Não é melhor assumir que para estes casos seja marcado na mão?



Atenciosamente,

Renata Postalli
Bibliotecária Júnior

---------------
[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

2017-02-21 17:02 GMT-03:00 Roberta Takenaka <notifications@github.com>:

**Comment by robertatakenaka** [comment]
O resultado é cada número é um xref.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2017-02-22 9:08 GMT-03:00 Renata Postalli <notifications@github.com>:

**Comment by RPostalli** [comment]
Entendi. Perfeito então.

Atenciosamente,

Renata Postalli
Bibliotecária Júnior

---------------
[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

Em 22 de fevereiro de 2017 09:22, Roberta Takenaka <notifications@github.com
