### ISSUE TITLE
[mkp|xpm] Arquivos de imagens "inline" não estão sendo incluídas no pacote

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2508]

**Comment by javani** [comment]
@robertatakenaka sugiro que a nomeação padrão para os casos de inline-graphic em inline-formula seja ?ieq1.svg etc, para inline-graphic apenas seja ?in1.xxx ou ?i1.xxx. O que você acha?

**Comment by robertatakenaka** [comment]
A regra de nomeação dos arquivos em src, está em:
http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_how_to_generate_xml-prepara.html#pasta-src

Para o Markup não importa se a imagem da equação está ou não inline. É importante que as imagens de equação estejam no src de acordo com o que está documentado.

**Comment by javani** [comment]
@robertatakenaka funcionou com eq.
