### ISSUE TITLE
[xpm] Melhoria em validações em referências

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2511]
- identificar trechos não etiquetados
- identificar quando person-group-type tem valor repetido
- identificar quando há In: em mixed-citation, há falta de article-title ou chapter-title

**Comment by javani** [comment]
Acho que seria melhor deixar como antes, só apresentando erro quando houver diferencia do source marcado com mixed, de given-names e de tipo de referência.
No caso de person-group, o único tipo que pode se repetir é o "author", os demais devem ser diferentes entre si.
