### ISSUE TITLE
[Markup 42] Melhoria: possibilidade de inclusão de código HTML de tabelas no arquivo para marcação

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2519]
Verificar a possibilidade de incluir código HTML de tabelas no arquivo de marcação assim como é feito com equações.  O programa executa a marcação, mas gera o XML sem o dado codificado (exclui o dado).
Caso seja possível fazer essa marcação, retirar automaticamente tags de parágrafo e atributos de altura e largura de td.
Envio arquivo usado como teste.
[02_2234.docx](https://github.com/scieloorg/PC-Programs/files/834846/02_2234.docx)

**Comment by robertatakenaka** [comment]
@javani 
Como solução foi criado um elemento chamado xhtml, dentro de tabwrap.
Possui um atributo href cujo valor é o nome de um arquivo que está em src e que segue a mesma regra de nomenclatura (http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_how_to_generate_xml-prepara.html#pasta-src, ou seja, nome-do-arquivo**t**idtabela.html).

Dentro deste html, deve conter uma tabela xhtml.  O XPM pegará do seu conteúdo de <table até </table> inclusive, desconsiderando quaisquer folhas de estilo que estiver sendo aplicada neste html

**Comment by javani** [comment]
@robertatakenaka não está fazendo a coleta.
Marcação:
![image](https://cloud.githubusercontent.com/assets/912953/24965839/a1cfcad6-1f7b-11e7-8409-88352629db6a.png)
Arquivo na pasta src:
![image](https://cloud.githubusercontent.com/assets/912953/24965874/b696c32a-1f7b-11e7-92b0-277f15d18156.png)

Resultado no xml:
![image](https://cloud.githubusercontent.com/assets/912953/24965929/e2151e20-1f7b-11e7-9b13-1816ae75b3e5.png)

Arquivos enviados por email.
