### ISSUE TITLE
[Markup 92] Lista de referências em vários elementos

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2520]
Programa não permite marcação em outros elementos do texto. Pela estrutura da JATS, é possível marcar lista de referências bibliográficas em:

```
<ack>, <app>, <app-group>, <back>, <bio>, <boxed-text>, <notes>, <ref-list>, <sec>
```
No programa, a marcação é possível em ```<back>```. Uma solução talvez seja deixá-lo como um elemento flutuante, na primeira linha do programa.

**Comment by robertatakenaka** [comment]
@javani: Todos os ref-list devem gerar na base registros de referências bibliográficas? Ou ficam só para apresentação no XML.
