### ISSUE TITLE
[WoS - ISI] Geração de SGML para publicações contínuas

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2523]
O SGML gerado para publicação contínua engloba todos os arquivos da publicação a cada atualização, ou seja, é incremental.
Verificar a possibilidade de gerar apenas com os novos artigos assim como é feito para os AOPs enviados ao Pubmed limitando o intervalo de datas da publicação.
Foi detectado que alguns artigos nessa modalidade não são carregados no WoS por causa da duplicidade de dados no arquivo SGML enviado.

**Comment by robertatakenaka** [comment]
@javani : já tentaram executar o procedimento com a mesma estrutura de lista usada para o PubMed?

**Comment by javani** [comment]
@robertatakenaka tentamos e não funcionou. O arquivo é gerado com todos os artigos

**Comment by javani** [comment]
@robertatakenaka continua gerando com todos os registros.
Na scilista - rsp NONE 20170320 20170327. Arquivo enviado por email.
