### ISSUE TITLE
[Markup92r4] Apresenta inconsistência no relatório de conteúdo para ref do tipo conferência e para person-group 

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2526]
Solicita chapter-title ou article-title para confproc, além de mais de um person-group para a referência.

![image](https://cloud.githubusercontent.com/assets/912953/24155083/9c8343ec-0e31-11e7-9a7b-0c6e70cb014f.png)

**Comment by robertatakenaka** [comment]
relacionado com #2511

**Comment by robertatakenaka** [comment]
aparentemente resolvido
