### ISSUE TITLE
[Markup 92r4] Considerar apenas <disp-formula> em <equation-counts>

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2527]
Ao fazer a marcação de equações em meio de parágrafos usando a tag [equation] o programa gera corretamente a tag inline-formula, mas apresenta erro no relatório de conteúdo relacionado a quantidade de equações presentes no documento.
![image](https://cloud.githubusercontent.com/assets/912953/24198422/a4935776-0ee4-11e7-9610-9062512b0452.png)
![image](https://cloud.githubusercontent.com/assets/912953/24198430/a9ea878a-0ee4-11e7-9b42-abb357f72bd9.png)
[1057.docx](https://github.com/scieloorg/PC-Programs/files/861415/1057.docx)

**Comment by robertatakenaka** [comment]
@javani: a imagem está ilegível. 
Verifiquei que o programa apenas conta os  elementos disp-formula e compara com o valor de equation-count/@count.

Por favor, me envie o XML.
