### ISSUE TITLE
[Markup93r2] Inconsistência relatório de conteúdo para afiliação

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2567]
Apresenta erro fatal de marcação em aff do tipo original conforme segue. A marcação está certa assim como o XML. 
Marcação
![image](https://cloud.githubusercontent.com/assets/912953/25454144/d966993a-2aa1-11e7-82e7-1c407c019461.png)

XML
![image](https://cloud.githubusercontent.com/assets/912953/25454189/f77ecabe-2aa1-11e7-9217-92a7252cd4c8.png)

Doc anexo
[v40n1a04.docx](https://github.com/scieloorg/PC-Programs/files/959613/v40n1a04.docx)

**Comment by robertatakenaka** [comment]
@javani : verifiquei o problema, por haver o caracter | (pipe) ele achou que havia mais de uma instituição. Bug no xpm mesmo.

**Comment by jenniferamato** [comment]
Teste v. 4.0.094t6: testado no Markup e XPM. Ticket pode ser fechado.
