### ISSUE TITLE
PMC não aceita SVG - Atualizar XPM para PMC

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#2569]
Precisamos (urgente) atualizar o XPM para que faça a geração de SVG em TIFF ou EPS ao gerar arquivo para PMC.

O ideal para imagens em PMC é:

Example: Image size is 900 pixels wide by 600 pixels in height, and the resolution is 300 dpi.

pixel dimension / resolution = physical width 

900 pixels / 300 dpi = 3 inches physical width 
600 pixels / 300 dpi = 2 inches physical height 
Intended Display Size = 3 x 2 inches.

Mais detalhes podem ser vistos em: https://www.ncbi.nlm.nih.gov/pmc/pub/filespec-images/

Email do PMC:

Hi Renata,
 
I apologize for the miscommunication. 
 
I have consulted with my colleagues and confirmed that we cannot support SVG files. As I noted in my previous email, uncompressed high-resolution TIFF or ESP files are required for all images. Additional information on our image quality specifications can be found here: https://www.ncbi.nlm.nih.gov/pmc/pub/filespec-images/
 
Please let us know if you have additional questions or concerns.
 
Thank you!
 
Clint 
 
— 
Clint E. Walker
Contractor
PubMed Central
pmc@ncbi.nlm.nih.gov

**Comment by robertatakenaka** [comment]
@RPostalli : enquanto não resolvo isso, o XPM inclui no pacote todos os arquivos cujo prefixo é o nome do arquivo XML, isto é, se há uma imagem xyz123.svg e uma imagem xyz123.eps ou .tiff ou .jpg todas vão para o pacote.

**Comment by RPostalli** [comment]
@robertatakenaka Quem está utilizando SVG só envia o formato SVG para tabelas e equações, eles não enviam mais outro formato. Teremos que realizar manualmente a geração dos SVG em TIFF (vamos usar por hora: http://image.online-convert.com/convert-to-tiff) de imagem por imagem dos pacotes e verificar as dimensões de cada uma, caso necessário teremos que abrir as imagens após geradas em TIFF e alterar manualmente os DPI e tamanhos.
