### ISSUE TITLE
[xpm] Possibilidade de configurar status de acesso disponível a Internet

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2578]
Em alguns locais o acesso a Internet é limitado, por este motivo, indicar via configuração de que o programa não deve usar os serviços de consulta pela Internet (validação de afiliações, DOI, journal meta, etc)

**Comment by robertatakenaka** [comment]
@javani : para inibir o uso da internet, configure o arquivo bin/xws.info, da seguinte forma:

ENABLED_WEB_ACCESS=off

Para qualquer outro valor diferente de "off", será considerado livre acesso à Internet.

A configuração de proxy mudou também. Agora ao invés de o programa tentar "descobrir" se há proxy, este arquivo deve estar configurado o endereço/porta do proxy.

**Comment by cinthia-vieira** [comment]
Status: funcionando; ticket pode ser fechado.

**Comment by cinthia-vieira** [comment]
Versão 4.0.094t6: funcionando
