### ISSUE TITLE
[Mkp 93] Inclui aleatoriamente tags com letras maiúsculas

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2583]
Quando incluída a tag [refs] em referência bibliográfica, em alguns casos inicia as tags em letra maiúscula (não deixa alterar para minúsculo).
A fonte usada é Times e a formatação foi feita por mim.
[bn-2016-0188.docx](https://github.com/scieloorg/PC-Programs/files/997551/bn-2016-0188.docx)

**Comment by robertatakenaka** [comment]
resolvido
