### ISSUE TITLE
[jats 1.1] <institution> dentro de <on-behalf-of>

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2586]
https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/on-behalf-of.html

![captura de tela 2017-05-19 as 09 59 58](https://cloud.githubusercontent.com/assets/505143/26248771/0c0d8f76-3c7a-11e7-9c40-fa93af70b0a9.png)

institution é opcional

**Comment by cinthia-vieira** [comment]
Status: funcionando; ticket pode ser fechado.

**Comment by cinthia-vieira** [comment]
Versão 4.0.094t6: tag `<institution>` não é gerada no documento XML em `<on-behalf-of>` mesmo se utilizando a tag Markup `[institid]`; a marcação somente gera a tag `<on-behalf-of>` sem informações de `<institution>`

[cir07217.docx](https://github.com/scieloorg/PC-Programs/files/1261343/cir07217.docx)
