### ISSUE TITLE
[jats 1.1] @symbol em <collab>

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2588]
https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/symbol.html

```xml

<table-wrap-foot>
<fn id="TF1-218" symbol="dagger">
<p>Data not available or incomplete for
this time period.</p></fn>
</table-wrap-foot>
```

**Comment by cinthia-vieira** [comment]
Status: funcionando; ticket pode ser fechado.

Relatório de estilos desaconselha o uso

**Comment by cinthia-vieira** [comment]
Versão 4.0.094: funcionando; erro do relatório de estilos se mantém.
