### ISSUE TITLE
(Markup 4.0.075 - Word 2010) Referências - ABNT -Implementar marcação de subresp em contrib de serial

### ISSUE THREAD

**Issue by vivianeneves** [scieloorg/PC-Programs#259]
Ver imagem. 
Não há tag para marcar tradução e revisão em contrib de serial.
Arquivo de teste enviado via e-mail. Ver 22ª Referência
![subrespcontribserial](https://f.cloud.github.com/assets/6368517/2061378/9ec2ceba-8c4e-11e3-8cdb-5f9133bac318.jpg)

**Comment by leticiaquino** [comment]
@robertatakenaka Resolvido. Não vamos mais dar manutenção para esta norma.

**Comment by robertatakenaka** [comment]
Creio que com a nova estrutura essa marcação está mais simples
