### ISSUE TITLE
[jats 1.1] <code>

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2592]
https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/code.html

![captura de tela 2017-05-19 as 09 58 18](https://cloud.githubusercontent.com/assets/505143/26248689/bb97d042-3c79-11e7-9ef7-7844f2efc6b9.png)

**Comment by robertatakenaka** [comment]
[Arquivo Comprimido 2.zip](https://github.com/scieloorg/PC-Programs/files/1235540/Arquivo.Comprimido.2.zip)

**Comment by cinthia-vieira** [comment]
Status: funcionando; ticket pode ser fechado.

**Comment by cinthia-vieira** [comment]
Versão 4.0.094t6: funcionando.
