### ISSUE TITLE
[mkp][xpm][xc] Considerar os demais atributos para datas em history além de received e accepted

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2593]
https://jats.nlm.nih.gov/publishing/tag-library/1.0/n-iki0.html
https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/date-type.html

http://jats4r.org/article-publication-and-history-dates

**Comment by jenniferamato** [comment]
@robertatakenaka , em histdate é possível marcar datetype="received" e  datetype="accepted", porém, já existia tag para marcação dos mesmos.

**Comment by robertatakenaka** [comment]
@jenniferamato : a questão não é o elemento mas os novos valores do atributo de tipo de data.

**Comment by jenniferamato** [comment]
@robertatakenaka , quis dizer que marcando uma data com a tag "received" e marcando uma data com "histdate" do tipo received, o resultado no XML seria o mesmo. Não estaria duplicado então?

**Comment by robertatakenaka** [comment]
@jenniferamato : anexa o arquivo de exemplo

**Comment by jenniferamato** [comment]
Em hist já existe as tags: received , revised e accepted: 

![hist](https://user-images.githubusercontent.com/16937218/29475501-6478d388-8436-11e7-901b-46c7064018b0.png)

E em histdate é possível marcar os mesmos tipos de datas: 

![hist2](https://user-images.githubusercontent.com/16937218/29475564-af142a6e-8436-11e7-90b3-7cded899f1bf.png)

Realizei a marcação dos dois jeitos e o resultado no XML está sendo o mesmo, minha dúvida seria apenas sobre a duplicidade.
