### ISSUE TITLE
(Markup 4.0.075 - Word 2010) Label de footnote não é marcado

### ISSUE THREAD

**Issue by vivianeneves** [scieloorg/PC-Programs#260]
O label da nota de rodapé fica fora da marcação e numeração do id da footnote difere do número real da nota, não sendo possível gerar esse número automaticamente na hora da apresentação do artigo em html.

Uma possibilidade é marcar com label que é elemento opcional de fn e fn-group. Veja Tag Library: http://jats.nlm.nih.gov/publishing/tag-library/1.1d1/
Ver footnotes do arquivo de teste enviado do ticket 259

![label_fn_075](https://f.cloud.github.com/assets/6368517/2061400/d90e5674-8c4f-11e3-9345-24466c8d30d7.png)

**Comment by robertatakenaka** [comment]
já fiz várias tentativas e não consigo obter o "texto" referente ao número do footnote.
