### ISSUE TITLE
[mkp 93] Não gera notas de rodapé em subdoc quando usada a tag *page-fn

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2600]
O programa não consegue relacionar as notas traduzidas com sub-article quando usada a tag *pn-page. Todas as notas ficam em back do artigo principal.
[9_ARQ95_art01.docx](https://github.com/scieloorg/PC-Programs/files/1047596/9_ARQ95_art01.docx)

**Comment by javani** [comment]
@robertatakenaka continua sem funcionar, inclusive na versão 4.094. Também não está funcionando a tag *fngrp , fn e *fn.
Notei que o problema ocorre apenas as notas com valores atribuídos de nota que ficam em back (other, presented-at etc). Para notas relacionadas ao autor funciona.

**Comment by javani** [comment]
@robertatakenaka fiz um update no comentário anterior.

**Comment by robertatakenaka** [comment]
@javani : não achei nota de rodapé no arquivo a13_117_126.docx

**Comment by robertatakenaka** [comment]
@javani quando você diz:
>  continua sem funcionar, inclusive na versão 4.094. Também não está funcionando a tag *fngrp , fn e *fn.

O que quer dizer? não marca ou não gera?

**Comment by javani** [comment]
Marca mas não gera

**Comment by robertatakenaka** [comment]
@javani : logo vou passar a correção, mas por outro lado há um problema de marcação:

no lugar de:
**[doctitle language="es"]El impacto epidemiológico de la invasión europea en América[/doctitle] [xref ref-type="fn" rid="fn1" label="1"]*[/xref]**

usar:

**[doctitle language="es"]El impacto epidemiológico de la invasión europea en América [xref ref-type="fn" rid="fn1" label="1"]*[/xref][/doctitle]**

**Comment by javani** [comment]
@robertatakenaka já tinha visto o problema, mas deixei assim pra eles identificarem o que acontece. De qualquer forma, no XML está certo. Inclui as notas e a xref manualmente.

**Comment by cinthia-vieira** [comment]
O Markup ainda não gera as notas no sub-article na versão 4.0.094 r2 ao construir o XML; para o artigo principal as notas são geradas. 

A marcação automática, entretanto, é realizada normalmente (o Markup reconhece e marca as notas corretamente)

**Comment by cinthia-vieira** [comment]
**Update**: docx anexado ao comentário

**Comment by cinthia-vieira** [comment]
Teste no Markup versão 4.0.094t6: funcionando corretamente; `<fn>` geradas em ambos artigos.
