### ISSUE TITLE
[mkp 93] negrito no label de tabela causa aviso

### ISSUE THREAD

**Issue by lucasssantos** [scieloorg/PC-Programs#2601]
O negrito no label da tabela causa o seguinte aviso:

![capturar](https://user-images.githubusercontent.com/19777809/26884624-92d1c3aa-4b76-11e7-8792-3db9d69b5f53.PNG)

O arquivo marcado:

![capturar](https://user-images.githubusercontent.com/19777809/26884694-c2c0ed34-4b76-11e7-8298-743c70ae0e8b.PNG)

Local dos arquivos: Y:\users\Lucas Santos\a4

**Comment by jenniferamato** [comment]
Teste v. 4.0.094t6: não está acusando aviso. Ticket pode ser fechado.
