### ISSUE TITLE
Elemento @seq e artigos sequenciais em mesma página

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2610]
Ao subir artigos que começam e terminam na mesma página, o XC dá erro de order (o que é esperado)
![xpm-seq1](https://user-images.githubusercontent.com/27728729/27448531-8270a5d0-575b-11e7-8345-8697a42ca268.PNG)
​(No caso de subir no XC, o erro é o de "esse order já foi encontrado em artigo tal")

Entretanto, a documentação SPS e JATS prevê um atributo para esse tipo de documento, o atributo @seq, que é acrescentado à tag <fpage> [[SPS](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/tagset/elemento-fpage.html); [JATS](https://jats.nlm.nih.gov/publishing/tag-library/1.0/n-yaw0.html)], mas esse atributo não é utilizado pelo XC, que exige uma tag de "other" para a criação da ordem dos artigos nesses casos. Utilizando a tag de "other", os arquivos são processados normalmente, apenas com um warning para paginação 
![xpm-seq2](https://user-images.githubusercontent.com/27728729/27448533-827b8946-575b-11e7-8909-02aa74207eac.PNG)
![xpm-seq3](https://user-images.githubusercontent.com/27728729/27448532-827b45a8-575b-11e7-9ffc-305448bb23ed.PNG)
​(Os arquivos também são processados no caso de se acrescentar letras na paginação.)

O PubMed Central, por sua vez, orienta o uso do atributo nesses casos, como diz a documentação ([PubMed Central Tagging](https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-fpage))

Seguem os relatórios XPM:

**Sem tag "other"; tag "seq":** [tag_seq.zip](https://github.com/scieloorg/PC-Programs/files/1095739/tag_seq.zip)
**Usando tag "other":** [tag_other.zip](https://github.com/scieloorg/PC-Programs/files/1095740/tag_other.zip)

Caso precise dos XML, os enviarei.

**Comment by cinthia-vieira** [comment]
Na versão 4.0.094 a tag é gerada corretamente, entretanto, a nomeação normalizada não leva em conta o conteúdo em `@seq` considerando apenas a numeração de `<fpage>/<elocation-id>`.

O XPM correspondente à versão reconhece a o atributo `@seq`, não gerando erros críticos de paginação, e mantendo os artigos na ordem estabelecida pelo atributo.

**Comment by cinthia-vieira** [comment]
Como reportado no ticket #2689 , a nomeação dos arquivos está sendo feita de forma correta.

Entretanto, o XPM não reconhece o atributo `@seq` como um diferenciador para o número de order, causando conflito no uso do atributo ao gerar orders iguais para artigos sequenciados:

![image](https://user-images.githubusercontent.com/27728729/29835411-4841e728-8cc8-11e7-84b5-aec1c3bfc588.png)

**Comment by robertatakenaka** [comment]
@cinthia-vieira : os arquivos possuem article-id do tipo (other)? Quando há `@seq` é necessário ter o article-id (other) para gerar o order corretamente, pois order somente pode ser número de 1 a 99999.

**Comment by cinthia-vieira** [comment]
@robertatakenaka no caso não, fiz sem order pra testar como ficaria. 

Acho interessante documentarmos a necessidade do uso de `@pub-id-type=other` para `@seq`, seja no SPS, seja em alguma documentação interna, pois no texto atual fica subentendido de que o atributo por si modifica o número de order gerado.

**Comment by robertatakenaka** [comment]
@cinthia-vieira : acho que podemos ter duas ações aqui:
1.  (eu) inserir uma mensagem que se houver `@seq`,  logo há necessidade de article-id (other)
2. (você) abrir um ticket no projeto scielo_publishing_schema **caso** na documentação não exista menção adequada de `@seq` e `article-id (other)`

**Comment by cinthia-vieira** [comment]
@robertatakenaka ótimo!!!

Abrirei o ticket e relaciono ele neste ticket, posso fazer isso? (github não é meu forte...)

**Comment by robertatakenaka** [comment]
@cinthia-vieira : se é no mesmo projeto basta escrever `#numero do ticket`, mas como é outro projeto, após criado o ticket lá, é só copiar o link e incluir aqui no comentário.

**Comment by cinthia-vieira** [comment]
Roberta, criei o ticket (https://github.com/scieloorg/scielo_publishing_schema/issues/543)! Entretanto, enquanto olhava a documentação, percebi que também teremos de acrescentar a orientação para usar o "other" na documentação do Markup. 

Onde posso criar um ticket com relação a isso? Ou posso sugerir isso no ticket já criado?
