### ISSUE TITLE
[xpm] Incluir validação de formato do ORCID

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2615]
A regex de validação do ORCID é: [0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[X0-9]{1}'

**Comment by jenniferamato** [comment]
Teste v. 4.0.094t6: testado no XPM. Ticket pode ser fechado.

**Comment by robertatakenaka** [comment]
Por favor, anexar o XML.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CAPES - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2018-08-31 11:24 GMT-03:00 alexxpsilva <notifications@github.com>:

**Comment by alexxpsilva** [comment]
Anexado.
[1414-8145-ean-22-03-e20170387.zip](https://github.com/scieloorg/PC-Programs/files/2340436/1414-8145-ean-22-03-e20170387.zip)

**Comment by robertatakenaka** [comment]
resolvido
