### ISSUE TITLE
[XC] Barra artigos que sofreram alteração de títulos

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2616]
Ao subir um artigo que teve uma palavra do título alterada, o XC não permitiu.

Link do relatório: (http://homolog.xml.scielo.br/reports/bjb/2017nahead/xc-2017-07-04_152518.html)

![bjb_ticket](https://user-images.githubusercontent.com/15328777/27841484-28215b16-60d8-11e7-94eb-eae32aad7ef1.png)
[1519-6984-bjb-1519-698404916.zip](https://github.com/scieloorg/PC-Programs/files/1122944/1519-6984-bjb-1519-698404916.zip)

**Comment by robertatakenaka** [comment]
Corrigido a apresentação dos dados do artigo no relatório

<img width="1211" alt="captura de tela 2017-07-04 as 17 35 57" src="https://user-images.githubusercontent.com/505143/27842403-33c6b1ca-60e0-11e7-892a-688159f25062.png">

**Comment by robertatakenaka** [comment]
Na aba Converter Validations, mostra que há alteração no título e em autores. O XC bloqueia quando há mudança em ambos.

No caso a ausência de ponto em **Mendes, J. F**

<img width="713" alt="captura de tela 2017-07-04 as 17 36 22" src="https://user-images.githubusercontent.com/505143/27842413-499ddfc8-60e0-11e7-85a6-b894273409e3.png">
