### ISSUE TITLE
[XC] Relatórios do XC estão em inglês

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2621]
Os relatórios do XC que estamos recebendo estão em inglês: 

Exemplos: 
http://homolog.xml.scielo.br/reports/abb/v31n3/xc-2017-07-10_140227.html
http://homolog.xml.scielo.br/reports/rounesp/v46n3/xc-2017-07-07_081718.html

Antes os relatórios eram gerados em português.

**Comment by robertatakenaka** [comment]
@jenniferamato : esta questão não depende de correção na aplicação, pois é um problema de configuração. Foi aberto um chamado no suporte. Por este motivo vou fechar este issue.
