### ISSUE TITLE
[Markup 93] Não reconhece marcação de [prefix] em autor

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2622]
Marcação:
[author role="nd" corresp="n" deceased="n" eqcontr="nd"][prefix]Sir[/prefix] [fname]William[/fname] [surname]Osler[/surname]†[/author]

XML:
```
            <contrib-group>
               <contrib contrib-type="author">
                  <name name-style="western">
                     <surname>Osler</surname>
                     <given-names>William</given-names>Sir</name>
               </contrib>
            </contrib-group>
```

[a14_649_662.docx](https://github.com/scieloorg/PC-Programs/files/1142193/a14_649_662.docx)

**Comment by cinthia-vieira** [comment]
Status: funcionando; ticket pode ser fechado.

**Comment by cinthia-vieira** [comment]
Versão 4.0.094t6: funcionando
