### ISSUE TITLE
[Markup 40093_20170627 e XPM] Não apresenta erro de xref de referência bibliográfica ausente

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2623]
Versão não apresenta erro para xref ausente de referência bibliográfica.
[editorial-psoc-28-03-00410.docx](https://github.com/scieloorg/PC-Programs/files/1165723/editorial-psoc-28-03-00410.docx)

**Comment by jenniferamato** [comment]
Teste v. 4.0.094t6: testado no Markup e XPM, está apresentando fatal error na ausência de referência bibliográfica. Ticket pode ser fechado.
