### ISSUE TITLE
(4.0.075) (melhoria) eliminar automaticamente as tags p, ao marcar o trecho com outra tag.

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#263]
para algumas tags que ficam dentro de xmlbody e que não precisam ser identificadas com p, por ex, quote, list, etc.

**Comment by leticiaquino** [comment]
@robertatakenaka Depende, essa funcionalidade seria interessante para listas, citações, tabelas, equações, figuras etc, porém se precisarmos remarcar uma seção, por exemplo, ao selecionar todo o [sec] (parágrafos, figuras etc) perdemos as marcações de [p], [xref], [fig], [tab]...
