### ISSUE TITLE
[xml markup] Gerar XML de acordo com versão de SPS

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2658]
Atualmente a geração de XML sempre é feita a partir da última versão da JATS.
Considerar a versão SPS para gerar JATS.

- SPS 1.6 gerar JATS 1.0
- SPS 1.7 gerar JATS 1.1

**Comment by cinthia-vieira** [comment]
Status: funcionando; ticket pode ser fechado.

**Comment by cinthia-vieira** [comment]
Teste v. 4.0.094t6: funcionando
