### ISSUE TITLE
[markup 93/94] Não gera XML por erro de inclusão de rid em xref

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2680]
[a09_230_244.doc.zip](https://github.com/scieloorg/PC-Programs/files/1252701/a09_230_244.doc.zip)

No arquivo anexo foram incluídos dois rid errados em xref de fn = [xref ref-type="fn" rid="n2"]*[/xref] e outro  [xref ref-type="fn" rid="n3"]*[/xref]
Além do XML não ser gerado, mostrou o erro numa parte do documento onde a marcação está correta.

![image](https://user-images.githubusercontent.com/912953/29715763-0dda7ace-897f-11e7-83b8-2827e9ca6904.png)
Gerando o XML na linha de comando, apareceu
![image](https://user-images.githubusercontent.com/912953/29715788-24113aee-897f-11e7-92a7-08608765813c.png)
Somente dessa forma consegui verificar que o problema era no rid de fn (no olho foi a busca).

**Comment by robertatakenaka** [comment]
@javani : só para registro: a "tradução" da mensgem é "Não é possível criar uma atributo rid em no nó do documento" (no caso, atributo rid no elemento article).

**Comment by javani** [comment]
@robertatakenaka obrigada Roberta.
