### ISSUE TITLE
(4.0.094 teste)[mkp xml] Considerar fpage/@seq no nome do XML

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2689]
Na versão 4.0.094 a tag é gerada corretamente, entretanto, a nomeação normalizada não leva em conta o conteúdo em @seq considerando apenas a numeração de <fpage>/<elocation-id>.

relacionado com #2610

**Comment by cinthia-vieira** [comment]
Nomeação funcionando corretamente (versão 4.0.094t6); o Markup gera nomes de acordo com a informação do atributo `@seq`. 

**Nome gerado:** 0717-6996-arq-95-105b 
**Doc base:** [9_ARQ95_art01.docx](https://github.com/scieloorg/PC-Programs/files/1261124/9_ARQ95_art01.docx)
