### ISSUE TITLE
[XC] Fatal error DOI

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2693]
Quando o DOI não possui prefixo SciELO, no relatório do XC está apresentando o seguinte erro para a maioria dos artigos: 

Exemplo: 2179-8966-rdp-8-2-830  

![rdp1](https://user-images.githubusercontent.com/16937218/29925150-cedff9be-8e35-11e7-87c5-1ebf13d61c50.PNG)

Em alguns arquivos como no 2179-8966-rdp-8-2-905, não apresentou erro: 

![rdp2](https://user-images.githubusercontent.com/16937218/29925152-d0a8abce-8e35-11e7-8eb1-a7b81d7b3a1e.png)

Relatório do XC:
http://homolog.xml.scielo.br/reports/rdp/v8n2/xc-2017-08-30_120152.html#view-reports-2179-8966-rdp-8-2-830

**Comment by robertatakenaka** [comment]
<img width="692" alt="captura de tela 2017-08-31 as 16 19 14" src="https://user-images.githubusercontent.com/505143/29941216-2f387a0c-8e68-11e7-9135-740c9cbbbdac.png">
