### ISSUE TITLE
[XPM] Indica ausência de PDF que está no pacote 

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#2707]
A validação  indica existência do PDF de acordo com o idioma do artigo, mas ao mesmo tempo informa q não há pdf no pacote.

![image](https://user-images.githubusercontent.com/6921625/30390090-58e9d5a8-988b-11e7-9cb7-a879a6bf7cc9.png)

**Comment by robertatakenaka** [comment]
@suelylc : acho que a mensagem está confusa... Mas está ou não o pdf ausente?

A primeira indica que o pdf espera é em inglês.
A segunda indica se encontrou ou não, no caso,  não encontrou no pacote.

**Comment by suelylc** [comment]
@robertatakenaka o PDF está no pacote sim. ( Não há sub-article no xml) 
![image](https://user-images.githubusercontent.com/6921625/30392860-7973c0c8-9894-11e7-9296-b704b566c411.png)

**Comment by robertatakenaka** [comment]
@suelylc : ah mas o inglês ele deve ter identificado do original mesmo. Mas verifique se na pasta scielo_package o arquivo pdf consta.

**Comment by suelylc** [comment]
@robertatakenaka está no scielo_package sim. 
A indicação do PDF com informação de idioma está ok, o que está estranho é somente indicar que o mesmo PDF não foi encontrado

**Comment by suelylc** [comment]
[1413-8123-csc-22-09-2873.zip](https://github.com/scieloorg/PC-Programs/files/1300405/1413-8123-csc-22-09-2873.zip)
