### ISSUE TITLE
[XPM] Indicação de Fatal error para ano = 2017 em referências 

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#2709]
O XPM está indicando Fatal Error para todas as referências que possuem  <year>2017</year>, conforme imagem abaixo

![image](https://user-images.githubusercontent.com/6921625/30490251-cc2386d8-9a0f-11e7-996b-6f9b54157ccb.png)

**Comment by robertatakenaka** [comment]
@suelylc : por gentileza, anexa 1 artigo xml

**Comment by suelylc** [comment]
@robertatakenaka . Segue, referência 1
[0213-9111-gs-31-01-00018.zip](https://github.com/scieloorg/PC-Programs/files/1307234/0213-9111-gs-31-01-00018.zip)

**Comment by robertatakenaka** [comment]
@suelylc melhorei a mensagem. E realmente está errada a data, pois no pdf está outra data.

<img width="871" alt="captura de tela 2017-09-15 as 16 14 25" src="https://user-images.githubusercontent.com/505143/30499460-fab7f3d2-9a30-11e7-80dc-ad6dcbaa00f2.png">
