### ISSUE TITLE
[Markup] Dados de financiamento em notas de rodapé de página

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2711]
Programa não aceita marcação de dados de financiamento em notas de rodapé de página marcados com *page-fn.

Testado no Markup 93 e 94.

Arquivo anexo. 
[Educar_65_Demanda_Artigo_04.docx](https://github.com/scieloorg/PC-Programs/files/1307220/Educar_65_Demanda_Artigo_04.docx)

**Comment by robertatakenaka** [comment]
@jenniferamato : Não permite marcar ou não gera os elementos no XML?

**Comment by jenniferamato** [comment]
@robertatakenaka , não permite marcar.

**Comment by robertatakenaka** [comment]
A área de nota de rodapé é uma área especial que não permite que o usuário insira as tags pelo programa, apesar de o próprio programa conseguir inserir as tags de fn. O problema é que não dá para habilitar para o usuário inserir as tags.
A solução que implementei foi extrair o conteúdo destas áreas especiais e mover para a área do corpo do texto, logo no final do documento, onde é possível fazer a marcação normalmente.

**Comment by javani** [comment]
@robertatakenaka fiz a marcação com a tag *page-fn e funcionou.
