### ISSUE TITLE
[XPM] Indica Fatal Error mas não apresenta onde

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2717]
O pacote anexo apresenta erros de estrutura e fatal error, porém não apresenta o erro em nenhum dos casos. Só é possível avaliar o erro abrindo o XML, que no caso é um erro com a tag alt-text.
[1980-5098-cflo-27-03-00767.zip](https://github.com/scieloorg/PC-Programs/files/1311649/1980-5098-cflo-27-03-00767.zip)

**Comment by alexxpsilva** [comment]
Complementando o ticket anterior, segue print dos relatórios

![xpm_erroralt](https://user-images.githubusercontent.com/15328777/30561429-64edb68a-9c91-11e7-9bdd-826fa61df235.png)

![xpm_erroralttext](https://user-images.githubusercontent.com/15328777/30561461-80706f38-9c91-11e7-9bd1-0a43da9b30f8.png)

**Comment by robertatakenaka** [comment]
resolvido
