### ISSUE TITLE
[mkp 93] Marcación automática (Vancouver) pierde estilos en las referencias 

### ISSUE THREAD

**Issue by oraliacr** [scieloorg/PC-Programs#2719]
Al utilizar la marcación automática Vancouver se pierden los estilos en las referencias. Dentro de [text-ref] aparece la información original pero sin ningún estilo (bold, italic).

Referencia antes de la marcación automática:
![imagen](https://user-images.githubusercontent.com/19307594/30603103-2598b426-9d2c-11e7-97ee-25f8c63d3bc3.png)

Referencia marcada:
![imagen](https://user-images.githubusercontent.com/19307594/30603115-2e060258-9d2c-11e7-8ce4-1c2fc42ac9c2.png)

**Comment by robertatakenaka** [comment]
Estimada @oraliacr 
Desafortunadamente no tenemos cómo corregir pues es una herramienta que no tenemos el código fuente. Una posibilidade de corregir manualmente después de marcar la cita, añadiendo los estilos.
Tendré que cerrarla.
