### ISSUE TITLE
[XPM] Mensagem de Fatal error em referencia com dois <year>

### ISSUE THREAD

**Issue by suelylc** [scieloorg/PC-Programs#2722]
[2175-764X-tla-56-02-00347.zip](https://github.com/scieloorg/PC-Programs/files/1322431/2175-764X-tla-56-02-00347.zip)
Algumas revista solicitam que seja incluído o ano da versão original logo após o nome dos autores, como no exemplo abaixo, e o XPM está apontando essa ocorrência.  De fato, a data considerada na referência é o ano de publicação.  

Sugestão: Ajustar mensagem de Fatal Error para referências onde há mais de um elemento <year> informando que deve ser mantido somente o ano de publicação da obra.

![image](https://user-images.githubusercontent.com/6921625/30713401-8663173c-9ee5-11e7-9587-51ca9c175dc0.png)

Segundo a jats <year> pode ocorrer 0 ou 1 vez https://jats.nlm.nih.gov/publishing/tag-library/1.0/n-pku2.html

**Comment by robertatakenaka** [comment]
@suelyc: no caso é a segunda data?

**Comment by suelylc** [comment]
@robertatakenaka, isso, a segunda data refere-se a data da obra.
