### ISSUE TITLE
[mkp] Tag <*authors> está bugada quando só tem dois autores

### ISSUE THREAD

**Issue by Gilcemir** [scieloorg/PC-Programs#2742]
Prezados, bom dia.
A tag <*authors> não funciona corretamente com apenas dois autores. 
Caso você tente marcar com essa tag uma ref com dois autores, ela marca errado se tem & ou and como separador dos dois autores.
Exemplo:
[ref id="r12" reftype="book"]Resende MDV and Duarte JB (2007) Precisão e controle de qualidade em experimentos de avaliação de cultivares. Pesquisa Agropecuária Tropical 37: 182-194.[/ref]
Fica:
[ref id="r12" reftype="book"][authors role="nd"][pauthor][surname]Resende MDV and Duarte[/surname] [fname]JB[/fname][/pauthor][/authors] (2007) Precisão e controle de qualidade em experimentos de avaliação de cultivares. Pesquisa Agropecuária Tropical 37: 182-194.[/ref]
Uma solução que tenho usado, desde quando começou esse bug é substituir o &/and por "," e depois substituo novamente por &/and. Porém, sempre que faço isso, a referência não é linkada corretamente no corpo do texto - essa referência deve ser marcada manualmente.
Espero ter sido claro quanto ao bug.
Att.,

**Comment by javani** [comment]
@robertatakenaka testado e funcionando.
