### ISSUE TITLE
[PUBMED] Geração de XML com erros

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2743]
A geração de arquivos XML para PubMed (citações) está ocorrendo com bugs.

Ao gerar o XML, os resumos estão vindo com título de seção ("Abstract" ou correspondente) sem nenhum acompanhamento de tags, imediatamente antes ou depois da tag `<abstract>`.

Também estão sendo geradas tags com valores vazios em `<OtherAbstract Language="">`, corrompendo o documento e tornando o XML inválido.

Seguem prints dos exemplos de erros:

**Erro em `<abstract>`**
*XML gerado para PubMed*
![image](https://user-images.githubusercontent.com/27728729/31225500-c5b9d506-a9a8-11e7-82e5-5d0a51bba23a.png)

*XML do SPS*
![image](https://user-images.githubusercontent.com/27728729/31225562-0d02bcca-a9a9-11e7-8e04-b263fc306294.png)

**Erro em `<OtherAbstract Language=>`**
![image](https://user-images.githubusercontent.com/27728729/31225309-d844e612-a9a7-11e7-93ed-325d8069e1b1.png)

**Comment by natalieakemi** [comment]
O erro de "abstract" ainda estão ocorrendo nos arquivos gerados do PubMed. 

![image](https://user-images.githubusercontent.com/19558447/32274953-8d0f80d6-bef0-11e7-8b48-7036c4d4db17.png)
