### ISSUE TITLE
[xpm] Remover as validações de datas das referências 

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2749]
O novo validador de pacotes (package_maker 94) está apontando uma restrição quanto à data da publicação consultada, informando que a data da bibliografia não pode ser posterior à data do recebimento do artigo. Ocorre que durante o processamento do artigo e revisão dos consultores, os autores têm oportunidade de fazer correções, podendo também incluir bibliografias. Portanto sugiro que tal restrição seja retirada.

> ref/year (2016) should not be greater than received/year (2015).

**Comment by jenniferamato** [comment]
@robertatakenaka , testado com 40094r3 e a validação continua: 

![teste](https://user-images.githubusercontent.com/16937218/32284729-42aebba0-bf0f-11e7-8a9b-35c8816b9387.png)
