### ISSUE TITLE
[mkp xmp] Ausência de xref de bibr

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2750]
XPM está apontando as ausências de citação de referências bibliográficas no XML, conforme citado a seguir. Sugiro que este teste seja inserido no relatório de erros de conteúdo que está junto com outros relatórios do Markup. Dessa forma, as correções podem ser feitas durante a primeira produção dos arquivos em XML, evitando que  tenhamos que abrir novamente os arquivos após a aplicação do package-maker.

<img width="786" alt="captura de tela 2017-10-17 as 10 49 47" src="https://user-images.githubusercontent.com/505143/31665826-eff15dec-b328-11e7-95b0-ab8fa6fa4920.png">

**Comment by javani** [comment]
@robertatakenaka o problema ocorre porque estão usando versões diferentes entre markup (93) e XPM (94). No markup 94 o erro é apontado adequadamente

**Comment by robertatakenaka** [comment]
@javani obrigada!
