### ISSUE TITLE
[xc] Modificar a estratégia de identificação de ex aop para a exclusão

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2751]
Um artigo aop quando é publicado em um fascículo pode ter alterações em título e nome.
O sistema atualmente identifica o ex aop por estes dados.

**Comment by RPostalli** [comment]
O ex aop só terá modificações quando existe a publicação de uma errata. Isso ocorre com frequência, e a maioria das erratas são relacionadas a nomes de autor e títulos. Segue lista de dados que são efetivamente corrigidos quando existe a publicação de uma errata (mais detalhes em nosso Guia de Errata em: http://www.scielo.org/local/File/Guia_para_o_registro_e_publicacao_de_Errata.pdf):

- Nome de autor
- Título de artigo
- Afiliação de autor
- Resumo (Completo)
- Palavras-chave
- Número de contrato de financiamento
- Instituição financiadora
- Número de registro de ensaio clínico
- Referências
- Legenda Bibliográfica (Título da revista, volume, número, periodicidade, paginação ou
elocation-id e ano)
- Datas de histórico do artigo
