### ISSUE TITLE
[PMC] Geração de XML com erros

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2756]
O XPM está gerando XML para PubMed Central com a seguinte tag para `<kwd-group>`:

![image](https://user-images.githubusercontent.com/27728729/31726423-b06d67a0-b405-11e7-93b3-260e7b0d3b91.png)

Também está gerando um espaço vazio entre as tags `<label>` e `<element-citation>` em `<ref>`

![image](https://user-images.githubusercontent.com/27728729/31727644-d77a80dc-b408-11e7-9563-db11ecdf6e30.png)

**Comment by robertatakenaka** [comment]
identifiquei o problema acontece quando o elemento gerado via ``<xsl:copy-of select="."/>``, o namespace é inserido.
