### ISSUE TITLE
[xpm] Remover as mensagens sobre order e article-id (other) 

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2757]
Estas mensagens somente devem aparecer em XC

<img width="1098" alt="captura de tela 2017-10-18 as 14 06 05" src="https://user-images.githubusercontent.com/505143/31729392-a21428a8-b40d-11e7-8875-75f6f9b415bb.png">

**Comment by jenniferamato** [comment]
@robertatakenaka , testado com 40094r3. Está ok, ticket pode ser fechado.
