### ISSUE TITLE
[xpm] Validar DOCTYPE

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2768]
Validar o PUBLIC ID vs SYSTEM ID e sps version.

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.7-branch/tagset/xml-doctype.html

Recebemos XML que continha:
``"-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.0 20120330//EN" ``

em 
``<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.0 20120330//EN" "http://jats.nlm.nih.gov/publishing/1.1/JATS-journalpublishing1.dtd">``

Enquanto deveria ser:

``"-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1 20151215//EN"``

**Comment by RPostalli** [comment]
Inserir na validação a relação =
SPS 1.7 = JATS 1.1
SPS 1.6 = JATS 1.0

**Comment by jenniferamato** [comment]
@robertatakenaka , testado com 40094r3. Está ok, ticket pode ser fechado.
