### ISSUE TITLE
XPM - Listar DOI

### ISSUE THREAD

**Issue by Ronaldo-Machado-Letra1** [scieloorg/PC-Programs#2771]
Sugestão de melhoria no relatório XPM: listar DOIs de cada artigo

**Comment by robertatakenaka** [comment]
@Ronaldo-Machado-Letra1 : Pode detalhar mais, por favor? Onde exatamente? Uma lista só com DOI?

**Comment by Ronaldo-Machado-Letra1** [comment]
**por exemplo**:
![doi](https://user-images.githubusercontent.com/32942490/31941081-3c6b9630-b89f-11e7-8321-e51559ea2a17.JPG)

**Comment by jenniferamato** [comment]
@robertatakenaka , testado com 40094r3. Está ok, ticket pode ser fechado.
