### ISSUE TITLE
[XPM 4.0.094] Não valida conjunto de AOPs

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2772]
Aparentemente, pela ausência da tag article-id do tipo other, o programa não consegue validar o conjunto de artigos apresentando inconsistência de dados entre artigo e pacote.
[scielo_package_xpm.zip](https://github.com/scieloorg/PC-Programs/files/1415386/scielo_package_xpm.zip)

**Comment by RPostalli** [comment]
tem referência também com a discussão da lista scielo-xml@googlegroups.com, título: [SciELO XML] Atualização XPM

**Comment by robertatakenaka** [comment]
![captura de tela 2017-10-26 as 10 18 35](https://user-images.githubusercontent.com/505143/32052466-1a5841e4-ba37-11e7-9b03-5854b37f7d87.png)
[2238-0019-trends-nahead-0717_xpm(1).zip](https://github.com/scieloorg/PC-Programs/files/1418289/2238-0019-trends-nahead-0717_xpm.1.zip)

**Comment by jenniferamato** [comment]
@robertatakenaka , testado. Está OK.
