### ISSUE TITLE
[XC 94] Não apresenta erro para DOI repetido na base

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2786]
XC não apresenta mais erro de DOI repetido e registrado na base ou no Crossref.

http://homolog.xml.scielo.br/reports/rarv/v41n4/xc_2017-10-30_115133.html (relatório XC)

No artigo publicado em 
``PRODUCTION OF MINI-CUTTINGS AND THE INFLUENCE OF LEAF REDUCTION ON ROOTING OF VINHÁTICO (Plathymenia foliolosa Benth.)1``
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-67622017000400202&lng=en&nrm=iso

, o DOI pertence ao artigo 
``FORMATIONS OF COASTAL FORESTS IN THE AMAZON AND ECOLOGICAL RELATIONS WITH VASCULAR EPIPHYTES``

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-67622017000200102&lng=en&nrm=iso&tlng=en

**Comment by robertatakenaka** [comment]
@javani : não consegui simular o problema no XC.
Aparentemente o XC está correto. 

O XC e XPM eles usam a api do CrossRef (https://api.crossref.org) para consultar os dados do DOI se pertencem ao próprio artigo, a outro artigo ou a nenhum.
No entanto, quando é nenhum, eles não indicam nada no relatório. Talvez uma possível mudança é indicar que nenhum dado foi encontrado.

Por exemplo: 

<img width="910" alt="captura de tela 2017-10-31 as 10 48 56" src="https://user-images.githubusercontent.com/505143/32224565-1f788eae-be29-11e7-84a4-a3c30b767af8.png">

<img width="878" alt="captura de tela 2017-10-31 as 10 46 36" src="https://user-images.githubusercontent.com/505143/32224569-21b98f92-be29-11e7-8162-7136ee27bae9.png">

**Comment by robertatakenaka** [comment]
@javani : identifiquei o problema. Como a consulta é para um serviço Web  (API) e quando aresposta era nenhum resultado , o XPM deixava de consultar qualquer serviço desta URL achando que o serviço estava fora do ar.
No relatório não aparecia nenhuma anotação: nem que já estava registrado, nem que estava registrado para outro artigo, porque na verdade o XPM não estava mais consultando.

Removi esta característica. Agora o XPM/XC vai consultar de qualquer forma todos os serviços.

Além disso, aproveitei inserir uma mensagem explícita de quando o DOI não está registrado ou se este serviço está fora do ar e também é indicado no relatório se o artigo não tem DOI, apenas como INFO.

**Comment by javani** [comment]
@robertatakenaka ok, entendido.

**Comment by jenniferamato** [comment]
@robertatakenaka , testado. Está OK.
