### ISSUE TITLE
[xpm] scielo_env.ini: XML_STRUCTURE_VALIDATOR_PREFERENCE_ORDER

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2789]
O valor indicado para XML_STRUCTURE_VALIDATOR_PREFERENCE_ORDER não está sendo considerado.

O XPM está usando packtools mesmo que o valor seja java|packtools

**Comment by javani** [comment]
@robertatakenaka continua considerando o packtools

**Comment by robertatakenaka** [comment]
@javani: por favor, verifique se seu arquivo está como 
XML_STRUCTURE_VALIDATOR_PREFERENCE_ORDER (correto)

e não XML_STRUCTURE_VALIDATOR_PREFERENCE (incorreto)

**Comment by javani** [comment]
@robertatakenaka está com o primeiro formato.
