### ISSUE TITLE
[mkp xml] (4.0.094) Corrigir falta de fn-group envolvendo fn dentro de back

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2795]
![image](https://user-images.githubusercontent.com/505143/32454335-19fc01f4-c306-11e7-983d-6a54ea228859.png)
Causado por generar:

```
673:        </ref-list>
674:        <fn fn-type="supplementary-material" id="fn2">
675:            <label><bold>Anexo. Material adicional</bold></label>
676:            <p> Se puede consultar material adicional a este artículo en su versión electrónica disponible en doi:10.1016/j.rcreu.2016.12.005</p>
677:        </fn>
678:    </back>
679:</article>
```

En lugar de:
```xml
</ref-list>
<fn-group>
                     <fn fn-type="supplementary-material" id="fn2">
                           <p>Se puede consultar material adicional a este artículo en su versión electrónica disponible en doi:10.1016/j.rcreu.2016.12.005</p>
                     </fn>
               </fn-group>
         </back>
   </article>
```

Nota: Este erro é apresentado pelo validador de DTD Java mas o do Packtools, no entanto, o erro aparece no Style Checker. Aparentemente não funciona a validação de DTD com packtools no Windows.

[v24n2a04.docx](https://github.com/scieloorg/PC-Programs/files/1447190/v24n2a04.docx)
[0121-8123-rcre-24-02-79.xml.zip](https://github.com/scieloorg/PC-Programs/files/1447195/0121-8123-rcre-24-02-79.xml.zip)

**Comment by javani** [comment]
@robertatakenaka o problema foi corrigido quando a nota é marcada apenas com fn.
