### ISSUE TITLE
Validação para page-counts em Publicação Contínua

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#2796]
Referente ao email:

Pessoal, boa tarde.

Quando houver uma revista Publicação Contínua com informação de quantidade de páginas em page-counts diferente de 1, cobrem a correção para que esta tag não seja mais incluída uma vez que ela não é obrigatória.

Vejam que pela JATS este dado é considerado quando a revista é impressa:(e portanto terá fpage e lpage não elocation.

Page Count
Total number of pages in a work in print; by convention, each page or partial page is counted as one. **Electronic-only works do not traditionally have page counts.
https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/page-count.html

Desta forma agimos conforme descreve a **JATS e não deixamos o XML "sujo". OK.

**Comment by robertatakenaka** [comment]
resolvido, verificado por @cinthia-vieira
