### ISSUE TITLE
 [scielo.org] instalação/ Pré-requisitos - pt

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2802]
Pré-requisitos*

Mudar de: 

Os pré-requisitos são procedimentos que já devem ter sido executados antes da instalação de SciELO PC Programs.
Uma vez que os pré-requisitos estão sendo atendidos, não é necessário executar os pré-requisitos cada vez que se instala SciELO PC Programs.

Para: 

Os pré-requisitos são procedimentos que devem ser executados antes da instalação de SciELO PC Programs.
Uma vez cumpridos os requisitos, não é necessário executá-los novamente ou todas as vezes que o SciELO PC Programs for instalado / atualizado.

**Comment by javani** [comment]
Ok na página
