### ISSUE TITLE
[scielo.org] instalação/ Verificar os pré-requisitos - pt

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2803]
Verificar os pré-requisitos*

Mudar de: 

Somente para os programas de gestão de coleção, que devem estar instalado em um servidor local.

Para:

Somente para os programas de gestão de coleção, que devem estar instalados em um servidor local. 
_________ 

Traduzir "Warning"

**Comment by javani** [comment]
Ticket corrigido
