### ISSUE TITLE
[scielo.org] instalação/ verificar a instalação de Python + pip - pt

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2804]
Verificar a instalação de Python + pip*

Iniciar as duas notas com letra maíuscula, inserir ponto final nas frases e mudar "Note" para "Nota". 
_______________

No passo 7, mudar de: 

Caso o resultado não seja o esperado, reinstalar Python.

para: 
Caso o resultado não seja o esperado, repita as instruções para instalar Python e pip.

**Comment by javani** [comment]
Ticket corrigido
