### ISSUE TITLE
[scielo.org] instalação/ Verificar a instalação de Pillow - pt

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2805]
Iniciar a nota com letra maíuscula, inserir ponto final na frase e mudar "Note" para "Nota".

de: 
Note
ao executar este comando a versão de python não necessariamente tem que ser igual a da imagem

para: 
Nota
Ao executar este comando a versão de python não necessariamente tem que ser igual a da imagem.

**Comment by javani** [comment]
Ticket corrigido
