### ISSUE TITLE
[scielo.org] instalação/ Verificar a instalação Java - pt

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2806]
Iniciar a nota com letra maiúscula, inserir ponto final na frase e mudar "Note" para "Nota".

De: 
ao executar este comando a versão de java não necessariamente tem que ser igual a da imagem

para: 

Ao executar este comando a versão de java não necessariamente tem que ser igual a da imagem.

**Comment by javani** [comment]
Ticket corrigido
