### ISSUE TITLE
[scielo.org] instalação/ Instalar os pré-requisitos - pt

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2807]
O subitem "Add aplicação no PATH" está em inglês. 

Mudar de: 

Use a shortcut to open that window is: Windows + Pause Break key.
Or click on Computer with right button of the mouse.
Then click on Properties.
Computer System Configuration
Click on Advanced Settings.
Then click on Environment Variables.
Find Path variable in the list.
Select Path, then click on Edit button.

Para: 

Use um atalho para abrir esta janela:  Windows + Pause Break.
Ou clique em Computador com o botão direito do mouse. 
Em seguida, clique em Propriedades.
Configuração do Sistema de Computador
Clique em Configurações avançadas.
E então, clique em Variáveis de Ambiente. 
Localize o caminho da variável na lista. 
Selecione Path e clique no botão Editar.

**Comment by javani** [comment]
Ticket corrigido
