### ISSUE TITLE
[scielo.org] instalação/ Download - pt 

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2808]
Mudar "note" para "nota" 
________

Mudar de: 

Não há mais novos desenvolvimento para os programas relacionados com MArkup SGML, no entanto, eles podem ser instalados com o instalador que está em xml_markup.

Para: 

Não há mais novos desenvolvimentos para os programas relacionados com o Markup SGML, no entanto, eles podem ser instalados com o instalador que está em xml_markup.

**Comment by javani** [comment]
Ticket corrigido
