### ISSUE TITLE
[DOCS.SCIELO] Sugestões de correção na documentação PC-Programs [PT/ES]

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2809]
## Documentação em Português

[Home](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/index_pt.html): correção de título:
de `Benvindo à documentação de SciELO PC Programs!` para `Bem-vindo à documentação de SciELO PC Programs!` 

[Download](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_installation_download.html): correção de texto em nota:
de `Não há mais novos desenvolvimento para os programas relacionados com MArkup SGML, no entanto, eles podem ser instalados com o instalador que está em xml_markup.` para `Não há mais novos desenvolvimento para os programas relacionados com Markup SGML, no entanto, eles podem ser instalados com o instalador que está em xml_markup.`

[Como instalar - Markup](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_installation_configure.html#markup): atualização de tradução
Traduzir os itens 1 e 2 do item **5. Selecionar**

[Como instalar - PC-Programs Completo](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_installation_configure.html#scielo-pc-programs-completo-title-manager-converter-markup-xpm-etc): atualização de tradução
Traduzir os itens Title Manager, Converter e XML SciELO do item **5. Selecionar**

[Como instalar - Title Manager e Converter](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_installation_configure.html#title-manager-e-converter): atualização de tradução
Traduzir o texto do item **Configurar a variável de ambiente:**

[Como instalar - Menu de Aplicação](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_installation_configure.html#menu-de-aplicacao): atualização de tradução
Traduzir o texto da seção **Menu de Aplicação**

## Documentação em Espanhol

[Requisitos - Add aplicación en el PATH](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/es_installation_requirements.html#add-aplicacion-en-el-path): atualização de tradução
[SUGESTÃO] Mudar título de `Add aplicación en el PATH` para `Incluir aplicación en el PATH` 
Traduzir texto do item Add applicación en el PATH

[Como instalar - Markup](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/es_installation_configure.html#markup): atualização de tradução
Traduzir os itens 1 e 2 do item **5. Selecionar**

[Como instalar - PC-Programs Completo](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/es_installation_configure.html#scielo-pc-programs-completo-title-manager-converter-markup-xpm-etc): atualização de tradução
Traduzir os itens Title Manager, Converter e XML SciELO do item **5. Selecionar**

[Como instalar - Title Manager y Converter](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/es_installation_configure.html#title-manager-y-converter): atualização de tradução
Traduzir o texto do item **Configurar la variable de ambiente BAP:**

[Como instalar - Menú de aplicación](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/es_installation_configure.html#menu-de-aplicacion): atualização de tradução
Traduzir o texto da seção **Menú de aplicación**

**Comment by javani** [comment]
Ticket corrigido
