### ISSUE TITLE
[scielo.org] instalação/ Como instalar/ SciELO PC Programs Completo: Title Manager, Converter, Markup, XPM etc - pt

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2811]
Traduzir imagem.

Traduzir item 5:

Title Manager: program to manage journals and issues databases
Converter: program to load the marked documents into the database
XML SciELO: (opcional) program to create XML format for PubMed

**Comment by javani** [comment]
Ticket corrigido
