### ISSUE TITLE
[scielo.org] instalação/ Como instalar/ Title Manager e Converter

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2812]
Traduzir: 

Set OS23470a to the environment variable BAP, by accessing the Windows menu: Control Panel -> Performance and Maintenance -> System -> Advanced Settings -> Environment variables.

Check if the variable already exists. If it does not, click New and enter the value.

**Comment by javani** [comment]
Ticket corrigido
