### ISSUE TITLE
[scielo.org] instalação/ Como configurar/XML Converter - pt

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2813]
Em Validação de tabelas e fórmulas:

mudar de: 
Para alterar este nível, editar o arquivo que correspond a c:\scielo\bin\scielo_collection.ini:

para: 
Para alterar este nível, editar o arquivo correspondente c:\scielo\bin\scielo_collection.ini:

**Comment by javani** [comment]
Ticket corrigido
