### ISSUE TITLE
[scielo.org] Instalación/ Requisitos - es

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2818]
mudar de: Solamente para los programas de gestión de colección, que deben estar instalador en un servidor local.

para: Solamente para los programas de gestión de colección, que deben estar instalados en un servidor local.
___________

mudar de: 3. Verificar si el comando presenta la versión de Python. Por exemplo:

para: 3. Verificar si el comando presenta la versión de Python. Por ejemplo:
__________

mudar de: 6. Verificar si el comando presenta la versión del pip. Por exemplo:

para: 6. Verificar si el comando presenta la versión del pip. Por ejemplo:
____________

traduzir subitem Add aplicación en el PATH
____________

Traduzir "Warning" 
Traduzir "Note", iniciar as notas com letra maiúscula e inserir ponto final.

**Comment by javani** [comment]
Ticket corrigido
