### ISSUE TITLE
[scielo.org] Instalación/ Cómo instalar - es

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2819]
Traduzir imagens para espanhol
_____________

Traduzir itens: 

5. Seleccionar los programas:

Title Manager: program to manage journals and issues databases
Converter: program to load the marked documents into the database
XML SciELO: (opcional) program to create XML format for PubMed

e 5. Seleccionar:

Markup: program to identify the bibliographic elements in the articles/texts
Markup - Automata files (opcionalmente): examples of files for automatic markup

**Comment by javani** [comment]
Ticket corrigido.
