### ISSUE TITLE
[scielo.org] Instalación/ Cómo configurar - es

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#2820]
Traduzir: 

Set OS23470a to the environment variable BAP, by acccedeng the Windows menu: Control Panel -> Performance and Maintenance -> System -> Advanced Settings -> Environment variables.

Check if the variable already exists. If it does not, click New and enter the value.
_____________

em: "off es para que XML Converter no exija los elementos codificados" , inserir ponto final.
____________

Traduzir: 
Sometimes the menu of the application will be created only for the Administrator user.
In this case, copy the SciELO folder to All Users folder, to all users have the menu.

**Comment by javani** [comment]
Documentação corrigida
