### ISSUE TITLE
[xpm] Versão 4.0.094 do XPM não exclui arquivos das traduções ao gerar pacote PMC

### ISSUE THREAD

**Issue by JoyceRaphaela** [scieloorg/PC-Programs#2822]
Tentei gerar o pacote da RLAE para o PMC através da versão 4.0.094 do XPM, no entanto mesmo selecionando a opção de gerar pacote PMC os arquivos referentes as traduções (pdf's e figuras das traduções) são mantidos na pasta pmc_package. Apenas no xml são retirados os sub-articles.

Caminho da pasta gerada: V:\SciELO\serial\rlae\v25\lote1717\Nova pasta\0104-1169-rlae-25-1717_xpm\pmc_package

**Comment by alexxpsilva** [comment]
Aproveitando o ticket...

observei agora que quando há imagens em .jpeg e .tif no pacote, na pasta do PMC está salvando ambas, anteriormente só salvava a imagem .tif
