### ISSUE TITLE
[XPM/XC] Incluir warning quando artigo do tipo "correction" apresentar contrib

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2831]
Artigos de correção não possuem autoria, mas há casos em que o XML vem com dados de contribuição preenchidos com os dados de autoria do artigo que será corrigido. Apresentar alerta - artigos do tipo errata não possuem autoria.

**Comment by robertatakenaka** [comment]
@javani : vc tem um exemplo, um arquivo?
