### ISSUE TITLE
[mkp xml] Ao gerar o XML as imagens que estão no src não foram consideradas

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2832]
[02_35075.docx](https://github.com/scieloorg/PC-Programs/files/1492188/02_35075.docx)
[src.zip](https://github.com/scieloorg/PC-Programs/files/1492189/src.zip)

pacote gerado:
[scielo_package.zip](https://github.com/scieloorg/PC-Programs/files/1492195/scielo_package.zip)
![captura de tela 2017-11-21 as 14 47 08](https://user-images.githubusercontent.com/505143/33085123-e95a8734-ceca-11e7-9d4f-fb6a770436d9.png)

```xml
<graphic xlink:href="1807-8621-asagr-40-01-11-gf1.jpg"/>
```

Nota: aparentemente o markup desconsiderou por serem de extensão .png.

**Comment by cinthia-vieira** [comment]
O Markup considera as imagens somente se elas seguem o seguinte padrão de nomeação:

Nome do doc- + **gf** + identificação da imagem **sem** zero + extensão.

Se o nome do arquivo imagem estiver com qualquer nomeação divergente desta, o markup utilizará essas imagens para realizar a marcação XML. 

Independente do nome dos arquivos na pasta src, o Markup cria novas imagens baseadas nas imagens contidas no arquivo doc, gerando dois grupos de imagens idênticas com nomes distintos (dentro da pasta src).
![image](https://user-images.githubusercontent.com/27728729/36496956-a5ca8adc-1718-11e8-9bb0-08ab4ec2f2d0.png)

Entretanto, este padrão de nomeação utilizado é diferente do indicado na documentação do Markup em **SciELO Docs**, [como podemos ver](http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_how_to_generate_xml-prepara.html#figura). Isso causa conflitos e dificuldades durante a preparação dos arquivos para marcação.

**Comment by robertatakenaka** [comment]
@cinthia-vieira : Originalmente quais são as imagens que estavam em src?

**Comment by cinthia-vieira** [comment]
Todo o conjunto dentro do retrângulo amarelo.

![image](https://user-images.githubusercontent.com/27728729/36498015-d5275762-171b-11e8-9017-569bd5f9d039.png)

**Comment by robertatakenaka** [comment]
@cinthia-vieira : Segundo a documentação:


>         Mesmo nome do arquivo .doc (sem a extensão) + f + identificação da figura + extensão do arquivo de imagem; ou
>         Mesmo nome do arquivo .doc (sem a extensão) + fig + identificação da figura + extensão do arquivo de imagem.


apendice-original2.doc deveria ter as imagens em src seguindo o padrão:

apendice-original2f01.jpg ou apendice-original2fig1.jpg

O padrão **-g**f é o que fica no scielo_package.

Por favor, faça um zip com  pacote de .doc + src e anexe aqui. Quero fazer uns testes.

**Comment by cinthia-vieira** [comment]
Quando utilizado o padrão f ou fig, o Markup ignora a imagem e utiliza essas imagens criadas pra converter o XML. Os arquivos grifados são os utilizados no `<xref>` do documento XML gerado.
![image](https://user-images.githubusercontent.com/27728729/36499031-d5db13e4-171e-11e8-91fa-0703fa2f1991.png)

Troquei as imagens em src pra essa padrão pra visualização ficar mais fácil. Estou anexando um pacote com as imagens em src (originais e geradas pelo markup) + arquivo doc + XML gerado. As imagens genéricas são as que estavam na pasta src, e as geradas pelo Markup são os gráficos.
[src.zip](https://github.com/scieloorg/PC-Programs/files/1745299/src.zip)

**Comment by cinthia-vieira** [comment]
Conversão e geração das imagens na pasta src corrigida; entretanto, as imagens são geradas com a extensão **.jpeg** e o XPM não as mostra na validação, mostrando apenas as imagens com extensão **.jpg**
