### ISSUE TITLE
[xc] Corrigir a identificação de seção

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2845]
```xml
<subj-group subj-group-type="heading">
                                        <subject>Nota</subject>
                                        <subj-group>
                                                <subject>Dossiê: Benzeno em Postos de Combustíveis</subject>
                                        </subj-group>
                                </subj-group>
```

O XC está identificando errado o seccode porque  estava considerando todos os subject,

<subject>Nota</subject>
<subject>Dossiê: Benzeno em Postos de Combustíveis</subject>

como título seção de sumário, quando deveria somente considerar o

```xml
<subj-group subj-group-type="heading">
                                        <subject>Nota</subject>
                                        
                                </subj-group>
```

 Somente considerar como seção de fascículo: 

`subj-group[@subj-group-type='heading']/subject`

**Comment by cinthia-vieira** [comment]
Teste OK, as seções aparecem corretamente no sumário.

Segue link em homolog.xml para verificação: [http://homolog.xml.scielo.br/scielo.php?script=sci_issuetoc&pid=0102-797220170001&lng=en&nrm=iso](http://homolog.xml.scielo.br/scielo.php?script=sci_issuetoc&pid=0102-797220170001&lng=en&nrm=iso)
