### ISSUE TITLE
[Mkp94r3 - Melhoria] Possibilitar a coleta das equações codificadas da pasta src

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#2849]
Assim como pode ser feito com as tabelas em XHTML, possibilitar a coleta das equações codificadas da src desde que codificadas em mathml e com a nomeação específica. Exemplo de um XML válido: 

```xml

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1 plus MathML 2.0//EN" "http://www.w3.org/TR/MathML2/dtd/xhtml-math11-f.dtd" [<!ENTITY mathml 'http://www.w3.org/1998/Math/MathML'>]>
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Untitled2</title>
<!-- MathML created with MathCast Equation Editor version 0.92 -->
</head>
<body>
  <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">
  <mrow>
    <msub>
      <mi>β</mi>
      <mn>1</mn>
    </msub>
    <mroot>
      <mn>23</mn>
      <mo>=</mo>
    </mroot>
    <mo>∑</mo>
    <mn>2</mn>
  </mrow>
</math>
</body>
</html>
```

**Comment by cinthia-vieira** [comment]
Não está puxando a equação corretamente.

Quando utilizada junto de uma equação MathML, não é considerada; quando utilizada sozinha, gera uma tag <alternatives> vazia

**Comment by robertatakenaka** [comment]
@cinthia-vieira : anexe o arquivo que está usando e mostre como está indicando dentro do arquivo marcado

**Comment by cinthia-vieira** [comment]
Marquei desta forma: 
![image](https://user-images.githubusercontent.com/27728729/36809499-dfe468da-1ca6-11e8-845c-afb3f65deca6.png)

Em anexo o doc com a marcação e o documento xhtml com a equação codificada em MathML
[eq_xhtml.zip](https://github.com/scieloorg/PC-Programs/files/1768596/eq_xhtml.zip)

**Comment by robertatakenaka** [comment]
@cinthia-vieira experimentou deixar somente o xhtml?

**Comment by cinthia-vieira** [comment]
Ainda gerando a tag `<alternatives/>` vazia na versão 40095_20180309

**Comment by cinthia-vieira** [comment]
As equações estão sendo recuperadas com sucesso para o documento XML; ticket resolvido
