### ISSUE TITLE
[XPM] Problema ao gerar aquivos PMC

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2859]
Estou tentando o pacote PMC na versão 94 release 29-09-17. e aparece o erro abaixo e não prossegue.

![rimtsp_xpm](https://user-images.githubusercontent.com/15328777/34211329-dbd27f88-e57f-11e7-9ff1-37d99f26f7e6.png)

Tentei passar na versão 94 relase 29-09-17 R6 e os artigos são gerados, porém percebi que em contrib-group e nas referências não estão sendo gerados conforme o padrão.

Exemplo.

Correto: 
```<contrib contrib-type="author">```
               
```<name name-style="western">```

Errado:  
```<contrib contrib-type="author">```

O mesmo ocorre nas referências.

Usei como teste o pacote da RIMTSP lote 1217 disponível em: V:\SciELO\serial\rimtsp\v59\0036-4665-rimtsp-1217\1678-9946-rimtsp-rpass-59-1217

**Comment by alexxpsilva** [comment]
@robertatakenaka o erro ocorre somente em contrib-group.

**Comment by robertatakenaka** [comment]
@alexxpsilva : western não é necessário
https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/pmc-jats1-sample1.xml

**Comment by alexxpsilva** [comment]
@robertatakenaka ok, não sabia.

Sendo assim pode fechar o ticket por gentileza.
