### ISSUE TITLE
[PubMed] Desconsiderar suffix na geração de arquivos para envio PubMed

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#2862]
O PubMed identifica o suffix em posição errada, diferente da usada no site SciELO e nas normas. Neste caso para criação de arquivos para PubMed, quando tiver a tag suffix ela deve ser excluída e seu conteúdo deve ser incluído como último item da tag LastName. Só nesta semana tivemos que corrigir manualmente 4 solicitações. 

Mais detalhes sobre o problema pode ser visto no email com título: Problem with tag identification | <suffix>

Como está hoje:

```xml
<Author>
				<FirstName>Marcos</FirstName>
				<LastName>Silva</LastName>
                                <Suffix>Junior</Suffix>
				<Affiliation>Department of Ultrasonography, Tianjin Medical University General Hospital, Tianjin, China</Affiliation>
			</Author>
```

Como deve ser:

```xml
<Author>
				<FirstName>Marcos</FirstName>
				<LastName>Silva Junior</LastName>                              
				<Affiliation>Department of Ultrasonography, Tianjin Medical University General Hospital, Tianjin, China</Affiliation>
			</Author>
```

PubMed informou:

> The ``<suffix>`` tag is used to add an author suffix like Jr., Sr., IV.  The suffix will display after the entire author name, not in the middle. (e.g., Smith JC Jr.) To achieve the display that you are looking for, please include both parts of the surname in the ``<LastName>`` tag.
> 
> ```<FirstName>Pedro Tadao</FirstName>
> 
> <LastName>Hamamoto Filho</LastName>
> ```
>  
> 
> This XML will display as Hamamoto Filho, PT.
> 
>  
> 
> If you have any further questions or concerns, please contact us at publisher@ncbi.nlm.nih.gov.

**Comment by robertatakenaka** [comment]
@RPostalli : poderemos ter um problema... Caso o autor seja americano vai acabar seguindo a regra "brasileira" e o XML para o PubMed ficará:

```<LastName>Smith Jr.</LastName>```

E será apresentado no PubMed como Smith Jr. JC.

**Comment by jenniferamato** [comment]
@robertatakenaka , teste realizado, está gerando corretamente.
