### ISSUE TITLE
[XC] Bloquear os documentos que não estiverem de acordo com os critérios mencionados abaixo

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2884]
A partir de 2018, somente serão indexados, publicados e incluídos nas métricas de desempenho dos periódicos da Coleção SciELO Brasil, documentos que apresentem conteúdo científico relevante, com autoria e afiliação institucional dos autores,  título próprio diferente do título da seção, citações e referências bibliográficas. 

http://www.scielo.br/avaliacao/Criterios_SciELO_Brasil_versao_revisada_atualizada_outubro_20171206.pdf

**Comment by cinthia-vieira** [comment]
O XC não bloqueia os documentos, apenas deixa a mensagem de erro de critérios, subindo o pacote normalmente em Homolog:

http://homolog.xml.scielo.br/reports/aval/v23n1/xc_2018-03-26_140507.html
(relatório aprovado)
