### ISSUE TITLE
mime-subtype="replace"  mimetype="replacea3_24_28006" 

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2893]
```xml
<inline-supplementary-material xlink:href="0103-507X-rbti-26-02-0130-suppl1.pdf" mimetype="application" mime-subtype="pdf">Material Suplementar</inline-supplementary-material>
```

Sin embargo, en mi archivo las etiquetas "mime-subtype" y "mimetype" difieren del ejemplo:

[
```xml
<inline-supplementary-material · mime-subtype="replace" · mimetype="replacea3_24_28006" · xlink:href="2448-8321-ib-30-s70-24-s006">Material · Suplementario</inline-supplementary-material>
```

]

[Arquivo Comprimido.zip](https://github.com/scieloorg/PC-Programs/files/1731894/Arquivo.Comprimido.zip)

**Comment by cinthia-vieira** [comment]
O XML não é gerado, apresentando o erro a seguir. O documento utilizado foi o mesmo anexado no ticket.
![image](https://user-images.githubusercontent.com/27728729/36607428-62ba60a8-18a5-11e8-83f7-817e58b7c72f.png)

**Comment by cinthia-vieira** [comment]
Roberta, a tag gerada é a seguinte:

`<inline-supplementary-material   xlink:href="2448-8321-ib-30-s70-24-s006">Material Suplementario</inline-supplementary-material>`

Segue o XML anexo
[2448-8321-ib-30-s70-24.zip](https://github.com/scieloorg/PC-Programs/files/1752703/2448-8321-ib-30-s70-24.zip)
