### ISSUE TITLE
[Markup e XPM 95] Tag institid gerando com erro

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2902]
O xml gerado está na estrutura esperada (de acordo com o ticket #2867 ) porém apresenta erro referente a tag de institution -original.
<img width="539" alt="captura de tela 2018-02-22 as 15 13 10" src="https://user-images.githubusercontent.com/505143/36556157-fb77a012-17e2-11e8-9199-328f8f3eb9af.png">

```xml

<aff id="aff2">
				<label>II</label>
				<institution-wrap>
					<institution-id institution-id-type="isni">0000 0004 1937 0722</institution-id>
					<institution content-type="original"> Doutora em Educação pela Universidade de
						São Paulo (USP), São Paulo, São Paulo, Brasil.0000 0004 1937
						0722</institution>
					<institution content-type="normalized">Universidade de São Paulo</institution>
					<institution content-type="orgname">Universidade de São Paulo
						(USP)</institution>
				</institution-wrap>
				<addr-line>
					<city>São Paulo</city>
					<state>São Paulo</state>
				</addr-line>
				<country country="BR">Brazil</country>
			</aff>
```

Apresenta o erro abaixo:

![institd_aff](https://user-images.githubusercontent.com/15328777/36497986-b9b0151e-171b-11e8-871e-cdde1aef81d6.png)

Se retirar o institution-original de institution-wrap conforme abaixo, o xml é válido.

```xml
<aff id="aff2">
				<label>II</label>
				<institution content-type="original"> Doutora em Educação pela Universidade de
					São Paulo (USP), São Paulo, São Paulo, Brasil.0000 0004 1937
					0722</institution>
				<institution-wrap>
					<institution-id institution-id-type="isni">0000 0004 1937 0722</institution-id>
					<institution content-type="normalized">Universidade de São Paulo</institution>
					<institution content-type="orgname">Universidade de São Paulo
						(USP)</institution>
				</institution-wrap>
				<addr-line>
					<city>São Paulo</city>
					<state>São Paulo</state>
				</addr-line>
				<country country="BR">Brazil</country>
			</aff>
```

**Comment by robertatakenaka** [comment]
@alexxpsilva : Acho que descobri o significado deste erro.
O Style Checker espera que aff tenha 1 institution (original). 
Enquanto não foi definido como representar institution-wrap, institution-id, não será possível resolver este ticket.

Por favor, anexe o .doc.

**Comment by alexxpsilva** [comment]
@robertatakenaka anexei o documento word e o XML gerado.
[rbeped-institid.zip](https://github.com/scieloorg/PC-Programs/files/1749004/rbeped-institid.zip)

**Comment by robertatakenaka** [comment]
https://github.com/scieloorg/scielo_publishing_schema/issues/603

**Comment by cinthia-vieira** [comment]
Em Markup, validação não considera institid como um erro e a tag é gerada corretamente.

**Comment by alexxpsilva** [comment]
No XPM a validação também está ok.
