### ISSUE TITLE
[mkp] Erro ao marcar 1 autor com authors.

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2911]
https://drive.google.com/file/d/1nm82V0spngZjvILAUVuPttZCH8V6gQ4s/view
[37n12a02.docx](https://github.com/scieloorg/PC-Programs/files/1758998/37n12a02.docx)

**Comment by cinthia-vieira** [comment]
Tag `*[authors]` não marca mais todo o conteúdo da referência até o autor seguinte, quando o autor é o mesmo. Funcionando corretamente
