### ISSUE TITLE
[mkp] fngrp

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#2912]
Caso 1: Quando não inseri [fngrp], indicou erro. 

![captura de tela 2018-02-26 as 13 47 26](https://user-images.githubusercontent.com/505143/36683153-9b5e5d9e-1afb-11e8-8942-0a98f88ecb0a.png)
![captura de tela 2018-02-26 as 13 46 42](https://user-images.githubusercontent.com/505143/36683160-9f2732d4-1afb-11e8-9f54-d0f5a7677272.png)

_______________________________________________________________

Caso 2. Quando inseri [fngrp] no texto principal, onde havia só um tipo de nota, não deu erro. 

![captura de tela 2018-02-26 as 13 51 33](https://user-images.githubusercontent.com/505143/36683486-76681524-1afc-11e8-9201-1ca55e26ee70.png)
![captura de tela 2018-02-26 as 13 51 49](https://user-images.githubusercontent.com/505143/36683502-7cc0bd40-1afc-11e8-9d7c-0a3db2409f0f.png)

_______________________________________________________________
Caso 3. Com sub-doc, quando não havia  [fngrp], não deu erro, mas não inseriu notas no xml
![captura de tela 2018-02-26 as 14 05 49](https://user-images.githubusercontent.com/505143/36684117-2f071872-1afe-11e8-814e-f499c2d9c9bd.png)
![captura de tela 2018-02-26 as 14 05 18](https://user-images.githubusercontent.com/505143/36684081-1819beee-1afe-11e8-8d02-2211fb917221.png)

_______________________________________________________________
Caso 4. Quando inseri fn-group onde havia notas de "author" também "other", indicou erro. Ou seja, não inseriu o fn-group no xml
![captura de tela 2018-02-26 as 14 12 45](https://user-images.githubusercontent.com/505143/36684446-258b93a8-1aff-11e8-800e-af0fc881f315.png)
![captura de tela 2018-02-26 as 14 14 04](https://user-images.githubusercontent.com/505143/36684509-5275c956-1aff-11e8-967f-7bdd4b773c9d.png)

_______________________________________________________________

Caso 5. Quando tinha sub-doc, mesmo usando [fngrp] em cada nota, indicou erro. -- fn-5
Aqui, não acusou erro. Entretanto, a [fn] que fica em <back> não foi convertida no subdoc, só no doc. As <author-notes> foram convertidas corretamente. O Markup nem considera a nota de rodapé em subdoc, pois marquei as notas de rodapé com o mesmo id no original e tradução, e o Markup não acusou erro.

![captura de tela 2018-02-26 as 14 17 35](https://user-images.githubusercontent.com/505143/36684660-d269c090-1aff-11e8-90b3-17513e809b84.png)
![captura de tela 2018-02-26 as 14 20 47](https://user-images.githubusercontent.com/505143/36684802-42639fc4-1b00-11e8-9be4-d80a052f5c6b.png)

**Comment by robertatakenaka** [comment]
Quando os tipos são de notas relacionadas aos autores, o fn é criado dentro de ```<author-notes>```
(caso 4 e 5).

**Comment by jbosco1951** [comment]
Bom dia,

Com tantos recursos de buscas e de cruzamentos de dados por meio eletrônico, acho que é uma grande perda de recursos (tempo e dinheiro) na marcação de tantos itens em cada bibliografia. Por exemplo, qual a necessidade de se inserir dados de paginação em uma bibliografia?  Acho que a inserção de título , primeiro autor e ano, é o suficiente para identificar e forma precisa, qualquer bibliografia. 
Att
João Bosco

**Comment by cinthia-vieira** [comment]
Roberta, encontrei mais um erro em [fngrp]:

Quando marcamos mais de uma [fn] com a tag [fngrp], o Markup não gera as notas dentro da tag <fn-group>. Com uma nota dentro de [fngrp], ou com várias [fn] marcadas sem [fngrp], o XML é gerado corretamente.
[notas.docx](https://github.com/scieloorg/PC-Programs/files/1790396/resenha01.docx)

**Comment by cinthia-vieira** [comment]
Sim, a este trecho!

A fngrp com duas notas gera sem a tag <fn-group>
A nota fora de fngrp é gerada em uma <fn-group> sozinha
E a fngrp com uma nota só também gera corretamente.

**Comment by RPostalli** [comment]
@cinthia-vieira informou que o erro continua.

**Comment by cinthia-vieira** [comment]
ainda gera grupos de notas de rodapé com erro, como o erro anteriormente reportado

**Comment by cinthia-vieira** [comment]
Em um segundo teste, as notas de rodapé dentro de [fngrp] estão sendo geradas corretamente. Ticket pode ser fechado novamente.
