### ISSUE TITLE
[mkp] Não valida/gera XML em SPS 1.8

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2917]
O Markup ainda não está validando a SPS 1.8, gerando o seguinte erro quando utilizamos esta versão para preencher os dados do artigo:

![image](https://user-images.githubusercontent.com/27728729/36806882-3aba2fbc-1ca0-11e8-978e-8ae8e1ebfe0d.png)

Segue anexo o documento utilizado para gerar o XML
[rolling-pass-a01.zip](https://github.com/scieloorg/PC-Programs/files/1768457/rolling-pass-a01.zip)

**Comment by robertatakenaka** [comment]
#2921
