### ISSUE TITLE
[mkp] Normalização de orgname não considera aspas

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2920]
A normalização de orgname, ao gerar os arquivos XML, não está considerando aspas no nome normalizado recuperado

[normalização.zip](https://github.com/scieloorg/PC-Programs/files/1774869/normalizacao.zip)

<img width="640" alt="orgname2" src="https://user-images.githubusercontent.com/505143/37033342-70c59bea-2124-11e8-84d3-41c6ece10037.PNG">
<img width="640" alt="orgname" src="https://user-images.githubusercontent.com/505143/37033343-70f81fc0-2124-11e8-8f2c-02c80643144a.PNG">

**Comment by cinthia-vieira** [comment]
Funcionando corretamente e gerando orgname com aspas no XML:

![image](https://user-images.githubusercontent.com/27728729/37400864-08a7c64a-2765-11e8-86fb-372e6e42df49.png)

**Comment by robertatakenaka** [comment]
@cinthia-vieira : eu removi as aspas que ficam dentro do norgname de propósito pois senão aspas dentro de aspas conflitam com as aspas do atributo.

**Comment by cinthia-vieira** [comment]
Ah, então ok! Vou colocar como OK de volta na planilha!
