### ISSUE TITLE
[XPM 95] Normalized ainda é validada

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2922]
Quando inserido um dado não normalizado, ou a tag está ausente o XPM acusa erro/sugestão como se fosse um dos 5 itens obrigatórios para publicação, o que não é o caso.

![xmp95_normalized](https://user-images.githubusercontent.com/15328777/36996222-fcef8e5e-2094-11e8-9ac5-45227c1c43ec.png)

Já quando a tag está ausente, porém a instituição é normalizada, ele pede para usar o nome normalizado.

![xmp95_normalized2](https://user-images.githubusercontent.com/15328777/36996233-06b136d6-2095-11e8-977e-b02d4bb728a2.png)

Relacionado ao #2887

**Comment by robertatakenaka** [comment]
@alexxpsilva : a mudança que vou fazer é que se ausente o normalized, não haverá nenhuma mensagem, mas se for informado o normalized, a mensagem de sugestão continuará, mas não será um erro, nem warning.

**Comment by RPostalli** [comment]
@robertatakenaka foi combinado na reunião SPS de 26/02 que não faríamos mais validação desta tag, está parte informada pelo Alex "Já quando a tag está ausente, porém a instituição é normalizada, ele pede para usar o nome normalizado." não pode ocorrer, já que o intuito é desestimular o uso.
Comentei sobre a cobrança quando o normalized está incorreto e também foi dito que deveria ser ignorado.Temos que retirar as validações totalmente.
