### ISSUE TITLE
[XPM 95] Article-type "correction" e "retraction"

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2924]
Exige autoria e referências para article-type dos tipos "correction" e "retraction"

![xpm95_errata](https://user-images.githubusercontent.com/15328777/37035920-d180cf56-212c-11e8-895f-ad52d3e4a0f1.png)

**Comment by cinthia-vieira** [comment]
Também ocorre no validador de conteúdo do Markup

![image](https://user-images.githubusercontent.com/27728729/37036256-db1ecf4e-212d-11e8-9864-d21d3b0799b9.png)

**Comment by cinthia-vieira** [comment]
ainda exige referências tanto pra errata quanto pra retratação

![image](https://user-images.githubusercontent.com/27728729/37399626-eedeafc0-2760-11e8-8aea-27a1c274f6f9.png)
![image](https://user-images.githubusercontent.com/27728729/37399677-1fabdb14-2761-11e8-8962-afad09b15090.png)

**Comment by alexxpsilva** [comment]
No XPM também continua exigindo referências para Errata e Retratação.

**Comment by robertatakenaka** [comment]
@cinthia-vieira : testar novamente pois o XC não estava atualizado

**Comment by cinthia-vieira** [comment]
Ainda exige as referências:

http://homolog.xml.scielo.br/reports/cta/v38n1/xc_2018-03-28_084424.html (artigo 181)
