### ISSUE TITLE
[MKP] Markup não puxa tabelas em HTML

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2926]
O Markup não está considerando as tabelas em HTML na marcação do documento, gerando tabelas vazias.

Segue em anexo o .doc marcado, o XML gerado e a tabela em html utilizada (é uma tabela para os três idiomas, feita somente para teste). Os demais erros de marcação são propositais.
[PCTrad01.zip](https://github.com/scieloorg/PC-Programs/files/1785895/PCTrad01.zip)

Além disso, ao tentar acessar a pasta ARTIGO_arquivos, o programa encontra um problema de autorização e para a geração do XML:
![image](https://user-images.githubusercontent.com/27728729/37046201-83ca0a74-2146-11e8-8539-9d77aa02f6a2.png)

**Comment by alexxpsilva** [comment]
@robertatakenaka ao realizar o teste do ticket #2902 observei que o XML gerou válido, porém o relatório do XPM dentro do markup aparece a mensagem de "Processing" e não gera o relatório.

Executei por linha de comando e aparece o mesmo "erro 13" da @cinthia-vieira 

![markup95_error13](https://user-images.githubusercontent.com/15328777/37050365-6cba2286-2152-11e8-91ce-f72ff8276482.png)

Validei no XPM 95 e está ok.

**Comment by robertatakenaka** [comment]
@alexxpsilva : o erro que você obteve é devido ao relatório estar aberto no Markup. Deixe o Markup apenas com o arquivo marcado aberto e tente novamente.

@cinthia-vieira : o erro que você obteve é devido a haver uma pasta dentro de src. Para resolver isso vou fazer o programa ignorar a pasta

**Comment by RPostalli** [comment]
@cinthia-vieira informou que o erro continua.

**Comment by cinthia-vieira** [comment]
ainda não puxa tabelas em HTML, não gerando a tag <table>

**Comment by robertatakenaka** [comment]
@cinthia-vieira : me mande os arquivos, e a pasta completa src zipada, mesmo com os arquivos de outro artigo, tudo mesmo

**Comment by cinthia-vieira** [comment]
[tables.zip](https://github.com/scieloorg/PC-Programs/files/1812690/tables.zip)

**Comment by cinthia-vieira** [comment]
Tabelas recuperadas com sucesso na geração dos documentos XML; ticket resolvido.
