### ISSUE TITLE
Programa esta removendo o caracter &#xA0

### ISSUE THREAD

**Issue by IsabelaGagliardi** [scieloorg/PC-Programs#2928]
Ao gerar o relatório no xml_package a equação aparece formatada corretamente, com os devidos dados separados:

![xpm_meu](https://user-images.githubusercontent.com/8876708/37051139-688ceb7e-2154-11e8-8c1f-e83c87513bb7.jpg)
Exemplo: **urban areas**
---------------------------------------------------------
Porém ao subir no homolog, essa mesma equação aparece com os dados juntos, como pode ser vista no relatório:

Relatório do homolog:
![homolog](https://user-images.githubusercontent.com/8876708/37051195-89028300-2154-11e8-9d9a-acd40adf3517.jpg)
Exemplo:  **urbanareas** 
-----------------------------------------
Segue uma parte da codificação da equação aqui citada:

````<mml:mrow>
<mml:mi>%</mml:mi>
<mml:mi>u</mml:mi>
<mml:mi>r</mml:mi>
<mml:mi>b</mml:mi>
<mml:mi>a</mml:mi>
<mml:mi>n</mml:mi>
<mml:mtext> </mml:mtext>
<mml:mi>a</mml:mi>
<mml:mi>r</mml:mi>
<mml:mi>e</mml:mi>
<mml:mi>a</mml:mi>
<mml:mi>s</mml:mi>
</mml:mrow>````

**Comment by robertatakenaka** [comment]
@IsabelaGagliardi @alexxpsilva Onde está o problema? No site ou no XPM?

**Comment by alexxpsilva** [comment]
@robertatakenaka o problema é no site.

**Comment by robertatakenaka** [comment]
identificado como obsoleto ou inválido por @cinthia-vieira
