### ISSUE TITLE
[MKP] Não gera tag "other" no XML

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2930]
Markup não está gerando a tag `<article-id pub-id-type="other">` quando o campo "order (in TOC)" é preenchido no formulário de marcação do doc.

[tag other.zip](https://github.com/scieloorg/PC-Programs/files/1786500/tag.other.zip)

**Comment by robertatakenaka** [comment]
@cinthia-vieira @RPostalli : realmente não faz porque foi decidido que o usuário não sabe o valor que deve preencher então apesar de existir no formulário não é feito a geração do other.

**Comment by RPostalli** [comment]
Ok @robertatakenaka acho melhor também. Acredito que exista instrução dessa tag na documentação do markup, @cinthia-vieira pode verificar por favor.

**Comment by cinthia-vieira** [comment]
A documentação do Markup traz as seguintes informações sobre a tag:

Preenchimento básico do campo:
>order (in TOC) | Incluir a ordem do artigo no sumário do fascículo. Deve ter, no mínimo, dois dígitos. Por exemplo, se o artigo for o primeiro do sumário, preencha este campo com “01” e assim por diante

Utilização em Ahead of Print:
http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_how_to_generate_xml-markup.html#ahead-of-print

Utilização em Publicação Contínua:
http://docs.scielo.org/projects/scielo-pc-programs/en/latest/pt_how_to_generate_xml-markup.html#publicacao-continua-rolling-pass

De forma geral, a documentação do Markup instrui o usuário a preencher o campo com os valores que usamos para subir os artigos em produção.

**Comment by RPostalli** [comment]
@cinthia-vieira obrigada, por favor abrir ticket para esta parte da documentação seja excluída, se mantermos vai causar problema. Link esse ticket com o novo que vc vai abrir.

**Comment by cinthia-vieira** [comment]
Ticket fechado via #2932
