### ISSUE TITLE
[MKP] Marcação AOP gera XML sem <pub-date>

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2933]
Ao preencher os campos "volid" e "issueno" com 00, para gerar documento AOP, o XML é gerado sem a tag <pub-date>

[AOP-sem-data.zip](https://github.com/scieloorg/PC-Programs/files/1789093/AOP-sem-data.zip)

**Comment by robertatakenaka** [comment]
@RPostalli @cinthia-vieira 

Teria que fazer o teste de preencher o ahpdate e ver se gera.
Mas se não gerar, talvez seja pelo mesmo motivo que não gera mais o other.

**Comment by cinthia-vieira** [comment]
@robertatakenaka preenchendo ahpdate funcionou. Vou fechar o ticket :)
