### ISSUE TITLE
[MKP] <role> (em [normaff]) é gerada fora de <contrib>

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2938]
Tag [role] dentro de [normaff] gera `<role>` fora de `<contrib>` no XML
[role.docx](https://github.com/scieloorg/PC-Programs/files/1790471/AOP01.docx)

**Comment by robertatakenaka** [comment]
[role] dentro de  [normaff] gerará <role> dentro de <aff>. No entanto, [role] dentro de [author] gerará ``<role>`` em ``<contrib>``.
![captura de tela 2018-03-07 as 15 58 09](https://user-images.githubusercontent.com/505143/37112169-7a05e96a-2220-11e8-9213-169745d7391c.png)

**Comment by cinthia-vieira** [comment]
Sim, a marcação a partir da tag [author] gera o XML corretamente, entretanto, utilizando a marcação dentro de [normaff], o Markup gera um XML com erro de DTD.

![image](https://user-images.githubusercontent.com/27728729/37112587-a1e3d46e-2221-11e8-978b-aee122754063.png)

![image](https://user-images.githubusercontent.com/27728729/37112804-4e653318-2222-11e8-8de2-39a83d5d401f.png)

**Comment by robertatakenaka** [comment]
@cinthia-vieira : como fica o XML utilizando role dentro de normaff?

**Comment by cinthia-vieira** [comment]
```xml <contrib-group>
				<contrib contrib-type="author">
					<name>
						<surname>ROCHA</surname>
						<given-names>MARTA MENDES</given-names>
					</name>
					<xref ref-type="aff" rid="aff1">
						<sup>
							<bold>*</bold>
						</sup>
					</xref>
					<on-behalf-of>da USP</on-behalf-of>
				</contrib>
				<role>Professora Doutora</role>
```


[role.zip](https://github.com/scieloorg/PC-Programs/files/1793744/role.zip)

**Comment by cinthia-vieira** [comment]
Tag sendo gerada corretamente; ticket resolvido
