### ISSUE TITLE
[XPM 95] Relatório Style Checker apresenta erros que em XML que estão de acordo com SPS e/ou JATS

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2942]
Ao utilizar a tag "response" no tipo "letter" é acusado erro de estrutura

![xpm95_response](https://user-images.githubusercontent.com/15328777/37151118-12025acc-22b3-11e8-8dd6-27b1916d2249.png)

[0066-782X-abc-108-04-383-v2.zip](https://github.com/scieloorg/PC-Programs/files/1793139/0066-782X-abc-108-04-383-v2.zip)

**Comment by robertatakenaka** [comment]
@alexxpsilva este relatório é gerado pelo packtools (Style Checker). Se você tem o Style Checker, valide este arquivo por lá e veja se o problema persiste. Se persistir, dê uma olhada na documentação do SPS a fim de verificar se a marcação está correta. Caso esteja correta, abra um ticket em packtools.

**Comment by alexxpsilva** [comment]
@robertatakenaka quando abri o ticket aqui, também abri [ticket no Manager](https://github.com/scieloorg/scielo-manager/issues/1430) , achei que fosse lá.

**Comment by alexxpsilva** [comment]
@robertatakenaka o Gustavo já corrigiu o ticket no packtools. Posso fechar este ticket?

**Comment by alexxpsilva** [comment]
O Style Checker vai flexibilizar a validação conforme ticket [https://github.com/scieloorg/packtools/issues/139#issuecomment-373024181](https://github.com/scieloorg/packtools/issues/139#issuecomment-373024181)

**Comment by alexxpsilva** [comment]
Ticket resolvido.
