### ISSUE TITLE
[mkp] [alttitle] não é gerada fora de [doctitle]

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2945]
Quando marcada fora de [doctitle], a tag [alttitle] não gera tag `<alt-title>` em nenhuma parte do XML.

Quando dentro de [doctitle], gera como uma parte da tag `<article-title>`

Marcação:
![image](https://user-images.githubusercontent.com/27728729/37160778-c2ca7be8-22cf-11e8-8732-2ef1894d41b5.png)

XML gerado:
```xml
<title-group>
	<article-title><bold>O clientelismo revisitado: .</bold>
                <alt-title>Resenha: Brokers, voters and clientelism: the puzzle of distributive politics</alt-title>
	</article-title>
	 	<subtitle><bold>uma explicação focada nos mediadores</bold></subtitle>
	<trans-title-group xml:lang="en">
		<trans-title>Clientelism revisited:</trans-title>
			<trans-subtitle>an explanation focused on mediators</trans-subtitle>
		</trans-title-group>
</title-group>
```
[alt-title.docx](https://github.com/scieloorg/PC-Programs/files/1793806/alt-title.docx)

**Comment by robertatakenaka** [comment]
@cinthia-vieira : ok, mas de qualquer forma neste caso em especial alttitle não deveria ser usado para marcar este trecho. O alttile neste contexto seria um título alternativo para ser usado em mecanismos de busca, por exemplo, se o título do artigo tivesse caracteres chineses então o título alternativo teria o título transliterado. 
Neste caso, me parece que Resenha: .... é um dado de product. Veja o primeiro parágrafo.

**Comment by cinthia-vieira** [comment]
@robertatakenaka: o título alternativo na verdade foi só uma frase que coloquei pra testar o funcionamento da tag. Mesmo marcando os conteúdos corretamente, se estiver fora de [doctitle], a tag não é gerada, não importa em que parte de front o título esteja.

**Comment by cinthia-vieira** [comment]
Geração da tag sendo realizada corretamente dentro de `<title-group>`; ticket resolvido

**Comment by cinthia-vieira** [comment]
Refazendo os testes, notei que a tag está sendo gerada fora da ordem estipulada pela JATS:

Na JATS, temos:
[Expanded Content Model](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/title-group.html)
(article-title, subtitle*, trans-title-group*, alt-title*, fn-group?)

O markup está gerando
(article-title, subtitle, alt-title, trans-title-group, fn-group)
[resenha01.docx](https://github.com/scieloorg/PC-Programs/files/1837523/resenha01.docx)
