### ISSUE TITLE
[MKP] equações dentro de [caption] geram <inline-formula>

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2948]
Ao marcar uma equação ([equation]) dentro da tag [caption], no XML gerado ela obrigatoriamente é gerada como `<inline-formula>`.

Para que a equação seja gerada de acordo com a DTD, a equação deve ser marcada dentro de [p], para ficar fora da tag gerada `<title>`.

[eq-caption.docx](https://github.com/scieloorg/PC-Programs/files/1796679/letter--01.docx)

<img width="654" alt="captura de tela 2018-03-14 as 10 05 45" src="https://user-images.githubusercontent.com/505143/37404012-5652ca48-276f-11e8-941a-bb04617d54c8.png">

![captura de tela 2018-03-14 as 10 17 37](https://user-images.githubusercontent.com/505143/37404562-007c4fc0-2771-11e8-9d06-4f961ef0028c.png)

Estrutura do *caption*
```xml
<caption>
<title>Deaths Among Patients Receiving Day Hospital
Care or Alternative Services.</title>
<p> Odds ratios of death by end of follow up were calculated
by fixed effects model. Heterogeneity between trials is
presented as &#x03C7;<sup>2</sup></p>
</caption>
```

**Comment by robertatakenaka** [comment]
@cinthia-vieira : não entendi este ticket.
Como deveria ficar?

**Comment by robertatakenaka** [comment]
Este ticket é inválido pois está gerando o XML conforme a DTD e conforme a marcação. 
Uma equation somente gera disp-formula quando é um destaque, quando é citável, etc. Dentro de um parágrafo é considerada apenas parte do texto, não tem conotação de "elemento da pesquisa".

**Comment by cinthia-vieira** [comment]
Quando dentro de `[caption]`, as equações são geradas como `<disp-formula>` no XML. O correto seria gerar `<inline-formula>`.

É um erro semelhante ao do ticket #2960 
[eq-caption.docx](https://github.com/scieloorg/PC-Programs/files/1811522/eq-caption.docx)

**Comment by cinthia-vieira** [comment]
Tag sendo gerada como sugerido; ticket resolvido
