### ISSUE TITLE
[XPM 95] Não valida os valores de date-type

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2951]
É acusado o erro abaixo para os seguintes valores de [date-type](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/master/tagset/elemento-date.html)

corrected | Data em que um artigo foi corrigido
-- | --
pub | Data de publicação (eletrônica ou impressa)
preprint | Data de divulgação de preprint
retracted | Data em que um artigo foi retratado
rev-request | Data de solicitação das revisões

![xpm95_date](https://user-images.githubusercontent.com/15328777/37209301-9668c8a2-2383-11e8-9b5b-526f7825794f.png)

**Comment by robertatakenaka** [comment]
@alexxpsilva : este relatório é gerado pelo packtools/Style Checker.

**Comment by alexxpsilva** [comment]
@robertatakenaka vou abrir o ticket lá

**Comment by alexxpsilva** [comment]
@robertatakenaka [ticket aberto](https://github.com/scieloorg/packtools/issues/140) se achar necessário pode fechar esse.

**Comment by alexxpsilva** [comment]
@robertatakenaka, testei novamente após a atualização do packtools e continua apresentando o mesmo erro.

Não deveria validar?

[rpp-date-type.zip](https://github.com/scieloorg/PC-Programs/files/1811686/rpp-date-type.zip)

**Comment by alexxpsilva** [comment]
@robertatakenaka, testei novamente e não apresenta o erro mencionado anteriormente, só apresenta o erro de estrutura da versão 1.8, só irei conseguir testar de fato após a correção da versão.

Fecharei este ticket com o intuito de testar após a correção da nova versão, se necessário abrirei novamente.
