### ISSUE TITLE
[mkp] [alt-text] dentro de [graphic] não gera tag, nem reconhece o texto

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2954]
Marcar uma imagem com [alt-text] dentro de [graphic], fora de [figrp], faz com que o XML gerado ignore a tag e o texto marcado na tag
(me refiro a esta tag graphic: ![image](https://user-images.githubusercontent.com/27728729/37284751-8665b2da-25db-11e8-97f9-0072e69d0dc0.png) )

[graph.docx](https://github.com/scieloorg/PC-Programs/files/1802786/graph.docx)

**Comment by robertatakenaka** [comment]
@cinthia-vieira : Estranhei, mas de fato é aceito na JATS:
```
Content Model

<!ELEMENT  graphic      %graphic-model;                              >

Expanded Content Model

(alt-text | long-desc | abstract | email | ext-link | uri | caption | object-id | kwd-group | label | attrib | permissions)*
```

E também existe alttext dentro de graphic no Markup.

**Comment by cinthia-vieira** [comment]
@robertatakenaka sim, este alttext não está sendo gerado ao ser marcado dentro de [graphic]

**Comment by robertatakenaka** [comment]
@cinthia-vieira : sim, entendi.

**Comment by cinthia-vieira** [comment]
Markup está gerando a tag corretamente.
