### ISSUE TITLE
[mkp] problemas nas tags [role], [fname] e [surname] em [sig]

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2955]
tag `<role>` não é prevista pela JATS como afiliada às tags `<sig>` e `<sig-block>`
![image](https://user-images.githubusercontent.com/27728729/37286591-298018fc-25e1-11e8-95d6-834dae52123f.png)
![image](https://user-images.githubusercontent.com/27728729/37286749-9e1a0c40-25e1-11e8-901d-6907643dd56b.png)

Além disso, independente de ser marcada dentro ou fora de [sig], a tag `<role>` é gerada dentro de `<sig>` no documento XML
![image](https://user-images.githubusercontent.com/27728729/37286693-6f964942-25e1-11e8-9754-78676ec061d3.png)
![image](https://user-images.githubusercontent.com/27728729/37286661-59c1e9fa-25e1-11e8-9ac0-65e8ad9b555e.png)

As tags `<fname>` e `<surname>`, em [sig] não são geradas no documento XML.

[sigblock.docx](https://github.com/scieloorg/PC-Programs/files/1802934/sigblock.docx)

**Comment by cinthia-vieira** [comment]
@robertatakenaka nas duas formas de se marcar `[role]` dentro de `[sig-block]` (tanto dentro de [sig], quanto fora), as mensagens de erro aparecem e o Markup sempre gera `<role>` dentro de `<sig>` como apresentado. 

Sugiro a remoção da tag [role] em [sig] pois a JATS e o SPS não preveem `<role>` dentro de `<sig>`

**Comment by robertatakenaka** [comment]
@cinthia-vieira : Suponho que o resultado esperado é:

```xml

<sig-block>
Yours Truly,
<sig>
Levent Cerit<break/>
PhD. Teacher
</sig>
</sig-block>

```

**Comment by cinthia-vieira** [comment]
@robertatakenaka levando em conta as documentações, eu acho que sim. Agora fica a questão da presença da tag `[role]` em `[sig]`, já que ela não pode ser usada...

**Comment by robertatakenaka** [comment]
@cinthia-vieira : sim. 

Aproveito para esclarecer que apesar de não aparecerem em sig-block como given-names e surname, fname e surname são marcados  para gerar o contrib.

**Comment by cinthia-vieira** [comment]
Geração da tag está sendo realizada corretamente, tanto em `<sig-block>`, quanto em `<contrib>`
