### ISSUE TITLE
[mkp]tags com xref estão sendo geradas com código &#34; entre as aspas

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2956]
Se há alguma xref ou ID, ou qualquer atributo que seja marcado com valor entre aspas, o markup está criando aspas codificadas (`&#34;`) entre as aspas simples.

![image](https://user-images.githubusercontent.com/27728729/37287051-8efc68e2-25e2-11e8-8337-2961b9d2626e.png)

[aspas-duplas.docx](https://github.com/scieloorg/PC-Programs/files/1802960/aspas-duplas.docx)

**Comment by cinthia-vieira** [comment]
Algumas tags ainda são geradas com as aspas, como [equation] e [graphic], por exemplo

**Comment by cinthia-vieira** [comment]
Mesmo com a atualização, a nova versão ainda gera o código nas aspas.

Não sei se é uma informação útil ou válida, mas o Markup está considerando as aspas do código como parte do valor do atributo. Creio que por isso está gerando aspas duas vezes, as aspas codificadas como o valor de id/xref e as aspas 'normais' geradas automaticamente pela marcação.

**Comment by robertatakenaka** [comment]
@cinthia-vieira : eu tinha esquecido de corrigir em outro ponto... Acho que agora está tudo corrigido.

**Comment by cinthia-vieira** [comment]
Aspas são geradas normalmente agora, ticket resolvido
