### ISSUE TITLE
[mkp] material suplementar dentro de [caption] gera <supplementary-material>

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2960]
Ao marcar` [supplmat]` em `[caption]`, é gerada a tag `<supplementary-material>`, que não é aceita dentro do `<title>` gerado a partir da tag MKP `[caption]`. 

Sugiro sempre que `[supplmat]` estiver dentro de `[caption]` ser gerado como uma tag `<inline-supplementary-material>`

**Comment by robertatakenaka** [comment]
@cinthia-vieira : por favor, incluir exemplos de como é o texto original, como é  a marcação do Markup, com é o XML

**Comment by cinthia-vieira** [comment]
Erro semelhante ao do ticket #2948, mas com a tag [supplmat]: em [caption], a tag gerada é `<supplementary-material>`, mas deveria ser `<inline-supplementary-material>`
[supplmat.docx](https://github.com/scieloorg/PC-Programs/files/1811555/supplmat.docx)

**Comment by robertatakenaka** [comment]
@cinthia-vieira : por favor, incluir exemplos de como é o texto original, como seria a marcação do Markup, como seria o XML

**Comment by robertatakenaka** [comment]
@cinthia-vieira : estou corrigindo mas não faz sentido haver um material suplementar dentro de caption.
Haver inline-formula e inline-graphic faz sentido pois respectivamente representam uma fórmula e um elemento gráfico dentro de caption. Como, por exemplo, uma menção a uma fórmula e/ou imagem dentro de um caption. Mas menção a um material suplementar ou está em um parágrafo ou está em um bloco. Não vejo aparecendo dentro de um caption...

**Comment by cinthia-vieira** [comment]
Tag sendo gerada como sugerido; ticket resolvido.

@robertatakenaka recebemos nessa semana uma questão na lista exatamente sobre este tema, de como marcar material suplementar no corpo do texto e legendas de imagens. Por isso, a sugestão de correção.
