### ISSUE TITLE
[mkp] Markup não gera novos XML após modificações

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2983]
Em alguns momentos, o Markup não gera XML com as modificações na marcação, recuperando informações antigas e gerando o mesmo XML, sem considerar as mudanças no documento.

O novo XML somente é gerado saindo da ferramenta e apagando os arquivos referentes às gerações de XML anteriores.

Não ocorre em todas as gerações de XML, normalmente acontece quando o XML apresenta algum erro.

**Comment by robertatakenaka** [comment]
@cinthia-vieira : incluir arquivos (xml + src)

**Comment by cinthia-vieira** [comment]
@robertatakenaka esse tipo de erro acontece com quase todos os documentos, mas não é em toda geração de XML que ocorre. 

No momento, está acontecendo com este documento:
[4510.zip](https://github.com/scieloorg/PC-Programs/files/1833513/4510.zip)
estou anexando a pasta work junto pois é uma das pastas que eu apago pra fazer com que o XML seja gerado com as modificações.

**Comment by robertatakenaka** [comment]
@cinthia-vieira : não consegui reproduzir o erro, mas acho que tem relação com #2984
