### ISSUE TITLE
[mkp] [figgrp] gera tag <figgrp> e não <fig>

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#2986]
Após a última atualização, a tag mkp [figgrp] está gerando uma tag XML `<figgrp>`. O correto seria `<fig>`

[figgrp.docx](https://github.com/scieloorg/PC-Programs/files/1837393/figgrp.docx)
[Edit-Trad01.txt](https://github.com/scieloorg/PC-Programs/files/1837396/Edit-Trad01.txt)

**Comment by robertatakenaka** [comment]
resolvido, verificado por @cinthia-vieira
