### ISSUE TITLE
[mkp] <institution-wrap> não é gerada

### ISSUE THREAD

**Issue by lucasssantos** [scieloorg/PC-Programs#2996]
Olá,

institution-wrap não é gerado no markup 95, apenas institution-id.

Markup: 
![capturar](https://user-images.githubusercontent.com/19777809/38823553-15be10fa-417d-11e8-9543-0b515023ee70.PNG)

Gera: 
![sdsd](https://user-images.githubusercontent.com/19777809/38823597-306296ce-417d-11e8-829e-1a2647e851cc.PNG)

XPM não acusa erro de institution.

Versão usada: y:/users/Roberta/scielo-installers/40095

**Comment by robertatakenaka** [comment]
resolvido, verificado por @cinthia-vieira
