### ISSUE TITLE
[XPM / XC 95] Bug referente aos critérios

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/PC-Programs#2998]
As ferramentas estão barrando quando o título do artigo é similar com o título da seção.

![bug_xpm_xc_criterios](https://user-images.githubusercontent.com/15328777/39189808-86d2254c-47a9-11e8-91c9-d636493d5a38.png)

[1980-5314-cp-48-167-10.txt](https://github.com/scieloorg/PC-Programs/files/1942902/1980-5314-cp-48-167-10.txt)

**Comment by robertatakenaka** [comment]
@alexxpsilva O motivo de não ter aceito este artigo é porque o article-type = other.

**Comment by RPostalli** [comment]
@robertatakenaka então não deveria acusar erro de critério num tipo de documento que não faz parte dos critérios correto? Pode retirar esta validação para tipo other.

**Comment by natalieakemi** [comment]
Também referente aos Critérios o XC está barrando quando o título do artigo é similar ao título da seção:

![image](https://user-images.githubusercontent.com/19558447/46809895-e1d3ed00-cd45-11e8-9095-928da0479198.png)

**Comment by alexxpsilva** [comment]
Testado novamente na da ta de hoje, com o article-type do tipo=other e o arquivo é aceitado.

Fecharei o ticket já que foi resolvido.
