### ISSUE TITLE
validar "epub-ppub' para publicação contínua

### ISSUE THREAD

**Issue by odiliohilariomoreirajunior** [scieloorg/PC-Programs#3002]
Para arquivos Ahead of Print e Publicação Contínua o pub-date deve ser "epub", porém se colocado o valor "epub-ppub" a data não aparece no site final conforme no imagem abaixo.
![37222448-df50b14c-23ab-11e8-9b99-081e4954f7a7](https://user-images.githubusercontent.com/29929654/42165694-34c5ef56-7ddf-11e8-9bc4-aaed3f462292.jpg)
Se possível, acrescentar esse erro para ser validado no XC e XPM.

**Comment by robertatakenaka** [comment]
identificado como obsoleto ou inválido por @cinthia-vieira
