### ISSUE TITLE
[MKP] XML gerado conta <inline-formula> dentro de <caption> em <counts>

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#3003]
Ao gerar o XML, as equações `<inline-formula>` estão sendo contadas e apresentada em `<equation-count>`

Documento onde isto ocorre está anexo.
[jss-v40n2-191893.zip](https://github.com/scieloorg/PC-Programs/files/2156373/jss-v40n2-191893.zip)

Para realizar o teste foi utilizado o último Markup disponibilizado no _users_

**Comment by robertatakenaka** [comment]
https://github.com/scieloorg/PC-Programs/issues/3167 é solicitado para não gerar mais a tag `<counts>`
