### ISSUE TITLE
Acusar erro para ORCID sem registro (fake)

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#3007]
Atualmente o XC e XPM acusam erro para ORCID mal formatado (relação com ticket: https://github.com/scieloorg/PC-Programs/issues/2615)

Mas não acusa erro para ORCID falso, ou seja o registro não existe mas a estrutura de criação do número está correta.

O artigo sobe para produção, mas ao clicar no link ORCID aparece: "The page requested cannot be found. If you have this page bookmarked, please delete it. If you have followed a link, please report it."

Exemplo autor:

Victor Francisco Figueiredo Rocha Soares e Silva1  
http://orcid.org/0000-0001-3031-5847

Artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1806-37132018005004102&lng=en&nrm=iso&tlng=en

**Comment by cinthia-vieira** [comment]
Validação funcionando, testado em todos os servidores de XC, com os seguintes erros:

**ORCID inexistente**: erro crítico;
**ORCID com formato inválido**: erro fatal;
**ORCID com caracteres indevidos**: erro fatal.

Seguem links para os relatórios de ORCIDs inexistentes:

**SciELO BR**: http://homolog.xml.scielo.br/reports/rsocp/v26n66/xc_2018-08-06_100920.html#view-reports-0104-4478-rsocp-26-66-0049 ;
**SciELO SP**: http://homolog.xml.scielosp.org/reports/csp/v34n7/xc_2018-08-06_103815.html#view-reports-1678-4464-csp-34-07-e00067218 ;
**SciELO Rev@Enf**: http://homolog.xml.revenf.bvs.br/reports/rgenf/v39/xc_2018-08-06_104533.html#view-reports-1983-1447-rgenf-39-e2017-0080 ;
**SciELO RevTur**: https://homolog.xml.revtur.org/reports/rbtur/v12n1/xc_2018-08-06_105330.html#view-reports-1982-6125-rbtur-12-01-00028 ;
