### ISSUE TITLE
[XPM / XC 95] Não estão acusando erro de provedor de DOI

### ISSUE THREAD

**Issue by Gabrielacrah** [scieloorg/PC-Programs#3017]
Periódicos que no xml estão diferentes do seu provedor de DOI não estão acusando erro, nem o xmp e xc acusam erro.

**Comment by RPostalli** [comment]
@robertatakenaka seria importante corrigir este problema. Uma revista terá que publicar errata para um fascículo inteiro porque usaram prefixo SciELO no DOI mas era da GN1 e não acusou erro no XPM nem no XC.

**Comment by robertatakenaka** [comment]
@RPostalli informar exemplos

**Comment by RPostalli** [comment]
@Gabrielacrah por favor coloque aqui o link do relatório XPM e XC, a imagem de como está acusando o erro, o link do fascículo em produção e o caminhos de onde estão os arquivos.

**Comment by Gabrielacrah** [comment]
**XMP:** [file:///V:/SciELO/serial/ea/v32n94/0103-4014-ea-32-94_xpm/errors/xpm.html#view-reports-0103-4014-ea-32-94-00003](url)

**XC:** [http://homolog.xml.scielo.br/reports/ea/v32n94/xc_2018-11-26_123014.html](url)

Nos relatórios deveriam mostrar que o provedor do periódico não pertence a SciELO e não conforme o print abaixo:
![sem titulo](https://user-images.githubusercontent.com/26415279/49439616-b3541a80-f7a8-11e8-9737-fd3491e7b3e7.png)

**Link do fascículo em produção:** [http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0103-401420180003&lng=en&nrm=iso](url)

**Caminho dos arquivos:** V:\SciELO\serial\ea\v32n94

**Comment by Gabrielacrah** [comment]
@robertatakenaka Segue o periódico que não tem provedor SciELO:

rmj v53n4: V:\SciELO\serial\rmj\v53n4\2531-0488-RMJ-53-4
