### ISSUE TITLE
[XPM / XC 95] Estão acusando erro de caractere válido de DOI

### ISSUE THREAD

**Issue by Gabrielacrah** [scieloorg/PC-Programs#3020]
Percebi que o XC e o XPM estão mostrando caractere inválido para underline sendo que faz parte dos caracteres validos na construção de DOI.

![xpm](https://user-images.githubusercontent.com/26415279/49801965-ccbe0f00-fd32-11e8-861c-e7ecf14df6cd.png)

**Comment by jenniferamato** [comment]
@robertatakenaka , 

Após essa correção, está acusando o seguinte erro: 

![image](https://user-images.githubusercontent.com/16937218/50280603-17770f80-0434-11e9-944d-1b232de8f3fd.png)

Mas SciELO é Publisher do periódico:

![image](https://user-images.githubusercontent.com/16937218/50280653-3a092880-0434-11e9-832a-143818875656.png)

https://www.crossref.org/titleList/

**Comment by robertatakenaka** [comment]
@jenniferamato isso não tem nada a ver com a solução.
Estas mensagens tem a ver com #3017
