### ISSUE TITLE
Retirar validação de XC e XPM de obrigatoriedade de xref e ref para Editorial

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#3023]
Relação com ticket https://github.com/scieloorg/scielo_publishing_schema/issues/782

----

- [x] XPM - remove validação de obrigatoriedade de xref e ref para Editorial

**Comment by JoyceRaphaela** [comment]
A versão teste do XPM 40096 ainda acusa erro crítico para a falta de referências e citações em editorial:

![Erro_crítico_editorial](https://user-images.githubusercontent.com/23195801/54526978-3fa0dc80-4957-11e9-8556-0288da9865a2.png)

[1807-0337-soc-20-49-9.zip](https://github.com/scieloorg/PC-Programs/files/2977800/1807-0337-soc-20-49-9.zip)

**Comment by robertatakenaka** [comment]
resolvido, verificado por @cinthia-vieira
