### ISSUE TITLE
[Style Checker/Packtools] Retirar validação de tags de paginação em AOP

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#3027]
Semelhante ao realizado no ticket #2988 para XPM e XC, retirar a validação da obrigatoriedade das tags `<fpage>`, `<lpage>` e `<elocation-id>` para artigos em Ahead of Print, uma vez que

> Ahead of Print (AOP) são artigos publicados separadamente antes da composição dos números e por este motivo não apresentam volume, número nem paginação, portanto, os elementos `<volume>`, `<issue>`, `<fpage>` e `<lpage>` ou `<elocation-id>` não devem ser utilizados. ([doc. narrativa AOP](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/master/narr/aheadofprint.html))

Seguem print do erro no Style Checker e XML de artigo em AOP de acordo com a versão **1.8 do SciELO Publishing Schema**

![image](https://user-images.githubusercontent.com/27728729/52353071-fa62c400-2a14-11e9-8419-2b0c1528cd2a.png)
[2238-0019-trends-2237-6089-2017-0129.zip](https://github.com/scieloorg/PC-Programs/files/2837040/2238-0019-trends-2237-6089-2017-0129.zip)

**Comment by robertatakenaka** [comment]
@cinthia-vieira por gentileza, como o packtools tem o repositório próprio abri este ticket no 

https://github.com/scieloorg/packtools/issues/166
