### ISSUE TITLE
Erro ao gerar arquivos PMC

### ISSUE THREAD

**Issue by felipeEsteves** [scieloorg/PC-Programs#3028]
Ao gerar os arquivos PMC da RPP, as imagens de tradução estão sendo excluídas do pacote.

**Comment by felipeEsteves** [comment]
Segue um zip contendo 2 artigos que apresentaram esse erro, ambos são ex-aop.
[0103-0582-rpp-37-01.zip](https://github.com/scieloorg/PC-Programs/files/2837654/0103-0582-rpp-37-01.zip)

**Comment by robertatakenaka** [comment]
@felipeEsteves: o XML 0103-0582-rpp-2019-37-1-00001.xml há a referência de somente  1 figura:
```
<graphic xmlns:xlink="http://www.w3.org/1999/xlink"
                        xlink:href="0103-0582-rpp-2019-37-1-00001-gf1-en.tif"/>
```

Então, talvez por isso, não há outra imagem dentro do pacote PMX

**Comment by felipeEsteves** [comment]
@robertatakenaka, correto, é enviado apenas o inglês para o PMX, porém até o ano passado a revista RPP publicava o artigo original em português e a tradução em inglês. Nesse caso, ao gerar o pacote PMC, os arquivos de tradução (inglês) foram excluídos, como pode ver na mensagem de erro do PMC abaixo:

File '0103-0582-rpp-2019-37-1-00006-gf1-en' not found.

A partir desse ano, a RPP passou a enviar os artigos originais em inglês, e a tradução em português.

**Comment by robertatakenaka** [comment]
@felipeEsteves acredito então que não é erro pois nunca houve uma especificação para incluir as traduções. Por gentileza, crie um ticket especificando como tratar artigos XML com traduções, pois não ficou claro para mim o que deve ser gerado...

**Comment by felipeEsteves** [comment]
@robertatakenaka correto, não é um erro, foi um caso especifico onde o periódico mudou o idioma original e tradução. Dessa forma, melhor mantermos como está.
