### ISSUE TITLE
[DOIMultilingue] Validação de doi em tradução

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3032]
- [x] XPM - cada idioma deve ter um DOI diferente
- [x] XPM - todos idiomas deve ter um DOI

**Comment by cinthia-vieira** [comment]
Sugiro que o alerta (warning) dado quando o DOI utilizado na tradução é o mesmo do artigo original seja um erro (error ou fatal error).

**Comment by cinthia-vieira** [comment]
- XPM e XC exigem DOI obrigatório para tradução;
- XC considera a falta de DOI para tradução erro blockante.

**Comment by robertatakenaka** [comment]
resolvido, verificado por @cinthia-vieira
