### ISSUE TITLE
Mostrar lembrete de falta de ORCID no XPM

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#3034]
Quando o artigo não possuir ORCID ou possuir apenas alguns autores com ORCID, mostrar lembrete como warning no XPM.

--- 
- [x] XPM - indica mensagem de WARNING quando há autores sem ORCID

**Comment by RPostalli** [comment]
Acusar FALTAL ERROR quando existir ORCID não registrado, ou com estrutura inválida.

**Comment by natalieakemi** [comment]
Ainda não está apresentando **fatal error** para ausência de ORCID.

Exemplo do relatório:
![image](https://user-images.githubusercontent.com/19558447/54528404-a4f6cc80-495b-11e9-9701-d80f33716741.png)

Está validando o contrib-id, por exemplo: LUIZ ANTONIO BIASI has no 

> contrib-id

, porém como existem outros tipos de contrib-id além do ORCID, verificar a possibilidade de validar o ORCID especificamente.

**Comment by JoyceRaphaela** [comment]
Notei que é recorrente a inserção do mesmo número de ORCID para autores diferentes, desse modo sugiro a possibilidade de apontar erro ao constar duplicação do número.

Segue em anexo pacote com XML e relatório do XPM:

[2179-8966-rdp-10-1-170.zip](https://github.com/scieloorg/PC-Programs/files/2977975/2179-8966-rdp-10-1-170.zip)

**Comment by robertatakenaka** [comment]
@JoyceRaphaela excelente sugestão !!!!

**Comment by robertatakenaka** [comment]
@RPostalli @natalieakemi : no momento que resolvi o ticket, ele estava pendente de aprovação para a versão 1.9... Então agora deve acusar erro FATAL?

**Comment by RPostalli** [comment]
@robertatakenaka ainda não é obrigatório ORCID, o último [comunicado](https://us4.campaign-archive.com/?u=f26dcf71797dd37381acb4aa5&id=60da747ecf) enviado em 20/12/2018 apenas informa que deve-se usar o dado. (Confirmei informação hoje 18/03/2019 novamente com a Sol)

Por deste motivo deve ficar ainda como Warning a inexistência do dado. Mas com todas as validações pertinentes quando o dado existir.

**Comment by JoyceRaphaela** [comment]
O XPM não está apontando Warning quando ocorre a ausência de ORCID.

Segue arquivo com o relatório:
[2179-8966-rdp-10-1-170.zip](https://github.com/scieloorg/PC-Programs/files/3013164/2179-8966-rdp-10-1-170.zip)
