### ISSUE TITLE
Referência do tipo Data com novo pub-id

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#3037]
Acrescentar validação de referência do tipo "data" e novo pub-id em XC e XPM
Permitir marcação de referência do tipo "data" e novo pub-id no Markup

Mais informações ver ticket https://github.com/scieloorg/scielo_publishing_schema/issues/775

Ver também
pub-id: https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/master/tagset/elemento-pub-id.html

element-citation: https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/master/tagset/elemento-element-citation.html

----
- [x] Markup - inclusão do item data na lista de tipos de referências
- [x] XPM - reconhece este novo tipo
- [x] XPM - valida a referência esperando que exista doi, link ou pub-id (conforme descrito acima)

**Comment by cinthia-vieira** [comment]
XPM e XC validam; MKP gera XML com pub-type "database"; o tipo documentado no SPS é "data"

**Comment by robertatakenaka** [comment]
@cinthia-vieira por favor, inclua os arquivos aqui para eu simular

**Comment by cinthia-vieira** [comment]
Docx. utilizado no teste: [43709.zip](https://github.com/scieloorg/PC-Programs/files/3013832/43709.zip)

**Comment by robertatakenaka** [comment]
@cinthia-vieira 
O Markup tem os dois tipos de valores: data e database (desde sempre).
Se está marcado como database vai ficar database.
Se está marcado como data vai ficar data.

![Captura de Tela 2020-03-03 às 14 26 09](https://user-images.githubusercontent.com/505143/75877918-70dc1c00-5df7-11ea-9144-c8fab2daf0d9.png)

Vou fechar este issue.
