### ISSUE TITLE
Melhorar a mensagem de que SPS 1.9 não tem suporte para DTD 1.0, mas sim para DTD 1.1

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#3038]
Atualizar XC, XPM, Markup.

https://github.com/scieloorg/scielo_publishing_schema/issues/792

- [X] Markup - não há nada para ser feito. O usuário deve preencher com o valor 1.9
- [X] XPM - não foi "retirado" o suporte a DTD 1.0 pois desde o SPS-1.8 não há este suporte. Mas sim, foi incluído o reconhecimento da SPS-1.9 e seu prazo de validade. Também foi aumentado o prazo de validade da SPS 1.8.

**Comment by JoyceRaphaela** [comment]
Ao realizar o teste em arquivos com DTD 1.0 e SPS 1.9, não foi acusado erro no relatório do XPM informando que a DTD 1.0 é inválida.

Segue XML com o relatório do XPM:

[1981-8122-bgoeldi-13-3-0501.zip](https://github.com/scieloorg/PC-Programs/files/2978136/1981-8122-bgoeldi-13-3-0501.zip)

**Comment by robertatakenaka** [comment]
@JoyceRaphaela acho que o problema é que o packtools ainda não está atualizado com a versão SPS-1.9

**Comment by robertatakenaka** [comment]
No XML, estava:
```xml
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.0 20120330//EN" "../../JATS-journalpublishing1.dtd">
```
`"-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.0 20120330//EN"` indica que é a versão 1.0.

mostrando o seguinte erro:

<img width="939" alt="Captura de Tela 2020-02-14 às 11 25 42" src="https://user-images.githubusercontent.com/505143/74539413-c1f5a000-4f1c-11ea-8ebb-e34c247b4110.png">

Mas o correto seria para validar contra a 1.1:
```xml
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1 20151215//EN" "https://jats.nlm.nih.gov/publishing/1.1/JATS-journalpublishing1.dtd">
```

Após corrigir, aparece o seguinte erro:

<img width="1117" alt="Captura de Tela 2020-02-14 às 11 26 43" src="https://user-images.githubusercontent.com/505143/74539825-74c5fe00-4f1d-11ea-928c-d8d5fa93150f.png">

Então, também há a necessidade de haver `dtd-version="1.1"`
