### ISSUE TITLE
[XC] [XPM] [Markup] - Texto Padrão para License-p em SciELO Brasil

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/PC-Programs#3039]
Markup: gerar xml já com o texto padrão (de acordo com o idioma do artigo)
XPM e XC: Validar se os textos estão de acordo com os textos estabelecidos: 

PT: Este é um artigo publicado em acesso aberto sob uma licença Creative Commons
EN: This is an article published in open access under a Creative Commons license
ES: Este es un artículo publicado en acceso abierto bajo una licencia Creative Commons

----

- [x] Markup - Aparentemente o Markup já gerava este texto padrão (conferir)
- [x] XPM - Validação WARNING de quando o texto não está conforme o padrão. Mas isso não foi considerado nem FATAL nem BLOCKING

**Comment by robertatakenaka** [comment]
@jenniferamato : acho que este texto deveria estar no arquivo e não ser inserido pelas ferramentas. A minha justificativa é que o PDF já deveria vir com este texto, logo o texto estaria no arquivo a ser marcado.

**Comment by RPostalli** [comment]
@robertatakenaka as revistas escolhem a forma que querem a licença no PDF não podemos interferir nesse processo. Algumas revistas adotam só logo, ou só texto ou logo e texto. Como será obrigatório para SPS 1.9 a informação no XML, nossas ferramentas devem criar o texto automaticamente e valida-lo também.

**Comment by robertatakenaka** [comment]
@jenniferamato Resolve se o texto ficar fixo no site apenas?

**Comment by RPostalli** [comment]
@robertatakenaka não resolve, porque a gente interopera o insumo XML com outras bases.

Veja como aparece no nosso site uma revista indexada com licença.
![image](https://user-images.githubusercontent.com/6084959/53414040-82047880-39ac-11e9-9f9f-49a727d721b1.png)

Ela é BY e informa o texto errado (BY-NC).

No PDF só mostra o logo (opção da revista):

![image](https://user-images.githubusercontent.com/6084959/53414219-fb9c6680-39ac-11e9-9425-d5357a267893.png)

Para isso sua solução resolveria, no entanto, veja como está a mesma revista indexada no PMC:
![image](https://user-images.githubusercontent.com/6084959/53414121-bd9f4280-39ac-11e9-8728-02b9bcc8adc0.png)

O erro foi propagado e o que é ainda pior, o PMC não mostra logo da licença, então parece que a revista tem licença diferente da que adota.

A única forma de eliminarmos este problema é obrigar um texto padrão e valida-lo. 

A validação do tipo de licença `<license>` inserido no XML já ocorre no XC através da title.

**Comment by RPostalli** [comment]
Exemplo bjmbr: http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0100-879X20190002&lng=en&nrm=iso

[1414-431X-bjmbr-rpass-01-52-02.zip](https://github.com/scieloorg/PC-Programs/files/2961339/1414-431X-bjmbr-rpass-01-52-02.zip)

**Comment by natalieakemi** [comment]
Não está apresentando erro para licença com texto diferente.

**Exemplo:**

![image](https://user-images.githubusercontent.com/19558447/54532262-1dfb2180-4966-11e9-956f-070971329fd7.png)

Segue XML com o relatório do XPM:
[0066-782X-abc-112-03-teste.zip](https://github.com/scieloorg/PC-Programs/files/2978198/0066-782X-abc-112-03-teste.zip)

**Comment by RPostalli** [comment]
Conforme reunião SPS foi decidido que esta regra não será mais aplicada. O texto da licença continuará livre, o que deve ser validado é se a licença em license condiz com o texto em license-p. Aberto novo ticket https://github.com/scieloorg/PC-Programs/issues/3055
