### ISSUE TITLE
[XC] [XPM] [Markup] Suportar @article-type="data-article"

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#3040]
Relação com ticket https://github.com/scieloorg/scielo_publishing_schema/issues/800

- [x] Markup - inclusão do item data-article na lista de doctopic

**Comment by francine-curivil** [comment]
Seguem os elementos obrigatórios e os opcionais em um data article:

**Elementos obrigatórios:**

- DOI
- Título diferente da seção
- Autores
- Afiliação
- Resumo
- Palavras-chave
- Seções
- Citações
- Referências
- Licença CC

**Elementos opcionais:**

- Histórico

**Comment by RPostalli** [comment]
@robertatakenaka isso quer dizer que para este tipo de documento vale a regra de validação dos 5 itens dos Critérios SciELO Brasil:

1 Autoria;
2 Afiliação;
3 Título (diferente da seção);
4 Citação;
5 Referência.

**Comment by robertatakenaka** [comment]
resolvido, verificado por @cinthia-vieira
