### ISSUE TITLE
Uso de pub-date/@pub-type com valores de collection e scielo

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3042]
https://github.com/scieloorg/scielo_publishing_schema/issues/565

- [x] Markup gera estas datas a partir dos mesmos dados preenchidos anteriormente, ou seja, o que gerava epub, agora gera scielo, o que gerava a data que correspondia a "fascículo" gera collection
- [x] XPM entende que existem estes novos tipos de datas
- [x] XC manter correspondência: data scielo será gravada no mesmo campo de epub (v223); data collection será gravada no mesmo campo de "data do fascículo" (v65); no entanto, para ficar explícito que são dados novos, entrarão em campos novos epub (v265). Ficará como repetitivo: ^k para chave real ou expected; ^v para valor da data e ^s (source) xml ou deduced.
- [ ] Para a versão sps 1.8.1, considerar que todos os documentos deverão ter epub (data completa real) e collection (data editorial expected), gerar o campo v265 para eles.

**Comment by RPostalli** [comment]
Relação com https://github.com/scieloorg/PC-Programs/issues/3064

**Comment by robertatakenaka** [comment]
resolvido, verificado por @cinthia-vieira
