### ISSUE TITLE
[XC / XPM / MARKUP] SPS 1.9 Novas datas de publicação em <pub-date>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#3064]
Relação com: https://github.com/scieloorg/scielo_publishing_schema/issues/565

Definido como Data de publicação em pub-date:

Documenta o uso da tag para versão 1.1
Documenta uso obrigatório de @publication-format com valor "electronic"
Documenta uso de valor em @date-type pub ao invés de scielo

Exemplo:

```
<pub-date publication-format="electronic" date-type="pub">
   <day>01</day>
   <month>01</month>
   <year>2018</year>
</pub-date>
 <pub-date publication-format="electronic" date-type="collection">
   <season>Jan-Feb</season>
   <year>2018</year>
</pub-date>
```

**Comment by cinthia-vieira** [comment]
O validador XPM apresenta os seguintes erros:

- está validando um tipo de data "rolling pass/aop" em todas as datas "pub", apresentando erro;

- não acusa erro se utilizados os valores de `@pub-type` da versão 1.8 (epub-ppub, por exemplo), ignorando a existência da data no relatório, em seu lugar;

- Não acusa erro se o atributo utilizado para `<pub-date>` for "pub-type", na versão 1.9 (o esperado é "date-type");

- não acusa erro ao se utilizar o atributo `@date-type` na versão 1.8, ou se utilizar o atributo `@pub-type` na versão 1.9, caso a combinação dos valores utilizados nos atributos for epub +collection; também não acusa erro se utilizar ambos os atributos no mesmo XML (data de publicação em SciELO como `@pub-type` e data de fascículo como `@date-type`, por exemplo);

- não gera relatório de erros caso a data "pub" não seja preenchida.
----
Por sua vez, o Markup:

- mkp gera a tag de data com os atributos ao contrário, e desconsidera o preenchimento 00, gerando a tag incompleta.

Em anexo, pacote de XML utilizado no teste; o arquivo 1807-8672-asas-41-e43709.xml foi gerado com a nova versão do MKP: 
[teste.zip](https://github.com/scieloorg/PC-Programs/files/3004812/teste.zip)

**Comment by robertatakenaka** [comment]
@cinthia-vieira : não entendi: "está validando um tipo de data "rolling pass/aop" em todas as datas "pub", apresentando erro;"

**Comment by cinthia-vieira** [comment]
@robertatakenaka tanto no XPM como no XC aparece um tipo de data "rolling pass/aop", como se tivesse uma terceira tag de data, o que gera um erro de combinação "incorreta". Anexo o html de um relatório de erros com esse erro e a pasta com os XML que o geraram (os XML estão bagunçados porque tem vários erros simulados neles).

- **Relatório XPM**: [xpm.zip](https://github.com/scieloorg/PC-Programs/files/3013804/xpm.zip)
- **Pasta de XML teste**: [teste.zip](https://github.com/scieloorg/PC-Programs/files/3013806/teste.zip)

**Comment by robertatakenaka** [comment]
0066-782X-abc-112-02-0119
```xml
<pub-date date-type="pub"><day>15</day><month>02</month><year>2019</year></pub-date><pub-date pub-type="collection"><day>15</day><month>02</month><year>2019</year></pub-date>
```
<img width="882" alt="Captura de Tela 2019-03-29 às 14 47 46" src="https://user-images.githubusercontent.com/505143/55252421-ab295a80-5231-11e9-95a2-1a7ae24fbac6.png">
------

1678-4596-cr-49-03-e20180045
```xml
<pub-date date-type="collection">
				<day>14</day>
				<month>03</month>
				<year>2019</year>
			</pub-date>
```
<img width="877" alt="Captura de Tela 2019-03-29 às 14 49 06" src="https://user-images.githubusercontent.com/505143/55252487-d3b15480-5231-11e9-8513-991100930a89.png">

----
1807-8672-asas-41-e43709
```xml
<pub-date date-type="pub" publication-format="electronic">
				<year>2019</year>
			</pub-date>
			<pub-date date-type="collection" publication-format="electronic">
				<season>02</season>
				<year>2019</year>
			</pub-date>
```

<img width="876" alt="Captura de Tela 2019-03-29 às 14 50 44" src="https://user-images.githubusercontent.com/505143/55252628-1c690d80-5232-11e9-977e-5db23597ab6e.png">

**Comment by cinthia-vieira** [comment]
Utilizando o Markup para realizar alguns testes, notei que o formulário de geração de doc exige obrigatoriamente o preenchimento do campo month/season, que gera a tag `<collection>`. Há também o problema de que a obrigatoriedade não é sinalizada na interface da ferramenta:
![image](https://user-images.githubusercontent.com/27728729/70326130-7b940e80-1812-11ea-9be6-7f95474d1248.png)

Uma vez que para PC e AOP as tags `<month>` ou `<season>` não devem existir em nosso SPS, sugiro retirar esta obrigatoriedade do formulário.

**Comment by robertatakenaka** [comment]
@RPostalli @cinthia-vieira 
Não vejo problema nos relatórios que informaram corretamente os erros nos XML.
No entanto, a partir do último comentário referente ao formulário do Markup em que algumas informações são preenchidas, fiz algumas melhorias em layout, mantendo a dateiso junto com a data artdate e ahpdate. Removi o (rolling) que estava junto com artdate. E melhorei as instruções de preenchimento deste formulário.

**Comment by RPostalli** [comment]
@robertatakenaka ok ciente.
