### ISSUE TITLE
[MKP] Equações dentro de [attrib] geram <disp-formula>

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/PC-Programs#3111]
Equações marcadas dentro da tag `[attrib]` geram XML com tags `<p>` e `<disp-formula>` ao invés de `<inline-formula>`. O problema se assemelha ao ticket #2948.

Arquivos para análise: [scieloxmlerrodestylechecker.zip](https://github.com/scieloorg/PC-Programs/files/3112553/scieloxmlerrodestylechecker.zip)

**Comment by robertatakenaka** [comment]
@cinthia-vieira porque  haveria equações dentro de attrib?

**Comment by cinthia-vieira** [comment]
@robertatakenaka então... este exemplo anterior é de um proc real que eu fiz na época. A revista, que utiliza o Markup para produzir seus XML, marcou a equação e o XML veio "errado", daí a criação do ticket.

**Comment by robertatakenaka** [comment]
@cinthia-vieira : isso não seria `<attrib>`, seria `<p>`. 
`<attrib>` é para dar crédito a quem fotografou, por exemplo...

**Comment by cinthia-vieira** [comment]
@robertatakenaka embora o uso ideal da tag seja de fato para creditar autores, esse não é o uso real da tag. Por exemplo, em SciELO muitas vezes é usada para colocar legendas ou informações extras nas figuras que não poderiam ser contidas adequadamente no arquivo de imagem e que, no PDF, não fazem parte do `<caption>` (o caso do exemplo citado, inclusive).  A própria JATS não define muito bem seu uso:

>Usage: This element is a very unregulated container that may hold a description of the source, name of the author, formal thanks, copyright material, or _other information_.

Ou seja, pode ser qualquer coisa, rs.


De toda forma, a tag `<inline-formula>` é aceita dentro de [`<attrib>`](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/attrib.html) pela JATS 1.1, mas não a tag `<disp-formula>`. Creio que, dado isso, o ticket de correção continua sendo pertinente, já que o Markup gera uma tag que não é aceita na estrutura de `<attrib>` de qualquer forma.

**Comment by robertatakenaka** [comment]
> Ou seja, pode ser qualquer coisa, rs.

Não concordo. Pode ser uma destas coisas, mas não a legenda do gráfico que acho que o mais apropriado no caso seria converter `<attrib>` para `<p>`.

Não questiono o `<inline-formula>`. De fato, se ocorrer equações dentro de `<attrib>` deveria ser identificado como `<inline-formula>`.

**Comment by RPostalli** [comment]
@robertatakenaka concordo com a @cinthia-vieira 

Nos fazemos o uso de attrib para além do que vc menciona. Não podemos perder informações textuais em figuras e equações mesmo que não sejam informações de crédito de autoria.

**Comment by robertatakenaka** [comment]
@RPostalli não iria perder porque o `<attrib>` pode ser convertido a `<p>` se ele contiver equações. Caso contrário, ficará como `<attrib>`.

https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/fig.html

**Comment by cinthia-vieira** [comment]
@robertatakenaka infelizmente, os casos de uso não são tão fáceis de identificar :(. 

O máximo que podemos fazer é, após a marcação pelo editor/prestador, orientar o uso correto da tag e reforçar o uso descrito no SPS caso não seja o ideal, mas não podemos "obrigar" a ferramenta a mudar uma coisa que, possivelmente, pode ser um `<attrib>` (como um texto de autoria + algo nada a ver no mesmo parágrafo. Acontece). Tem o agravante de que esses casos não-ortodoxos de uso de `<attrib>` também ocorrem com prestadores que não usam o Markup, e creio que "corrigir" essa cultura de uso demandaria discutir se vale ou não a pena criar uma validação de conteúdo no XPM/XC para o uso da tag (o que eu acho exagerado, sendo sincera).

Adendo a isso, uma vez que `<inline-formula>` é aceito dentro de `<attrib>`, por que forçaríamos a ferramenta a não gerar uma tag aceita pela JATS? Mesmo que se conceitualmente o uso fosse dúbio, ainda tá dentro do aceito por JATS, não vejo por que impedir o Markup de gerar uma tag que tá correta...

Em todo o caso, a gente acabaria esbarrando em mais outro problema, já que a plataforma web não mostra os textos de `<p>` soltos em `<fig>`, somente `<p>` dentro de outras tags (uma delas `<attrib>`, por isso a solução de utilizar a tag pra inserir infos extras).

Pra terminar a parede de texto (rs) eu realmente acho que faz mais sentido só adequar a geração das equações como `<inline-formula>` em `<attrib>`, ao invés mexer no Markup, daí na Web, daí na documentação e possivelmente no XPM/XC. Não acho que a tag valha todo esse sofrimento rs.

**Comment by robertatakenaka** [comment]
@cinthia-vieira @RPostalli melhor discutir pessoalmente

**Comment by robertatakenaka** [comment]
Para ilustrar o caso

**PDF**

<img width="421" alt="Captura de Tela 2020-02-27 às 13 45 48" src="https://user-images.githubusercontent.com/505143/75465558-92588600-5967-11ea-8ef2-8849efa9b071.png">

**Marcação**

![Captura de Tela 2020-02-27 às 13 49 29](https://user-images.githubusercontent.com/505143/75465886-0b57dd80-5968-11ea-99e4-4fcb0739c4cc.png)
![Captura de Tela 2020-02-27 às 13 49 14](https://user-images.githubusercontent.com/505143/75465900-10b52800-5968-11ea-88ed-83fe2f648ac8.png)

**Comment by robertatakenaka** [comment]
`<attrib>` não seria o elemento correto para identificar a legenda de gráfico, deveria haver uma solução melhor para identificar textos dentro de  figuras (`figgrp` ou `fig`)  além de `<alternative-text>` e `<attrib>`. Desta forma, abri #3178
