### ISSUE TITLE
Inserção de scielo-id na base ISIS e no XML pelo XML Converter

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3123]
### Descrição da nova funcionalidade
Eu, como **Kernel Gate**, gostaria que **no XML e na Base ISIS houvesse indicação do scielo-id**, então **é possível identificar o documento**.

### Critérios de aceitação
Para isso, o XML Converter gerará o scielo-id e  inserirá na base ISIS e também adicionará no XML que vai para o Kernel Gate.
O scielo-id deve ficar no campo v885 da base ISIS e no article/front/article-meta/article-id (https://github.com/scieloorg/document-store/blob/master/docs/adr/0006-novo-pid-do-scielo.md).

### Anexos
N/A
### Referências
https://github.com/scieloorg/document-store/blob/master/docs/adr/0006-novo-pid-do-scielo.md

**Comment by RPostalli** [comment]
@robertatakenaka e em relação a este ticket https://github.com/scieloorg/opac/issues/994
Produção vai ter acesso a esse novo PID? Envio casos onde precisamos do PID:

Cadastro de DOI Manager:

![image](https://user-images.githubusercontent.com/6084959/60094453-7f2f4f80-9722-11e9-8ca2-523e75942a4a.png)

Correção no PubMed:

![image](https://user-images.githubusercontent.com/6084959/60094598-e5b46d80-9722-11e9-8472-c1f3147a3ad1.png)
