### ISSUE TITLE
[PubMed] Acréscimo tag <PubDate PubStatus = "ecollection"> no XML

### ISSUE THREAD

**Issue by odiliohilariomoreirajunior** [scieloorg/PC-Programs#3132]
Por gentileza acrescente na geração do xml pubmed a tag de data de collection <PubDate PubStatus = "ecollection"> para que apareça no pubmed as datas de publicação e coleção dos artigos.

Hoje na geração dos xml para o pubmed a tag ecollection não é gerada aparecendo no pubmed somente a data de publicação.

<img width="729" alt="eins" src="https://user-images.githubusercontent.com/29929654/65327976-9c41b600-db8b-11e9-9c53-ce241fddfa0d.PNG">

É necassário a inclusão da tag `<PubDate PubStatus = "ecollection">` para que as datas de coleção também sejam apresentadas.

<img width="807" alt="collection" src="https://user-images.githubusercontent.com/29929654/65328245-40c3f800-db8c-11e9-8a31-b25806249640.PNG">

No xml a tag será apresentada dessa forma.

<img width="215" alt="xml" src="https://user-images.githubusercontent.com/29929654/65328438-b4660500-db8c-11e9-9068-7fb9de0fb62c.PNG">

Envio um arquivo xml para análise
Att.
[einsv1820190916-20190917.zip](https://github.com/scieloorg/PC-Programs/files/3635840/einsv1820190916-20190917.zip)

**Comment by odiliohilariomoreirajunior** [comment]
Ao gerar o xml para o pubmed na versão do sps 1.8, está sendo criado duas tags incorretas, "ppublish" para a data de coleção e "aheadofprint" para a data de epub.

```
<PubDate PubStatus="ppublish">
            <Year>2019</Year>
         </PubDate>
```

```
<History>
            <PubDate PubStatus="aheadofprint">
            <Year>2019</Year>
            <Month>09</Month>
            <Day>23</Day>
         </PubDate>
      </History>
```

O correto seria 

```
<PubDate PubStatus="epublish">
				<Year>2019</Year>
				<Month>09</Month>
				<Day>23</Day>
			</PubDate>
```


```
<History>
<PubDate PubStatus="ecollection">
				<Year>2019</Year>
			</PubDate>
</History>
```

**Comment by robertatakenaka** [comment]
@odiliohilariomoreirajunior 
poderia me ajudar?
Eu gostaria de um exemplo de como estão as datas no XML SPS. Você mencionou a versão 1.8 que gerou:
```xml
<PubDate PubStatus="ppublish">
            <Year>2019</Year>
         </PubDate>
```

```xml
<History>
            <PubDate PubStatus="aheadofprint">
            <Year>2019</Year>
            <Month>09</Month>
            <Day>23</Day>
         </PubDate>
      </History>
```

**Comment by odiliohilariomoreirajunior** [comment]
@robertatakenaka 

Isso mesmo é na versão 1.8.

Segue arquivos para análise.
[arquivo_pubmed.zip](https://github.com/scieloorg/PC-Programs/files/3841491/arquivo_pubmed.zip)

**Comment by everton-henrique** [comment]
Ao tentarmos gerar os arquivos, nos casos de publicação continua que são versão 1.8, notamos que o registro  de Pubdate  é gerado como no exemplo baixo:

```<PubDate PubStatus="ppublish">```
           ``` <Year>2019</Year>```
         ```</PubDate>```

O correto seria:
```<PubDate PubStatus="epublish">```
				```<year>2019</year>```
				```<month>11</month>``` 
```<day>07</day>```
				```</Pubdate>```

Anexos o XML gerado com o problema e os XMLs originalmente publicados:

[bjmbrv52n1120191107-20191108.txt](https://github.com/scieloorg/PC-Programs/files/3843055/bjmbrv52n1120191107-20191108.txt)
[1414-431X-bjmbr-52-11-e8333.txt](https://github.com/scieloorg/PC-Programs/files/3843052/1414-431X-bjmbr-52-11-e8333.txt)
[1414-431X-bjmbr-52-11-e8567.txt](https://github.com/scieloorg/PC-Programs/files/3843053/1414-431X-bjmbr-52-11-e8567.txt)
[1414-431X-bjmbr-52-11-e8950.txt](https://github.com/scieloorg/PC-Programs/files/3843054/1414-431X-bjmbr-52-11-e8950.txt)

**Comment by robertatakenaka** [comment]
@odiliohilariomoreirajunior @everton-henrique 
Então, ao que me parece todos os documentos mesmo que não aop, terão 
```xml
<PubDate PubStatus="epublish">
				<year>2019</year> 
				<month>11</month> 
                                <day>07</day> 
				</Pubdate>
```

e 
```xml
<History>
<PubDate PubStatus="ecollection">
				<Year>2019</Year>
			</PubDate>
</History>
```
???

**Comment by everton-henrique** [comment]
Exatamente, é isso.

**Comment by odiliohilariomoreirajunior** [comment]
@robertatakenaka estou revendo a questão dos fascículos, para publicação contínua está correto.

**Comment by robertatakenaka** [comment]
@odiliohilariomoreirajunior não há como distinguir publicação contínua de fascículo

**Comment by RPostalli** [comment]
@roberta por favor use a seguinte regra para gerar PubMed de fascículo regular Para SPS 1.8

No SciELO estará:

```
<pub-date date-type="collection" publication-format="electronic">
<month>10</month>
<year>2019</year>
</pub-date>

<pub-date date-type="pub" publication-format="electronic">
<day>07</day>
<month>11</month>
<year>2019</year>
</pub-date>
```

Duas coisas devem ocorrer para o XML PubMed:
1. A data collection se tornará uma data do tipo  `<PubDate PubStatus="ppublish">`
2. A data pub será ignorada do XML

Como é possível saber o que é um fascículo regular.
- Serão os arquivos que terão no XML SciELO uma dala de collection considerando month + year ou season + year (Essa regra também se aplica para ex-aop)

O XML PubMed para fascículo regular (com ou sem ex-aop) seria:

```
<ArticleSet>
	<Article>
		<Journal>
			<PublisherName>Sociedade Brasileira de Cardiologia - SBC</PublisherName>
			<JournalTitle>Arq Bras Cardiol</JournalTitle>
			<Issn>1678-4170</Issn>
			<Volume>113</Volume>
			<Issue>4</Issue>
			 <PubDate PubStatus="ppublish">
				<Year>2019</Year>
				<Month>11</Month>			
			</PubDate>
		</Journal>
          ...
</ArticleIdList>
		<History>
			<PubDate PubStatus="received">
				<Year>2018</Year>
				<Month>07</Month>
				<Day>30</Day>
			</PubDate>
			<PubDate PubStatus="accepted">
				<Year>2019</Year>
				<Month>01</Month>
				<Day>23</Day>
			</PubDate>				
		</History>
...
</Article>
```

Rola de fazer desta forma?

**Comment by robertatakenaka** [comment]
@RPostalli 
Então pelo que entendi 
O modelo para os fascículos regulares terá ppublish (vindo da data collection) e nenhuma data a mais no History.

Já para contínua e ahead of print, usamos epublish (vindo da data pub) e inserimos em History a data ecollection (vindo da data collection).

**Comment by RPostalli** [comment]
@robertatakenaka isso, so no caso de regular, não é certo afirmar que não terá data de histórico, estes documentos podem dar datas de aceito, recebido etc. Nao terá data de histórico em relação as datas de publicação (fascículo e coleção).
É isso :)

**Comment by RPostalli** [comment]
@robertatakenaka, o @odiliohilariomoreirajunior irá testar e assim que possível lhe damos um feedback.

**Comment by odiliohilariomoreirajunior** [comment]
@robertatakenaka realizei os testes e é necessário ajustar alguns pontos.

Os fascículos estão gerando com a tag de `<PubDate PubStatus="ecollection">` junto com `<PubDate PubStatus="ppublish">`. Essas tags juntas são incompatíveis, teria que tirar a tag de `<PubDate PubStatus="ecollection">`.

Os arquivos AOP estão gerando com a tag de `<PubDate PubStatus="epublish">` o correto seria `<PubDate PubStatus="aheadofprint">`.

Os arquivos PC 1.8 e 1.9 estão gerando corretamente com as tags de `<PubDate PubStatus="epublish">` e `<PubDate PubStatus="ecollection">`.
