### ISSUE TITLE
[mkp] Disponibilizar novos elementos para identificar dados de papéis segundo CRediT

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3144]
### Descrição da nova funcionalidade
Eu, como **[tipo de cargo/ usuário / papel em sistema]**, gostaria que **fosse ampliada a gama de valores para contribuição de autores**, então **os valores de tipo de contribuição fossem compatíveis com CRediT**.

Disponibilizar o elemento `[credit]` dentro de `/doc/author`.
Disponibilizar o atributo  `credit/@uri`

term | uri
--- | ---
Contributor Roles/Conceptualization | https://casrai.org/term/contributor-roles-conceptualization
Contributor Roles/Data curation | https://casrai.org/term/contributor-roles-data-curation
Contributor Roles/Formal analysis | https://casrai.org/term/contributor-roles-formal-analysis
Contributor Roles/Funding acquisition | https://casrai.org/term/contributor-roles-funding-acquisition
Contributor Roles/Investigation | https://casrai.org/term/contributor-roles-investigation
Contributor Roles/Methodology | https://casrai.org/term/contributor-roles-methodology
Contributor Roles/Project administration | https://casrai.org/term/contributor-roles-project-administration
Contributor Roles/Resources | https://casrai.org/term/contributor-roles-resources
Contributor Roles/Software | https://casrai.org/term/contributor-roles-software
Contributor Roles/Supervision | https://casrai.org/term/contributor-roles-supervision
Contributor Roles/Validation | https://casrai.org/term/contributor-roles-validation
Contributor Roles/Visualization | https://web.archive.org/web/20180314065118/http://dictionary.casrai.org/Contributor_Roles/Visualization
Contributor Roles/Writing – original draft | https://casrai.org/term/contributor-roles-writing-original-draft
Contributor Roles/Writing – review &amp; editing | https://casrai.org/term/contributor-roles-writing-review-editing

### Critérios de aceitação
Ser possível marcar de 0 a n vezes dentro de `/doc/author`
- elemento `[credit]` 
- atributo `credit/@uri`

### Anexos
n/a

### Referências
https://casrai.org/term/contributor-roles/
https://github.com/scieloorg/scielo_publishing_schema/issues/821

**Comment by RPostalli** [comment]
@robertatakenaka essa decisão estava pedente de ser documentada nos Critérios. Eu coloquei como sugestão, mas não sei qual foi a decisão da avaliação e Abel em relação a isso. Sugiro consulta-los antes de documentar em SPS/markup etc

**Comment by robertatakenaka** [comment]
@gustavofonseca @RPostalli o que acham desta proposta?

**Comment by gustavofonseca** [comment]
> Disponibilizar o elemento `[credit]` dentro de `/doc/author`.
> Disponibilizar o atributo `credit/@uri`

Estes elementos são exclusivos do Markup? Eu não os reconheço no contexto da SciELO PS

**Comment by gustavofonseca** [comment]
Outra dúvida, não há entre as novas URLs uma apropriada para o termo _Visualization_?

**Comment by RPostalli** [comment]
@gustavofonseca estanhamento não. Essa é a única URL que existe para esse termo, e é a única diferente.

**Comment by robertatakenaka** [comment]
@gustavofonseca @RPostalli olhem o issue relacionado: #3152 
O issue #3144 é referente a criar tags/atributos no programa de marcação. Decidi assim porque se vocês compararem o JATS 1.1 (`@content-type`) e JATS 1.2 (`@term-id`) eles entres si estão muito distintos, sendo assim sugeri nem um nem outro: `@uri`.
Já o #3152 é sobre transformar estas tags/atributos nos correspondentes do SPS.
Sobre a "Contributor Roles/Visualization", aparentemente eles retiraram da documentação, mas colocaram link para o "web.archive.org".

**Comment by RPostalli** [comment]
@robertatakenaka de acordo.
