### ISSUE TITLE
Adicionar PID no XML exportado para o SciELO Publishing Framework

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/PC-Programs#3145]
### Descrição da tarefa

Para garantir a retrocompatibilidade entre o novo site alimentado pelo processo do `spf` é necessário que todos os XMLs contenham o PID.

### Subtarefas

- [ ] Adicionar PID para XMLs importados pelo SPF

## Considerações e notas
N/A

**Comment by robertatakenaka** [comment]
Pessoal,
Precisamos de ajuda em uma definição. Precisamos acrescentar PID no XML e precisamos definir como ele ficaria.

https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/article-id.html
Atributos:
- id Document Internal Identifier
- pub-id-type Type of Publication Identifier
- specific-use Specific Use
- xml:base Base

https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/article-id.html
Atributos:
- **assigning-authority Authority Responsible for an Identifier**
- id Document Internal Identifier
- pub-id-type Type of Publication Identifier
- specific-use Specific Use
- xml:base Base

Valores válidos para pub-id-type.
https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/pub-id-type.html

Usamos `<article-id pub-id-type="publisher-id">1037</article-id>` ou 
`<article-id pub-id-type="doi">10.1128/JCM.39.7.2634-2636.2001</article-id>` porque é obrigatório tem 1 article-id.

Não podemos afirmar que  `<article-id pub-id-type="publisher-id">1037</article-id>` é um PID.

Teríamos que criar um novo `article-id`.
Já temos o `<article-id pub-id-type="publisher-id" specific-use="scielo"/>` para identificar o novo **scielo-id**.

O que vocês sugerem para representar o PID?
Alguém contra representar assim:
`<article-id pub-id-type="publisher-id" specific-use="scielo-pid"/>`?

No entanto, aparentemente o pub-id-type não precisa ser obrigatório, especialmente se usarmos o specific-use já que qualificaria o article-id. Uma dúvida que surgiu é que se é OK ter mais de um article-id com o mesmo valor de pub-id-type.

**Comment by gustavofonseca** [comment]
Eu não vejo problema em definirmos 2 elementos `<article-id>`, um para o PID antigo e um para o novo. Por exemplo:

* `<article-id pub-id-type="publisher-id" specific-use="scielo">LZFSDqy67GZDNjDBGktqbzP</article-id>`: PID no formato novo; e
* `<article-id pub-id-type="publisher-id" specific-use="scielo-legacy">S1678-69712019000500202</article-id>`: PID legado.

> No entanto, aparentemente o pub-id-type não precisa ser obrigatório, especialmente se usarmos o specific-use já que qualificaria o article-id. Uma dúvida que surgiu é que se é OK ter mais de um article-id com o mesmo valor de pub-id-type.

De fato o atributo `@pub-id-type` não é obrigatório para a JATS, mas eu não vejo vantagem em omiti-lo. Estou perdendo algo?

**Comment by jamilatta** [comment]
@joffilyfe 

Também não vejo problema em termos 2 elementos como `<article-id>`.

Não entendi a dúvida "Uma dúvida que surgiu é que se é OK ter mais de um article-id com o mesmo valor de pub-id-type"!, quando pergunta isso explicitamente teremos nesses nós o atributo **specific-use**?

**Comment by jamilatta** [comment]
Concordo em utiliza **scielo-pid** com qualificador!

**Comment by gustavofonseca** [comment]
> Concordo em utiliza **scielo-pid** como qualificador!

_ PID_  é um termo genérico que pode trazer confusão. _Estou falando do novo ou do antigo?_ 

Minha sugestão é que qualificar o antigo como _legado_: `@specific-use="scielo-legacy"`. Enquanto o novo é simplesmente `@specific-use="scielo"`.

**Comment by robertatakenaka** [comment]
Concordo que `scielo-legacy` é menos pior que `scielo-pid`, mas ainda assim... tudo pode virar legado e aí? Alguém pode dar mais sugestões?

**Comment by gustavofonseca** [comment]
De fato tudo pode virar legado. 

Há também a possibilidade de que seja versionado, algo como `scielo-v1`, `scielo-v2` etc. O nosso PID novo seria a versão _v2_, por exemplo.

**Comment by jamilatta** [comment]
@gustavofonseca 

Acho que **scielo-v1** , **scielo-v2** ganha versionamento, mas perde semantica instantânea, teremos que necessáriamente recorer a uma documentação para sabermos que **scielo-v2** é nosso PID!

**Comment by robertatakenaka** [comment]
@jamilatta acho que OK termos documentação para isso.

- **scielo-v1** também havia um pid mas o pid usado era no formato ano com 2 dígitos
- **scielo-v2** é o pid como o conhecemos hoje

Não está excelente mas já está melhor que `scielo-legacy` e `scielo-pid`.
Alguém mais sugere algo diferente? @joffilyfe @patymori

**Comment by patymori** [comment]
Por que estamos colocando que o novo identificador é PID? Talvez não seja tão ruim dizer que o ID atual se chama PID, já que já é amplamente conhecido assim no SciELO, e deveríamos tentar encontrar um novo nome para a solução nova. Então, o atual ficaria como `scielo-pid` e o novo ganharia outro nome.

**Comment by jamilatta** [comment]
Concordo com a Patrícia a tendência de criarmos vários **ID** aumenta com a solução de **scielo-v1**, além de perdermos a semântica .

**Comment by robertatakenaka** [comment]
**Conclusão**:
- todos os article-id gerados por SciELO, vamos identificar com article/@specific-use="scielo-v?" 
onde ? é o número da versão do ID.
- vamos documentar isso no https://github.com/scieloorg/scielo_publishing_schema/projects/1#card-28759918

Chegamos a essa conclusão porque o article-id é feito para representar ID em quaisquer contextos e com a combinação de `@pub-id-type` e `@specific-use` pode-se dar mais semântica ao ID.
O `@pub-id-type` somente pode ter uma lista fechada de valores, dos quais nenhum representa SciELO. Por este motivo, temos que fazer uso de `@specific-use`. Sobre a versão v1, v2, e assim por diante, é para dar uma indicação de cronologia.

**scielo-v1** - representa o primeiro PID usado na SciELO que era composto por ano com dois dígitos entre parêntesis e volume e número. Este formato resultou em problema para identificar os suplementos.
**scielo-v2** - representa o PID S + ISSN + YYYY + ORDEM NO ANO (4 DIGITOS) + ORDEM NO FASCÍCULO (5 DÍGITOS)
**scielo-v3** - representa o ID que estamos adotando no Kernel, vide formato em:
https://github.com/scieloorg/kernel/blob/master/docs/adr/0006-novo-pid-do-scielo.md

**Nota**: não necessariamente um documento terá todos os ID. Ou seja, artigos que entrarão no Kernel a partir do sistema (novo) de ingestão, terão article-id a partir de scielo-v3.

**Comment by gustavofonseca** [comment]
> ### Descrição da tarefa
> 
> Para garantir a retrocompatibilidade entre o novo site alimentado pelo processo do `spf` é necessário que todos os XMLs contenham o PID.
> ### Subtarefas
> 
>     * [ ]  Adicionar PID para XMLs importados pelo SPF
> 
> 
> ## Considerações e notas
> 
> N/A

De acordo com o que foi definido é possível incluir mais detalhes na descrição deste ticket. O XC deve garantir que ao término da sua execução os XMLs possuam PIDs nas versões 2 e 3; sendo a _versão 2_ para garantir a compatibilidade com os processos baseados em bases ISIS e a _versão 3_ para operar corretamente na nova plataforma do SciELO Publishing Framework.

**Comment by gustavofonseca** [comment]
@joffilyfe, este ticket pode ser fechado ou ainda falta fazermos algo?

**Comment by joffilyfe** [comment]
> @joffilyfe, este ticket pode ser fechado ou ainda falta fazermos algo?

Com base na discussão da issue e pull requests mergeados, acredito que o ticket **pode sim** ser encerrado, em vista que o XC já inclui as versões `2` e `3` dos pids.

Observação: É possível notar que mais alguns PRs utilizaram esta issue para referenciar mudanças na especificação dos pids :)
