### ISSUE TITLE
[mkpxml] Gerar os elementos da taxonomia CRediT

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3152]
### Descrição da nova funcionalidade
Eu, como **[produtor de XML]**, gostaria que **[após identificar os elementos no programa de marcação e executasse o comando "Gerar XML"]**, então **[o programa gerasse os elementos correspondentes no XML]**.

### Critérios de aceitação

Para JATS 1.1

De | Para
--- | ---
[credit uri="https://casrai.org/term/contributor-roles-conceptualization"] | `<role content-type="https://casrai.org/term/contributor-roles-conceptualization" >Conceptualization</role>`
[credit uri="https://casrai.org/term/contributor-roles-conceptualization"] | `<role content-type="https://casrai.org/term/contributor-roles-conceptualization">`
[credit uri="https://casrai.org/term/contributor-roles-data-curation"] | `<role content-type="https://casrai.org/term/contributor-roles-data-curation">`
[credit uri="https://casrai.org/term/contributor-roles-formal-analysis"] | `<role content-type="https://casrai.org/term/contributor-roles-formal-analysis">`
[credit uri="https://casrai.org/term/contributor-roles-funding-acquisition"] | `<role content-type="https://casrai.org/term/contributor-roles-funding-acquisition">`
[credit uri="https://casrai.org/term/contributor-roles-investigation"] | `<role content-type="https://casrai.org/term/contributor-roles-investigation">`
[credit uri="https://casrai.org/term/contributor-roles-methodology"] | `<role content-type="https://casrai.org/term/contributor-roles-methodology">`
[credit uri="https://casrai.org/term/contributor-roles-project-administration"] | `<role content-type="https://casrai.org/term/contributor-roles-project-administration">`
[credit uri="https://casrai.org/term/contributor-roles-resources"] | `<role content-type="https://casrai.org/term/contributor-roles-resources">`
[credit uri="https://casrai.org/term/contributor-roles-software"] | `<role content-type="https://casrai.org/term/contributor-roles-software">`
[credit uri="https://casrai.org/term/contributor-roles-supervision"] | `<role content-type="https://casrai.org/term/contributor-roles-supervision">`
[credit uri="https://casrai.org/term/contributor-roles-validation"] | `<role content-type="https://casrai.org/term/contributor-roles-validation">`
[credit uri="https://web.archive.org/web/20180314065118/http://dictionary.casrai.org/Contributor_Roles/Visualization"] | `<role content-type="https://web.archive.org/web/20180314065118/http://dictionary.casrai.org/Contributor_Roles/Visualization">`
[credit uri="https://casrai.org/term/contributor-roles-writing-original-draft"] | `<role content-type="https://casrai.org/term/contributor-roles-writing-original-draft">`
[credit uri="https://casrai.org/term/contributor-roles-writing-review-editing"] | `<role content-type="https://casrai.org/term/contributor-roles-writing-review-editing">`

**SPS 1.10 está adotando JATS 1.1.**

Para JATS 1.2 em diante seria:
De ```[credit uri="https://casrai.org/term/contributor-roles-writing-original-draft"]```
Para
```xml
<role vocab="CRediT" 
vocab-identifier="https://casrai.org/term/contributor-roles"
vocab-term="Writing &#8212; Original Draft"
vocab-term-identifier="https://casrai.org/term/contributor-roles-writing-original-draft" 
degree-contribution="lead">Writing &ndash; Original Draft</role>
```

### Anexos
n/a

### Referências
https://github.com/scieloorg/scielo_publishing_schema/issues/821
https://jats4r.org/credit-taxonomy
https://casrai.org/term/contributor-roles/

**Comment by robertatakenaka** [comment]
duplicado #3139

**Comment by robertatakenaka** [comment]
@gustavofonseca @RPostalli o que acham desta proposta?

**Comment by RPostalli** [comment]
Perfeita @robertatakenaka de acordo. \o

**Comment by gustavofonseca** [comment]
Estou com os 2 pés atrás em relação à URL do termo visualization. Esta implementação seguira estritamente o que foi definido [neste documento?](https://docs.google.com/document/d/1UwHgZc-99cnRlg5lfbLMPAbfWmDLmgMYY1fxgdh9ScI/edit#heading=h.tazxj8791rlr)
