### ISSUE TITLE
Retirar obrigatoriedade da tag normalized (impacto de Desabilitar Wayta) #558

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3156]
SPS
- [x] Documentar no SPS https://github.com/scieloorg/scielo_publishing_schema/issues/558

PC Programs
- [x] Remover do Markup
- [x] Não gerar o XML
- [x] Remover a validação dos dados no XPM (não foi necessário fazer nada)
- [x] Não armazenar os dados na base de dados

Packtools
- [x] Remover a validação dos dados no style checker  (não foi necessário fazer nada)

Site wayta
- [x] Desabilitar o site / colocar mensagem para o repositório do github 
(Agendamos uma data para remover o Wayta https://calendar.google.com/calendar/r/eventedit/NHJvNTNnbzE4czJtZWt2OGdrcDQxamFmZm8gcm9iZXJ0YS50YWtlbmFrYUBzY2llbG8ub3Jn?tab=mc. O site não pode sair do ar enquanto não tivermos a versão de programas que não o consulta mais.)

**Comment by RPostalli** [comment]
@robertatakenaka a documentação disso já foi feita no [SPS 1.8](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/whatsnew-1.8.html), só faltou a exclusão de PC Programs e Packtools.

![image](https://user-images.githubusercontent.com/6084959/69355410-7bb3dc00-0c60-11ea-89f5-6d503463ec56.png)

**Comment by RPostalli** [comment]
LEMBRETE: Retirar o http://wayta.scielo.org/ do ar.
