### ISSUE TITLE
[xc] Bloquear a entrada de ex aop como aop

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/PC-Programs#3176]
Temos tido com frequência o reaparecimento de Ex-AOPs na lista de AOPs que ficam duplicado com os artigos já inseridos num fascículo.

Isso ocorre quando há a necessidade de corrigir (reproc) algum artigo que era Ex-AOP mas ao invés do técnico corrigir no fascículo ele corrige no lote de AOP.

Por isso solicito que seja inserido no XC uma regra onde uma vez que um AOP entra no fascículo ele não pode voltar a ser AOP. 

Acusar FATAL ERROR e bloquear caso isso ocorra.

**Comment by robertatakenaka** [comment]
> Isso ocorre quando há a necessidade de corrigir (reproc) algum artigo que era Ex-AOP mas ao invés do técnico corrigir no fascículo ele corrige no lote de AOP.

Gostaria de saber como é feita a solicitação de reproc de um artigo ex-aop. Gostaria de entender qual é o motivo que leva à pessoa a reprocessar o artigo aop no lugar de reprocessar o artigo já publicado em um fascículo. Essa solicitação é feita pelo editor, pelo prestador, como é feita?

**Comment by robertatakenaka** [comment]
> Por isso solicito que seja inserido no XC uma regra onde uma vez que um AOP entra no fascículo ele não pode voltar a ser AOP.

A abordagem não necessariamente deve ser esta. Por este motivo, faço o questionamento anterior.

**Comment by RPostalli** [comment]
*como é feita a solicitação de reproc de um artigo ex-aop?
RESPOSTA: A pergunta não é essa, não ocorre solicitação de reproc de ex-aop (não existe isso, não faz sentido), conforme informei no ticket "ao invés do técnico corrigir no fascículo ele corrige no lote de AOP".

A pergunta certa é: Por que o técnico consegue corrigir o lote de AOP em detrimento do artigo no fascículo. A resposta é a seguinte:
1. O único controle que temos de artigos em AOP é na PTS;
2. Fascículos possuem registro mas não de artigos individuais;
3. AOPs e PCs possuem registro de individuais (artigo por artigo);
4. Quando o reproc é solicitado (ex. corrigir uma imagem) e é enviado o título do artigo, se o técnico (responsável pelo fluxo) buscar na PTS o artigo, o primeiro que ele vai encontrar é o artigo em AOP já que não existe busca de artigo individual em fascículo);
5. O técnico poderia buscar no google ou site do SciELO? Sim! Mas eu não controlo esse tipo de processo.
6. Esse erro humano é gerado pela falta de automatização dos processos de registro de documentos. Em resumo é um COMBO: humano + falta de automatização.

*Essa solicitação é feita pelo editor, pelo prestador, como é feita?
RESPOSTA: É indiferente por onde vem a solicitação, a falta de dados e a metodologia de pesquisa do responsável pelo fluxo para buscar o artigo que preciso ser reprocessado é o que gera o erro. Mas respondendo a  pergunta reprocs são solicitados por qualquer indivíduo responsável pela cadeia de publicação de artigos, ou seja:
1. Equipe editorial da revista;
2. Autores;
3. Outras unidades de SciELO;
4. Própria unidade de produção;
5. Abel.

*A abordagem não necessariamente deve ser esta.
PERGUNTA: Quais seriam outros métodos de abordagem para bloquear o erro?
