### ISSUE TITLE
[PC-Programs] Considerar nas métricas o tipo de documento data-article como citável

### ISSUE THREAD

**Issue by ednilson** [scieloorg/PC-Programs#3185]
### Descrição da tarefa
Considerar nas métricas o tipo de documento data-article como citável.
Este issue atende parte da resolução de outro issue: https://github.com/scieloorg/articles_meta/issues/183

### Considerações e notas
Rastrear o código para verificar se poderá ocorrer outros impactos baseados nesta tarefa.

Arquivos que serão afetados:
https://github.com/scieloorg/PC-Programs/blob/master/docs/source/markup_tags.rst
https://github.com/scieloorg/PC-Programs/blob/master/src/scielo/bin/pmc/j1.0/dtd/jats1.0/JATS-base-test1.dtd
https://github.com/scieloorg/PC-Programs/blob/master/src/scielo/bin/xml/modules/attributes.py

Recomendo verificar DTDs e XSLs

**Comment by robertatakenaka** [comment]
duplicado #3020
