### ISSUE TITLE
[markup][parecer] Disponibilizar novos elementos e atributos e seus valores

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3218]
### Descrição da nova funcionalidade
Eu, como **[marcador]**, gostaria que **[estivessem disponíveis novos elementos e atributos referentes aos documentos de pareceres]**, então **[poderia indentificar os dados necessários]**.

- [x] `article/@article-type`. Valores: `referee-report`
- [x] `sub-article/@article-type`. Valores: `referee-report`

- [x] ``<role>`` com ``"@specific-use"`` com valores ``"reviewer"`` ou ``"editor"``. 
- [x] `<contrib contrib-type="author"/>`

Ex: 
```xml
<contrib contrib-type="author">
        <name>
	    <surname>Doe</surname>
	    <given-names>Jane X</given-names>
	</name>
	<role specific-use="reviewer">Reviewer</role>
        <xref ref-type="aff" rid="aff1"/>
</contrib>
```

- [x] Anônimo
Quando o parecer não considerar autoria explícita utilizar `<anonymous/>` + `<role>` com atributo "@specific-use" com os valores: "reviewer" ou "editor".

- [x] Documento relacionado
```xml
<related-object object-type="peer-reviewed-material" id="r01" xlink:href="10.1590/abd1806-4841.20142998" ext-link-type="doi"/>
```

- [x] Relacionado externo:
```xml
        <p>This report can be read on:<related-object object-type="referee-report" ext-link-type="uri" xlink:href="https://publons.com/publon/000000/#review-2020xxx">Publons</related-object>
```

- [x] histórico
```xml
<history>
    <date date-type="referee-report-received">
      <day>10</day>
      <month>01</month>
      <year>2020</year>
    </date>
</history>
```

- [x] Custom data

```xml
<custom-meta-group>
               <custom-meta>
                 <meta-name>peer-review-recommendation</meta-name>
                 <meta-value>accept</meta-value>
               </custom-meta>
            </custom-meta-group>
```

### Critérios de aceitação
a definir

### Anexos
n/a

### Referências
https://github.com/scieloorg/scielo_publishing_schema/issues/791#issuecomment-573187089

**Comment by robertatakenaka** [comment]
@RPostalli seria isso aqui, certo? Pode verificar se estaria faltando algo?

**Comment by RPostalli** [comment]
@robertatakenaka falta.

para OPR o grupo JATS4R decidiu que obrigatoriamente contrib-type tem que ser do tipo author, por isso o uso de role para definir o papel do autor.

De resto ta tudo OK \o/

**Comment by robertatakenaka** [comment]
> @robertatakenaka falta.
> 
> para OPR o grupo JATS4R decidiu que obrigatoriamente contrib-type tem que ser do tipo author, por isso o uso de role para definir o papel do autor.
> 
> De resto ta tudo OK \o/

Acrescentei na descrição agora

**Comment by RPostalli** [comment]
@robertatakenaka agora ta OK. \o

**Comment by RPostalli** [comment]
> @RPostalli seria isso aqui, certo? Pode verificar se estaria faltando algo?

teste
