### ISSUE TITLE
[prodtools][xpm]Programa está informando "erro" no lugar de "info" a respeito do DOI de um artigo

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3225]
### Descrição do problema
Programa está informando "erro" no lugar de "info" a respeito do DOI de um artigo

### Passos para reproduzir o problema
1. Execute o XPM para quaisquer XML:
```python xml_package_maker.py 2523-3106-adr-60-31.xml```
2. Abra o relatório e clique em "Validações Individuais"
3. Depois, na lateral dos dados do documento, clique em "Validações de conteúdo"
4. Observe o erro apresentado:
<img width="869" alt="Captura de Tela 2020-06-15 às 07 49 23" src="https://user-images.githubusercontent.com/505143/84649789-83c5b880-aedd-11ea-8811-614732139797.png">

### Comportamento esperado
Trocar "ERRO" por "INFO"

### Anexos
[2523-3106-adr-60-31.xml.zip](https://github.com/scieloorg/PC-Programs/files/4779768/2523-3106-adr-60-31.xml.zip)

### Ambiente utilizado
n/a

**Comment by patymori** [comment]
@robertatakenaka, com a última versão do XPM o resultado não é o mesmo. Agora está como WARNING e a mensagem é outra. Segue:

<img width="1170" alt="Screen Shot 2020-06-18 at 17 35 16" src="https://user-images.githubusercontent.com/18053487/85069265-34f07b00-b18a-11ea-940d-3d643996dabf.png">

Ainda continua sendo um problema, tendo que atender ao comportamento esperado descrito no issue?

**Comment by robertatakenaka** [comment]
@patymori a mensagem está diferente porque na descrição foi possível consultar o CrossRef e retornar que o DOI está registrado para um determinado periódico e para um determinado documento. No entanto, quando você executou ele não conseguiu acessar o CrossRef e, por isso, a mensagem que você obteve foi outra.

No caso da descrição, o BUG não é o texto da mensagem, mas sim que o "error level":  `validation_status.STATUS_ERROR` no lugar de `validation_status.STATUS_INFO`.
