### ISSUE TITLE
A conversão de entidades HTML falha em algumas situações

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/PC-Programs#3228]
### Descrição do problema

Ao executar a conversão de pacotes SPS a classe `Entity2Char`[1] não é capaz de converter algumas entidades que foram introduzidas de forma errada no XML.

Por exemplo, as entidades `&amp;lt;` e `&amp;gt;` deveriam ser convertidas para `&lt;` e `&gt;`.

`Entity2Char`
https://github.com/scieloorg/PC-Programs/blob/ebd1c759007982440a402c018a38d0341ae70892/src/scielo/bin/xml/prodtools/utils/xml_utils.py#L28

### Passos para reproduzir o problema
1. Baixe o pacote [1];
2. Configure o XC;
3. Execute a conversão do pacote [1]
4. Observe que a conversão falha porque a entidade &gt; é convertida para `>` e isto quebra o XML;

### Comportamento esperado

Espera-se que a conversão seja executada com sucesso e que o XML esteja bem formado.

### Screenshots ou vídeos
N/A

### Anexos

[[1] - Pacote SPS](https://drive.google.com/open?id=1qUcIhKh9H3AdFF6k_igjkZ_D0W5nJzwV)

### Ambiente utilizado

Linux 64 bits

**Comment by robertatakenaka** [comment]
@scieloorg/scielo-brazil-developers :
Considerações
1) Há testes e eles devem passar sem alterações nos testes
2) Se o XML contivesse `&l;` no lugar de `&amp;lt;` ou `&g;` no lugar de `&amp;gt;` o programa não quebra

**Comment by robertatakenaka** [comment]
@patymori acrescento que deve existir uns testes além dos já existentes:

1. `&amp;lt;` ->  `&lt;`
2. `&amp;gt;` ->  `&gt;`
3. `&lt;` ->  `&lt;`
4. `&gt;` ->  `&gt;`
