### ISSUE TITLE
PUBMED não ta gerando os arquivos xml com ORCID e alguns estão gerando faltando afiliações

### ISSUE THREAD

**Issue by PriscilaLeme** [scieloorg/PC-Programs#3235]
Boa tarde Roberta!
Ao gerar os xmls para o pubmed notamos que está gerando sem a informação de ORCID dos autores para algumas revistas. E também não estão sendo geradas todas as afiliações dos autores contidas nos xmls.

Aqui se localizam dois exemplos de xml que foram gerados sem ORCID e com afiliações faltando:
Y:\SciELO_team\Núcleo de Publicação\FLUXO\ENVIO DE BASES ISI E PUBMED\Envio_Bases\PUBMED\2020\Maio\03-06-2020\Exemplos arquivos sem orcid e afiliação faltando

E onde estão os xmls originais:
V:\SciELO\serial\dpjo\v25n2\2176-9451-dpjo-25-02
V:\SciELO\serial\anp\v78n5\1678-4227-anp-78-05

**Comment by robertatakenaka** [comment]
@PriscilaLeme
use os templates para abrir issue: NOVA FUNCIONALIDADE ou REPORTAR PROBLEMA
pois preciso de informação que não está constando na descrição.
Em outras palavras, qual é o resultado esperado? como se representa orcid no pubmed?

**Comment by robertatakenaka** [comment]
@PriscilaLeme estou suspeitando que se funciona para alguns casos e não para outros o problema pode estar no XML. Tente comparar os XML originais que geraram corretamente o PubMed com os XML originais que não geraram corretamente o PubMed.

**Comment by robertatakenaka** [comment]
foi resolvido, duplicado
