### ISSUE TITLE
[XC] Docker de XC Server

### ISSUE THREAD

**Issue by patymori** [scieloorg/PC-Programs#3267]
### Descrição da nova funcionalidade
Eu, como **Administrador de Infraestrutura**, gostaria que **fosse criada imagem Docker do XC**, então **será possível rodar o XC em container ou PODs Kubernetes**.

### Critérios de aceitação
- Deve ler configuração de arquivo INI
- Deve prever que utilizará MX de um volume
- Deve conter as aplicações do XC (diretório `src/scielo/bin/xml`)

### Anexos
N/A

### Referências
.

**Comment by robertatakenaka** [comment]
@patymori considerar a documentação: https://github.com/scieloorg/PC-Programs/blob/master/docs/source/xc.md
e também https://docs.google.com/drawings/d/1x0vBLxovt8GRokRAXnJVveNMUqjWxRHtSQfeH0NIfGc/edit
