### ISSUE TITLE
[PubMed] XML está sendo gerado com afiliações faltando

### ISSUE THREAD

**Issue by JoyceRaphaela** [scieloorg/PC-Programs#3324]
Ao gerar o XML para envio ao PubMed verificamos que quando há presença de mais de uma afiliação ligada a um autor somente uma afiliação é gerada, sendo que as outras afiliações ligadas a esse autor são excluídas do XML, conforme exemplificado nas imagens abaixo:

XML do artigo:
<img width="363" alt="michele" src="https://user-images.githubusercontent.com/23195801/90928450-409c3000-e3cd-11ea-8f78-e71c40c3cb68.png">
<img width="541" alt="affmichele" src="https://user-images.githubusercontent.com/23195801/90928634-a4265d80-e3cd-11ea-9c67-1fa628ce26ff.png">

XML gerado para o PubMed:
<img width="459" alt="michelepubmed" src="https://user-images.githubusercontent.com/23195801/90928480-51e53c80-e3cd-11ea-9863-3e414dca320d.png">

Arquivos referentes ao artigo utilizado como exemplo:
[1678-8060-mioc-115-e200225.zip](https://github.com/scieloorg/PC-Programs/files/5110998/1678-8060-mioc-115-e200225.zip)
V:\SciELO\serial\mioc\v115\lote 5520\1678-8060-mioc-115-55

XML gerado para envio ao PubMed:
[miocv11520200814-20200815.zip](https://github.com/scieloorg/PC-Programs/files/5110995/miocv11520200814-20200815.zip)
Y:\SciELO_team\Núcleo de Publicação\FLUXO\ENVIO DE BASES ISI E PUBMED\Envio_Bases\PUBMED\2020\Agosto\19-08-2020\PubMed

**Comment by JoyceRaphaela** [comment]
Segue link para o acesso ao Guia do PubMed:
https://docs.google.com/document/d/1VGj4Bw-2LzO6T8hECA9DqDYei2Pp104Bm43H_STDrVo/edit#heading=h.2tla8xyho2tp

**Comment by robertatakenaka** [comment]
Após inserir algumas mensagens ("print") no script `src/scielo/bin/xml/app_modules/tools4dsk/xml_pubmed.py`, o problema não voltou a aparecer e não conseguimos identificar o problema. Talvez ao incluir `print`, o script demorou um pouco mais para terminar de executar e isso favoreceu com que a geração do XML completasse com sucesso.

**Nota:**
Originalmente o script de geração do XML do PubMed, usava a base de dados ISIS e outra XSL.
Com as novas demandas e para tomar proveito do XML SPS, foram feitas melhorias no script. A nova versão do script não excluiu a geração do XML da forma antiga (base de dados ISIS). A forma nova sobrescreve o XML gerado pela versão antiga.

Por algum motivo, o `xml_pubmed.py` (forma nova), não estava gerando o XML, então, a versão antiga era visualizada, com os defeitos comentados neste issue.

**Comment by gustavofonseca** [comment]
@robertatakenaka, este ticket pode ser fechado?
