### ISSUE TITLE
Traduções em XML - Data de recebido/aceito e correspondência

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#37]
Os dados de histórico do artigo e de correspondência não aparecerem nas traduções.
Exemplo: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0104-11692013000200475&lng=en&nrm=iso&tlng=pt

**Comment by leticiaquino** [comment]
@robertatakenaka resolvido.

**EN -** http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S2317-17822015000600584&lng=pt&nrm=iso&tlng=en&ORIGINALLANG=en

**PT -** http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S2317-17822015000600584&lng=pt&nrm=iso&tlng=pt&ORIGINALLANG=pt
