### ISSUE TITLE
(docs) Atualizar documentação Markup: como habilitar macro

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#501]
![abrir](https://cloud.githubusercontent.com/assets/505143/2920834/1ac5933e-d6ec-11e3-8dfe-2f8ff09d1e23.jpg)
![abrir2](https://cloud.githubusercontent.com/assets/505143/2920837/1ac6e270-d6ec-11e3-97a9-67f820d5c542.jpg)
![abrir3](https://cloud.githubusercontent.com/assets/505143/2920835/1ac61700-d6ec-11e3-9212-babb1aa3a49a.jpg)
![habilitarmarkup](https://cloud.githubusercontent.com/assets/505143/2920836/1ac6c998-d6ec-11e3-94aa-66e24ae9b53b.jpg)
![macros](https://cloud.githubusercontent.com/assets/505143/2920838/1ac7fea8-d6ec-11e3-852f-dd7f99213730.jpg)
![markup](https://cloud.githubusercontent.com/assets/505143/2920839/1ac9f35c-d6ec-11e3-9b13-eb6f2f4fc4f9.jpg)

**Comment by leticiaquino** [comment]
@robertatakenaka acredito que foi documentado já:

http://docs.scielo.org/projects/scielo-pc-programs/en/latest/markup.html#enabling-macro-execution
