### ISSUE TITLE
Faltando todas as imagens das figuras e tabelas do artigo 

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#61]
A imagem não está disponível no arquivo XLS, porém está aparecendo normalmente no HTML. Link: http://homolog.xml.scielo.br/article_plus.php?pid=S0001-37652013005000039&tlng=en&lng=en;

AABC v85n1 – Artigo 405
Faltando imagem (Figure 2);

Artigo 349
Faltando todas as imagens do artigo (três ao todo);

Artigo 337
Faltando todas as imagens e tabelas do artigo;

Artigo 307

Artigo 223

**Comment by robertatakenaka** [comment]
@javani e @leticiaquino : parece que foi resolvido, correto?

**Comment by leticiaquino** [comment]
@robertatakenaka pelo o que eu pude ver, apenas o arquivo : http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0001-37652013000100223&lng=en&nrm=iso&tlng=en não apresenta imagens.
Vou verificar e assim que possível comento o resultado.
