### ISSUE TITLE
Título do item "Referências Bibliográficas" em sub-article

### ISSUE THREAD

**Issue by javani** [scieloorg/PC-Programs#69]
Por não incluirmos o ref-list no sub-article, nas interfaces de tradução aparece o label no título principal do artigo.
Exemplo: RLAE em pt e es o label aparece "References"
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-11692013000300655&lng=en&nrm=iso&tlng=pt 
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-11692013000300655&lng=en&nrm=iso&tlng=es
PRIORIDADE: Minor
MODULO: ArticlePage

**Comment by robertatakenaka** [comment]
Este ticket deve estar no Web: https://github.com/scieloorg/Web/issues/213
