### ISSUE TITLE
(Markup 4.0.085 Word2010)[article] BUG em símbolos matemáticos em tabelas

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#743]
Não foi possível gerar arquivo .xml. Os símbolos matemáticos da tabela apresentam erro ao converter. Veja:

![bug-tabs](https://cloud.githubusercontent.com/assets/4397365/3553870/004ef72c-0908-11e4-89d1-8827d50f315d.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\743

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
acho que foi resolvido
