### ISSUE TITLE
(Markup 4.0.086 - Word2010) Markup não identifica [text-ref] para capítulo de livro

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#795]
Verificamos que o programa Markup 4.0.086 (com as atualizações do dia 15/08) não faz identificação de [text-ref] quando o autor "previous" está no capítulo de livro. Exemplo:

![text-ref](https://cloud.githubusercontent.com/assets/4397365/3951567/7b1ce548-26d8-11e4-85d2-5ce25a5f109d.jpg)

somente nesse caso o [text-ref] não funciona..

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\795

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
relacionado com #786
