### ISSUE TITLE
(Markup 4.0.086 - Word2010)Programa não identifica [xref] de autor corporativo no [xmlbody]

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#812]
Verificamos que o programa Markup não identifica [xref] de autor corporativo no corpo do texto, veja:

![xref](https://cloud.githubusercontent.com/assets/4397365/3995964/0e3fe8ae-292f-11e4-969a-8e94e6a8e93f.jpg)

Ref. marcada:

![ref-cauthor](https://cloud.githubusercontent.com/assets/4397365/3995966/19ce98be-292f-11e4-991d-43aaae176936.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\TICKETS\812

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
será identificado manualmente
