### ISSUE TITLE
(Markup 4.0.089 - Word 2013)Marcação automática de label e caption de tab não é possível em arquivos .docx

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/PC-Programs#993]
Verifiquei que o programa Markup não faz a marcação automática de label e caption de tabelas quando o arquivo está no formato .docx, apenas quando está em .doc.
Fiz o seguinte teste:
tentei marcar a tabela 1 do arquivo no formato .docx e a marcação ficou da seguinte forma:
![em docsx](https://cloud.githubusercontent.com/assets/4397365/4753526/cf882e5e-5ab7-11e4-8d16-0dbbf59b42f7.jpg)

Em seguida eu converti o mesmo arquivo para o formato .doc e refiz a marcação. O resultado foi o que segue abaixo:

![comodoc](https://cloud.githubusercontent.com/assets/4397365/4753550/00c2387a-5ab8-11e4-9214-4c5ee759d6aa.jpg)

Em .doc os dados de tabela foram identificados.

Os arquivos estão disponíveis em:
Y:\SciELO_team\XML_PMC\TICKETS\993

**MODULO - MarkupXML
PRIORIDADE - Medium**

**Comment by robertatakenaka** [comment]
resolvido salvando o arquivo em .doc ao iniciar a marcação
